Repository mastodon/mastodon, pull requests merged in 2018-07, with the labels that each got.

#7918 Re-add follow recommendations API
  app/controllers/api/v1/suggestions_controller.rb
  app/lib/potential_friendship_tracker.rb
  app/models/account.rb
  app/models/concerns/account_interactions.rb
  app/services/favourite_service.rb
  app/services/post_status_service.rb
  app/services/reblog_service.rb
  config/routes.rb
  spec/controllers/api/v1/suggestions_controller_spec.rb
  spec/models/account_spec.rb
Labels: api

#7930 Fix style of attachment list on /about
  app/javascript/styles/mastodon/about.scss
Labels: bug, ui

#7931 Fix M hotkey inserting @undefined when in detailed status
  app/javascript/mastodon/features/status/index.js
Labels: bug, ui

#7933 Fix check for PotentialFriendshipTracker when replying
  app/services/post_status_service.rb
Labels: bug

#7928 Fix 'Unknown addon provider in scalingo.json'
  scalingo.json
Labels: deployment

#7934 Allow the media modal to be closed by pressing back
  app/javascript/mastodon/features/ui/components/media_modal.js
Labels: ui

#7932 Disable service worker media cache and IndexedDB storage
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/service_worker/entry.js
Labels: performance, ui

#7936 Add white outline to black emojis (fix #5083)
  app/javascript/styles/application.scss
  app/javascript/styles/mastodon/accessibility.scss
Labels: accessibility, ui

#7959 Send undo of boost to original poster if reblog
  app/services/remove_status_service.rb
Labels: bug

#7960 In keyword filter, account for reblogs, HTML and whole-words
  app/javascript/mastodon/selectors/index.js
  app/lib/feed_manager.rb
Labels: bug

#7963 Fix gradient, regression from #7927
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/rtl.scss
Labels: bug, ui

#7964 Revert "Fix dark background error on user-mention autosuggest (#7937)"
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug, ui

#7976 Fix missing irreversible in filters API, expires_in param
  app/controllers/api/v1/filters_controller.rb
  app/serializers/rest/filter_serializer.rb
Labels: api, bug

#7977 Fix filters not affecting notifications in web UI
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/selectors/index.js
Labels: bug, ui

#7978 Add API method to remove a suggestion
  app/controllers/api/v1/suggestions_controller.rb
  app/models/concerns/account_interactions.rb
  config/routes.rb
Labels: api

#7979 Add follow button to detailed status, add gradient to mask bio cut-off
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/modal.scss
  app/javascript/styles/mastodon/stream_entries.scss
  app/views/remote_follow/new.html.haml
  app/views/shared/_landing_strip.html.haml
  app/views/stream_entries/_detailed_status.html.haml
Labels: ui

#7990 Add link to filters in web UI dropdown
  app/javascript/mastodon/features/compose/components/action_bar.js
Labels: ui

#7993 Add missing Korean translation
  config/locales/ko.yml
Labels: localization

#7448 Update uws dependency to 10.148.0
  package.json
  yarn.lock
Labels: deployment

#7466 Add dependencies for uWebSockets
  Aptfile
Labels: deployment

#8014 Do not count self in potential friendships
  app/lib/potential_friendship_tracker.rb
Labels: bug

#8016 Weblate translations (2018-07-14)
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/doorkeeper.ja.yml
  config/locales/doorkeeper.pt-BR.yml
  config/locales/el.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.el.yml
  config/locales/simple_form.fa.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.sk.yml
  config/locales/sk.yml
Labels: internationalization

#8013 Display Mastodon version in footer of web UI
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
Labels: ui

#8012 Fix static GIFs being saved as empty files when using local storage
  lib/paperclip/gif_transcoder.rb
Labels: bug

#8009 Fix streaming API still using filtered instead of chosen languages
  streaming/index.js
Labels: bug

#8010 Disable language detection for texts shorter than 140 characters
  app/lib/language_detector.rb
  spec/lib/language_detector_spec.rb
Labels: bug

#8011 Display full acct on public status pages, always
  app/helpers/stream_entries_helper.rb
  spec/helpers/stream_entries_helper_spec.rb
Labels: ui

#8019 Upgrade Node.js to v8.x on Docker image
  Dockerfile
  package.json
  yarn.lock
Labels: bug, deployment

#8022 Downgrade react-swipeable-views to v0.12.13 from v0.12.14 (regression from #6655)
  package.json
  yarn.lock
Labels: bug

#7562 Use LoadingBar instead of blur to indicate that an image is loading (fixes #4060)
  app/javascript/mastodon/features/ui/components/image_loader.js
  app/javascript/styles/mastodon/components.scss
Labels: help wanted, ui

#7780 Dockerfile: run asset precompilation as a build step
  Dockerfile
Labels: deployment

#8023 Upgrade Node.js to v8.x on nvmrc
  .nvmrc
Labels: deployment

#8026 Fix index detection a migration to revert index change
  db/migrate/20180514140000_revert_index_change_on_statuses_for_api_v1_accounts_account_id_statuses.rb
Labels: bug

#8029 Add admin dashboard
  app/controllers/admin/dashboard_controller.rb
  app/javascript/styles/application.scss
  app/javascript/styles/mastodon/dashboard.scss
  app/lib/potential_friendship_tracker.rb
  app/views/admin/dashboard/index.html.haml
  config/locales/en.yml
  config/navigation.rb
  config/routes.rb
Labels: admin support

#8032 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#8034 Whitelist dat/ipfs/gopher links in sanitizer
  app/lib/sanitize_config.rb
Labels: bug

#8037 Fix activity:interactions counter to count all interactions
  app/lib/potential_friendship_tracker.rb
  app/services/favourite_service.rb
  app/services/post_status_service.rb
  app/services/reblog_service.rb
Labels: bug

#8039 Fix ActivityPub::UpdateDistributionWorker regression
  app/workers/activitypub/update_distribution_worker.rb
Labels: activitypub, bug

#8038 Display trending hashtags on admin dashboard
  app/controllers/admin/dashboard_controller.rb
  app/models/trending_tags.rb
  app/views/admin/dashboard/index.html.haml
Labels: admin support

#8040 Add missing translation for admin dashboard trends section
  config/locales/en.yml
Labels: bug

#8043 Ensure container of React components has full width
  app/javascript/styles/mastodon/stream_entries.scss
Labels: bug, ui

#8044 Hide "A look inside" in mobile layout on frontpage
  app/javascript/styles/mastodon/about.scss
Labels: ui

#8047 Weblate translations (2018-07-18)
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  config/locales/da.yml
  config/locales/devise.da.yml
  config/locales/doorkeeper.cs.yml
  config/locales/doorkeeper.eo.yml
  config/locales/doorkeeper.it.yml
  config/locales/el.yml
  config/locales/eo.yml
  config/locales/fa.yml
  config/locales/gl.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/oc.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.sk.yml
  config/locales/sk.yml
Labels: localization

#8069 Add secure option to additional cookie
  config/initializers/devise.rb
Labels: security

#8074 Fix .column-back-button line-height
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#8073 Prevent scrolling main frame when navigating in image gallery with arrow keys
  app/javascript/mastodon/features/ui/components/media_modal.js
Labels: ui

#8084 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#8092 Prevent ActivityPub movedTo recursion
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/process_account_service.rb
Labels: activitypub, bug, security

#8091 Order invites by recent first
  app/controllers/invites_controller.rb
Labels: ui

#8089 Add missing formatting to the text in hero widget
  app/javascript/styles/mastodon/widgets.scss
Labels: bug, ui

#8088 Fix size/dimension values in avatar/header hint localizations
  app/views/settings/profiles/show.html.haml
  config/locales/activerecord.ast.yml
  config/locales/devise.ast.yml
  config/locales/devise.tr.yml
  config/locales/doorkeeper.ast.yml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ast.yml
  config/locales/simple_form.bg.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.cs.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.el.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.he.yml
  config/locales/simple_form.hr.yml
  config/locales/simple_form.hu.yml
  config/locales/simple_form.id.yml
  config/locales/simple_form.io.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.ko.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.no.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pl.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.pt.yml
  config/locales/simple_form.ru.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sl.yml
  config/locales/simple_form.sr-Latn.yml
  config/locales/simple_form.sr.yml
  config/locales/simple_form.sv.yml
  config/locales/simple_form.th.yml
  config/locales/simple_form.tr.yml
  config/locales/simple_form.uk.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
Labels: bug, localization

#8095 Do not scroll up when modal is opened
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/account_gallery/index.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/blocks/index.js
  app/javascript/mastodon/features/community_timeline/index.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/domain_blocks/index.js
  app/javascript/mastodon/features/favourited_statuses/index.js
  app/javascript/mastodon/features/favourites/index.js
  app/javascript/mastodon/features/follow_requests/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/mutes/index.js
  app/javascript/mastodon/features/pinned_statuses/index.js
  app/javascript/mastodon/features/public_timeline/index.js
  app/javascript/mastodon/features/reblogs/index.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/mastodon/features/ui/index.js
Labels: bug, ui

#8096 Weblate translations (2018-07-30)
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/te.json
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/devise.cs.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/simple_form.cs.yml
  config/locales/simple_form.ko.yml
  config/locales/uk.yml
Labels: localization

#8101 Convert MOV and WEBM to MP4, raise maximum limit to 40MB
  app/models/media_attachment.rb
Labels: compatibility

#8090 Fix incorrect context definition for the "featured" keyword
  app/lib/activitypub/adapter.rb
Labels: activitypub, bug

#8102 Enforce username format for remote users, too
  app/models/account.rb
  spec/models/account_spec.rb
Labels: security

#8100 Compensate for scrollbar disappearing when media modal visible
  app/controllers/about_controller.rb
  app/controllers/accounts_controller.rb
  app/controllers/auth/confirmations_controller.rb
  app/controllers/auth/passwords_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/controllers/auth/sessions_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/tags_controller.rb
  app/javascript/mastodon/containers/media_container.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/containers.scss
  spec/controllers/about_controller_spec.rb
Labels: bug, ui

#8093 Do not hide hashtag timeline in mobile view, make it full-window
  app/javascript/styles/mastodon/about.scss
Labels: bug, ui

#8107 Add separate setting for sidebar text (site_short_description)
  app/controllers/admin/settings_controller.rb
  app/models/form/admin_settings.rb
  app/presenters/instance_presenter.rb
  app/views/admin/settings/edit.html.haml
  app/views/application/_sidebar.html.haml
  app/views/shared/_og.html.haml
  config/locales/en.yml
  config/settings.yml
  spec/views/about/show.html.haml_spec.rb
Labels: admin support
