Repository mastodon/mastodon, pull requests merged in 2018-06, with the labels that each got.

#7694 Fix duplicate key attributes
  app/javascript/mastodon/features/getting_started/index.js
Labels: bug

#7696 Update ESLint for Code Climate
  .eslintrc.yml
  app/javascript/mastodon/service_worker/entry.js
  package.json
  yarn.lock
Labels: bug

#7700 Improve trends layout
  app/javascript/mastodon/features/getting_started/components/trends.js
  app/javascript/mastodon/features/getting_started/containers/trends_container.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/trends/index.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#7701 Fix margin between compose warning, reply indicator and textarea
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7705 Weblate translations (2018-06-02)
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/zh-HK.json
  config/locales/devise.eu.yml
  config/locales/devise.nl.yml
  config/locales/devise.zh-HK.yml
  config/locales/doorkeeper.eu.yml
  config/locales/eu.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.ko.yml
  config/locales/sl.yml
  config/locales/zh-HK.yml
Labels: localization

#7719 Add tests for embeds controller
  spec/controllers/api/web/embeds_controller_spec.rb
  spec/lib/status_finder_spec.rb
Labels: testing

#7721 Fix bug in order of conversations in web UI
  app/javascript/mastodon/features/status/index.js
Labels: bug

#7722 Fix activity-stream-tabs colors and set text variables for text colors
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug, ui

#7723 Display numbers in account header using shortNumberFormat for consistency
  app/javascript/mastodon/components/hashtag.js
  app/javascript/mastodon/features/account/components/action_bar.js
  app/javascript/mastodon/utils/numbers.js
Labels: ui

#7728 Remove unnecessary underline on accounts table
  app/views/admin/accounts/_account.html.haml
Labels: bug

#7729 Submit report using meta key
  app/javascript/mastodon/features/ui/components/report_modal.js
Labels: ui

#7724 Change border color of activity-stream
  app/javascript/styles/mastodon-light/diff.scss
Labels: ui

#7733 Detect extname from Content-Type
  app/models/concerns/remotable.rb
Labels: bug

#7735 Add redraft function
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/reducers/compose.js
  app/models/status.rb
Labels: ui

#7742 Add missing locale strings
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: localization

#7751 Add missing dot for remote image
  app/models/concerns/remotable.rb
Labels: bug

#7750 Preserve newlines in delete & redraft and desktop notifications
  app/javascript/mastodon/reducers/compose.js
  app/javascript/mastodon/utils/html.js
Labels: bug, ui

#7749 Fix fetch of remote image with multiple Content-Type headers
  app/models/concerns/remotable.rb
Labels: bug

#7753 🌍: 🇵🇱⬆️
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#7754 Add "Edit profile" link to public profile page, increase bottom padding
  app/javascript/styles/mastodon/footer.scss
  app/views/accounts/_follow_button.html.haml
Labels: ui

#7756 Do not accept ActivityPub follow requests from blocked user
  app/lib/activitypub/activity/follow.rb
Labels: activitypub, bug

#7759 Weblate translations (2018-06-08)
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  config/locales/ca.yml
  config/locales/el.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/pt-BR.yml
  config/locales/sk.yml
Labels: localization

#7771 Ensure emoji-mart dependency is updated
  yarn.lock
Labels: bug

#7767 Fix has_one association on Web::PushSubscription
  app/models/web/push_subscription.rb
Labels: bug

#7776 Control the focus when clicking the "CW" button.
  app/javascript/mastodon/features/compose/components/compose_form.js
Labels: ui

#7779 Weblate translations (2018-06-10)
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/sk.json
  config/locales/eu.yml
  config/locales/ko.yml
  config/locales/sk.yml
Labels: localization

#7778 Uniform media and video spoiler settings and fix them of the light theme
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7794 Add tests for followers_accounts_controller
  spec/controllers/follower_accounts_controller_spec.rb
Labels: testing

#7800 Add tests for following accounts controller
  spec/controllers/following_accounts_controller_spec.rb
Labels: testing

#7798 Fix "Invalid DOM property `class`" (regression from #7789)
  app/javascript/mastodon/features/compose/components/navigation_bar.js
Labels: bug

#7797 Hide status content when spoiler text is not empty (regression #7395)
  app/javascript/mastodon/actions/importer/normalizer.js
Labels: bug

#7803 Add "find friends", "invite people", and more to getting started footer
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
Labels: ui

#7806 Remove placeholder text for media-only toots
  app/services/post_status_service.rb
Labels: breaking

#7807 Fix vertical alignment of navigation bar
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7805 Add autofollow option to invites
  app/controllers/auth/registrations_controller.rb
  app/controllers/invites_controller.rb
  app/javascript/styles/mastodon/accounts.scss
  app/models/invite.rb
  app/services/bootstrap_timeline_service.rb
  app/views/auth/registrations/new.html.haml
  app/views/authorize_follows/_card.html.haml
  app/views/invites/_form.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  db/migrate/20180615122121_add_autofollow_to_invites.rb
  db/schema.rb
Labels: ui

#7811 Fix regression where CW is focused on reply
  app/javascript/mastodon/features/compose/components/compose_form.js
Labels: bug

#7814 Update Persian translation
  app/javascript/mastodon/locales/fa.json
Labels: localization

#7819 Add missing Korean translations
  app/javascript/mastodon/locales/ko.json
  config/locales/ko.yml
  config/locales/simple_form.ko.yml
Labels: localization

#7817 Fix autosuggest-textarea backgrounds in Light theme and some minor adjustments
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug, ui

#7818 Adjust account__action-bar contents
  app/javascript/mastodon/features/account/components/action_bar.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#7821 Do not pre-emojify note HTML in accounts REST API
  app/serializers/rest/account_serializer.rb
Labels: api, bug

#7826 Fix the action with X button on compose form
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7823 Change language opt-out to language opt-in
  app/controllers/settings/preferences_controller.rb
  app/models/account.rb
  app/models/status.rb
  app/models/user.rb
  app/views/settings/preferences/show.html.haml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fa.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.he.yml
  config/locales/simple_form.hu.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.ko.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.no.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pl.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.pt.yml
  config/locales/simple_form.ru.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sr-Latn.yml
  config/locales/simple_form.sr.yml
  config/locales/simple_form.sv.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
  db/migrate/20180616192031_add_chosen_languages_to_users.rb
  db/schema.rb
  spec/controllers/settings/preferences_controller_spec.rb
  spec/models/status_spec.rb
  spec/models/user_spec.rb
Labels: ui

#7827 DataTransfer.types may Array-like object
  app/javascript/mastodon/features/ui/index.js
Labels: bug

#7829 Remove unused indexes
  db/migrate/20180617162849_remove_unused_indexes.rb
  db/schema.rb
Labels: performance

#7828 Allow selecting default posting language instead of auto-detect
  app/controllers/api/v1/accounts/credentials_controller.rb
  app/controllers/settings/preferences_controller.rb
  app/javascript/styles/mastodon/forms.scss
  app/lib/user_settings_decorator.rb
  app/models/user.rb
  app/serializers/rest/credential_account_serializer.rb
  app/services/post_status_service.rb
  app/views/settings/preferences/show.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
Labels: ui

#7835 Add tests for shares_controller
  spec/controllers/shares_controller_spec.rb
Labels: testing

#7839 Weblate translations (2018-06-18)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/sk.json
  config/locales/ar.yml
  config/locales/de.yml
  config/locales/doorkeeper.de.yml
  config/locales/eu.yml
  config/locales/gl.yml
  config/locales/it.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.it.yml
Labels: localization

#7840 Serialize language into ActivityPub JSON
  app/serializers/activitypub/note_serializer.rb
Labels: activitypub, bug

#7844 Always send content for backwards-compatibility
  app/serializers/activitypub/note_serializer.rb
Labels: activitypub

#7845 Update bcrypt to 3.1.12 fix issue with Fedora
  Gemfile.lock
Labels: bug

#7848 fix filter languages label on settings (ja)
  config/locales/simple_form.ja.yml
Labels: localization

#7866 Add missing tests for confirmations controller
  spec/controllers/auth/confirmations_controller_spec.rb
Labels: testing

#7867 Replace bypass option with bypass_sign_in
  app/controllers/auth/confirmations_controller.rb
Labels: testing

#7879 Add tests for remote_unfollows_controller
  app/controllers/remote_unfollows_controller.rb
  spec/controllers/remote_unfollows_controller_spec.rb
Labels: testing

#7886 Fix Chrome issue with sizes="0px"
  app/javascript/mastodon/components/media_gallery.js
Labels: bug

#7887 Update Chinese (Simplified) Translations
  config/locales/simple_form.zh-CN.yml
  config/locales/zh-CN.yml
Labels: localization

#7889 Add /mastodon/bin to $PATH
  Dockerfile
Labels: deployment

#7890 Weblate translations (2018-06-25)
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/ca.yml
  config/locales/de.yml
  config/locales/devise.sk.yml
  config/locales/devise.zh-TW.yml
  config/locales/doorkeeper.sk.yml
  config/locales/doorkeeper.zh-TW.yml
  config/locales/eu.yml
  config/locales/gl.yml
  config/locales/it.yml
  config/locales/ms.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fa.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
  config/locales/sk.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: localization

#7895 Add .bundle to .dockerignore
  .dockerignore
Labels: bug, deployment

#7894 Add symbolic link for yarnpkg (regression from #7889)
  Dockerfile
  bin/yarn
Labels: bug, deployment

#7896 [i18n] Occitan
  app/javascript/mastodon/locales/oc.json
Labels: localization

#7905 Keyword/phrase filtering
  app/controllers/api/v1/filters_controller.rb
  app/controllers/filters_controller.rb
  app/javascript/mastodon/actions/filters.js
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/community_timeline/components/column_settings.js
  app/javascript/mastodon/features/compose/containers/reply_indicator_container.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/home_timeline/components/column_settings.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/containers/status_list_container.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/reducers/filters.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/styles/mastodon/components.scss
  app/lib/feed_manager.rb
  app/models/account.rb
  app/models/concerns/expireable.rb
  app/models/custom_filter.rb
  app/models/invite.rb
  app/serializers/rest/filter_serializer.rb
  app/views/filters/_fields.html.haml
  app/views/filters/edit.html.haml
  app/views/filters/index.html.haml
  app/views/filters/new.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20180628181026_create_custom_filters.rb
  db/schema.rb
  spec/controllers/api/v1/filter_controller_spec.rb
  spec/fabricators/custom_filter_fabricator.rb
  spec/lib/feed_manager_spec.rb
  spec/models/custom_filter_spec.rb
Labels: api, ui
