Repository mastodon/mastodon, pull requests merged in 2018-10, with the labels that each got.

#8835 Double the threshold for "read more" functionality
  app/javascript/mastodon/components/status_content.js
Labels: ui

#8864 Fix handling of ActivityPub activities lacking some attributes
  app/lib/activitypub/activity/accept.rb
  app/lib/activitypub/activity/delete.rb
  app/lib/activitypub/activity/reject.rb
  app/lib/activitypub/activity/undo.rb
Labels: activitypub

#8868 Fix link verification for remote accounts
  app/models/account.rb
  app/serializers/rest/account_serializer.rb
  app/services/verify_link_service.rb
  spec/services/verify_link_service_spec.rb
Labels: bug

#8813 Change admin accounts default sort to most recent
  app/controllers/admin/accounts_controller.rb
  app/helpers/admin/filter_helper.rb
  app/models/account_filter.rb
  app/views/admin/accounts/index.html.haml
  spec/controllers/admin/accounts_controller_spec.rb
  spec/models/account_filter_spec.rb
Labels: admin support

#8807 Limit the number of people that can be followed from one account
  app/models/follow.rb
  app/models/follow_request.rb
  app/validators/follow_limit_validator.rb
  app/workers/import_worker.rb
  config/locales/en.yml
  spec/models/follow_spec.rb
Labels: admin support

#8898 Change documentation URL
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/ui/components/onboarding_modal.js
  app/views/home/index.html.haml
  app/views/layouts/public.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: ui

#8901 i18n: Update Polish translation
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
  yarn.lock
Labels: localization

#8919 Remove dead code
  app/controllers/concerns/signature_verification.rb
Labels: refactoring

#8927 i18n: Add Japanese translations
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/ja.json
  config/locales/en.yml
  config/locales/ja.yml
Labels: localization

#8906 Track historical space stats in PgHero to determine PostgreSQL growth
  app/workers/scheduler/pghero_scheduler.rb
  config/sidekiq.yml
  db/migrate/20181007025445_create_pghero_space_stats.rb
  db/schema.rb
Labels: admin support

#8942 Add dns-prefetch if using different host for assets or uploads
  app/helpers/application_helper.rb
  app/views/layouts/application.html.haml
Labels: performance

#8951 Move network calls out of transaction in ActivityPub handler
  app/lib/activitypub/activity/create.rb
Labels: performance

#8952 Fix typo in ActivityPub Create handler
  app/lib/activitypub/activity/create.rb
Labels: bug

#8959 Improve signature verification safeguards
  app/controllers/concerns/signature_verification.rb
  app/lib/formatter.rb
  spec/controllers/concerns/signature_verification_spec.rb
Labels: security

#8961 Fix type of conversation ID in conversations API
  app/serializers/rest/conversation_serializer.rb
Labels: api, bug

#8958 Fix microformats on statuses according to updated spec
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
Labels: bug

#8963 Fix missing protocol in dns-prefetch, improve code style
  app/helpers/application_helper.rb
  app/views/layouts/embedded.html.haml
  config/environments/production.rb
Labels: bug

#8964 Display customized mascot in web UI and fix admin form for it
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
  app/views/admin/settings/edit.html.haml
Labels: ui

#8973 Improve style of notice/alert messages
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/forms.scss
Labels: ui

#8965 Improve form for selecting media display preference
  app/views/settings/preferences/show.html.haml
Labels: ui

#8950 Improve support for aspects/circles
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/tag_manager.rb
  app/lib/feed_manager.rb
  app/lib/formatter.rb
  app/lib/ostatus/atom_serializer.rb
  app/models/account_conversation.rb
  app/models/mention.rb
  app/models/notification.rb
  app/models/status.rb
  app/models/stream_entry.rb
  app/policies/status_policy.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/services/batched_remove_status_service.rb
  app/services/fan_out_on_write_service.rb
  app/services/remove_status_service.rb
  app/views/stream_entries/_detailed_status.html.haml
  app/workers/activitypub/distribution_worker.rb
  app/workers/activitypub/reply_distribution_worker.rb
  db/migrate/20181010141500_add_silent_to_mentions.rb
  db/schema.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: activitypub

#8999 Do not show "limited" visibility in default visibility preference
  app/models/status.rb
  app/views/settings/preferences/show.html.haml
Labels: bug

#9009 Add unread indicator to conversations
  app/controllers/api/v1/conversations_controller.rb
  app/controllers/api/v1/reports_controller.rb
  app/javascript/mastodon/actions/conversations.js
  app/javascript/mastodon/features/direct_timeline/components/conversation.js
  app/javascript/mastodon/features/direct_timeline/containers/conversation_container.js
  app/javascript/mastodon/reducers/conversations.js
  app/javascript/styles/mastodon/components.scss
  app/models/account_conversation.rb
  app/serializers/rest/conversation_serializer.rb
  config/initializers/doorkeeper.rb
  config/routes.rb
  db/migrate/20181018205649_add_unread_to_account_conversations.rb
  db/schema.rb
Labels: api, ui

#9024 Add "disable" button to report screen
  app/controllers/admin/reports_controller.rb
  app/views/admin/accounts/show.html.haml
  app/views/admin/reports/show.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: admin support

#9027 Do not test PAM authentication by default
  .env.test
  spec/controllers/auth/sessions_controller_spec.rb
Labels: testing

#8830 Add option to block reports from domain
  app/controllers/admin/domain_blocks_controller.rb
  app/javascript/packs/admin.js
  app/lib/activitypub/activity/flag.rb
  app/models/domain_block.rb
  app/views/admin/domain_blocks/_domain_block.html.haml
  app/views/admin/domain_blocks/index.html.haml
  app/views/admin/domain_blocks/new.html.haml
  app/views/admin/email_domain_blocks/_email_domain_block.html.haml
  app/views/admin/instances/_instance.html.haml
  config/locales/en.yml
  db/migrate/20181017170937_add_reject_reports_to_domain_blocks.rb
  db/schema.rb
Labels: admin support

#9051 Fix cull tripping on nil in last_webfingered_at
  lib/mastodon/accounts_cli.rb
Labels: bug

#9049 Downgrade fog-openstack to 0.3.7 and fog-core to 2.1.0
  Gemfile
  Gemfile.lock
Labels: bug

#9056 Revert "RTL: remove blank character inside bdi"
  app/javascript/mastodon/components/display_name.js
Labels: bug

#9010 Show suggested follows on search screen in mobile layout
  app/javascript/mastodon/actions/suggestions.js
  app/javascript/mastodon/components/account.js
  app/javascript/mastodon/features/compose/components/search_results.js
  app/javascript/mastodon/features/compose/containers/search_results_container.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/suggestions.js
Labels: ui

#9050 Fix public timelines not instantly updating on compose
  app/javascript/mastodon/actions/compose.js
Labels: bug

#9073 Fix JS error when posting from page without router context
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/compose/components/compose_form.js
Labels: bug

#9074 Show upload options on click as well as hover
  app/javascript/mastodon/features/compose/components/upload.js
Labels: bug

#9075 Fix RTL layout of status display names
  app/javascript/styles/mastodon/rtl.scss
  app/views/stream_entries/_simple_status.html.haml
Labels: bug

#9084 Fix missing plural keys
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  config/locales/ar.yml
  config/locales/devise.ar.yml
Labels: bug, i18n

#9081 Set @body_classes to admin layout
  app/controllers/admin/base_controller.rb
  app/controllers/filters_controller.rb
  app/controllers/invites_controller.rb
  app/controllers/settings/applications_controller.rb
  app/controllers/settings/deletes_controller.rb
  app/controllers/settings/exports_controller.rb
  app/controllers/settings/follower_domains_controller.rb
  app/controllers/settings/imports_controller.rb
  app/controllers/settings/migrations_controller.rb
  app/controllers/settings/notifications_controller.rb
  app/controllers/settings/preferences_controller.rb
  app/controllers/settings/profiles_controller.rb
  app/controllers/settings/sessions_controller.rb
  app/controllers/settings/two_factor_authentication/confirmations_controller.rb
  app/controllers/settings/two_factor_authentication/recovery_codes_controller.rb
  app/controllers/settings/two_factor_authentications_controller.rb
  app/views/layouts/admin.html.haml
Labels: bug, i18n

#9072 Add consistent interpolations check to CircleCI
  .circleci/config.yml
  config/locales/ar.yml
  config/locales/bg.yml
  config/locales/ca.yml
  config/locales/devise.bg.yml
  config/locales/devise.ca.yml
  config/locales/devise.fr.yml
  config/locales/devise.he.yml
  config/locales/devise.hr.yml
  config/locales/devise.hu.yml
  config/locales/devise.io.yml
  config/locales/devise.ja.yml
  config/locales/devise.nl.yml
  config/locales/devise.no.yml
  config/locales/devise.oc.yml
  config/locales/devise.pl.yml
  config/locales/devise.pt-BR.yml
  config/locales/devise.uk.yml
  config/locales/devise.zh-HK.yml
  config/locales/devise.zh-TW.yml
  config/locales/he.yml
  config/locales/hr.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/pt.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.io.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.uk.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/zh-HK.yml
Labels: testing

#9070 i18n: Update Polish translation
  config/locales/pl.yml
Labels: i18n

#9103 Fix conversations not being marked read on click
  app/javascript/mastodon/features/direct_timeline/components/conversation.js
Labels: bug, ui

#9102 Fix direct messages column not loading more items on scroll
  app/javascript/mastodon/features/direct_timeline/components/conversations_list.js
  app/javascript/mastodon/features/direct_timeline/containers/conversations_list_container.js
Labels: bug, ui

#9100 Remove character counter from edit profile
  app/javascript/packs/public.js
  app/views/settings/profiles/show.html.haml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ast.yml
  config/locales/simple_form.bg.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.cs.yml
  config/locales/simple_form.cy.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.el.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fa.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.he.yml
  config/locales/simple_form.hr.yml
  config/locales/simple_form.hu.yml
  config/locales/simple_form.id.yml
  config/locales/simple_form.io.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.ka.yml
  config/locales/simple_form.ko.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.no.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pl.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.pt.yml
  config/locales/simple_form.ru.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sl.yml
  config/locales/simple_form.sr-Latn.yml
  config/locales/simple_form.sr.yml
  config/locales/simple_form.sv.yml
  config/locales/simple_form.th.yml
  config/locales/simple_form.tr.yml
  config/locales/simple_form.uk.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
Labels: ui

#9109 Add locality check to ActivityPub::FetchRemoteAccountService
  app/services/activitypub/fetch_remote_account_service.rb
  db/migrate/20181026034033_remove_faux_remote_account_duplicates.rb
  db/schema.rb
Labels: activitypub, bug

#9108 Do not remove "dead" domains in tootctl accounts cull
  lib/cli.rb
  lib/mastodon/accounts_cli.rb
  lib/mastodon/domains_cli.rb
  lib/mastodon/emoji_cli.rb
  lib/mastodon/feeds_cli.rb
  lib/mastodon/media_cli.rb
  lib/mastodon/settings_cli.rb
Labels: admin support

#9120 Include preview cards in status entity in REST API
  app/controllers/application_controller.rb
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/status/components/card.js
  app/javascript/mastodon/features/status/containers/card_container.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/styles/mastodon/components.scss
  app/models/status.rb
  app/serializers/rest/status_serializer.rb
  app/services/fetch_link_card_service.rb
Labels: api, ui

#9101 Add progress indicators to MigrateAccountConversations
  db/migrate/20181024224956_migrate_account_conversations.rb
Labels: deployment

#9119 Reset status cache when status_stat or media_attachment updates
  app/models/media_attachment.rb
  app/models/status.rb
  app/models/status_stat.rb
Labels: bug

#9104 Update i18n-tasks and change CircleCI command
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  config/locales/activerecord.ast.yml
  config/locales/ast.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/devise.ast.yml
  config/locales/devise.cs.yml
  config/locales/devise.cy.yml
  config/locales/devise.hr.yml
  config/locales/devise.pl.yml
  config/locales/devise.zh-TW.yml
  config/locales/doorkeeper.ast.yml
  config/locales/en_GB.yml
  config/locales/hr.yml
  config/locales/pl.yml
  config/locales/simple_form.en_GB.yml
  config/locales/sk.yml
  config/locales/sr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
Labels: testing

#9133 Fix dimensions of preview cards, fix crash in web UI, fix warning
  app/javascript/mastodon/actions/cards.js
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/status_content.js
  app/javascript/mastodon/features/status/components/card.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/status/containers/card_container.js
  app/javascript/mastodon/reducers/cards.js
  app/javascript/mastodon/reducers/statuses.js
Labels: bug

#9139 Update i18n-tasks to master
  Gemfile
  Gemfile.lock
Labels: dependencies

#9140 Bump sanitize from 4.6.6 to 5.0.0
  Gemfile
  Gemfile.lock
  spec/lib/formatter_spec.rb
Labels: dependencies

#9145 RTL: fix preferences page checkbox margins
  app/javascript/styles/mastodon/rtl.scss
Labels: i18n, ui

#9146 RTL: fix toot privacy preferences radio buttonss
  app/javascript/styles/mastodon/rtl.scss
Labels: i18n, ui

#9148 Bump i18n-tasks from master to 0.9.28
  Gemfile
  Gemfile.lock
Labels: dependencies

#9150 Accept the same payload in multiple inboxes and deliver
  app/lib/activitypub/activity/create.rb
  app/services/fan_out_on_write_service.rb
Labels: activitypub

#9161 Revert "Send Clear-Site-Data when logging out (8627)"
  app/controllers/auth/sessions_controller.rb
Labels: bug

#9162 Fix td instead of th in sessions table header
  app/views/auth/registrations/_sessions.html.haml
Labels: bug

#9163 Fix empty display name precedence over username in web UI
  app/javascript/mastodon/actions/importer/normalizer.js
Labels: bug

#9171 Revert "Fix FetchAtomService content type handling (#9132)"
  app/services/fetch_atom_service.rb
  spec/services/fetch_atom_service_spec.rb
Labels: bug

#9173 Fix reducer error when conversation has no last status in web UI
  app/javascript/mastodon/reducers/conversations.js
Labels: bug
