Repository mastodon/mastodon, pull requests merged in 2018-02, with the labels that each got.

#6455 Added #call spec
  spec/services/fetch_atom_service_spec.rb
Labels: testing

#6451 Interactive `rake mastodon:setup` task
  Gemfile
  Gemfile.lock
  lib/tasks/mastodon.rake
Labels: admin support, deployment

#6464 Fix Chewy trying to update index with the wrong strategy
  config/initializers/chewy.rb
Labels: bug

#6478 Fix media button type
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/features/video/index.js
Labels: bug, ui

#6471 Click card to embed external content
  app/javascript/mastodon/features/status/components/card.js
  app/javascript/styles/mastodon/components.scss
  app/services/fetch_link_card_service.rb
Labels: ui

#6480 After click to embed video, autoplay it
  app/javascript/mastodon/features/status/components/card.js
Labels: ui

#6476 Fix Catalan translation of remote_follow acct
  config/locales/ca.yml
Labels: localization

#6475 Fix Spanish translation of remote_follow acct
  config/locales/es.yml
Labels: localization

#6487 Limit the languages used for notification mailer test
  spec/mailers/notification_mailer_spec.rb
Labels: testing

#6450 Isolate each specs for cache store
  config/environments/test.rb
  spec/models/setting_spec.rb
  spec/presenters/instance_presenter_spec.rb
  spec/rails_helper.rb
Labels: testing

#6482 Cache relationships in API
  app/javascript/mastodon/actions/search.js
  app/models/account_domain_block.rb
  app/models/block.rb
  app/models/concerns/relationship_cacheable.rb
  app/models/follow.rb
  app/models/follow_request.rb
  app/models/mute.rb
  app/presenters/account_relationships_presenter.rb
Labels: performance

#6507 Fix media spoiler design
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/stream_entries.scss
Labels: ui

#6508 Don't resize avatars/headers if their dimensions are already right
  app/models/concerns/account_avatar.rb
  app/models/concerns/account_header.rb
Labels: bug

#6517 Improve performance of feed_manager_spec
  spec/lib/feed_manager_spec.rb
Labels: testing

#6514 Set Docker permissions during the build process
  Dockerfile
  docker_entrypoint.sh
Labels: deployment

#6513 Use pull queue for chewy jobs
  config/initializers/chewy.rb
Labels: bug

#6515 Fix avatar and header issues by using custom geometry detector
  Gemfile
  Gemfile.lock
  app/lib/fast_geometry_parser.rb
  app/models/concerns/account_avatar.rb
  app/models/concerns/account_header.rb
  app/models/media_attachment.rb
  app/models/preview_card.rb
  app/models/site_upload.rb
  config/application.rb
  lib/paperclip/lazy_thumbnail.rb
Labels: bug

#6527 Fix bug in relationships API introduced by #6482
  app/controllers/api/v1/accounts/relationships_controller.rb
  app/presenters/account_relationships_presenter.rb
  spec/controllers/api/v1/accounts/relationships_controller_spec.rb
Labels: bug

#6529 Make sure file is opened in LazyThumbnail processor
  app/models/concerns/account_avatar.rb
  app/models/concerns/account_header.rb
  lib/paperclip/lazy_thumbnail.rb
Labels: bug

#6520 Focal points
  app/controllers/api/v1/media_controller.rb
  app/javascript/images/reticle.png
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/features/compose/components/upload.js
  app/javascript/mastodon/features/compose/containers/upload_container.js
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/features/video/index.js
  app/javascript/mastodon/reducers/compose.js
  app/javascript/styles/mastodon/components.scss
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/adapter.rb
  app/models/media_attachment.rb
  app/serializers/activitypub/image_serializer.rb
Labels: activitypub, api, ui

#6528 Only store redirect location if not in JSON format
  app/controllers/application_controller.rb
Labels: bug

#6486 Redesign landing page (again)
  app/controllers/admin/settings_controller.rb
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/presenters/instance_presenter.rb
  app/views/about/_forms.html.haml
  app/views/about/_links.html.haml
  app/views/about/_registration.html.haml
  app/views/about/more.html.haml
  app/views/about/show.html.haml
  app/views/about/terms.html.haml
  app/views/admin/settings/edit.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/zh-CN.yml
  spec/views/about/show.html.haml_spec.rb
Labels: ui

#6531 Fix container regression
  app/views/layouts/auth.html.haml
  app/views/layouts/modal.html.haml
  app/views/layouts/public.html.haml
Labels: ui

#6537 Fix nil error in focal_point?
  app/serializers/activitypub/image_serializer.rb
Labels: bug

#6550 i18n: Update Japanese translations
  config/locales/ja.yml
  config/locales/simple_form.ja.yml
Labels: localization

#6559 Improve public account cards
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/javascript/styles/mastodon/accounts.scss
  app/views/accounts/_follow_button.html.haml
  app/views/accounts/_grid_card.html.haml
  app/views/accounts/_header.html.haml
Labels: ui

#6543 Better grid layout for the landing page
  app/javascript/styles/mastodon/about.scss
  app/views/about/show.html.haml
Labels: ui

#6545 Grid layout for tag pages
  app/javascript/styles/mastodon/about.scss
  app/views/tags/_features.html.haml
  app/views/tags/show.html.haml
Labels: ui

#6570 Federated reports
  app/controllers/api/v1/reports_controller.rb
  app/javascript/mastodon/actions/reports.js
  app/javascript/mastodon/features/ui/components/report_modal.js
  app/javascript/mastodon/reducers/reports.js
  app/javascript/styles/mastodon/components.scss
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/flag.rb
  app/models/report.rb
  app/serializers/activitypub/flag_serializer.rb
  app/services/report_service.rb
  db/schema.rb
  spec/lib/activitypub/activity/flag_spec.rb
  spec/services/report_service_spec.rb
Labels: activitypub, admin support

#6571 Reject->Follow will remove the follow if it exists
  app/lib/activitypub/activity/reject.rb
Labels: activitypub
