Repository mastodon/mastodon, pull requests merged in 2018-12, with the labels that each got.

#9290 Improve account suspension speed and completeness
  app/models/account.rb
  app/models/concerns/account_associations.rb
  app/services/batched_remove_status_service.rb
  app/services/suspend_account_service.rb
  app/workers/admin/suspension_worker.rb
  lib/mastodon/domains_cli.rb
Labels: performance

#9427 Add profile directory
  app/controllers/admin/tags_controller.rb
  app/controllers/api/v1/accounts/credentials_controller.rb
  app/controllers/directories_controller.rb
  app/controllers/settings/profiles_controller.rb
  app/helpers/admin/filter_helper.rb
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/widgets.scss
  app/models/account.rb
  app/models/account_stat.rb
  app/models/account_tag_stat.rb
  app/models/concerns/account_associations.rb
  app/models/concerns/account_counters.rb
  app/models/tag.rb
  app/policies/tag_policy.rb
  app/services/update_account_service.rb
  app/views/admin/tags/_tag.html.haml
  app/views/admin/tags/index.html.haml
  app/views/directories/index.html.haml
  app/views/layouts/public.html.haml
  app/views/settings/profiles/show.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20181203003808_create_accounts_tags_join_table.rb
  db/migrate/20181203021853_add_discoverable_to_accounts.rb
  db/migrate/20181204193439_add_last_status_at_to_account_stats.rb
  db/migrate/20181204215309_create_account_tag_stats.rb
  db/schema.rb
  spec/fabricators/account_tag_stat_fabricator.rb
  spec/models/account_tag_stat_spec.rb
Labels: ui

#9449 Fix various things in the directory
  app/javascript/styles/mastodon/widgets.scss
  app/models/tag.rb
  app/views/directories/index.html.haml
Labels: bug

#9464 Make notification time smaller and reduce contrast
  app/javascript/styles/mastodon/components.scss
Labels: ui

#9465 Cache hashtag sample accounts, and exclude ineligible ones
  app/models/account.rb
  app/models/tag.rb
  app/views/directories/index.html.haml
Labels: bug, performance

#9489 Improve e-mail MX validator and add tests
  app/models/user.rb
  app/validators/email_mx_validator.rb
  spec/validators/email_mx_validator_spec.rb
Labels: admin support, bug, testing

#9491 [i18n] Update Occitan
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/ms.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ro.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/ta.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/oc.yml
  config/locales/simple_form.oc.yml
Labels: i18n

#9504 Use find_or_initialize_by
  app/services/pubsubhubbub/subscribe_service.rb
Labels: refactoring

#9511 Fix bootsnap cache directory being declared relatively
  config/boot.rb
Labels: bug

#9527 I18n: Correct pluralization of Czech
  config/locales/cs.yml
  config/locales/devise.cs.yml
Labels: i18n

#9399 Add notification quick-filter bar in the frontend app
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/notifications/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/filter_bar.js
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/notifications/containers/filter_bar_container.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/styles/mastodon/components.scss
Labels: ui, work in progress

#9434 Add timeout to web push workers and stop retries when getting 4xx
  app/models/web/push_subscription.rb
  app/workers/web/push_notification_worker.rb
Labels: performance

#9539 Remove "most popular" tab from profile directory, add responsive design
  app/controllers/directories_controller.rb
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/widgets.scss
  app/models/account.rb
  app/views/directories/index.html.haml
  app/views/layouts/public.html.haml
  config/locales/ar.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eu.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/sk.yml
  config/routes.rb
Labels: ui

#9541 Fix regression in #9539
  app/models/account.rb
Labels: bug

#9531 Add new first-time tutorial
  app/javascript/images/screen_federation.svg
  app/javascript/images/screen_hello.svg
  app/javascript/images/screen_interactions.svg
  app/javascript/mastodon/actions/onboarding.js
  app/javascript/mastodon/containers/mastodon.js
  app/javascript/mastodon/features/introduction/index.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/features/ui/components/onboarding_modal.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/styles/application.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/introduction.scss
Labels: ui

#9554 Make notifications quick-filter use consistent style with profile tabs
  app/javascript/styles/mastodon/components.scss
Labels: ui

#9573 Allow unauthenticated REST API access to GET /api/v1/accounts/:id/statuses
  app/controllers/api/v1/accounts/statuses_controller.rb
Labels: api

#9590 Skip mailer job retries when a record no longer exists
  config/initializers/delivery_job.rb
Labels: bug

#9609 Show 40 profiles per directory page instead of 30
  app/controllers/directories_controller.rb
Labels: ui

#9552 Sanitize and sandbox toot embeds
  app/controllers/api/web/embeds_controller.rb
  app/javascript/mastodon/features/ui/components/embed_modal.js
Labels: security

#9572 Add REST API for creating an account
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/auth/confirmations_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/models/user.rb
  app/services/app_sign_up_service.rb
  app/views/user_mailer/confirmation_instructions.html.haml
  app/views/user_mailer/confirmation_instructions.text.erb
  config/initializers/rack_attack.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20181219235220_add_created_by_application_id_to_users.rb
  db/schema.rb
  lib/mastodon/accounts_cli.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/fabricators/user_fabricator.rb
  spec/models/user_spec.rb
  spec/services/app_sign_up_service_spec.rb
Labels: api

#9628 Fix ThreadResolveWorker getting queued with invalid URLs
  app/lib/activitypub/activity/create.rb
  app/lib/ostatus/activity/creation.rb
  app/lib/request.rb
Labels: bug

#9639 Redirect to reports overview instead of report after account action
  app/controllers/admin/account_actions_controller.rb
Labels: admin support

#9640 Add exclude_reblogs option to account statuses API
  app/controllers/api/v1/accounts/statuses_controller.rb
Labels: api

#9643 Improve admin UI for account view
  app/controllers/admin/accounts_controller.rb
  app/javascript/styles/mastodon/dashboard.scss
  app/models/user.rb
  app/services/resolve_account_service.rb
  app/views/admin/accounts/show.html.haml
  app/views/admin/followers/index.html.haml
  app/views/admin/statuses/index.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/ms.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: admin support

#9675 Remove visible timestamps for notifications
  app/javascript/mastodon/features/notifications/components/notification.js
Labels: ui
