Repository mastodon/mastodon, pull requests merged in 2018-09, with the labels that each got.

#8534 Fix wrong string being used on login failure when using LDAP
  lib/devise/ldap_authenticatable.rb
Labels: bug

#8548 Fix static URL when disable autoplay (regression from #8507)
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
Labels: bug

#8555 Integrating `:one` and `:other` in ar.yml (regression from #8535)
  config/locales/ar.yml
Labels: bug

#8559 Add preference for report notification e-mails, skip for duplicates
  app/controllers/settings/preferences_controller.rb
  app/models/report.rb
  app/models/user.rb
  app/services/report_service.rb
  app/views/settings/notifications/show.html.haml
  config/locales/simple_form.en.yml
  config/settings.yml
  spec/services/report_service_spec.rb
Labels: admin support

#8560 Whitelist report notification param in Settings::NotificationsController
  app/controllers/settings/notifications_controller.rb
Labels: bug

#8561 Weblate translations (2018-09-01)
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/ro.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/whitelist_ro.json
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/devise.cy.yml
  config/locales/el.yml
  config/locales/fa.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/simple_form.cy.yml
Labels: internationalization

#8578 Fix nil error in admin_account_link_to helper
  app/helpers/admin/account_moderation_notes_helper.rb
Labels: bug

#8582 Weblate translations (2018-09-02)
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/sr.json
  config/locales/co.yml
  config/locales/de.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.sr.yml
  config/locales/sr.yml
Labels: internationalization

#8583 Enable ro and ta locales in Rails
  app/helpers/settings_helper.rb
  config/application.rb
Labels: internationalization

#8584 Redirect from old authorize_follow path
  config/routes.rb
Labels: bug

#8637 Fix dropdown arrow position
  app/javascript/styles/mastodon/components.scss
Labels: ui

#8652 RU: Translation fixes
  app/javascript/mastodon/locales/ru.json
  config/locales/ru.yml
  config/locales/simple_form.ru.yml
Labels: localization

#8642 tootctl accounts [add|del|cull]
  lib/mastodon/accounts_cli.rb
  lib/mastodon/cli_helper.rb
Labels: admin support

#8674 Group reports by target account
  app/helpers/admin/account_moderation_notes_helper.rb
  app/helpers/home_helper.rb
  app/javascript/styles/mastodon/admin.scss
  app/views/admin/reports/_account.html.haml
  app/views/admin/reports/_report.html.haml
  app/views/admin/reports/index.html.haml
  app/views/settings/exports/show.html.haml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: admin support, ui

#8692 Weblate translations (2018-09-13)
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ro.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/activerecord.ast.yml
  config/locales/activerecord.cy.yml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/devise.ast.yml
  config/locales/devise.cy.yml
  config/locales/doorkeeper.ast.yml
  config/locales/en_GB.yml
  config/locales/es.yml
  config/locales/it.yml
  config/locales/ko.yml
  config/locales/oc.yml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ast.yml
  config/locales/simple_form.cy.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.en_GB.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.ro.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.zh-TW.yml
  config/locales/sk.yml
  config/locales/sr.yml
  config/locales/zh-TW.yml
Labels: localization

#8675 Move more tasks to tootctl
  .rubocop.yml
  lib/cli.rb
  lib/mastodon/accounts_cli.rb
  lib/mastodon/emoji_cli.rb
  lib/mastodon/feeds_cli.rb
  lib/mastodon/media_cli.rb
  lib/tasks/mastodon.rake
Labels: admin support

#8696 i18n: Add ja translations
  config/locales/ja.yml
Labels: localization

#8708 add several missing alt tags
  app/views/about/more.html.haml
  app/views/about/show.html.haml
Labels: accessibility

#8715 Fix “Toots” tab highlighting for replies and media timelines
  app/javascript/mastodon/features/account/components/action_bar.js
  app/views/accounts/_header.html.haml
Labels: ui

#8703 Redesign forms, verify link ownership with rel="me"
  app/helpers/home_helper.rb
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/boost.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/forms.scss
  app/lib/activitypub/activity/update.rb
  app/models/account.rb
  app/serializers/rest/account_serializer.rb
  app/services/activitypub/process_account_service.rb
  app/services/fetch_link_card_service.rb
  app/services/update_account_service.rb
  app/services/verify_link_service.rb
  app/views/about/_registration.html.haml
  app/views/accounts/_bio.html.haml
  app/views/admin/change_emails/show.html.haml
  app/views/admin/custom_emojis/new.html.haml
  app/views/admin/domain_blocks/new.html.haml
  app/views/admin/email_domain_blocks/new.html.haml
  app/views/admin/settings/edit.html.haml
  app/views/auth/confirmations/finish_signup.html.haml
  app/views/auth/confirmations/new.html.haml
  app/views/auth/passwords/edit.html.haml
  app/views/auth/passwords/new.html.haml
  app/views/auth/registrations/edit.html.haml
  app/views/auth/registrations/new.html.haml
  app/views/auth/sessions/new.html.haml
  app/views/auth/sessions/two_factor.html.haml
  app/views/filters/_fields.html.haml
  app/views/invites/_form.html.haml
  app/views/invites/index.html.haml
  app/views/settings/applications/_fields.html.haml
  app/views/settings/imports/show.html.haml
  app/views/settings/preferences/show.html.haml
  app/views/settings/profiles/show.html.haml
  app/views/settings/two_factor_authentication/confirmations/new.html.haml
  app/views/settings/two_factor_authentications/show.html.haml
  app/workers/verify_account_links_worker.rb
  config/initializers/simple_form.rb
  config/locales/en.yml
  config/locales/simple_form.en.yml
  spec/services/verify_link_service_spec.rb
Labels: ui

#8719 Fix performance regression in Account::Field#verifiable?
  app/models/account.rb
Labels: bug, performance

#8721 Fix VerifyAccountLinksWorker not being queued
  app/services/update_account_service.rb
Labels: bug

#8727 i18n: Update Polish translation
  config/locales/pl.yml
Labels: localization

#8733 Fix failed profile verification when rel attribute including values other than me
  app/services/verify_link_service.rb
  spec/services/verify_link_service_spec.rb
Labels: bug

#8764 RTL: fix settings button margins in column headers
  app/javascript/styles/mastodon/rtl.scss
Labels: bug, internationalization, ui

#8765 Cache instance info
  app/controllers/api/v1/instances_controller.rb
Labels: api, performance

#8767 RTL: fix statubar action buttons/counter margins
  app/javascript/styles/mastodon/rtl.scss
Labels: ui

#8770 Add nginx and systemd templates
  config/sidekiq.yml
  dist/mastodon-sidekiq.service
  dist/mastodon-streaming.service
  dist/mastodon-web.service
  dist/nginx.conf
  docs/Contributing-to-Mastodon/Sponsors.md
  docs/Contributing-to-Mastodon/Translating.md
  docs/Extensions.md
  docs/README.md
  docs/Running-Mastodon/Administration-guide.md
  docs/Running-Mastodon/Development-guide.md
  docs/Running-Mastodon/Heroku-guide.md
  docs/Running-Mastodon/Production-guide.md
  docs/Running-Mastodon/Scalingo-guide.md
  docs/Running-Mastodon/Tuning.md
  docs/Running-Mastodon/Vagrant-guide.md
  docs/Specs-and-RFCs-used.md
  docs/Using-Mastodon/2FA.md
  docs/Using-Mastodon/Apps.md
  docs/Using-Mastodon/FAQ.md
  docs/Using-Mastodon/List-of-Mastodon-instances.md
  docs/Using-Mastodon/User-guide.md
  docs/Using-the-API/API.md
  docs/Using-the-API/OAuth-details.md
  docs/Using-the-API/Push-notifications.md
  docs/Using-the-API/Streaming-API.md
  docs/Using-the-API/Testing-with-cURL.md
  docs/Using-the-API/Tips-for-app-developers.md
Labels: docs

#8768 Weblate translations (2018-09-24)
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/it.json
  config/locales/ar.yml
  config/locales/cy.yml
  config/locales/devise.cy.yml
  config/locales/doorkeeper.cy.yml
  config/locales/it.yml
  config/locales/pl.yml
  config/locales/simple_form.cy.yml
  config/locales/simple_form.sk.yml
  config/locales/sk.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
Labels: localization

#8776 Update icon name changed by the Font Awesome 5 (regression from #8484)
  app/javascript/mastodon/features/compose/index.js
  app/views/layouts/modal.html.haml
  config/navigation.rb
Labels: bug, ui

#8792 Fix some icons names, unavailable in fontawesome5 (free license).
  app/javascript/mastodon/components/column_header.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
Labels: bug, ui

#8795 Fix broken report detail (regression from #8569)
  app/views/admin/reports/_status.html.haml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.cs.yml
  config/locales/simple_form.cy.yml
  config/locales/simple_form.da.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.el.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fa.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ka.yml
  config/locales/simple_form.ko.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pl.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.ro.yml
  config/locales/simple_form.ru.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sr.yml
  config/locales/simple_form.sv.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
Labels: bug

#8799 Migrate to font-awesome 5.0.
  app/helpers/application_helper.rb
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar-test.js.snap
  app/javascript/mastodon/components/attachment_list.js
  app/javascript/mastodon/components/bot_icon.js
  app/javascript/mastodon/components/column_back_button.js
  app/javascript/mastodon/components/column_back_button_slim.js
  app/javascript/mastodon/components/column_header.js
  app/javascript/mastodon/components/icon_button.js
  app/javascript/mastodon/components/load_gap.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/components/moved_note.js
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/features/compose/components/privacy_dropdown.js
  app/javascript/mastodon/features/compose/components/search.js
  app/javascript/mastodon/features/compose/components/search_results.js
  app/javascript/mastodon/features/compose/components/upload.js
  app/javascript/mastodon/features/compose/components/upload_progress.js
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/list_editor/components/search.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/notifications/components/clear_column_button.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/features/pinned_statuses/index.js
  app/javascript/mastodon/features/status/components/card.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/components/boost_modal.js
  app/javascript/mastodon/features/ui/components/column_header.js
  app/javascript/mastodon/features/ui/components/column_link.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/mastodon/features/ui/components/onboarding_modal.js
  app/javascript/mastodon/features/ui/components/tabs_bar.js
  app/javascript/mastodon/features/video/index.js
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/rtl.scss
  app/javascript/styles/mastodon/tables.scss
  app/javascript/styles/mastodon/widgets.scss
  app/views/about/_links.html.haml
  app/views/stream_entries/_status.html.haml
  spec/helpers/application_helper_spec.rb
Labels: ui

#8811 Add tootctl accounts backup
  lib/mastodon/accounts_cli.rb
Labels: admin support

#8820 Fix class autoloading issue in ActivityPub::Activity::Create
  app/lib/activitypub/activity/create.rb
Labels: bug

#8823 RTL: fix margins: public-layout.header.nav-button
  app/javascript/styles/mastodon/rtl.scss
Labels: bug, internationalization, ui

#8812 Fix tootctl accounts reattaching not unsuspending deleted account
  lib/mastodon/accounts_cli.rb
Labels: admin support, bug

#8827 Fix timeline pagination
  app/models/concerns/paginable.rb
Labels: bug

#8831 Fix that Rails.cache information could not be sent via StatsD
  config/initializers/statsd.rb
Labels: bug
