Repository mastodon/mastodon, pull requests merged in 2018-11, with the labels that each got.

#8904 Allow joining several hashtags in a single column
  app/controllers/api/v1/timelines/tag_controller.rb
  app/controllers/tags_controller.rb
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js
  app/javascript/mastodon/features/hashtag_timeline/containers/column_settings_container.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/features/standalone/hashtag_timeline/index.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/timelines.js
  app/javascript/styles/mastodon/_mixins.scss
  app/javascript/styles/mastodon/components.scss
  app/models/status.rb
  app/services/hashtag_query_service.rb
  config/brakeman.ignore
  package.json
  spec/services/hashtag_query_service_spec.rb
  yarn.lock
Labels: ui

#9227 Increase default column width from 330px to 350px
  app/javascript/styles/mastodon/components.scss
Labels: ui

#9233 Cancel list scroll reset after mouse move on wheel scroll
  app/javascript/mastodon/components/scrollable_list.js
Labels: bug

#9220 Optimize the process of following someone
  app/controllers/api/v1/accounts_controller.rb
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/reducers/relationships.js
  app/services/concerns/author_extractor.rb
  app/services/follow_service.rb
  app/services/process_mentions_service.rb
  app/services/resolve_account_service.rb
  app/workers/local_notification_worker.rb
  spec/controllers/authorize_interactions_controller_spec.rb
Labels: performance, ui

#9230 Fix follow limit validator reporting lower number past threshold
  app/validators/follow_limit_validator.rb
Labels: bug

#9229 Display amount of freed disk space in tootctl media remove
  lib/mastodon/media_cli.rb
Labels: admin support

#9228 Add "Show thread" link to self-replies
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/status/components/action_bar.js
Labels: ui

#9224 Use local instead of global loading indicator for timelines, account timelines
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/components/scrollable_list.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/styles/mastodon/components.scss
Labels: performance, ui

#9236 Reduce connect timeout limit and limit signature failures by source IP
  app/controllers/concerns/signature_verification.rb
  app/lib/request.rb
Labels: performance

#9239 Fix nil error regression from #9229 in tootctl media remove
  lib/mastodon/media_cli.rb
Labels: bug

#9252 Fix loading indicator inconsistency
  app/javascript/mastodon/actions/custom_emojis.js
  app/javascript/mastodon/actions/favourites.js
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/features/notifications/index.js
Labels: ui

#9261 i18n: Add ja translations
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/ja.json
Labels: i18n

#9275 Fix null error introduced in #9270
  app/javascript/mastodon/features/status/components/card.js
Labels: bug

#9291 Remove intermediary arrays when creating hash maps from results
  app/controllers/application_controller.rb
  app/lib/entity_cache.rb
  app/lib/formatter.rb
  app/lib/settings/scoped_settings.rb
  app/models/concerns/account_interactions.rb
  app/models/notification.rb
  app/models/setting.rb
  app/models/status.rb
  app/models/trending_tags.rb
  app/services/batched_remove_status_service.rb
  spec/models/notification_spec.rb
Labels: performance

#9292 Prevent multiple handlers for Delete of Actor from running at the same time
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/delete.rb
Labels: bug

#9295 Move account counters to separate table
  app/controllers/admin/instances_controller.rb
  app/controllers/api/v1/accounts/follower_accounts_controller.rb
  app/controllers/api/v1/accounts/following_accounts_controller.rb
  app/controllers/api/v1/blocks_controller.rb
  app/controllers/api/v1/endorsements_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/controllers/api/v1/lists/accounts_controller.rb
  app/controllers/api/v1/statuses/favourited_by_accounts_controller.rb
  app/controllers/api/v1/statuses/reblogged_by_accounts_controller.rb
  app/models/account.rb
  app/models/account_stat.rb
  app/models/concerns/account_counters.rb
  app/models/follow.rb
  app/models/notification.rb
  app/models/status.rb
  app/presenters/instance_presenter.rb
  db/migrate/20181116165755_create_account_stats.rb
  db/migrate/20181116173541_copy_account_stats.rb
  db/post_migrate/20181116184611_copy_account_stats_cleanup.rb
  db/schema.rb
  spec/fabricators/account_stat_fabricator.rb
  spec/models/account_spec.rb
  spec/models/account_stat_spec.rb
  spec/models/notification_spec.rb
  spec/models/status_stat_spec.rb
Labels: performance

#9303 Fix filter ID not being a string in REST API
  app/serializers/rest/filter_serializer.rb
Labels: api, bug

#9314 Cast status_count to integer
  app/presenters/instance_presenter.rb
Labels: bug

#9329 Fix connect timeout not being enforced
  app/lib/request.rb
  spec/lib/request_spec.rb
Labels: bug, performance, security

#9335 Revert "Sort self-replies to the top of the thread (#9296)"
  app/models/concerns/status_threading_concern.rb
Labels: bug

#9320 Sort self-replies to the top of descendants
  app/models/concerns/status_threading_concern.rb
  spec/models/concerns/status_threading_concern_spec.rb
Labels: api

#9340 Redesign admin accounts index
  app/controllers/admin/accounts_controller.rb
  app/helpers/admin/account_moderation_notes_helper.rb
  app/helpers/admin/filter_helper.rb
  app/helpers/stream_entries_helper.rb
  app/javascript/packs/public.js
  app/models/account.rb
  app/models/account_filter.rb
  app/models/user.rb
  app/views/admin/accounts/_account.html.haml
  app/views/admin/accounts/index.html.haml
  app/views/admin/accounts/show.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sl.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  spec/controllers/admin/accounts_controller_spec.rb
  spec/models/account_filter_spec.rb
  spec/models/user_spec.rb
Labels: admin support

#9371 Change identities id column to a bigint
  app/models/identity.rb
  db/migrate/20181127130500_identity_id_to_bigint.rb
  db/schema.rb
Labels: bug

#9375 Do not leak existence of e-mail addresses during login attempt in French translation
  config/locales/devise.fr.yml
Labels: security

#9379 Fix nil error when no DNS addresses are found for host
  app/lib/request.rb
Labels: bug

#9380 Don't count suspended users in user count
  app/presenters/instance_presenter.rb
Labels: bug

#9358 Skip deliveries to inboxes that have already been marked as unavailable
  app/workers/activitypub/delivery_worker.rb
Labels: performance

#9381 Fix TLS handshake timeout not being enforced
  app/lib/request.rb
Labels: bug, security

#9401 Remove npm-run-all dependency
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js
  package.json
  yarn.lock
Labels: dependencies
