Repository mastodon/mastodon, pull requests merged in 2018-04, with the labels that each got.

#6988 improve zh-HK localization by referring zh-TW and zh-CN
  config/locales/activerecord.zh-HK.yml
  config/locales/devise.zh-HK.yml
  config/locales/doorkeeper.zh-HK.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/zh-HK.yml
Labels: localization

#6997 Support all ActivityPub actor types
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/fetch_remote_key_service.rb
  app/services/fetch_atom_service.rb
  app/services/resolve_account_service.rb
  app/services/resolve_url_service.rb
Labels: activitypub

#7004 i18n: update zh-HK translation
  app/javascript/mastodon/locales/zh-HK.json
  config/locales/simple_form.zh-HK.yml
  config/locales/zh-HK.yml
Labels: localization

#7005 Russian language updated
  app/javascript/mastodon/locales/ru.json
  config/locales/doorkeeper.ru.yml
  config/locales/ru.yml
  config/locales/simple_form.ru.yml
Labels: localization

#7007 Weblate translations (2018-04-02)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/ar.yml
  config/locales/devise.zh-TW.yml
  config/locales/doorkeeper.ar.yml
  config/locales/doorkeeper.fa.yml
  config/locales/doorkeeper.id.yml
  config/locales/doorkeeper.sk.yml
  config/locales/doorkeeper.zh-TW.yml
  config/locales/eo.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/simple_form.ko.yml
  config/locales/sk.yml
Labels: localization

#7022 i18n: Add Japanese translations for #7000
  app/javascript/mastodon/locales/defaultMessages.json
  config/locales/ja.yml
Labels: localization

#6984 Add contact account to landing page ("Administered by")
  app/javascript/styles/mastodon/about.scss
  app/views/about/show.html.haml
  config/locales/en.yml
  spec/views/about/show.html.haml_spec.rb
Labels: ui

#6666 Adjust privacy policy
  app/javascript/styles/mastodon/about.scss
  app/workers/scheduler/ip_cleanup_scheduler.rb
  config/locales/ca.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/zh-CN.yml
Labels: breaking, legal

#7058 Forward deletes on the same path as reply forwarding
  app/lib/activitypub/activity/delete.rb
Labels: activitypub

#7053 Add a circuit breaker for ActivityPub deliveries
  Gemfile
  Gemfile.lock
  app/workers/activitypub/delivery_worker.rb
  config/initializers/stoplight.rb
Labels: activitypub

#6789 Enable updating additional account information from user preferences via rest api
  app/controllers/api/v1/accounts/credentials_controller.rb
  app/lib/user_settings_decorator.rb
  spec/controllers/api/v1/accounts/credentials_controller_spec.rb
  spec/lib/user_settings_decorator_spec.rb
Labels: api

#7083 Exclude status itself from context query
  app/models/concerns/status_threading_concern.rb
Labels: refactoring

#7085 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#7100 Improve load gap styling in web UI
  app/javascript/mastodon/components/load_gap.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#7102 Paginate ancestor statuses in public page
  app/controllers/api/v1/statuses_controller.rb
  app/controllers/statuses_controller.rb
  app/javascript/styles/mastodon/stream_entries.scss
  app/models/concerns/status_threading_concern.rb
  app/views/stream_entries/_status.html.haml
  spec/models/concerns/status_threading_concern_spec.rb
  spec/views/stream_entries/show.html.haml_spec.rb
Labels: performance, ui

#7049 i18n: Add Japanese translations for privacy policy and more
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/ja.json
  config/locales/ja.yml
Labels: localization

#7131 i18n: Update Polish translation
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/pl.json
  config/locales/en.yml
  config/locales/pl.yml
Labels: localization

#7138 docker-compose: Only bind ports 3000 and 4000 on localhost.
  docker-compose.yml
Labels: deployment

#7002 Add and revise Traditional Chinese (zh-TW) translation for serveral strings
  app/javascript/mastodon/locales/zh-TW.json
Labels: localization

#7141 Weblate translations (2018-04-15)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/ar.yml
  config/locales/devise.fi.yml
  config/locales/devise.sk.yml
  config/locales/doorkeeper.fi.yml
  config/locales/doorkeeper.sk.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/fi.yml
  config/locales/ja.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.sk.yml
  config/locales/sk.yml
Labels: localization

#7104 Redirect to account status page for page of status stream entry
  app/controllers/stream_entries_controller.rb
  spec/controllers/stream_entries_controller_spec.rb
Labels: bug

#7149 Fix status filtering in contexts reducer
  app/javascript/mastodon/reducers/contexts.js
Labels: bug

#7165 Update "private" label in French javascript locale file
  app/javascript/mastodon/locales/fr.json
Labels: localization

#7168 Perform processing before connecting to the database
  streaming/index.js
Labels: refactoring

#7177 zh-HK translation
  app/javascript/mastodon/locales/zh-HK.json
  config/locales/devise.zh-HK.yml
  config/locales/doorkeeper.zh-HK.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/zh-HK.yml
Labels: localization

#4514 Direct messages column
  app/controllers/api/v1/timelines/direct_controller.rb
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/features/direct_timeline/containers/column_settings_container.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  app/javascript/mastodon/reducers/contexts.js
  app/javascript/mastodon/reducers/settings.js
  app/models/status.rb
  app/services/batched_remove_status_service.rb
  app/services/fan_out_on_write_service.rb
  app/services/remove_status_service.rb
  config/routes.rb
  spec/models/status_spec.rb
  streaming/index.js
  yarn.lock
Labels: ui, work in progress

#7180 Fix comparing id
  app/javascript/mastodon/compare_id.js
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/timelines.js
Labels: bug

#7125 Add color variables of texts for better accesibility
  app/javascript/mastodon/features/ui/components/actions_modal.js
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/boost.scss
  app/javascript/styles/mastodon/compact_header.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  app/javascript/styles/mastodon/footer.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/landing_strip.scss
  app/javascript/styles/mastodon/stream_entries.scss
  app/javascript/styles/mastodon/tables.scss
  app/javascript/styles/mastodon/variables.scss
Labels: accessibility, ui

#7181 i18n: Update Polish translation
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
  config/locales/simple_form.pl.yml
Labels: localization

#7184 Rescue SSL errors when processing mentions, remove useless line
  app/services/process_mentions_service.rb
Labels: bug

#7183 Fix text color in "show more" link inside boost confirmation modal
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7192 Replace preload link tag to Rails helper
  app/views/home/index.html.haml
Labels: enhancement, performance

#7188 Improve report layout
  app/controllers/admin/reported_statuses_controller.rb
  app/controllers/admin/reports_controller.rb
  app/helpers/admin/account_moderation_notes_helper.rb
  app/helpers/application_helper.rb
  app/helpers/stream_entries_helper.rb
  app/javascript/packs/admin.js
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/tables.scss
  app/views/admin/action_logs/_action_log.html.haml
  app/views/admin/action_logs/index.html.haml
  app/views/admin/report_notes/_report_note.html.haml
  app/views/admin/reports/_account.html.haml
  app/views/admin/reports/_account_details.html.haml
  app/views/admin/reports/_action_log.html.haml
  app/views/admin/reports/_report.html.haml
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/index.html.haml
  app/views/admin/reports/show.html.haml
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  spec/controllers/admin/reported_statuses_controller_spec.rb
Labels: admin support, ui

#7196 Replace Travis to CircleCI
  .circleci/config.yml
  .travis.yml
Labels: testing

#7199 Fix Esc hotkey behavior
  app/javascript/mastodon/components/autosuggest_textarea.js
Labels: bug, ui

#7203 Fix spec for sr-Latn
  app/controllers/concerns/localized.rb
Labels: bug, testing

#7205 Ignore keyevents during text composition
  app/javascript/mastodon/components/autosuggest_textarea.js
Labels: bug, ui

#7206 Introduce rspec-retry
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: testing

#7212 one grammar fix
  app/javascript/mastodon/locales/fr.json
Labels: localization

#7213 Separate high contrast theme
  app/javascript/styles/contrast.scss
  app/javascript/styles/contrast/diff.scss
  app/javascript/styles/contrast/variables.scss
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/compact_header.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/landing_strip.scss
  app/javascript/styles/mastodon/stream_entries.scss
  app/javascript/styles/mastodon/variables.scss
  config/locales/en.yml
  config/themes.yml
Labels: accessibility, ui

#7215 Add parallel test processors
  .circleci/config.yml
  .env.test
Labels: testing

#7216 Replace badge to CircleCI
  README.md
Labels: docs

#7219 Reset locale on registration tests
  spec/controllers/auth/registrations_controller_spec.rb
Labels: bug, testing

#7185 Fix: Use "welches" instead of "dass" in translation
  config/locales/de.yml
Labels: localization

#7225 Fix randomly fail (similar #7219)
  spec/controllers/concerns/localized_spec.rb
Labels: bug, testing

#7207 Do not set emoji as inline-block (fixes #5743)
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#7227 Fix text colors related to separating high contrast theme
  app/javascript/styles/contrast/variables.scss
  app/javascript/styles/mastodon/components.scss
Labels: accessibility, ui

#7186 Fix: Use "exportierten" instead of "exportieren" in translation
  config/locales/de.yml
Labels: localization

#7228 Rescue Mastodon::LengthValidationError in Remoteable
  app/models/concerns/remotable.rb
Labels: bug

#7048 Remove "nsfw" category for sensitive statuses in OStatus serializer
  app/lib/ostatus/atom_serializer.rb
  app/services/process_hashtags_service.rb
  spec/lib/ostatus/atom_serializer_spec.rb
Labels: breaking

#7223 Resize images before upload in web UI to reduce bandwidth
  app/javascript/mastodon/actions/compose.js
Labels: performance, ui

#7233 Improve relative timestamps in web UI
  app/javascript/mastodon/components/relative_timestamp.js
Labels: ui

#7236 Refactor resizeImage method
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/push_notifications/registerer.js
  app/javascript/mastodon/base_polyfills.js
  app/javascript/mastodon/load_polyfills.js
  app/javascript/mastodon/utils/__tests__/base64-test.js
  app/javascript/mastodon/utils/base64.js
  app/javascript/mastodon/utils/resize_image.js
Labels: performance, refactoring, ui

#7235 Move precompile step to build stage
  .circleci/config.yml
Labels: testing

#7229 Detect and prevent image bombs, max. processable dimension 4096^2
  app/lib/exceptions.rb
  app/models/concerns/attachmentable.rb
  app/models/custom_emoji.rb
  app/models/media_attachment.rb
Labels: security

#7239 🌍: Make 🇵🇱 translation more consistent
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
  config/locales/simple_form.pl.yml
Labels: localization

#7241 tasks/mastodon: fix prompt for Redis password
  lib/tasks/mastodon.rake
Labels: bug

#7148 Paginate descendant statuses in public page
  app/controllers/api/v1/statuses_controller.rb
  app/controllers/statuses_controller.rb
  app/models/concerns/status_threading_concern.rb
  app/views/stream_entries/_more.html.haml
  app/views/stream_entries/_status.html.haml
  spec/controllers/statuses_controller_spec.rb
  spec/models/concerns/status_threading_concern_spec.rb
  spec/views/stream_entries/show.html.haml_spec.rb
Labels: performance, ui

#7251 Fix ID duplication in timelines
  app/javascript/mastodon/reducers/timelines.js
Labels: bug, ui

#7263 Better phrasing in swedish translation
  app/javascript/mastodon/locales/sv.json
  config/locales/sv.yml
Labels: localization

#7266 Weblate translations 20180426
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sv.json
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/sk.yml
  config/locales/sv.yml
Labels: localization

#7267 Add Basque language support
  app/helpers/settings_helper.rb
  config/application.rb
Labels: localization

#7272 Add support for separate Redis for cache
  config/environments/production.rb
  lib/mastodon/redis_config.rb
Labels: performance

#7271 Add entity cache
  app/lib/entity_cache.rb
  app/lib/formatter.rb
  app/models/account.rb
  app/models/custom_emoji.rb
  app/models/status.rb
Labels: performance

#7285 Fix "Show more" URL on paginated threads for remote statuses
  app/controllers/statuses_controller.rb
  app/controllers/stream_entries_controller.rb
  app/views/stream_entries/_status.html.haml
Labels: bug

#7287 Return HTTP 410 for suspended accounts in GET /api/v1/accounts/:id
  app/controllers/api/v1/accounts_controller.rb
Labels: api

#7290 Fix missing domain attribute in EntityCache for emoji
  app/lib/entity_cache.rb
Labels: bug

#7289 Disable API access when login is disabled
  app/controllers/api/base_controller.rb
Labels: api

#7294 [i18n] Occitan update
  app/javascript/mastodon/locales/oc.json
  config/locales/oc.yml
  config/locales/simple_form.oc.yml
Labels: localization

#7297 Fix missing updated_at attribute on emoji EntityCache
  app/lib/entity_cache.rb
Labels: bug
