Repository mastodon/mastodon, pull requests merged in 2018-03, with the labels that each got.

#6575 Ensure that boolean params in the API are parsed for truthiness
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/accounts/search_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/search_controller.rb
  app/controllers/api/v1/timelines/public_controller.rb
  app/controllers/api/v1/timelines/tag_controller.rb
Labels: api, bug

#6573 Fix margin on top action button, fix width of counters on frontpage
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/forms.scss
  app/views/settings/preferences/show.html.haml
Labels: ui

#6572 Add "Toots/Toots with replies/Media" tab below profile header
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/features/account/components/action_bar.js
  app/javascript/mastodon/features/account_gallery/components/media_item.js
  app/javascript/mastodon/features/account_gallery/index.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/react_router_helpers.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6576 Add only_media param to public and hashtag timelines API
  app/controllers/api/v1/timelines/public_controller.rb
  app/controllers/api/v1/timelines/tag_controller.rb
Labels: api

#6578 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#6574 Add contact_account and languages to instance API
  app/serializers/rest/instance_serializer.rb
Labels: api, work in progress

#6581 i18n: Update Japanese translations
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/ja.yml
Labels: localization

#6589 Improve style of web UI account tabs
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6591 Add close modal icon to report dialog
  app/javascript/mastodon/features/ui/components/report_modal.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6588 Weblate translations (2018-03-02)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  config/locales/activerecord.ar.yml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/devise.ar.yml
  config/locales/devise.ca.yml
  config/locales/devise.de.yml
  config/locales/devise.eo.yml
  config/locales/devise.hr.yml
  config/locales/devise.hu.yml
  config/locales/devise.pt.yml
  config/locales/devise.sk.yml
  config/locales/devise.sv.yml
  config/locales/doorkeeper.ar.yml
  config/locales/doorkeeper.eo.yml
  config/locales/doorkeeper.hu.yml
  config/locales/eo.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.hu.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.pt.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sv.yml
  config/locales/sk.yml
  config/locales/sv.yml
Labels: localization

#6593 When search enabled, display hint in search popout
  app/javascript/mastodon/features/compose/components/search.js
  app/javascript/mastodon/features/ui/components/tabs_bar.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
Labels: ui

#6590 Responsively enforce 16:9 ratio on all media thumbnails in web UI
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/video/index.js
  app/javascript/styles/mastodon/components.scss
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
Labels: ui

#6594 Move "compose" on mobile to floating action button
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/tabs_bar.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6597 Change "or" translatable
  config/locales/en.yml
Labels: internationalization

#6608 Translate Korean
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/ko.json
  config/locales/ko.yml
Labels: localization

#6614 Finalize location on scrollable notifications when unmounting
  app/javascript/mastodon/features/notifications/index.js
Labels: bug

#6610 Federate pinned statuses over ActivityPub
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/api/v1/statuses/pins_controller.rb
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/add.rb
  app/lib/activitypub/activity/remove.rb
  app/lib/activitypub/adapter.rb
  app/models/account.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/add_serializer.rb
  app/serializers/activitypub/collection_serializer.rb
  app/serializers/activitypub/outbox_serializer.rb
  app/serializers/activitypub/remove_serializer.rb
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/process_account_service.rb
  app/workers/activitypub/synchronize_featured_collection_worker.rb
  config/routes.rb
  db/migrate/20180304013859_add_featured_collection_url_to_accounts.rb
  db/schema.rb
  spec/lib/activitypub/activity/add_spec.rb
  spec/lib/activitypub/activity/remove_spec.rb
  spec/lib/activitypub/activity/update_spec.rb
Labels: activitypub

#6616 Typo in change password template
  app/views/auth/passwords/edit.html.haml
Labels: bug

#6622 Do not require images in about.js and share.js
  app/javascript/packs/about.js
  app/javascript/packs/share.js
Labels: refactoring

#6619 Show media on report UI
  app/javascript/mastodon/features/report/components/status_check_box.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6624 Do not default site_title with site_hostname in InstanceHelper
  app/helpers/instance_helper.rb
  spec/helpers/instance_helper_spec.rb
Labels: refactoring

#5956 [RFC] Improved media modal
  app/javascript/mastodon/components/extended_video_player.js
  app/javascript/mastodon/features/ui/components/image_loader.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/mastodon/features/ui/components/video_modal.js
  app/javascript/mastodon/features/ui/components/zoomable_image.js
  app/javascript/styles/mastodon/components.scss
Labels: enhancement, help wanted, ui

#6632 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#6638 Normalize translations
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: localization

#6615 Replace onScrollToBottom with onLoadMore
  app/javascript/mastodon/components/scrollable_list.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/favourited_statuses/index.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/ui/containers/status_list_container.js
Labels: bug

#6644 Fix accounts' display name/bio not being set from initial state
  app/javascript/mastodon/reducers/accounts.js
Labels: bug, ui

#6652 Use withRouter for TabsBar
  app/javascript/mastodon/features/ui/components/tabs_bar.js
Labels: performance, refactoring

#6653 Use React.PureComponent instead of React.Component
  app/javascript/mastodon/features/notifications/components/clear_column_button.js
  app/javascript/mastodon/features/ui/components/bundle.js
  app/javascript/mastodon/features/ui/components/bundle_column_error.js
  app/javascript/mastodon/features/ui/components/bundle_modal_error.js
Labels: performance, refactoring

#6650 Extract routes from UI component
  app/javascript/mastodon/features/ui/index.js
Labels: performance, refactoring

#6661 Add headings to the security settings page
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/forms.scss
  app/views/auth/registrations/_sessions.html.haml
  app/views/auth/registrations/edit.html.haml
  config/locales/ar.yml
  config/locales/bg.yml
  config/locales/ca.yml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hr.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  config/navigation.rb
Labels: ui

#6662 Separate chown command in Dockerfile. Use tootsuite/mastodon image
  Dockerfile
  docker-compose.yml
Labels: deployment

#6648 Remove pointer events on the entire UI when a dropdown menu is open
  app/javascript/mastodon/actions/dropdown_menu.js
  app/javascript/mastodon/components/dropdown_menu.js
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/reducers/dropdown_menu.js
  app/javascript/mastodon/reducers/index.js
Labels: ui

#6664 Use target instead of origin in Remove activity
  app/lib/activitypub/activity/remove.rb
  app/serializers/activitypub/remove_serializer.rb
  spec/lib/activitypub/activity/remove_spec.rb
Labels: activitypub

#6668 Fix wrong target URIs in ActivityPub Add/Remove
  app/serializers/activitypub/add_serializer.rb
  app/serializers/activitypub/remove_serializer.rb
Labels: activitypub, bug

#6671 Don't double-escape statuses in titles
  app/views/stream_entries/show.html.haml
Labels: bug

#6672 Remove text requirement when media attached from statuses
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/components/status_content.js
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/features/compose/containers/compose_form_container.js
  app/javascript/mastodon/reducers/compose.js
  app/lib/formatter.rb
  app/models/status.rb
  app/services/post_status_service.rb
Labels: ui

#6674 In wide layout, columnize Mastodon features on landing page
  app/javascript/styles/mastodon/about.scss
  app/views/about/show.html.haml
Labels: ui

#6676 Fix focal point modals broken by #5956
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
Labels: bug

#6678 Fix cover behaviour of thumbnails that are wider than taller
  app/javascript/mastodon/components/media_gallery.js
Labels: bug, ui

#6684 fix validation error (media only status)
  app/lib/activitypub/activity/create.rb
  app/lib/ostatus/activity/creation.rb
Labels: bug

#6680 Display AttachmentList in timelines in compact style when media missing
  app/javascript/mastodon/components/attachment_list.js
  app/javascript/mastodon/components/status.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6690 Weblate translations (2018-03-08)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/ar.yml
  config/locales/fr.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.ar.yml
  config/locales/sk.yml
Labels: localization

#6679 After blocking domain with reject_media, invalidate cache
  app/services/block_domain_service.rb
  lib/tasks/mastodon.rake
Labels: bug

#6691 For now, put a "." into no-text statuses with media for backcompat
  app/services/post_status_service.rb
Labels: activitypub

#6693 Display AttachmentList in notifications
  app/javascript/mastodon/components/attachment_list.js
  app/javascript/mastodon/components/status.js
Labels: ui

#6692 When enabled, always display media in gallery. Also: click to reveal
  app/javascript/mastodon/components/permalink.js
  app/javascript/mastodon/features/account_gallery/components/media_item.js
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#6695 Improve styling of closed registrations message, rename button
  app/javascript/styles/mastodon/about.scss
  app/views/about/_forms.html.haml
  config/locales/en.yml
Labels: ui

#6694 If login redirects to omniauth, redirect logout to root_path
  app/controllers/auth/sessions_controller.rb
Labels: bug

#6697 Add polyfill for Object.values (regression from #6644)
  app/javascript/mastodon/base_polyfills.js
  app/javascript/mastodon/load_polyfills.js
  package.json
Labels: browser compatibility, bug

#6706 Add missing meta description to profiles, some other SEO stuff
  app/helpers/stream_entries_helper.rb
  app/views/about/show.html.haml
  app/views/accounts/_og.html.haml
  app/views/accounts/show.html.haml
  app/views/follower_accounts/index.html.haml
  app/views/following_accounts/index.html.haml
  app/views/layouts/application.html.haml
Labels: new user experience

#6703 Missing korean translations
  app/javascript/mastodon/locales/ko.json
Labels: localization

#6708 Weblate translations (2018-03-09)
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/sk.json
  config/locales/ca.yml
  config/locales/de.yml
  config/locales/devise.pt-BR.yml
  config/locales/eo.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/sk.yml
Labels: localization

#6707 Change avatar size on form hints
  config/locales/devise.tr.yml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.bg.yml
  config/locales/simple_form.ca.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.eo.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.fi.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.gl.yml
  config/locales/simple_form.he.yml
  config/locales/simple_form.hr.yml
  config/locales/simple_form.hu.yml
  config/locales/simple_form.id.yml
  config/locales/simple_form.io.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.ja.yml
  config/locales/simple_form.ko.yml
  config/locales/simple_form.nl.yml
  config/locales/simple_form.no.yml
  config/locales/simple_form.oc.yml
  config/locales/simple_form.pl.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.pt.yml
  config/locales/simple_form.ru.yml
  config/locales/simple_form.sk.yml
  config/locales/simple_form.sr-Latn.yml
  config/locales/simple_form.sr.yml
  config/locales/simple_form.sv.yml
  config/locales/simple_form.th.yml
  config/locales/simple_form.tr.yml
  config/locales/simple_form.uk.yml
  config/locales/simple_form.zh-CN.yml
  config/locales/simple_form.zh-HK.yml
  config/locales/simple_form.zh-TW.yml
Labels: localization

#6709 Fix thumbnail not filling entire space sometimes
  app/javascript/mastodon/components/media_gallery.js
Labels: bug, ui

#6711 When inside Docker, output saved configuration during mastodon:setup
  lib/tasks/mastodon.rake
Labels: deployment

#6685 docs: Add AUTHORS file
  AUTHORS.md
Labels: docs

#6724 Remove git from Docker image
  Dockerfile
Labels: deployment

#6722 Remove su-exec from Docker image
  Dockerfile
Labels: deployment

#6720 Do not double html-encode page titles
  app/views/layouts/application.html.haml
Labels: bug

#6731 i18n: Update Polish translation
  app/javascript/mastodon/locales/pl.json
Labels: localization

#6733 Add show more/less toggle for entire threads in web UI
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/column_header.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6741 Make Catalan words with the L geminate letter work in hashtags
  app/javascript/mastodon/features/compose/containers/warning_container.js
  app/models/tag.rb
Labels: internationalization

#6583 Add license info to README
  README.md
Labels: docs

#6740 Fix focal point cropping in MediaGallery, fix focal point modal
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#6746 Fix follow relationships not loading after notifications fetch
  app/javascript/mastodon/actions/notifications.js
Labels: bug, ui

#6753 Hide pinned toots on with replies
  app/javascript/mastodon/features/account_timeline/index.js
Labels: enhancement, ui

#6763 Do not run lint in Travis CI
  .travis.yml
Labels: testing

#6767 Do not overwrite some status attributes in reducer
  app/javascript/mastodon/reducers/statuses.js
Labels: bug, ui

#6771 Change the title of sensitive button by state
  app/javascript/mastodon/features/compose/containers/sensitive_button_container.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: accessibility, ui

#6768 Adjust RTL styles for landing page
  app/javascript/mastodon/components/status_content.js
  app/javascript/styles/mastodon/rtl.scss
  app/views/about/show.html.haml
Labels: bug, internationalization

#6772 Change the title of spoiler button by state
  app/javascript/mastodon/features/compose/containers/spoiler_button_container.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: accessibility, ui

#6774 Hide loading bar on status interactions
  app/javascript/mastodon/actions/interactions.js
Labels: ui

#6800 Correct the reference to user's password in mastodon:add_user task
  lib/tasks/mastodon.rake
Labels: bug

#6806 Downgrade Dockerfile to Ruby 2.4.3 on Alpine 3.6
  Dockerfile
Labels: bug, deployment, priority - critical

#6819 Fix elephant graphic being draggable and selectable
  app/javascript/mastodon/features/compose/index.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6818 Revert #6479, hide sensitive text/images from OpenGraph previews
  app/helpers/stream_entries_helper.rb
  app/views/accounts/_og.html.haml
  app/views/accounts/show.html.haml
  app/views/stream_entries/_og_description.html.haml
  app/views/stream_entries/_og_image.html.haml
  app/views/stream_entries/show.html.haml
  config/i18n-tasks.yml
  config/locales/en.yml
Labels: ui

#6822 Ignore media validation when attaching to status during processing
  app/lib/activitypub/activity/create.rb
  app/lib/ostatus/activity/creation.rb
Labels: bug, priority - high

#6827 Weblate translations 20180319
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sv.json
  config/locales/ar.yml
  config/locales/es.yml
  config/locales/simple_form.fi.yml
  config/locales/sk.yml
Labels: localization

#6813 request: in the event of failure, try other IPs (#6761)
  app/lib/request.rb
  spec/lib/request_spec.rb
Labels: bug

#6842 Use username/domain to match existing accounts in ActivityPub
  app/services/activitypub/process_account_service.rb
Labels: activitypub

#6843 Fix i18n fallback configuration conflicts with environment configurations
  config/application.rb
  config/environments/production.rb
Labels: bug

#6844 Permit dots in usernames with conditions
  app/models/account.rb
  app/validators/unique_username_validator.rb
Labels: breaking, compatibility

#6859 Hide floating action button on thread views
  app/javascript/mastodon/features/ui/components/columns_area.js
Labels: ui

#6862 Fix MENTION_RE to not match nil usernames
  app/models/account.rb
Labels: priority - critical

#6858 Do not re-query mentions from serializers
  app/serializers/activitypub/note_serializer.rb
  app/serializers/rest/status_serializer.rb
Labels: bug, priority - critical

#6869 [i18n] Occitan update
  app/javascript/mastodon/locales/oc.json
  config/locales/oc.yml
  config/locales/simple_form.oc.yml
Labels: localization

#6874 Weblate translations (2018-03-23)
  app/javascript/mastodon/locales/ca.json
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.sk.yml
  config/locales/sk.yml
Labels: localization

#6887 Internationalize unexpected error message
  app/javascript/mastodon/features/ui/containers/notifications_container.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  app/javascript/mastodon/middleware/errors.js
Labels: internationalization

#6889 Close http connection in perform method of Request class
  app/helpers/jsonld_helper.rb
  app/lib/provider_discovery.rb
  app/lib/request.rb
  app/models/concerns/remotable.rb
  app/services/fetch_atom_service.rb
  app/services/fetch_link_card_service.rb
  app/services/resolve_account_service.rb
  app/services/send_interaction_service.rb
  app/services/subscribe_service.rb
  app/services/unsubscribe_service.rb
  app/workers/activitypub/delivery_worker.rb
  app/workers/pubsubhubbub/confirmation_worker.rb
  app/workers/pubsubhubbub/delivery_worker.rb
  lib/tasks/mastodon.rake
  spec/lib/request_spec.rb
Labels: refactoring

#6325 Note if the user is already following the target when authorizing follow
  app/views/authorize_follows/_post_follow_actions.html.haml
  app/views/authorize_follows/show.html.haml
  app/views/authorize_follows/success.html.haml
  config/locales/en.yml
  config/locales/ja.yml
Labels: ui

#6875 Change “Toots with replies” to “Toots and replies”
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
Labels: ui

#6801 Show media modal on public pages
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/components/modal_root.js
  app/javascript/mastodon/containers/media_galleries_container.js
  app/javascript/mastodon/containers/media_gallery_container.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
Labels: ui

#6890 Rename variables to have semantic meanings in notifications reducer
  app/javascript/mastodon/reducers/notifications.js
Labels: refactoring

#6903 i18n: Update Polish translation
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/pl.json
  config/locales/pl.yml
Labels: localization

#6915 Fix moved account handling in IndexedDB feature (regression from #6826)
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
Labels: bug

#6891 Validate HTTP response length while receiving
  app/helpers/jsonld_helper.rb
  app/lib/exceptions.rb
  app/lib/provider_discovery.rb
  app/lib/request.rb
  app/models/account.rb
  app/models/application_record.rb
  app/models/concerns/account_avatar.rb
  app/models/concerns/account_header.rb
  app/models/concerns/remotable.rb
  app/models/custom_emoji.rb
  app/models/media_attachment.rb
  app/models/preview_card.rb
  app/services/fetch_atom_service.rb
  app/services/fetch_link_card_service.rb
  app/services/resolve_account_service.rb
  app/workers/pubsubhubbub/confirmation_worker.rb
  spec/lib/request_spec.rb
  spec/models/concerns/remotable_spec.rb
Labels: performance

#6926 Fix UniqueUsernameValidator comparison
  app/models/concerns/account_finder_concern.rb
  app/validators/unique_username_validator.rb
  lib/mastodon/version.rb
  lib/tasks/mastodon.rake
Labels: bug, priority - critical

#6932 Clone response before put it to the cache (regression from #6902)
  app/javascript/mastodon/service_worker/entry.js
Labels: bug

#6933 Fix LoadMore on account media gallery (regression from #6876)
  app/javascript/mastodon/features/account_gallery/index.js
Labels: bug

#6941 Document CORS requirement for asset host
  .env.production.sample
Labels: docs

#6950 Fix TypeError on follow notification (regression from #6826)
  app/javascript/mastodon/actions/notifications.js
Labels: bug

#6965 update ja locale
  app/javascript/mastodon/locales/ja.json
Labels: localization

#6628 Add some UI for user-defined domain blocks
  app/javascript/mastodon/actions/domain_blocks.js
  app/javascript/mastodon/components/domain.js
  app/javascript/mastodon/containers/domain_container.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/mastodon/features/domain_blocks/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/domain_lists.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/relationships.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#6968 Fix compatibility with PeerTube
  app/lib/activitypub/activity/create.rb
  app/services/fetch_atom_service.rb
  app/services/resolve_url_service.rb
Labels: activitypub, compatibility

#6979 i18n: Add Japanese translations for domain blocks
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: localization
