Repository mastodon/mastodon, pull requests merged in 2018-08, with the labels that each got.

#8111 Do not show pinned toots when min_id is set (regression from #6497)
  app/controllers/accounts_controller.rb
Labels: bug

#8135 Update fr.yml for 3 spelling mistakes and a typo
  config/locales/fr.yml
Labels: localization

#8146 Public profile endorsements (accounts picked by profile owner)
  app/controllers/accounts_controller.rb
  app/controllers/api/v1/accounts/pins_controller.rb
  app/helpers/home_helper.rb
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/features/account/components/action_bar.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/mastodon/reducers/relationships.js
  app/javascript/styles/mastodon/widgets.scss
  app/models/account.rb
  app/models/account_pin.rb
  app/models/concerns/account_interactions.rb
  app/presenters/account_relationships_presenter.rb
  app/serializers/rest/relationship_serializer.rb
  app/views/accounts/show.html.haml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20180808175627_create_account_pins.rb
  db/schema.rb
  spec/fabricators/account_pin_fabricator.rb
  spec/models/account_pin_spec.rb
Labels: api, ui

#8142 Update /terms and /about/more to use public layout
  app/controllers/about_controller.rb
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/widgets.scss
  app/views/about/_administration.html.haml
  app/views/about/_contact.html.haml
  app/views/about/more.html.haml
  app/views/about/show.html.haml
  app/views/about/terms.html.haml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/bg.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hr.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/io.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sl.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  spec/views/about/_contact.html.haml_spec.rb
Labels: ui

#8158 Adjust responsive design for /about/more and /terms
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/widgets.scss
  app/views/about/more.html.haml
Labels: ui

#8155 i18n: Update Polish translation
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/pl.yml
Labels: localization

#8167 Weblate translations (2018-08-11)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/uk.json
  config/locales/activerecord.cs.yml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/devise.cs.yml
  config/locales/doorkeeper.co.yml
  config/locales/doorkeeper.cs.yml
  config/locales/doorkeeper.da.yml
  config/locales/doorkeeper.de.yml
  config/locales/doorkeeper.eu.yml
  config/locales/doorkeeper.fr.yml
  config/locales/el.yml
  config/locales/eu.yml
  config/locales/gl.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/oc.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.ar.yml
  config/locales/simple_form.co.yml
  config/locales/simple_form.cs.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.el.yml
  config/locales/simple_form.eu.yml
  config/locales/simple_form.fr.yml
  config/locales/uk.yml
Labels: localization

#8169 i18n: fix Slovak language name
  app/helpers/settings_helper.rb
Labels: localization

#8171 Weblate translations (2018-08-12)
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/nl.json
  config/locales/da.yml
  config/locales/de.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/simple_form.ar.yml
Labels: localization

#8179 Expect relays to answer with accept/reject
  app/lib/activitypub/activity/accept.rb
  app/lib/activitypub/activity/reject.rb
  app/models/relay.rb
  db/migrate/20180812123222_change_relays_enabled.rb
  db/schema.rb
Labels: activitypub

#8182 Add post-deployment migration system
  .rubocop.yml
  config/initializers/0_post_deployment_migrations.rb
  db/post_migrate/.gitkeep
  lib/generators/post_deployment_migration_generator.rb
  lib/templates/rails/post_deployment_migration/migration.rb
Labels: deployment

#8199 Show exact number of followers/statuses on export page/in tooltip
  app/javascript/mastodon/features/account/components/action_bar.js
  app/models/export.rb
  app/views/accounts/_header.html.haml
  app/views/settings/exports/show.html.haml
  app/views/settings/imports/show.html.haml
  spec/models/export_spec.rb
Labels: ui

#8181 Display replies count in web UI
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#8250 Add Georgian language translation
  app/helpers/settings_helper.rb
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/whitelist_ka.json
  config/application.rb
  config/locales/activerecord.ka.yml
  config/locales/devise.ka.yml
  config/locales/doorkeeper.ka.yml
  config/locales/ka.yml
  config/locales/simple_form.ka.yml
Labels: localization

#8202 Add remote interaction dialog for toots
  app/controllers/authorize_follows_controller.rb
  app/controllers/authorize_interactions_controller.rb
  app/controllers/intents_controller.rb
  app/controllers/remote_interaction_controller.rb
  app/helpers/home_helper.rb
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/stream_entries.scss
  app/models/remote_follow.rb
  app/serializers/webfinger_serializer.rb
  app/views/authorize_follows/_post_follow_actions.html.haml
  app/views/authorize_follows/show.html.haml
  app/views/authorize_interactions/_post_follow_actions.html.haml
  app/views/authorize_interactions/error.html.haml
  app/views/authorize_interactions/show.html.haml
  app/views/authorize_interactions/success.html.haml
  app/views/layouts/modal.html.haml
  app/views/remote_interaction/new.html.haml
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
  app/views/stream_entries/show.html.haml
  app/views/well_known/webfinger/show.xml.ruby
  config/brakeman.ignore
  config/locales/en.yml
  config/routes.rb
  spec/controllers/authorize_interactions_controller_spec.rb
  spec/controllers/intents_controller_spec.rb
Labels: ui

#8251 Fix error when trying to update counters for statuses that are gone
  app/models/favourite.rb
  app/models/status.rb
  spec/models/status_spec.rb
Labels: bug

#8200 Add "sign in to participate" message to public toot page
  app/javascript/styles/mastodon/stream_entries.scss
  app/views/stream_entries/_status.html.haml
  config/locales/en.yml
Labels: ui

#8216 Add dependency to support read-replicas
  Gemfile
  Gemfile.lock
Labels: deployment, performance

#8279 Add admin function to deactivate all invites
  app/controllers/admin/invites_controller.rb
  app/policies/invite_policy.rb
  app/views/admin/invites/index.html.haml
  config/locales/en.yml
  config/routes.rb
Labels: admin support

#8278 Link to mobile apps page
  app/javascript/mastodon/features/getting_started/index.js
  app/views/layouts/public.html.haml
  config/locales/en.yml
Labels: ui

#8281 Do not use WHERE NOT IN in CopyStatusStats migration
  db/migrate/20180812173710_copy_status_stats.rb
Labels: deployment

#8277 Show compose form on delete & redraft when in mobile layout
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
Labels: bug

#8286 Make unfollow button light up red when hovered
  app/helpers/stream_entries_helper.rb
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/stream_entries.scss
Labels: ui

#8282 Make user active duration configurable via environment variable
  app/models/user.rb
Labels: performance

#8287 Keep scheduler jobs unique until they're done
  app/workers/scheduler/backup_cleanup_scheduler.rb
  app/workers/scheduler/doorkeeper_cleanup_scheduler.rb
  app/workers/scheduler/email_scheduler.rb
  app/workers/scheduler/feed_cleanup_scheduler.rb
  app/workers/scheduler/ip_cleanup_scheduler.rb
  app/workers/scheduler/media_cleanup_scheduler.rb
  app/workers/scheduler/subscriptions_cleanup_scheduler.rb
  app/workers/scheduler/subscriptions_scheduler.rb
  app/workers/scheduler/user_cleanup_scheduler.rb
Labels: bug, deployment

#8290 i18n: Update Polish translation
  config/locales/pl.yml
Labels: localization

#8299 Fix a variable for a Finnish translation
  config/locales/fi.yml
Labels: bug, localization

#8305 Increase reach of Delete->Actor activities
  app/services/suspend_account_service.rb
  spec/services/suspend_account_service_spec.rb
Labels: activitypub

#8317 Add API endpoint to list featured accounts (fixes #8315)
  app/controllers/api/v1/endorsements_controller.rb
  app/models/account_pin.rb
  config/routes.rb
Labels: api

#8332 Add missing indices for ON DELETE CASCADE constraints
  db/migrate/20180820232245_add_foreign_key_indices.rb
  db/schema.rb
Labels: performance

#8353 Add confirmation step to account suspensions
  app/controllers/admin/reports_controller.rb
  app/controllers/admin/suspensions_controller.rb
  app/javascript/styles/mastodon/forms.scss
  app/models/account.rb
  app/models/form/admin_suspension_confirmation.rb
  app/views/admin/accounts/show.html.haml
  app/views/admin/reports/show.html.haml
  app/views/admin/suspensions/new.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/admin/reports_controller_spec.rb
  spec/controllers/admin/suspensions_controller_spec.rb
Labels: admin support

#8372 Improve federated ID validation
  app/helpers/jsonld_helper.rb
  app/lib/ostatus/activity/creation.rb
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/fetch_remote_key_service.rb
  app/services/activitypub/fetch_remote_status_service.rb
  app/services/fetch_remote_account_service.rb
  spec/services/activitypub/fetch_remote_account_service_spec.rb
  spec/services/activitypub/fetch_remote_status_service_spec.rb
  spec/services/fetch_remote_account_service_spec.rb
  spec/services/fetch_remote_status_service_spec.rb
Labels: security

#8386 Do not check for file existence when serializing ActivityPub actor
  app/serializers/activitypub/actor_serializer.rb
Labels: performance

#8390 Add aria-label to column regions
  app/javascript/mastodon/components/column.js
  app/javascript/mastodon/features/community_timeline/index.js
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/favourited_statuses/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/public_timeline/index.js
  app/javascript/mastodon/features/standalone/community_timeline/index.js
  app/javascript/mastodon/features/standalone/public_timeline/index.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/trends/index.js
Labels: accessibility

#8388 Fix off-by-one error in aria-posinset
  app/javascript/mastodon/components/intersection_observer_article.js
Labels: accessibility

#8395 When registrations closed, link "Sign up" to joinmastodon.org
  app/views/auth/shared/_links.html.haml
  app/views/layouts/public.html.haml
Labels: ui

#8387 Give focused status a sensible aria-label for screen readers
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/status/index.js
Labels: accessibility

#8400 Fix regression when suspending not from report
  app/controllers/admin/suspensions_controller.rb
Labels: bug

#8329 Allow mods to disable login, improve message when login disabled
  app/controllers/api/base_controller.rb
  app/controllers/application_controller.rb
  app/controllers/auth/sessions_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  spec/models/user_spec.rb
Labels: admin support

#8399 Add admin custom CSS setting
  app/controllers/admin/settings_controller.rb
  app/controllers/custom_css_controller.rb
  app/javascript/styles/mastodon/forms.scss
  app/models/form/admin_settings.rb
  app/presenters/instance_presenter.rb
  app/views/admin/settings/edit.html.haml
  app/views/layouts/application.html.haml
  config/routes.rb
Labels: admin support

#8409 Upgrade Doorkeeper to 5.0.0
  Gemfile
  Gemfile.lock
Labels: api, bug

#8419 Revise Japanese translation of `deleted_status`
  config/locales/ja.yml
Labels: localization

#8411 Add improved CLI interface for removing remote media
  app/workers/maintenance/destroy_media_worker.rb
  app/workers/maintenance/redownload_account_media_worker.rb
  app/workers/maintenance/uncache_media_worker.rb
  bin/tootctl
  lib/cli.rb
  lib/mastodon/media_cli.rb
  lib/tasks/mastodon.rake
Labels: admin support

#8420 Weblate translations (2018-08-25)
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/cs.yml
  config/locales/doorkeeper.da.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/ko.yml
  config/locales/simple_form.fr.yml
Labels: localization

#8440 Wait until relationship is loaded before showing follow button
  app/javascript/mastodon/features/account/components/header.js
Labels: ui

#8439 Add theme identifier to body classes for easier custom CSS styling
  app/helpers/application_helper.rb
  app/views/layouts/application.html.haml
  config/locales/en.yml
  spec/helpers/application_helper_spec.rb
Labels: admin support, bug

#8441 Add health endpoint to streaming API
  streaming/index.js
Labels: deployment

#8455 Fix regression from #8439
  app/helpers/application_helper.rb
Labels: bug

#8437 Add CLI interface for importing custom emoji
  lib/cli.rb
  lib/mastodon/cli_helper.rb
  lib/mastodon/emoji_cli.rb
  lib/mastodon/media_cli.rb
Labels: admin support

#8460 Add aria-label to notifications
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/reducers/notifications.js
Labels: accessibility

#8458 Fix low-hanging rubocop gripes
  .rubocop.yml
  app/controllers/api/v1/lists/accounts_controller.rb
  app/controllers/api/v1/lists_controller.rb
  app/lib/feed_manager.rb
  app/mailers/user_mailer.rb
  app/models/concerns/expireable.rb
  app/models/user.rb
  lib/tasks/db.rake
  lib/tasks/mastodon.rake
Labels: refactoring

#8483 Weblate translations (2018-08-27)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cs.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  config/locales/cs.yml
  config/locales/ja.yml
  config/locales/pl.yml
  config/locales/simple_form.pl.yml
Labels: internationalization

#8421 Replace '貼' with '嘟' for 'toot'
  app/javascript/mastodon/locales/zh-TW.json
Labels: localization

#8515 Update de.json
  app/javascript/mastodon/locales/de.json
Labels: localization

#8536 Add Welsh language option
  app/helpers/settings_helper.rb
  config/application.rb
Labels: internationalization

#8538 Normalize Welsh (regression from #8535)
  config/locales/activerecord.cy.yml
  config/locales/devise.cy.yml
  config/locales/doorkeeper.cy.yml
  config/locales/simple_form.cy.yml
Labels: bug

#8539 Save button for relays translatable
  config/locales/en.yml
Labels: internationalization
