Repository mastodon/mastodon, pull requests merged in 2019-04, with the labels that each got.

#10480 Add `tootctl accounts approve`
  lib/mastodon/accounts_cli.rb
Labels: admin support

#10481 Add `tootctl emoji purge`
  lib/mastodon/emoji_cli.rb
Labels: admin support

#10482 Fix missing long description on `tootctl statuses remove`
  lib/mastodon/statuses_cli.rb
Labels: admin support

#10449 Fix admin validation being too strict about usernames
  app/controllers/home_controller.rb
  app/controllers/shares_controller.rb
  app/models/concerns/account_finder_concern.rb
  app/presenters/instance_presenter.rb
  app/validators/existing_username_validator.rb
Labels: bug

#10469 Add batch actions for approving and rejecting pending accounts
  app/controllers/admin/pending_accounts_controller.rb
  app/models/form/account_batch.rb
  app/views/admin/accounts/index.html.haml
  app/views/admin/pending_accounts/_account.html.haml
  app/views/admin/pending_accounts/index.html.haml
  config/locales/en.yml
  config/navigation.rb
  config/routes.rb
Labels: admin support

#10517 Fix glitched out "not found" message for non-existing profiles in web UI
  app/javascript/mastodon/actions/alerts.js
  app/javascript/mastodon/features/account_gallery/index.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
Labels: bug

#10519 Fix permission denied bug on approve all/reject all pending accounts
  app/controllers/admin/pending_accounts_controller.rb
Labels: bug

#10524 Add "why do you want to join" field to invite requests
  app/controllers/about_controller.rb
  app/controllers/admin/pending_accounts_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/widgets.scss
  app/models/user.rb
  app/models/user_invite_request.rb
  app/views/about/_registration.html.haml
  app/views/admin/pending_accounts/_account.html.haml
  app/views/auth/registrations/new.html.haml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/en_GB.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/kk.yml
  config/locales/ko.yml
  config/locales/lt.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/simple_form.en.yml
  config/locales/sk.yml
  config/locales/sq.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  db/migrate/20190409054914_create_user_invite_requests.rb
  db/schema.rb
  spec/fabricators/user_invite_request_fabricator.rb
  spec/models/user_invite_request_spec.rb
Labels: admin support

#10529 Add preference to disable e-mails about new pending accounts
  app/controllers/settings/preferences_controller.rb
  app/models/user.rb
  app/views/settings/notifications/show.html.haml
  config/locales/simple_form.en.yml
  config/settings.yml
Labels: admin support

#10528 Add invite request to pending account notification e-mail
  app/controllers/admin/pending_accounts_controller.rb
  app/helpers/application_helper.rb
  app/views/admin_mailer/new_pending_account.text.erb
  spec/mailers/previews/admin_mailer_preview.rb
Labels: bug

#10534 Change HTML validator to ignore all errors except unmatched tags
  app/models/form/admin_settings.rb
  app/validators/html_validator.rb
Labels: admin support

#10545 Weblate translations (2019-04-10)
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/bn.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/kk.json
  app/javascript/mastodon/locales/lv.json
  app/javascript/mastodon/locales/ms.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ro.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sq.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/ta.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
  babel.config.js
  config/locales/activerecord.de.yml
  config/locales/activerecord.el.yml
  config/locales/activerecord.fr.yml
  config/locales/activerecord.gl.yml
  config/locales/activerecord.kk.yml
  config/locales/activerecord.nl.yml
  config/locales/activerecord.sk.yml
  config/locales/devise.fr.yml
Labels: i18n

#10547 Fix Keybase verification using wrong domain for remote accounts
  app/lib/proof_provider/keybase.rb
  app/lib/proof_provider/keybase/badge.rb
  app/lib/proof_provider/keybase/verifier.rb
  app/lib/proof_provider/keybase/worker.rb
  app/models/account_identity_proof.rb
  spec/lib/proof_provider/keybase/verifier_spec.rb
Labels: bug

#10573 Add hi.json
  app/javascript/mastodon/locales/hi.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/whitelist_hi.json
Labels: bug

#10623 Fix sign up button not saying sign up when invite is used
  app/views/auth/registrations/new.html.haml
Labels: bug

#10624 Fix stoplight logging to stderr separate from Rails logger
  config/initializers/stoplight.rb
Labels: bug

#10622 Fix not being able to save e-mail preference for new pending accounts
  app/controllers/settings/notifications_controller.rb
Labels: bug

#10621 Fix LDAP/PAM/SAML/CAS users not being approved instantly
  app/models/concerns/ldap_authenticable.rb
  app/models/concerns/omniauthable.rb
  app/models/concerns/pam_authenticable.rb
  app/models/user.rb
Labels: bug

#10630 Add blurhash
  Gemfile
  Gemfile.lock
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/report/components/status_check_box.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/mastodon/features/ui/components/video_modal.js
  app/javascript/mastodon/features/video/index.js
  app/javascript/styles/mastodon/components.scss
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/adapter.rb
  app/models/media_attachment.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/rest/media_attachment_serializer.rb
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
  db/migrate/20190420025523_add_blurhash_to_media_attachments.rb
  db/schema.rb
  lib/paperclip/blurhash_transcoder.rb
  package.json
  yarn.lock
Labels: api, ui

#10642 Fix approved column being set to nil instead of false
  app/models/user.rb
Labels: bug
