Repository mastodon/mastodon, pull requests merged in 2019-07, with the labels that each got.

#10353 Add request pool to improve delivery performance
  Gemfile
  Gemfile.lock
  app/lib/connection_pool/shared_connection_pool.rb
  app/lib/connection_pool/shared_timed_stack.rb
  app/lib/request.rb
  app/lib/request_pool.rb
  app/workers/activitypub/delivery_worker.rb
  spec/lib/connection_pool/shared_connection_pool_spec.rb
  spec/lib/connection_pool/shared_timed_stack_spec.rb
  spec/lib/request_pool_spec.rb
Labels: performance

#11233 Change ActivityPub::DeliveryWorker to not retry HTTP 501 errors
  app/workers/activitypub/delivery_worker.rb
Labels: bug

#11230 Fix StatsD UDP sockets not being cleaned up in Sidekiq
  app/lib/sidekiq_error_handler.rb
Labels: bug

#11232 Remove unused StatsD code and expose StatsD as a global variable
  config/initializers/instrumentation.rb
  config/initializers/statsd.rb
Labels: refactoring

#11212 Remove deprecated REST API `GET /api/v1/timelines/direct`
  app/controllers/api/v1/timelines/direct_controller.rb
  app/models/status.rb
  config/routes.rb
  spec/controllers/api/v1/timelines/direct_controller_spec.rb
  spec/models/status_spec.rb
Labels: api, breaking

#11214 Remove deprecated REST API `POST /api/v1/notifications/dismiss?id=:id`
  config/routes.rb
Labels: api, breaking

#11213 Remove deprecated REST API `GET /api/v1/statuses/:id/card`
  app/controllers/api/v1/statuses_controller.rb
  config/routes.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
Labels: api, breaking

#11242 Fix option to send e-mail notification about account action always being true
  app/models/admin/account_action.rb
Labels: bug

#11231 Fix URLs appearing twice in errors of ActivityPub::DeliveryWorker
  app/lib/request.rb
  app/workers/activitypub/delivery_worker.rb
Labels: bug

#11249 Refactor controllers for statuses, accounts, and more
  app/controllers/about_controller.rb
  app/controllers/accounts_controller.rb
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/inboxes_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/activitypub/replies_controller.rb
  app/controllers/api/proofs_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/account_controller_concern.rb
  app/controllers/concerns/account_owned_concern.rb
  app/controllers/concerns/status_controller_concern.rb
  app/controllers/custom_css_controller.rb
  app/controllers/emojis_controller.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/controllers/home_controller.rb
  app/controllers/intents_controller.rb
  app/controllers/manifests_controller.rb
  app/controllers/media_controller.rb
  app/controllers/public_timelines_controller.rb
  app/controllers/remote_follow_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/well_known/host_meta_controller.rb
  app/controllers/well_known/webfinger_controller.rb
  app/lib/activitypub/activity/announce.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/delete.rb
  app/lib/activitypub/tag_manager.rb
  app/models/status.rb
  app/serializers/activitypub/activity_serializer.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/collection_serializer.rb
  app/serializers/activitypub/emoji_serializer.rb
  app/serializers/activitypub/note_serializer.rb
  app/services/process_hashtags_service.rb
  app/views/statuses/_simple_status.html.haml
  config/routes.rb
  spec/controllers/concerns/account_controller_concern_spec.rb
  spec/controllers/statuses_controller_spec.rb
  spec/requests/link_headers_spec.rb
Labels: refactoring

#11250 Remove unused remote unfollow controller
  app/controllers/remote_unfollows_controller.rb
  app/views/remote_unfollows/_card.html.haml
  app/views/remote_unfollows/_post_follow_actions.html.haml
  app/views/remote_unfollows/error.html.haml
  app/views/remote_unfollows/success.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/remote_unfollows_controller_spec.rb
Labels: refactoring

#11268 Refactor domain block checks
  app/controllers/concerns/signature_verification.rb
  app/helpers/domain_control_helper.rb
  app/lib/tag_manager.rb
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/fetch_remote_poll_service.rb
  app/services/activitypub/process_account_service.rb
  app/services/activitypub/process_collection_service.rb
  app/services/activitypub/process_poll_service.rb
  app/services/resolve_account_service.rb
  spec/services/resolve_account_service_spec.rb
Labels: refactoring

#11271 Fix activity being rendered within activity due to caching
  app/serializers/activitypub/activity_serializer.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/collection_serializer.rb
  app/serializers/activitypub/emoji_serializer.rb
  app/serializers/activitypub/note_serializer.rb
Labels: bug

#11251 Refactor fetching of remote resources
  app/helpers/jsonld_helper.rb
  app/lib/request.rb
  app/services/activitypub/fetch_remote_status_service.rb
  app/services/fetch_atom_service.rb
  app/services/fetch_link_card_service.rb
  app/services/fetch_remote_account_service.rb
  app/services/fetch_remote_status_service.rb
  app/services/fetch_resource_service.rb
  app/services/resolve_url_service.rb
  app/workers/activitypub/delivery_worker.rb
  spec/services/fetch_remote_account_service_spec.rb
  spec/services/fetch_resource_service_spec.rb
  spec/services/resolve_url_service_spec.rb
Labels: refactoring

#11284 Add HTTP signatures to all outgoing ActivityPub GET requests
  app/helpers/jsonld_helper.rb
  app/lib/request.rb
  app/services/fetch_resource_service.rb
  spec/controllers/concerns/signature_verification_spec.rb
  spec/services/fetch_remote_account_service_spec.rb
  spec/services/fetch_resource_service_spec.rb
Labels: activitypub

#11269 Add ActivityPub secure mode
  app/controllers/accounts_controller.rb
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/inboxes_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/activitypub/replies_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/account_controller_concern.rb
  app/controllers/concerns/signature_verification.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/tags_controller.rb
  app/lib/activitypub/adapter.rb
  spec/controllers/activitypub/inboxes_controller_spec.rb
Labels: activitypub

#11300 Fix leaking private statuses the admin account follows
  app/services/resolve_url_service.rb
Labels: security

#11302 Change default interface of web and streaming from 0.0.0.0 to 127.0.0.1
  config/puma.rb
  docker-compose.yml
  streaming/index.js
Labels: deployment

#11304 Add periodic removal of older thumbnails for preview cards
  app/workers/maintenance/uncache_preview_worker.rb
  app/workers/scheduler/preview_cards_cleanup_scheduler.rb
  config/sidekiq.yml
Labels: admin support

#11317 Fix consistent interpolations (regression from #11153)
  config/locales/sk.yml
Labels: bug

#9984 Add option to disable real-time updates in web UI
  app/controllers/settings/preferences_controller.rb
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/compare_id.js
  app/javascript/mastodon/components/load_pending.js
  app/javascript/mastodon/components/scrollable_list.js
  app/javascript/mastodon/features/community_timeline/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/setting_toggle.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/ui/containers/status_list_container.js
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/mastodon/reducers/timelines.js
  app/lib/user_settings_decorator.rb
  app/models/user.rb
  app/serializers/initial_state_serializer.rb
  app/views/settings/preferences/appearance/show.html.haml
  config/locales/simple_form.en.yml
  config/settings.yml
Labels: ui

#11345 Fix only one middle dot being recognized in hashtags
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: bug

#11351 Change Dockerfile to bind to 0.0.0.0 instead of docker-compose.yml
  Dockerfile
  docker-compose.yml
Labels: bug

#11359 Change single-column mode to scroll the whole page
  app/javascript/mastodon/components/scrollable_list.js
  app/javascript/mastodon/containers/media_container.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/blocks/index.js
  app/javascript/mastodon/features/community_timeline/index.js
  app/javascript/mastodon/features/domain_blocks/index.js
  app/javascript/mastodon/features/favourited_statuses/index.js
  app/javascript/mastodon/features/favourites/index.js
  app/javascript/mastodon/features/follow_requests/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/lists/index.js
  app/javascript/mastodon/features/mutes/index.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/pinned_statuses/index.js
  app/javascript/mastodon/features/public_timeline/index.js
  app/javascript/mastodon/features/reblogs/index.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/components.scss
Labels: ui

#11303 Remove WebSub subscriptions
  app/models/concerns/account_associations.rb
  app/models/subscription.rb
  app/policies/subscription_policy.rb
  app/services/suspend_account_service.rb
  app/workers/scheduler/subscriptions_cleanup_scheduler.rb
  config/sidekiq.yml
  db/post_migrate/20190715031050_drop_subscriptions.rb
  db/schema.rb
  spec/fabricators/subscription_fabricator.rb
  spec/models/subscription_spec.rb
  spec/policies/subscription_policy_spec.rb
  spec/services/batched_remove_status_service_spec.rb
  spec/services/remove_status_service_spec.rb
  spec/services/suspend_account_service_spec.rb
Labels: refactoring

#8657 Change locale detection to run once per session
  app/controllers/application_controller.rb
  app/controllers/concerns/localized.rb
  config/application.rb
  spec/controllers/concerns/localized_spec.rb
Labels: bug

#11343 Fix `alerts` booleans not being typecast correctly in push subscription
  app/serializers/rest/web_push_subscription_serializer.rb
Labels: bug

#11398 Remove modules.localIdentName
  config/webpack/rules/css.js
Labels: bug

#11393 Change account domain block to clear out notifications and follows
  app/javascript/mastodon/actions/domain_blocks.js
  app/javascript/mastodon/reducers/conversations.js
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/suggestions.js
  app/services/after_block_domain_from_account_service.rb
  app/services/after_block_service.rb
  app/services/follow_service.rb
Labels: refactoring, ui

#11412 Fix invites not being disabled upon account suspension
  app/controllers/invites_controller.rb
  app/models/invite.rb
  app/models/user.rb
  app/services/suspend_account_service.rb
  spec/models/invite_spec.rb
Labels: security

#11409 Add search results pagination to web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/compose/components/search_results.js
  app/javascript/mastodon/features/compose/containers/search_results_container.js
  app/javascript/mastodon/reducers/search.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#11418 Fix tabs bar scrolling along with content on mobile
  app/javascript/styles/mastodon/components.scss
Labels: bug

#11422 Add autosuggestions for hashtags
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/components/autosuggest_hashtag.js
  app/javascript/mastodon/components/autosuggest_input.js
  app/javascript/mastodon/components/autosuggest_textarea.js
  app/javascript/mastodon/reducers/compose.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#11442 Fix emoji autosuggestions
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/components/autosuggest_input.js
  app/javascript/mastodon/components/autosuggest_textarea.js
  app/javascript/mastodon/reducers/compose.js
Labels: bug

#11441 Fix tag normalization and migration not removing duplicate tags
  app/models/tag.rb
  db/migrate/20190726175042_add_case_insensitive_index_to_tags.rb
  spec/models/tag_spec.rb
Labels: bug

#11450 Fix delete regression
  app/lib/feed_manager.rb
Labels: bug
