Repository mastodon/mastodon, pull requests merged in 2019-10, with the labels that each got.

#12028 Remove HEAD request from fetching link previews
  app/services/fetch_link_card_service.rb
  spec/services/fetch_link_card_service_spec.rb
Labels: performance

#12030 Fix delete conversation action not being reflected in web UI
  app/javascript/mastodon/reducers/conversations.js
Labels: bug

#12029 Fix long domain block descriptions breaking table layout
  app/javascript/styles/mastodon/about.scss
  app/views/about/_domain_blocks.html.haml
Labels: bug, ui

#12031 Add refresh button to list of rebloggers/favouriters in web UI
  app/javascript/mastodon/features/favourites/index.js
  app/javascript/mastodon/features/reblogs/index.js
Labels: ui

#12033 Add error description and button to copy stack trace to web UI
  app/javascript/mastodon/components/error_boundary.js
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/basics.scss
Labels: ui

#12048 Fix featured hashtag URL being interpreted as media or with_replies
  app/controllers/accounts_controller.rb
Labels: bug

#12045 Fix account counters being overwritten by parallel writes
  app/models/account_stat.rb
  db/migrate/20191001213028_add_lock_version_to_account_stats.rb
  db/schema.rb
  spec/models/account_stat_spec.rb
Labels: bug

#12041 Fix needlessly indexing unsearchable statuses into ElasticSearch
  app/chewy/statuses_index.rb
  app/models/status.rb
Labels: bug

#12059 Fix media editing modal and profile directory in light theme
  app/javascript/mastodon/features/ui/components/embed_modal.js
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
Labels: bug, ui

#12060 Fix issues in RTL layout in web UI
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/rtl.scss
Labels: bug, ui

#12062 Add br, es-AR, et, mk, nn to available locales
  app/helpers/settings_helper.rb
  config/application.rb
Labels: i18n

#12066 Fix wrong attribute in MoveWorker
  app/workers/move_worker.rb
Labels: bug

#12064 Add `reason` param to `POST /api/v1/accounts` REST API
  app/controllers/api/v1/accounts_controller.rb
  app/services/app_sign_up_service.rb
  spec/services/app_sign_up_service_spec.rb
Labels: api

#12085 Fix S3 adapter retrying failing uploads with exponential backoff
  config/initializers/paperclip.rb
Labels: performance

#12084 Fix performance of home feed regeneration
  app/controllers/api/v1/timelines/home_controller.rb
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/components/missing_indicator.js
  app/javascript/mastodon/components/regeneration_indicator.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/generic_not_found/index.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/introduction.scss
  app/lib/feed_manager.rb
  app/models/home_feed.rb
  app/models/status.rb
  spec/models/home_feed_spec.rb
  spec/models/status_spec.rb
Labels: performance

#12089 Fix `GET /api/v1/instance` REST APIs being unavailable in secure mode
  app/controllers/api/v1/instances/activity_controller.rb
  app/controllers/api/v1/instances/peers_controller.rb
  app/controllers/api/v1/instances_controller.rb
Labels: bug

#12091 Fix hashtag timeline REST API accepting too many hashtags
  app/services/hashtag_query_service.rb
Labels: bug, performance

#12092 Fix existing user records with now-renamed `pt` locale
  db/migrate/20191007013357_update_pt_locales.rb
  db/schema.rb
Labels: bug

#12093 Fix issues with tootctl's parallelization and progress reporting
  lib/mastodon/cli_helper.rb
Labels: bug

#12097 Fix tootctl not allocating enough database connections for main thread
  lib/mastodon/cli_helper.rb
  lib/mastodon/feeds_cli.rb
Labels: bug

#12095 Fix old migration trying to use new column due to default status scope
  db/migrate/20181024224956_migrate_account_conversations.rb
Labels: bug

#12122 Add admin setting to auto-approve hashtags
  app/models/form/admin_settings.rb
  app/models/tag.rb
  app/views/admin/settings/edit.html.haml
  config/locales/en.yml
  config/settings.yml
Labels: admin support

#12135 Fix not showing if emoji has a local counterpart in admin UI
  app/views/admin/custom_emojis/_custom_emoji.html.haml
Labels: bug

#12130 Fix admin setting to auto-approve hashtags not affecting query
  app/models/tag.rb
  app/models/trending_tags.rb
Labels: bug

#12131 Fix media editing modal changing dimensions when image loads
  app/javascript/mastodon/components/extended_video_player.js
  app/javascript/mastodon/components/gifv.js
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/styles/mastodon/components.scss
Labels: bug

#12138 Fix preloaded JSON-LD context for identity not being used
  config/initializers/json_ld.rb
  lib/json_ld/identity.rb
Labels: bug, performance

#12142 Fix auto-report string saying the account has been auto-silenced
  app/lib/spam_check.rb
  config/locales/en.yml
Labels: bug

#12219 Fix notification message for own poll
  app/javascript/mastodon/features/notifications/components/notification.js
Labels: bug
