Repository mastodon/mastodon, pull requests merged in 2019-03, with the labels that each got.

#10130 Fix home timeline perpetually reloading when empty
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/reducers/timelines.js
Labels: bug

#10111 Add polls
  app/controllers/api/v1/polls/votes_controller.rb
  app/controllers/api/v1/polls_controller.rb
  app/controllers/api/v1/statuses_controller.rb
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/actions/polls.js
  app/javascript/mastodon/components/poll.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/containers/media_container.js
  app/javascript/mastodon/containers/poll_container.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/polls.js
  app/javascript/styles/application.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/polls.scss
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/create.rb
  app/models/concerns/account_associations.rb
  app/models/poll.rb
  app/models/poll_vote.rb
  app/models/status.rb
  app/policies/poll_policy.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/activitypub/vote_serializer.rb
  app/serializers/rest/poll_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/services/activitypub/fetch_remote_poll_service.rb
  app/services/post_status_service.rb
  app/services/vote_service.rb
  app/validators/poll_validator.rb
  app/validators/vote_validator.rb
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20190225031541_create_polls.rb
  db/migrate/20190225031625_create_poll_votes.rb
  db/migrate/20190226003449_add_poll_id_to_statuses.rb
  db/schema.rb
  spec/controllers/api/v1/filters_controller_spec.rb
  spec/controllers/api/v1/polls/votes_controller_spec.rb
  spec/controllers/api/v1/polls_controller_spec.rb
  spec/fabricators/poll_fabricator.rb
  spec/fabricators/poll_vote_fabricator.rb
  spec/models/poll_spec.rb
  spec/models/poll_vote_spec.rb
Labels: activitypub, api

#10138 Fix vote validation for polls with multiple choices
  app/validators/vote_validator.rb
Labels: bug

#10139 Fix web UI crash on page load when detailed status has a poll
  app/javascript/mastodon/components/poll.js
Labels: bug

#10144 Fix remote poll expiration time
  app/lib/activitypub/activity/create.rb
  app/services/activitypub/fetch_remote_poll_service.rb
Labels: bug

#10145 Fix typo in ActivityPub::FetchRemotePollService
  app/services/activitypub/fetch_remote_poll_service.rb
Labels: bug

#10146 Fix another typo in ActivityPub::FetchRemotePollService
  app/services/activitypub/fetch_remote_poll_service.rb
Labels: bug

#10148 Fix missing in_reply_to in ActivityPub::VoteSerializer
  app/serializers/activitypub/vote_serializer.rb
Labels: bug

#10143 Add tests for ActivityPub poll processing
  app/lib/activitypub/activity/create.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: testing

#10151 Fix ActivityPub votes having nil IDs
  app/serializers/activitypub/vote_serializer.rb
Labels: bug

#10168 Fix poll options not being stripped of surrounding whitespace on save
  app/models/poll.rb
Labels: bug

#10167 Fix featured tag form not failing on failed tag validations
  app/models/featured_tag.rb
Labels: bug

#10166 Add test ensuring that unknown object types are rejected
  spec/lib/activitypub/activity/create_spec.rb
Labels: testing

#10165 Fix various issues in polls
  app/helpers/stream_entries_helper.rb
  app/javascript/mastodon/components/poll.js
  app/javascript/styles/mastodon/polls.scss
  app/models/poll_vote.rb
  app/serializers/activitypub/note_serializer.rb
  app/views/stream_entries/_poll.html.haml
Labels: bug

#10170 Fix last_fetched_at not being set on polls
  app/services/activitypub/fetch_remote_poll_service.rb
Labels: bug

#10172 Fix NoMethodError in ActivityPub::NoteSerializer
  app/serializers/activitypub/note_serializer.rb
Labels: bug

#10171 Fix status creation API silently discarding invalid poll
  app/models/status.rb
Labels: bug

#10185 Render unicode emoji in polls using emoji pack
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/components/poll.js
Labels: ui

#10184 Add UI for creating polls
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/features/compose/components/poll_button.js
  app/javascript/mastodon/features/compose/components/poll_form.js
  app/javascript/mastodon/features/compose/components/upload_button.js
  app/javascript/mastodon/features/compose/containers/poll_button_container.js
  app/javascript/mastodon/features/compose/containers/poll_form_container.js
  app/javascript/mastodon/features/compose/containers/upload_button_container.js
  app/javascript/mastodon/reducers/compose.js
  app/javascript/styles/mastodon/polls.scss
Labels: ui

#10186 Fix poll validation issues
  app/validators/poll_validator.rb
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/fa.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/ko.yml
  config/locales/sk.yml
Labels: bug

#10188 Avoid line breaks in poll options
  app/javascript/styles/mastodon/polls.scss
Labels: bug, ui

#10189 Fix poll options not rendering text after vote/refresh
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/polls.js
  app/javascript/mastodon/components/poll.js
  app/javascript/mastodon/reducers/polls.js
Labels: bug

#10131 Fix public timelines being broken by new toots when they are not mounted
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/reducers/timelines.js
  app/javascript/mastodon/stream.js
Labels: bug

#10213 Fix NaN in Poll component
  app/javascript/mastodon/components/poll.js
Labels: bug, ui

#10225 Fix SSL configuration regression in streaming API
  streaming/index.js
Labels: bug

#10231 Fix streaming API always attempting to use SSL with Postgres
  streaming/index.js
Labels: bug

#10240 Fix remote interaction dialogs being indexed by search engines
  app/views/remote_follow/new.html.haml
  app/views/remote_interaction/new.html.haml
Labels: bug

#10245 Fix public timeline page not paginating correctly
  app/javascript/mastodon/features/standalone/public_timeline/index.js
Labels: bug

#10248 Add muted style for polls in web UI
  app/javascript/styles/mastodon/polls.scss
Labels: bug, ui

#10247 Optimize RemoveStatusService by removing n+1 query and using shared inboxes
  app/services/remove_status_service.rb
Labels: performance

#10246 Fix poll update handler calling method was that was not available
  app/helpers/jsonld_helper.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/delete.rb
  app/lib/activitypub/activity/update.rb
  app/models/concerns/expireable.rb
  app/services/activitypub/fetch_replies_service.rb
  app/services/notify_service.rb
  app/services/vote_service.rb
  app/workers/activitypub/distribute_poll_update_worker.rb
Labels: bug, work in progress

#10249 Fix `tagged` param not being normalized before querying tags
  app/controllers/accounts_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/timelines/tag_controller.rb
  app/controllers/tags_controller.rb
  app/models/tag.rb
Labels: api, bug

#10217 Refactor User model, extract PamAuthenticable, LdapAuthenticable
  app/models/concerns/ldap_authenticable.rb
  app/models/concerns/omniauthable.rb
  app/models/concerns/pam_authenticable.rb
  app/models/concerns/user_roles.rb
  app/models/user.rb
Labels: refactoring

#10259 Improve invites list with click-to-copy inputs
  app/javascript/styles/mastodon/tables.scss
  app/views/admin/invites/_invite.html.haml
  app/views/admin/invites/index.html.haml
  app/views/invites/_invite.html.haml
  app/views/invites/index.html.haml
Labels: ui

#10265 Fix wrong method used in PollExpirationNotifyWorker
  app/workers/poll_expiration_notify_worker.rb
Labels: bug

#10264 Fix error in AdminMailer#new_pending_account
  app/mailers/admin_mailer.rb
Labels: bug

#10109 Add a preferences API so apps can share basic behaviours
  app/controllers/api/v1/preferences_controller.rb
  app/serializers/rest/preferences_serializer.rb
  config/routes.rb
Labels: api, work in progress

#9851 Add `visibility` param to reblog REST API
  app/controllers/api/v1/statuses/reblogs_controller.rb
  app/models/status.rb
  app/services/reblog_service.rb
Labels: api

#10274 Fix maxed-out invites not showing up as expired in UI
  app/views/admin/invites/_invite.html.haml
  app/views/invites/_invite.html.haml
Labels: bug

#10275 Show disappointed elephant if web UI crashes
  app/javascript/mastodon/components/error_boundary.js
  app/javascript/mastodon/containers/mastodon.js
  app/javascript/mastodon/features/ui/components/bundle.js
Labels: ui

#10261 Fix detailed poll validation errors not being returned in the API
  app/models/status.rb
  app/services/post_status_service.rb
  config/locales/activerecord.en.yml
Labels: api, bug

#10277 Bump webpacker from 3.5.5 to 4.0.2
  Gemfile
  Gemfile.lock
  app/serializers/rest/instance_serializer.rb
  app/serializers/rss/account_serializer.rb
  app/serializers/rss/tag_serializer.rb
  app/views/about/more.html.haml
  app/views/about/show.html.haml
  app/views/application/_sidebar.html.haml
  app/views/home/index.html.haml
  app/views/layouts/admin.html.haml
  app/views/layouts/auth.html.haml
  app/views/layouts/mailer.html.haml
  app/views/layouts/public.html.haml
  app/views/notification_mailer/favourite.html.haml
  app/views/notification_mailer/follow.html.haml
  app/views/notification_mailer/follow_request.html.haml
  app/views/notification_mailer/mention.html.haml
  app/views/notification_mailer/reblog.html.haml
  app/views/shared/_og.html.haml
  app/views/user_mailer/backup_ready.html.haml
  app/views/user_mailer/confirmation_instructions.html.haml
  app/views/user_mailer/email_changed.html.haml
  app/views/user_mailer/password_change.html.haml
  app/views/user_mailer/reconfirmation_instructions.html.haml
  app/views/user_mailer/reset_password_instructions.html.haml
  app/views/user_mailer/warning.html.haml
  app/views/user_mailer/welcome.html.haml
  bin/webpack
  bin/webpack-dev-server
  config/webpack/configuration.js
  config/webpack/development.js
  config/webpack/loaders/assets.js
  config/webpack/loaders/babel.js
  config/webpack/loaders/babel_external.js
  config/webpack/production.js
  config/webpack/rules/babel.js
  config/webpack/rules/css.js
  config/webpack/rules/file.js
  config/webpack/rules/index.js
  config/webpack/rules/mark.js
  config/webpack/rules/node_modules.js
  config/webpack/shared.js
  config/webpacker.yml
  jest.config.js
  package.json
  yarn.lock
Labels: dependencies

#10268 Add relationship manager UI
  app/controllers/relationships_controller.rb
  app/controllers/settings/follower_domains_controller.rb
  app/helpers/admin/filter_helper.rb
  app/javascript/styles/mastodon/tables.scss
  app/models/form/account_batch.rb
  app/views/relationships/_account.html.haml
  app/views/relationships/show.html.haml
  app/views/settings/follower_domains/show.html.haml
  config/locales/ar.yml
  config/locales/ast.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/eo.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gl.yml
  config/locales/he.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/kk.yml
  config/locales/ko.yml
  config/locales/lt.yml
  config/locales/ms.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sq.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
  config/navigation.rb
  config/routes.rb
  spec/controllers/relationships_controller_spec.rb
Labels: ui

#10292 Fix scrollbar styles on compose textarea, small bugs
  app/javascript/mastodon/features/compose/components/poll_form.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#9059 Reduce server load caused by anonymous viewing.
  app/controllers/accounts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/statuses_controller.rb
Labels: performance

#10293 Fix relationship manager on narrow screens
  app/javascript/styles/mastodon/tables.scss
Labels: ui

#10308 Add dormant filter to relationship manager, rename other filters
  app/controllers/relationships_controller.rb
  app/helpers/admin/filter_helper.rb
  app/views/relationships/show.html.haml
  config/locales/en.yml
Labels: ui

#10260 Disable real-time updates on public pages to improve readability
  app/javascript/mastodon/features/standalone/hashtag_timeline/index.js
  app/javascript/mastodon/features/standalone/public_timeline/index.js
Labels: ui

#10297 Add Keybase integration
  app/controllers/api/proofs_controller.rb
  app/controllers/settings/identity_proofs_controller.rb
  app/controllers/well_known/keybase_proof_config_controller.rb
  app/javascript/images/logo_transparent_black.svg
  app/javascript/images/proof_providers/keybase.png
  app/javascript/styles/mastodon/forms.scss
  app/lib/proof_provider.rb
  app/lib/proof_provider/keybase.rb
  app/lib/proof_provider/keybase/badge.rb
  app/lib/proof_provider/keybase/config_serializer.rb
  app/lib/proof_provider/keybase/serializer.rb
  app/lib/proof_provider/keybase/verifier.rb
  app/lib/proof_provider/keybase/worker.rb
  app/models/account_identity_proof.rb
  app/models/concerns/account_associations.rb
  app/views/accounts/_bio.html.haml
  app/views/settings/identity_proofs/_proof.html.haml
  app/views/settings/identity_proofs/index.html.haml
  app/views/settings/identity_proofs/new.html.haml
  config/locales/en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20190316190352_create_account_identity_proofs.rb
  db/schema.rb
  spec/controllers/api/proofs_controller_spec.rb
  spec/controllers/settings/identity_proofs_controller_spec.rb
  spec/controllers/well_known/keybase_proof_config_controller_spec.rb
  spec/fabricators/account_identity_proof_fabricator.rb
  spec/lib/proof_provider/keybase/verifier_spec.rb
Labels: api, ui

#10295 Add missing locales (bn, ga, hi)
  app/helpers/settings_helper.rb
  config/application.rb
Labels: i18n

#10349 If registrations have been re-opened when user confirms account, approve
  app/models/user.rb
Labels: bug

#10347 Add custom closed registrations message to landing page when set
  app/javascript/styles/mastodon/forms.scss
  app/presenters/instance_presenter.rb
  app/views/about/_registration.html.haml
Labels: ui

#10348 Add validations to admin settings
  app/controllers/admin/settings_controller.rb
  app/models/form/admin_settings.rb
  app/validators/existing_username_validator.rb
  app/validators/html_validator.rb
  app/views/admin/settings/edit.html.haml
  config/locales/en.yml
  config/navigation.rb
  spec/controllers/admin/settings_controller_spec.rb
Labels: admin support

#10352 Fix vote-after-expiration not showing error, count vote as interaction
  app/services/vote_service.rb
Labels: bug

#10355 Fix MergeWorker being queued for remote users
  app/models/follow_request.rb
Labels: bug

#10337 Redesign profile column in web UI to match design on public pages
  app/javascript/mastodon/features/account/components/action_bar.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
Labels: ui

#10374 Improve performance of list of blocked domains by caching counts
  app/models/instance.rb
  app/views/admin/instances/index.html.haml
Labels: admin support, performance

#10373 Add `blocked_by` relationship to the REST API
  app/presenters/account_relationships_presenter.rb
  app/serializers/rest/relationship_serializer.rb
Labels: api

#10366 Change icons of features on admin dashboard to remove bias
  app/controllers/admin/dashboard_controller.rb
  app/controllers/directories_controller.rb
  app/helpers/admin/dashboard_helper.rb
  app/javascript/styles/mastodon/admin.scss
  app/models/account.rb
  app/views/admin/dashboard/index.html.haml
  config/locales/en.yml
Labels: admin support, bug, ui

#10378 Remove unused ActivityPub `@context` values depending on response
  app/lib/activitypub/adapter.rb
  app/lib/activitypub/serializer.rb
  app/serializers/activitypub/accept_follow_serializer.rb
  app/serializers/activitypub/activity_serializer.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/add_serializer.rb
  app/serializers/activitypub/block_serializer.rb
  app/serializers/activitypub/collection_serializer.rb
  app/serializers/activitypub/delete_actor_serializer.rb
  app/serializers/activitypub/delete_serializer.rb
  app/serializers/activitypub/emoji_serializer.rb
  app/serializers/activitypub/flag_serializer.rb
  app/serializers/activitypub/follow_serializer.rb
  app/serializers/activitypub/image_serializer.rb
  app/serializers/activitypub/like_serializer.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/activitypub/public_key_serializer.rb
  app/serializers/activitypub/reject_follow_serializer.rb
  app/serializers/activitypub/remove_serializer.rb
  app/serializers/activitypub/undo_announce_serializer.rb
  app/serializers/activitypub/undo_block_serializer.rb
  app/serializers/activitypub/undo_follow_serializer.rb
  app/serializers/activitypub/undo_like_serializer.rb
  app/serializers/activitypub/update_poll_serializer.rb
  app/serializers/activitypub/update_serializer.rb
  app/serializers/activitypub/vote_serializer.rb
  config/initializers/active_model_serializers.rb
  spec/lib/activitypub/adapter_spec.rb
Labels: activitypub, performance

#10398 Fix alternative relay support regression
  app/lib/activitypub/activity/announce.rb
Labels: activitypub, bug

#10404 Add order options to relationship manager UI
  app/controllers/relationships_controller.rb
  app/helpers/admin/filter_helper.rb
  app/views/relationships/show.html.haml
  config/locales/en.yml
Labels: ui

#10403 Add `tootctl search deploy` to avoid ugly rake task syntax
  lib/cli.rb
  lib/mastodon/search_cli.rb
Labels: deployment

#10401 Rename :poll to :preloadable_poll and :owned_poll to :poll on Status
  app/helpers/stream_entries_helper.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/update.rb
  app/lib/formatter.rb
  app/models/notification.rb
  app/models/status.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/activitypub/update_poll_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/services/post_status_service.rb
  app/views/stream_entries/_detailed_status.html.haml
  app/views/stream_entries/_simple_status.html.haml
  app/workers/activitypub/distribute_poll_update_worker.rb
  config/locales/activerecord.en.yml
  spec/lib/activitypub/activity/create_spec.rb
Labels: i18n, performance

#10367 Add `tootctl self-destruct`
  .rubocop.yml
  lib/cli.rb
Labels: admin support

#10420 Add indication that you have been blocked in web UI
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
  app/javascript/styles/mastodon/stream_entries.scss
Labels: ui

#10421 Fix search in web UI not setting a limit, restore limit of 5
  app/javascript/mastodon/actions/search.js
Labels: ui

#10422 Fix transparent avatars showing underlying elements in avatar stack and profile
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/widgets.scss
Labels: ui

#10413 Fix emoji-mart crashing web UI on search by reverting the upgrade to 2.10.0
  app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.js
  app/javascript/mastodon/features/emoji/emoji_picker.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  config/webpack/rules/node_modules.js
  package.json
  yarn.lock
Labels: bug, ui

#10414 Add ActivityPub representation for identity proofs
  app/lib/activitypub/adapter.rb
  app/lib/proof_provider/keybase.rb
  app/serializers/activitypub/actor_serializer.rb
  app/services/activitypub/process_account_service.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: activitypub

#10340 Bump version to 2.8.0rc1
  AUTHORS.md
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: work in progress

#10425 Cache error 410 responses in recommended nginx configuration
  dist/nginx.conf
Labels: deployment
