Repository mastodon/mastodon, pull requests merged in 2019-02, with the labels that each got.

#9997 Fix URL linkifier grabbing full-width spaces and quotations
  app/lib/formatter.rb
  config/initializers/twitter_regex.rb
  spec/lib/formatter_spec.rb
Labels: bug

#9983 Add "copy link" item to status action bars
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/features/status/components/action_bar.js
Labels: ui

#10008 Add available locales for lv, ms, sq
  app/helpers/settings_helper.rb
  config/application.rb
Labels: i18n

#10001 Fix timeline jumps
  app/javascript/mastodon/components/media_gallery.js
  app/javascript/mastodon/components/scrollable_list.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/features/status/components/card.js
  app/javascript/mastodon/features/video/index.js
Labels: ui

#10028 Fix color of static page links in high contrast theme
  app/javascript/styles/contrast/diff.scss
Labels: accessibility, bug

#10029 Fix hashtags select styling in default and high contrast themes
  app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js
  app/javascript/styles/mastodon/_mixins.scss
  app/javascript/styles/mastodon/components.scss
Labels: accessibility, bug, ui

#10030 Fix style regressions on landing page
  app/javascript/styles/mastodon/about.scss
Labels: bug, ui

#10005 Filter incoming Create activities by relation to local activity
  app/lib/activitypub/activity/create.rb
  app/services/activitypub/process_collection_service.rb
  app/workers/activitypub/processing_worker.rb
Labels: activitypub

#10042 Add tight rate-limit for API deletions
  config/initializers/rack_attack.rb
Labels: api, performance

#10040 Fix hashtag column not subscribing to stream on mount
  app/javascript/mastodon/features/hashtag_timeline/index.js
Labels: bug

#10047 Change conversations to always show names of other participants
  app/javascript/mastodon/components/display_name.js
Labels: ui

#10048 Fix relay enabling/disabling not resetting inbox availability status
  app/models/relay.rb
Labels: bug

#10041 Filter incoming Announce activities by relation to local activity
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/announce.rb
  app/lib/activitypub/activity/create.rb
  spec/lib/activitypub/activity/announce_spec.rb
Labels: activitypub

#10054 Change buttons on timeline preview to open the interaction dialog
  app/javascript/mastodon/components/status_action_bar.js
Labels: ui

#10055 Change error graphic to hover-to-play
  app/javascript/packs/error.js
  app/javascript/styles/mastodon/basics.scss
  app/views/layouts/error.html.haml
  public/oops.png
Labels: accessibility

#10060 Add registrations attribute to instance entity in REST API
  app/serializers/rest/instance_serializer.rb
Labels: api

#10058 Add vapid_key to the application entity in the REST API
  app/controllers/api/v1/apps/credentials_controller.rb
  app/serializers/rest/application_serializer.rb
Labels: api

#10057 Fix mutes, blocks, domain blocks and follow requests not paginating
  app/javascript/mastodon/features/blocks/index.js
  app/javascript/mastodon/features/domain_blocks/index.js
  app/javascript/mastodon/features/follow_requests/index.js
  app/javascript/mastodon/features/mutes/index.js
Labels: bug

#10062 Add logging for rejected ActivityPub payloads and add tests
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/announce.rb
  app/lib/activitypub/activity/create.rb
  spec/lib/activitypub/activity/announce_spec.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: bug, testing

#10065 Fix Announce activities of unknown statuses not fetching those statuses
  app/lib/activitypub/activity.rb
  spec/lib/activitypub/activity/announce_spec.rb
Labels: activitypub, bug

#10108 Fix web UI not removing notifications after block
  app/javascript/mastodon/reducers/notifications.js
Labels: bug, ui

#10091 Add type, limit, offset, min_id, max_id, account_id to search API
  app/chewy/statuses_index.rb
  app/controllers/api/v1/accounts/search_controller.rb
  app/controllers/api/v1/search_controller.rb
  app/controllers/api/v2/search_controller.rb
  app/models/account.rb
  app/models/tag.rb
  app/services/account_search_service.rb
  app/services/search_service.rb
  config/brakeman.ignore
  spec/services/account_search_service_spec.rb
  spec/services/search_service_spec.rb
Labels: api

#10121 Improve account media query
  app/controllers/api/v1/accounts/statuses_controller.rb
Labels: performance
