Repository mastodon/mastodon, pull requests merged in 2019-06, with the labels that each got.

#10912 Remove dependency on history
  package.json
Labels: dependencies

#10927 Revert "Bump react-redux-loading-bar from 4.0.8 to 4.2.0"
  package.json
  yarn.lock
Labels: bug

#10963 Add profile directory link to single column navigation panel
  app/javascript/mastodon/features/ui/components/navigation_panel.js
Labels: ui

#10960 Fix poll API not requiring authentication on non-public polls
  app/controllers/api/v1/polls_controller.rb
  spec/controllers/api/v1/polls_controller_spec.rb
Labels: api, security

#10966 Refactor all ActivityPub deliveries to be serialized and signed through one concern
  app/lib/activitypub/activity/follow.rb
  app/models/account.rb
  app/models/form/account_batch.rb
  app/models/status.rb
  app/services/after_block_domain_from_account_service.rb
  app/services/authorize_follow_service.rb
  app/services/block_service.rb
  app/services/concerns/payloadable.rb
  app/services/favourite_service.rb
  app/services/follow_service.rb
  app/services/process_mentions_service.rb
  app/services/reblog_service.rb
  app/services/reject_follow_service.rb
  app/services/remove_status_service.rb
  app/services/report_service.rb
  app/services/suspend_account_service.rb
  app/services/unblock_service.rb
  app/services/unfavourite_service.rb
  app/services/unfollow_service.rb
  app/services/vote_service.rb
  app/workers/activitypub/distribute_poll_update_worker.rb
  app/workers/activitypub/distribution_worker.rb
  app/workers/activitypub/reply_distribution_worker.rb
  app/workers/activitypub/update_distribution_worker.rb
Labels: refactoring

#10961 Fix margins on profile metadata in single column mode
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#10972 Cleanup various controllers
  app/controllers/accounts_controller.rb
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/account_controller_concern.rb
  app/controllers/custom_css_controller.rb
  app/controllers/emojis_controller.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/stream_entries_controller.rb
Labels: refactoring

#10973 Fix not being able to directly switch between list timelines in web UI
  app/javascript/mastodon/features/list_timeline/index.js
Labels: bug, ui

#10982 Fix sass-lint config
  .sass-lint.yml
  app/javascript/styles/contrast/diff.scss
  app/javascript/styles/contrast/variables.scss
  app/javascript/styles/mailer.scss
  app/javascript/styles/mastodon/_mixins.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/polls.scss
  app/javascript/styles/mastodon/rtl.scss
  package.json
Labels: bug

#10985 Add waiting time to list of pending accounts in admin UI
  app/controllers/admin/accounts_controller.rb
  app/views/admin/pending_accounts/_account.html.haml
  config/locales/en.yml
Labels: admin support

#10989 Fix some React warnings
  app/javascript/mastodon/components/autosuggest_textarea.js
  app/javascript/mastodon/features/compose/components/compose_form.js
Labels: bug

#10990 Fix RTL layout not being RTL within the columns area
  app/javascript/styles/mastodon/rtl.scss
Labels: bug

#10992 Improve light theme
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/lists/index.js
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/stream_entries.scss
  app/views/accounts/show.html.haml
Labels: ui

#10994 Change full logo to use primary text color of the given theme
  app/helpers/stream_entries_helper.rb
  app/javascript/images/logo_full.svg
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/containers.scss
  app/views/about/show.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/auth.html.haml
  app/views/layouts/public.html.haml
Labels: ui

#10996 Fix more issues in the light theme
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#11003 Fix position of search icon
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#11002 Change priority of delete activity forwards for replies and reblogs
  app/lib/activitypub/activity/delete.rb
Labels: performance

#11008 Run yarn manage:translations
  app/javascript/mastodon/locales/ar.json
  app/javascript/mastodon/locales/ast.json
  app/javascript/mastodon/locales/bg.json
  app/javascript/mastodon/locales/bn.json
  app/javascript/mastodon/locales/ca.json
  app/javascript/mastodon/locales/co.json
  app/javascript/mastodon/locales/cy.json
  app/javascript/mastodon/locales/da.json
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/el.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/eo.json
  app/javascript/mastodon/locales/es.json
  app/javascript/mastodon/locales/eu.json
  app/javascript/mastodon/locales/fa.json
  app/javascript/mastodon/locales/fi.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/mastodon/locales/gl.json
  app/javascript/mastodon/locales/he.json
  app/javascript/mastodon/locales/hi.json
  app/javascript/mastodon/locales/hr.json
  app/javascript/mastodon/locales/hu.json
  app/javascript/mastodon/locales/hy.json
  app/javascript/mastodon/locales/id.json
  app/javascript/mastodon/locales/io.json
  app/javascript/mastodon/locales/it.json
  app/javascript/mastodon/locales/ja.json
  app/javascript/mastodon/locales/ka.json
  app/javascript/mastodon/locales/kk.json
  app/javascript/mastodon/locales/ko.json
  app/javascript/mastodon/locales/lv.json
  app/javascript/mastodon/locales/ms.json
  app/javascript/mastodon/locales/nl.json
  app/javascript/mastodon/locales/no.json
  app/javascript/mastodon/locales/oc.json
  app/javascript/mastodon/locales/pl.json
  app/javascript/mastodon/locales/pt-BR.json
  app/javascript/mastodon/locales/pt.json
  app/javascript/mastodon/locales/ro.json
  app/javascript/mastodon/locales/ru.json
  app/javascript/mastodon/locales/sk.json
  app/javascript/mastodon/locales/sl.json
  app/javascript/mastodon/locales/sq.json
  app/javascript/mastodon/locales/sr-Latn.json
  app/javascript/mastodon/locales/sr.json
  app/javascript/mastodon/locales/sv.json
  app/javascript/mastodon/locales/ta.json
  app/javascript/mastodon/locales/te.json
  app/javascript/mastodon/locales/th.json
  app/javascript/mastodon/locales/tr.json
  app/javascript/mastodon/locales/uk.json
  app/javascript/mastodon/locales/zh-CN.json
  app/javascript/mastodon/locales/zh-HK.json
  app/javascript/mastodon/locales/zh-TW.json
Labels: i18n

#11019 Fix login sometimes redirecting to paths that are not pages
  app/controllers/custom_css_controller.rb
  app/controllers/manifests_controller.rb
  app/controllers/media_controller.rb
  app/controllers/media_proxy_controller.rb
Labels: bug

#11043 Add German translations
  app/javascript/mastodon/locales/de.json
  app/javascript/mastodon/locales/whitelist_de.json
  config/locales/de.yml
  config/locales/simple_form.de.yml
Labels: i18n

#11045 Fix list not being automatically unpinned when it returns 404 in web UI
  app/javascript/mastodon/actions/alerts.js
  app/javascript/styles/mastodon/components.scss
Labels: bug

#11061 Fix Serbian pluralization rules requiring a "many" key
  config/locales/sr-Latn.rb
  config/locales/sr.rb
Labels: i18n

#11083 Resync Nanobox files with the 2.9.0 release
  boxfile.yml
  nanobox/nginx-local.conf
  nanobox/nginx-stream.conf.erb
  nanobox/nginx-web.conf.erb
Labels: deployment

#10836 Fix sanitizer making block level elements unreadable
  app/lib/sanitize_config.rb
  spec/lib/sanitize_config_spec.rb
Labels: activitypub

#9387 Add moderation API
  app/controllers/admin/accounts_controller.rb
  app/controllers/api/v1/admin/account_actions_controller.rb
  app/controllers/api/v1/admin/accounts_controller.rb
  app/controllers/api/v1/admin/reports_controller.rb
  app/models/account.rb
  app/models/account_filter.rb
  app/models/concerns/user_roles.rb
  app/models/report.rb
  app/models/report_filter.rb
  app/models/user.rb
  app/serializers/rest/admin/account_serializer.rb
  app/serializers/rest/admin/report_serializer.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  spec/controllers/api/v1/admin/account_actions_controller_spec.rb
  spec/controllers/api/v1/admin/accounts_controller_spec.rb
  spec/controllers/api/v1/admin/reports_controller_spec.rb
Labels: admin support, api

#11130 Fix converted media being saved with original extension and mime type
  app/models/concerns/attachmentable.rb
  app/models/media_attachment.rb
  config/application.rb
  lib/paperclip/type_corrector.rb
Labels: bug

#11138 Change domain blocks to automatically support subdomains
  app/controllers/admin/domain_blocks_controller.rb
  app/controllers/admin/instances_controller.rb
  app/controllers/media_proxy_controller.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/flag.rb
  app/lib/ostatus/activity/creation.rb
  app/models/account.rb
  app/models/custom_emoji.rb
  app/models/domain_block.rb
  app/models/instance.rb
  app/services/activitypub/process_account_service.rb
  app/services/block_domain_service.rb
  app/services/resolve_account_service.rb
  app/services/unblock_domain_service.rb
  app/services/update_remote_profile_service.rb
  spec/models/account_spec.rb
  spec/models/domain_block_spec.rb
Labels: admin support

#11139 Remove expensive counters from federation page in admin UI
  app/models/instance.rb
  app/views/admin/instances/index.html.haml
Labels: admin support

#11145 Fix audio not being downloaded from remote servers
  app/lib/activitypub/activity/create.rb
  app/models/media_attachment.rb
  app/serializers/initial_state_serializer.rb
Labels: bug

#11146 Add `short_description` and `approval_required` to `GET /api/v1/instance`
  app/serializers/rest/instance_serializer.rb
Labels: api

#11151 Fix audio-only OGG and WebM files not being processed as such
  app/models/concerns/attachmentable.rb
  app/models/media_attachment.rb
Labels: bug

#11179 Fix unnecessary SQL query performed on unauthenticated requests
  app/controllers/application_controller.rb
Labels: performance

#11196 Add categories for custom emojis
  app/controllers/api/v1/custom_emojis_controller.rb
  app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.js
  app/javascript/mastodon/features/emoji/emoji.js
  app/models/custom_emoji.rb
  app/models/custom_emoji_category.rb
  app/serializers/rest/custom_emoji_serializer.rb
  db/migrate/20190627222225_create_custom_emoji_categories.rb
  db/migrate/20190627222826_add_category_id_to_custom_emojis.rb
  db/schema.rb
  lib/mastodon/emoji_cli.rb
  spec/fabricators/custom_emoji_category_fabricator.rb
  spec/models/custom_emoji_category_spec.rb
  yarn.lock
Labels: ui

#11210 Fix support for MP4 files that are actually M4V files
  app/models/concerns/attachmentable.rb
Labels: bug
