Repository mastodon/mastodon, pull requests merged in 2019-11, with the labels that each got.

#7107 Add bookmarks
  app/controllers/api/v1/bookmarks_controller.rb
  app/controllers/api/v1/statuses/bookmarks_controller.rb
  app/javascript/mastodon/actions/bookmarks.js
  app/javascript/mastodon/actions/interactions.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/bookmarked_statuses/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/status_lists.js
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
  app/models/bookmark.rb
  app/models/concerns/account_associations.rb
  app/models/concerns/account_interactions.rb
  app/models/status.rb
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/status_serializer.rb
  app/services/backup_service.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  db/migrate/20180831171112_create_bookmarks.rb
  db/schema.rb
  spec/controllers/api/v1/bookmarks_controller_spec.rb
  spec/controllers/api/v1/statuses/bookmarks_controller_spec.rb
  spec/fabricators/bookmark_fabricator.rb
Labels: suggestion

#12403 Add cache for OEmbed endpoints to avoid extra HTTP requests
  app/services/fetch_link_card_service.rb
  app/services/fetch_oembed_service.rb
  spec/services/fetch_oembed_service_spec.rb
Labels: bug, performance

#12377 Add relationship-based options to status dropdowns
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
Labels: ui

#12430 Fix account dropdown not opening due to regression from #12377
  app/javascript/mastodon/containers/dropdown_menu_container.js
Labels: bug

#12439 Fix OEmbed discovery not handling different URL variants in query
  app/services/fetch_oembed_service.rb
Labels: bug

#12495 Fix proofs API being inaccessible in secure mode
  app/controllers/api/proofs_controller.rb
Labels: bug

#12494 Fix n+1 query for bookmarks on statuses
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/status_serializer.rb
Labels: bug, performance
