Repository mastodon/mastodon, pull requests merged in 2020-10, with the labels that each got.

#14915 Fix regressions in icon buttons in web UI
  app/javascript/mastodon/components/icon_button.js
  app/javascript/styles/mastodon/components.scss
  app/views/statuses/_simple_status.html.haml
Labels: bug

#14919 Remove dependency on goldfinger gem
  Gemfile
  Gemfile.lock
  app/helpers/webfinger_helper.rb
  app/lib/webfinger.rb
  app/models/account_alias.rb
  app/models/account_migration.rb
  app/models/form/redirect.rb
  app/models/remote_follow.rb
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/process_mentions_service.rb
  app/services/resolve_account_service.rb
  app/views/well_known/host_meta/show.xml.ruby
  spec/controllers/remote_follow_controller_spec.rb
  spec/controllers/well_known/host_meta_controller_spec.rb
  spec/lib/feed_manager_spec.rb
Labels: bug

#14963 Add IP-based rules
  app/controllers/admin/ip_blocks_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/helpers/admin/action_logs_helper.rb
  app/lib/fast_ip_map.rb
  app/models/concerns/expireable.rb
  app/models/form/ip_block_batch.rb
  app/models/ip_block.rb
  app/models/user.rb
  app/policies/ip_block_policy.rb
  app/services/app_sign_up_service.rb
  app/views/admin/ip_blocks/_ip_block.html.haml
  app/views/admin/ip_blocks/index.html.haml
  app/views/admin/ip_blocks/new.html.haml
  app/views/admin/pending_accounts/_account.html.haml
  app/workers/scheduler/ip_cleanup_scheduler.rb
  config/initializers/rack_attack.rb
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20201008202037_create_ip_blocks.rb
  db/migrate/20201008220312_add_sign_up_ip_to_users.rb
  db/schema.rb
  lib/cli.rb
  lib/mastodon/ip_blocks_cli.rb
  spec/fabricators/ip_block_fabricator.rb
  spec/lib/fast_ip_map_spec.rb
  spec/models/ip_block_spec.rb
  spec/services/app_sign_up_service_spec.rb
Labels: admin support

#14985 Change how missing desktop notifications permission is displayed
  app/javascript/mastodon/actions/onboarding.js
  app/javascript/mastodon/features/notifications/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/notifications_permission_banner.js
  app/javascript/mastodon/features/notifications/components/setting_toggle.js
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/ui/components/notifications_counter_icon.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#14510 Add follower synchronization mechanism
  Gemfile
  Gemfile.lock
  app/controllers/activitypub/followers_synchronizations_controller.rb
  app/controllers/activitypub/inboxes_controller.rb
  app/lib/activitypub/tag_manager.rb
  app/models/account.rb
  app/models/concerns/account_interactions.rb
  app/models/follow.rb
  app/services/activitypub/prepare_followers_synchronization_service.rb
  app/services/activitypub/synchronize_followers_service.rb
  app/workers/activitypub/delivery_worker.rb
  app/workers/activitypub/distribution_worker.rb
  app/workers/activitypub/followers_synchronization_worker.rb
  config/routes.rb
  spec/controllers/activitypub/followers_synchronizations_controller_spec.rb
  spec/controllers/activitypub/inboxes_controller_spec.rb
  spec/models/concerns/account_interactions_spec.rb
  spec/services/activitypub/synchronize_followers_service_spec.rb
  spec/workers/activitypub/delivery_worker_spec.rb
Labels: activitypub
