Repository mastodon/mastodon, pull requests merged in 2020-06, with the labels that each got.

#13952 Fix wrong route helper in encrypted messages controller
  app/controllers/api/v1/crypto/encrypted_messages_controller.rb
  app/serializers/rest/encrypted_message_serializer.rb
Labels: api, bug

#14013 Add e-mail-based sign in challenge for users with disabled 2FA
  app/controllers/auth/sessions_controller.rb
  app/controllers/concerns/sign_in_token_authentication_concern.rb
  app/controllers/concerns/two_factor_authentication_concern.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/auth/sessions/sign_in_token.html.haml
  app/views/user_mailer/sign_in_token.html.haml
  app/views/user_mailer/sign_in_token.text.erb
  config/locales/en.yml
  config/locales/simple_form.en.yml
  db/migrate/20200608113046_add_sign_in_token_to_users.rb
  db/schema.rb
  spec/controllers/auth/sessions_controller_spec.rb
  spec/mailers/previews/user_mailer_preview.rb
Labels: security

#14064 [security] Bump rack from 2.2.2 to 2.2.3
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#14095 Change design of audio players in web UI
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/audio/index.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#14122 Change volume control and download buttons in web UI
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/audio/index.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/video/index.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#14181 Fix trying to write non-existent image remote URL attribute on preview cards
  app/models/concerns/remotable.rb
  spec/models/concerns/remotable_spec.rb
Labels: bug

#14184 Fix remote files not using Content-Type header, streaming
  app/lib/response_with_limit.rb
  app/models/concerns/attachmentable.rb
  app/models/concerns/remotable.rb
  config/application.rb
  config/initializers/paperclip.rb
  lib/paperclip/image_extractor.rb
  lib/paperclip/media_type_spoof_detector_extensions.rb
  lib/paperclip/response_with_limit_adapter.rb
  spec/models/concerns/remotable_spec.rb
Labels: bug, performance
