Repository mastodon/mastodon, pull requests merged in 2020-09, with the labels that each got.

#11595 Add featured hashtags as an ActivityPub collection
  app/controllers/activitypub/collections_controller.rb
  app/lib/activitypub/adapter.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/collection_serializer.rb
  app/serializers/activitypub/hashtag_serializer.rb
Labels: activitypub

#14729 Fix various warnings in rspec
  spec/lib/feed_manager_spec.rb
  spec/lib/spam_check_spec.rb
  spec/services/unallow_domain_service_spec.rb
  spec/workers/scheduler/feed_cleanup_scheduler_spec.rb
Labels: refactoring

#14730 Remove obsolete IndexedDB operations from web UI
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/actions/statuses.js
Labels: refactoring

#14728 Refactor how public and tag timelines are queried
  app/controllers/api/v1/timelines/public_controller.rb
  app/controllers/api/v1/timelines/tag_controller.rb
  app/controllers/tags_controller.rb
  app/models/public_feed.rb
  app/models/status.rb
  app/models/tag_feed.rb
  app/services/hashtag_query_service.rb
  spec/models/public_feed_spec.rb
  spec/models/status_spec.rb
  spec/models/tag_feed_spec.rb
  spec/services/fan_out_on_write_service_spec.rb
Labels: refactoring

#14761 Refactor feed manager
  app/lib/feed_manager.rb
  app/services/after_block_service.rb
  app/services/notify_service.rb
  app/services/precompute_feed_service.rb
  app/workers/feed_insert_worker.rb
  app/workers/merge_worker.rb
  app/workers/mute_worker.rb
  app/workers/unmerge_worker.rb
  spec/lib/feed_manager_spec.rb
Labels: refactoring

#14766 Change web UI to show empty profile for suspended accounts
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_gallery/index.js
  app/javascript/mastodon/features/account_timeline/index.js
Labels: ui

#14765 Change REST API to return empty data for suspended accounts
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/api/v1/accounts/featured_tags_controller.rb
  app/controllers/api/v1/accounts/follower_accounts_controller.rb
  app/controllers/api/v1/accounts/following_accounts_controller.rb
  app/controllers/api/v1/accounts/identity_proofs_controller.rb
  app/controllers/api/v1/accounts/lists_controller.rb
  app/controllers/api/v1/accounts/relationships_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/blocks_controller.rb
  app/controllers/api/v1/endorsements_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/controllers/api/v1/lists/accounts_controller.rb
  app/controllers/api/v1/mutes_controller.rb
  app/controllers/api/v1/notifications_controller.rb
  app/controllers/api/v1/statuses/favourited_by_accounts_controller.rb
  app/controllers/api/v1/statuses/reblogged_by_accounts_controller.rb
  app/models/notification.rb
  app/policies/status_policy.rb
  app/serializers/rest/account_serializer.rb
  lib/paperclip/attachment_extensions.rb
  lib/paperclip/url_generator_extensions.rb
Labels: api

#14767 Refactor settings controllers
  app/controllers/concerns/export_controller_concern.rb
  app/controllers/oauth/authorized_applications_controller.rb
  app/controllers/settings/aliases_controller.rb
  app/controllers/settings/applications_controller.rb
  app/controllers/settings/base_controller.rb
  app/controllers/settings/deletes_controller.rb
  app/controllers/settings/exports/blocked_accounts_controller.rb
  app/controllers/settings/exports/blocked_domains_controller.rb
  app/controllers/settings/exports/following_accounts_controller.rb
  app/controllers/settings/exports/lists_controller.rb
  app/controllers/settings/exports/muted_accounts_controller.rb
  app/controllers/settings/exports_controller.rb
  app/controllers/settings/featured_tags_controller.rb
  app/controllers/settings/identity_proofs_controller.rb
  app/controllers/settings/imports_controller.rb
  app/controllers/settings/migration/redirects_controller.rb
  app/controllers/settings/migrations_controller.rb
  app/controllers/settings/pictures_controller.rb
  app/controllers/settings/preferences_controller.rb
  app/controllers/settings/profiles_controller.rb
  app/controllers/settings/sessions_controller.rb
  app/controllers/settings/two_factor_authentication/confirmations_controller.rb
  app/controllers/settings/two_factor_authentication/otp_authentication_controller.rb
  app/controllers/settings/two_factor_authentication/recovery_codes_controller.rb
  app/controllers/settings/two_factor_authentication/webauthn_credentials_controller.rb
  app/controllers/settings/two_factor_authentication_methods_controller.rb
  app/views/auth/registrations/_sessions.html.haml
  app/views/auth/registrations/edit.html.haml
  app/views/oauth/authorized_applications/index.html.haml
  config/navigation.rb
  spec/controllers/settings/deletes_controller_spec.rb
Labels: refactoring

#14778 Fix reported statuses not being included in warning e-mail
  app/models/admin/account_action.rb
Labels: bug

#14803 Fix unreadable placeholder text color in high contrast theme in web UI
  app/javascript/styles/contrast/diff.scss
Labels: bug

#14807 Bump selfsigned from 1.10.7 to 1.10.8
  yarn.lock
Labels: dependencies, security

#14822 Fix not being able to enable status notifications in Web Push API
  app/controllers/api/v1/push/subscriptions_controller.rb
  app/controllers/api/web/push_subscriptions_controller.rb
Labels: bug

#14855 Fix method of the DELETE DATA button
  app/views/admin/accounts/show.html.haml
Labels: bug

#14859 Fix crash streaming server when receive invalid json
  streaming/index.js
Labels: bug

#14904 Bump puma from 5.0.1 to 5.0.2
  Gemfile.lock
Labels: dependencies
