Repository mastodon/mastodon, pull requests merged in 2020-12, with the labels that each got.

#15284 Fix too low contrast on new media modal background in web UI
  app/javascript/mastodon/components/modal_root.js
Labels: bug

#15285 Fix alert when failing to save timeline markers in web UI
  app/javascript/mastodon/actions/markers.js
Labels: bug

#15283 Fix not being able to open audio modal in web UI
  app/javascript/mastodon/blurhash.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/ui/components/audio_modal.js
  app/javascript/mastodon/features/ui/components/media_modal.js
  app/javascript/mastodon/features/ui/components/video_modal.js
  app/javascript/mastodon/features/video/index.js
Labels: bug

#15287 Fix slow distinct queries where grouped queries are faster
  app/controllers/accounts_controller.rb
  app/controllers/admin/statuses_controller.rb
  app/models/account.rb
  app/models/form/account_batch.rb
Labels: performance

#15286 Fix unnecessary re-rendering of various components when typing in web UI
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/selectors/index.js
Labels: performance

#15282 Fix performance on instances list in admin UI
  Gemfile
  Gemfile.lock
  app/controllers/admin/domain_blocks_controller.rb
  app/controllers/admin/instances_controller.rb
  app/controllers/api/v1/instances/peers_controller.rb
  app/models/account.rb
  app/models/concerns/domain_materializable.rb
  app/models/domain_allow.rb
  app/models/domain_block.rb
  app/models/instance.rb
  app/models/instance_filter.rb
  app/models/unavailable_domain.rb
  app/policies/domain_block_policy.rb
  app/presenters/instance_presenter.rb
  app/views/admin/instances/_instance.html.haml
  app/views/admin/instances/index.html.haml
  app/views/admin/instances/show.html.haml
  app/workers/scheduler/instance_refresh_scheduler.rb
  config/brakeman.ignore
  config/locales/en.yml
  config/sidekiq.yml
  db/migrate/20201206004238_create_instances.rb
  db/schema.rb
  db/views/instances_v01.sql
  lib/mastodon/domains_cli.rb
  spec/controllers/admin/instances_controller_spec.rb
  spec/models/account_spec.rb
Labels: admin support, performance

#13043 Add stoplight for object storage failures, return HTTP 503
  app/controllers/api/base_controller.rb
  app/controllers/application_controller.rb
  app/lib/activitypub/activity/create.rb
  config/initializers/paperclip.rb
  lib/paperclip/attachment_extensions.rb
Labels: performance

#15355 Add option to obfuscate domain name in public list of domain blocks
  app/controllers/admin/domain_blocks_controller.rb
  app/models/domain_block.rb
  app/views/about/_domain_blocks.html.haml
  app/views/admin/domain_blocks/edit.html.haml
  app/views/admin/domain_blocks/new.html.haml
  config/locales/en.yml
  db/migrate/20201218054746_add_obfuscate_to_domain_blocks.rb
  db/schema.rb
Labels: admin support

#15364 Fix resolving accounts sometimes creating duplicate records for a given AP id
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/process_account_service.rb
  app/services/resolve_account_service.rb
  app/workers/account_merging_worker.rb
  lib/mastodon/accounts_cli.rb
  spec/services/resolve_account_service_spec.rb
Labels: security

#15368 Fix ResolveAccountService accepting mismatching acct: URI
  app/services/resolve_account_service.rb
  spec/services/resolve_account_service_spec.rb
Labels: security

#15372 Ran `i18n-tasks normalize`
  config/locales/bn.yml
  config/locales/doorkeeper.hy.yml
  config/locales/eu.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/hy.yml
  config/locales/id.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/sc.yml
  config/locales/sv.yml
  config/locales/uk.yml
  config/locales/vi.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
Labels: bug

#15387 Fix unnecessary queries when batch-removing statuses, 100x faster
  app/models/favourite.rb
  app/models/status.rb
  app/services/batched_remove_status_service.rb
  app/services/delete_account_service.rb
  config/initializers/chewy.rb
  lib/chewy/strategy/custom_sidekiq.rb
  spec/services/batched_remove_status_service_spec.rb
Labels: performance

#15414 Fix trying to privatize empty media attachments
  app/services/suspend_account_service.rb
  app/services/unsuspend_account_service.rb
Labels: bug

#15421 Fix undefined method error when batch-removing statuses with ElasticSearch on
  app/services/batched_remove_status_service.rb
  app/services/delete_account_service.rb
Labels: bug

#15420 Fix error when changing ACL on missing objects during suspension
  app/services/suspend_account_service.rb
  app/services/unsuspend_account_service.rb
Labels: bug
