Repository mastodon/mastodon, pull requests merged in 2020-08, with the labels that each got.

#14479 Fix handling of Reject Follow when a matching follow relationship exists
  app/lib/activitypub/activity/reject.rb
  spec/lib/activitypub/activity/reject_spec.rb
Labels: activitypub, bug

#14566 Fix destructuring error when unsubscribing without subscribing
  streaming/index.js
Labels: bug

#14662 Use Status.group instead of Status.distinct in HashQueryService
  app/controllers/api/v1/timelines/tag_controller.rb
  app/services/hashtag_query_service.rb
Labels: performance

#14673 Eagerly load statuses with the main query in Api::V1::FavouritesController
  app/controllers/api/v1/favourites_controller.rb
Labels: bug, performance

#14675 Replace incorrect use of distinct with group
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/timelines/public_controller.rb
Labels: bug, performance

#14674 Eagerly load statuses with the main query in Api::V1::BookmarksController
  app/controllers/api/v1/bookmarks_controller.rb
Labels: bug, performance

#14677 Introduce ApplicationController#cache_collection_paginated_by_id
  app/controllers/accounts_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/notifications_controller.rb
  app/controllers/api/v1/timelines/public_controller.rb
  app/controllers/api/v1/timelines/tag_controller.rb
  app/controllers/concerns/cache_concern.rb
Labels: bug, performance

#14684 Fix videos with near-60 fps being rejected
  app/models/media_attachment.rb
Labels: bug

#14682 Fix inefficiencies in fan-out-on-write service
  app/services/fan_out_on_write_service.rb
Labels: performance

#14683 Add support for dereferencing objects through bearcaps
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/dereferencer.rb
  spec/lib/activitypub/dereferencer_spec.rb
Labels: activitypub

#14687 Make Array-creation behavior of Paginable more predictable
  app/controllers/api/v1/admin/accounts_controller.rb
  app/controllers/api/v1/admin/reports_controller.rb
  app/controllers/api/v1/bookmarks_controller.rb
  app/controllers/api/v1/conversations_controller.rb
  app/controllers/api/v1/crypto/encrypted_messages_controller.rb
  app/controllers/api/v1/favourites_controller.rb
  app/controllers/api/v1/scheduled_statuses_controller.rb
  app/controllers/concerns/cache_concern.rb
  app/models/account_conversation.rb
  app/models/concerns/paginable.rb
Labels: refactoring
