Repository mastodon/mastodon, pull requests merged in 2021-07, with the labels that each got.

#16462 Preload libjemalloc.so for long-running Ruby
  dist/mastodon-sidekiq.service
  dist/mastodon-web.service
Labels: bug, deployment, ruby

#16485 Add `configuration` attribute to `GET /api/v1/instance`
  app/serializers/rest/instance_serializer.rb
  app/validators/status_length_validator.rb
Labels: api

#16487 Add ability to filter reports by origin of target account
  app/models/report_filter.rb
  app/views/admin/reports/index.html.haml
  config/locales/en.yml
Labels: moderation
