Repository mastodon/mastodon, pull requests merged in 2022-09, with the labels that each got.

#19095 Add ability to filter followed accounts' posts by language
  app/controllers/api/v1/accounts_controller.rb
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/mastodon/features/subscribed_languages_modal/index.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/lib/feed_manager.rb
  app/models/concerns/account_interactions.rb
  app/models/export.rb
  app/models/follow.rb
  app/models/follow_request.rb
  app/serializers/rest/relationship_serializer.rb
  app/services/follow_service.rb
  app/services/import_service.rb
  app/validators/language_validator.rb
  app/workers/refollow_worker.rb
  app/workers/unfollow_follow_worker.rb
  db/migrate/20220829192633_add_languages_to_follows.rb
  db/migrate/20220829192658_add_languages_to_follow_requests.rb
  db/schema.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/settings/exports/following_accounts_controller_spec.rb
  spec/lib/feed_manager_spec.rb
  spec/models/concerns/account_interactions_spec.rb
  spec/models/export_spec.rb
  spec/models/follow_request_spec.rb
  spec/services/follow_service_spec.rb
  spec/workers/refollow_worker_spec.rb
Labels: api, NLnet

#19232 Add retention policy for cached content and media
  app/lib/redis_configuration.rb
  app/lib/vacuum.rb
  app/lib/vacuum/access_tokens_vacuum.rb
  app/lib/vacuum/backups_vacuum.rb
  app/lib/vacuum/feeds_vacuum.rb
  app/lib/vacuum/media_attachments_vacuum.rb
  app/lib/vacuum/preview_cards_vacuum.rb
  app/lib/vacuum/statuses_vacuum.rb
  app/lib/vacuum/system_keys_vacuum.rb
  app/models/content_retention_policy.rb
  app/models/form/admin_settings.rb
  app/views/admin/settings/edit.html.haml
  app/workers/scheduler/backup_cleanup_scheduler.rb
  app/workers/scheduler/feed_cleanup_scheduler.rb
  app/workers/scheduler/media_cleanup_scheduler.rb
  app/workers/scheduler/vacuum_scheduler.rb
  config/locales/simple_form.en.yml
  config/settings.yml
  config/sidekiq.yml
  spec/fabricators/access_grant_fabricator.rb
  spec/fabricators/preview_card_fabricator.rb
  spec/lib/vacuum/access_tokens_vacuum_spec.rb
  spec/lib/vacuum/backups_vacuum_spec.rb
  spec/lib/vacuum/feeds_vacuum_spec.rb
  spec/lib/vacuum/media_attachments_vacuum_spec.rb
  spec/lib/vacuum/preview_cards_vacuum_spec.rb
  spec/lib/vacuum/statuses_vacuum_spec.rb
  spec/lib/vacuum/system_keys_vacuum_spec.rb
  spec/workers/scheduler/feed_cleanup_scheduler_spec.rb
  spec/workers/scheduler/media_cleanup_scheduler_spec.rb
Labels: moderation, NLnet

#19244 Fix auto detect language for translate service
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  app/lib/translation_service/deepl.rb
  app/lib/translation_service/libre_translate.rb
Labels: bug

#19246 Fix language dropdown sometimes not appearing in web UI
  app/models/user.rb
Labels: bug

#19248 Fix content retention policy settings not accepting a blank value
  app/models/form/admin_settings.rb
Labels: bug

#19250 Add sign-up button to logged-out web UI
  app/javascript/mastodon/components/column_header.js
  app/javascript/mastodon/components/poll.js
  app/javascript/mastodon/components/status_content.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/mastodon/features/ui/components/sign_in_banner.js
  app/javascript/mastodon/initial_state.js
  app/javascript/styles/mastodon/components.scss
  app/serializers/initial_state_serializer.rb
Labels: ui

#18072 Install python3 when building with Docker
  Dockerfile
Labels: bug

#19253 Remove volume number from hashtags in web UI
  app/javascript/mastodon/components/hashtag.js
Labels: ui
