Repository mastodon/mastodon, pull requests merged in 2022-08, with the labels that each got.

#17881 Remove nanobox
  .env.nanobox
  boxfile.yml
  nanobox/nginx-local.conf
  nanobox/nginx-stream.conf.erb
  nanobox/nginx-web.conf.erb
Labels: wontfix

#17885 Hide audio posts when marked as sensitive
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/audio/index.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/styles/mastodon/components.scss
Labels: wontfix

#18001 Change short description so that it logically follows the long decription
  lib/mastodon/accounts_cli.rb
Labels: wontfix

#17858 Make Mastodon use its own gemset
  .ruby-gemset
Labels: wontfix

#19037 Add ability to block sign-ups from IP
  app/controllers/auth/registrations_controller.rb
  app/models/ip_block.rb
  app/services/app_sign_up_service.rb
  config/locales/simple_form.en.yml
  spec/services/app_sign_up_service_spec.rb
Labels: moderation

#18979 Change e-mail domain blocks to match subdomains of blocked domains
  app/models/email_domain_block.rb
  spec/models/email_domain_block_spec.rb
Labels: moderation

#18945 Add ability to filter individual posts
  app/controllers/api/v1/filters/statuses_controller.rb
  app/controllers/filters/statuses_controller.rb
  app/controllers/filters_controller.rb
  app/javascript/mastodon/actions/filters.js
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/compose/components/language_dropdown.js
  app/javascript/mastodon/features/filters/added_to_filter.js
  app/javascript/mastodon/features/filters/select_filter.js
  app/javascript/mastodon/features/ui/components/filter_modal.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/filters.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/mastodon/utils/filters.js
  app/javascript/mastodon/utils/icons.js
  app/javascript/styles/mastodon/components.scss
  app/models/concerns/account_interactions.rb
  app/models/custom_filter.rb
  app/models/custom_filter_status.rb
  app/models/form/status_filter_batch_action.rb
  app/presenters/filter_result_presenter.rb
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/filter_result_serializer.rb
  app/serializers/rest/filter_serializer.rb
  app/serializers/rest/filter_status_serializer.rb
  app/views/filters/_filter.html.haml
  app/views/filters/_filter_fields.html.haml
  app/views/filters/statuses/_status_filter.html.haml
  app/views/filters/statuses/index.html.haml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220808101323_create_custom_filter_statuses.rb
  db/schema.rb
  spec/controllers/api/v1/filters/statuses_controller_spec.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
  spec/fabricators/custom_filter_status_fabricator.rb
  spec/presenters/status_relationships_presenter_spec.rb
Labels: NLnet

#18924 Fix action type for unfollowHashtag
  app/javascript/mastodon/actions/tags.js
Labels: bug

#18409 Replace to `workbox-webpack-plugin` from `offline-plugin`
  app/javascript/mastodon/main.js
  app/javascript/mastodon/service_worker/entry.js
  app/javascript/mastodon/service_worker/web_push_notifications.js
  app/javascript/mastodon/storage/db.js
  app/javascript/mastodon/storage/modifier.js
  config/webpack/production.js
  package.json
  public/sw.js
  public/sw.js.map
  yarn.lock
Labels: dependencies, javascript

#19040 Add audit log entries for user roles
  app/controllers/admin/roles_controller.rb
  app/controllers/admin/users/roles_controller.rb
  app/controllers/concerns/accountable_concern.rb
  app/helpers/admin/action_logs_helper.rb
  app/models/account.rb
  app/models/account_warning.rb
  app/models/admin/action_log.rb
  app/models/admin/action_log_filter.rb
  app/models/announcement.rb
  app/models/appeal.rb
  app/models/custom_emoji.rb
  app/models/domain_allow.rb
  app/models/domain_block.rb
  app/models/email_domain_block.rb
  app/models/form/account_batch.rb
  app/models/instance.rb
  app/models/ip_block.rb
  app/models/report.rb
  app/models/status.rb
  app/models/unavailable_domain.rb
  app/models/user.rb
  app/models/user_role.rb
  config/locales/en.yml
  db/migrate/20220824164433_add_human_identifier_to_admin_action_logs.rb
  db/post_migrate/20220824164532_remove_recorded_changes_from_admin_action_logs.rb
  db/schema.rb
  spec/helpers/admin/action_log_helper_spec.rb
Labels: moderation, refactoring

#19053 Add ability to select all accounts matching search for batch actions
  app/controllers/admin/accounts_controller.rb
  app/javascript/packs/admin.js
  app/javascript/styles/mastodon/tables.scss
  app/models/custom_filter_status.rb
  app/models/form/account_batch.rb
  app/views/admin/accounts/index.html.haml
  config/locales/en.yml
Labels: moderation

#19054 Fix "select all matching items" being offered when all items are on the page
  app/views/admin/accounts/index.html.haml
Labels: bug

#19065 Add admin API for managing IP blocks
  app/controllers/api/v1/admin/ip_blocks_controller.rb
  app/models/ip_block.rb
  app/policies/ip_block_policy.rb
  app/serializers/rest/admin/ip_block_serializer.rb
  config/routes.rb
Labels: api, moderation

#19067 Add admin API for managing canonical e-mail blocks
  app/controllers/api/v1/admin/canonical_email_blocks_controller.rb
  app/helpers/admin/action_logs_helper.rb
  app/models/admin/action_log_filter.rb
  app/models/canonical_email_block.rb
  app/policies/canonical_email_block_policy.rb
  app/serializers/rest/admin/canonical_email_block_serializer.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220827195229_change_canonical_email_blocks_nullable.rb
  db/schema.rb
  lib/mastodon/canonical_email_blocks_cli.rb
Labels: api, moderation

#19066 Add admin API for managing e-mail domain blocks
  app/controllers/api/v1/admin/email_domain_blocks_controller.rb
  app/models/email_domain_block.rb
  app/serializers/rest/admin/email_domain_block_serializer.rb
  config/routes.rb
Labels: api, moderation

#18964 Change following and followers API to be accessible without being logged in
  app/controllers/api/v1/accounts/follower_accounts_controller.rb
  app/controllers/api/v1/accounts/following_accounts_controller.rb
Labels: api

#18963 Change search API to be accessible without being logged in
  app/controllers/api/v2/search_controller.rb
Labels: api
