Repository mastodon/mastodon, pull requests merged in 2022-06, with the labels that each got.

#18583 Change label of publish button to be "Publish" again
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
Labels: i18n

#18247 Add /api/v1/admin/domain_blocks
  app/controllers/api/v1/admin/domain_blocks_controller.rb
  app/models/domain_block.rb
  app/serializers/rest/admin/domain_block_serializer.rb
  app/serializers/rest/admin/existing_domain_block_error_serializer.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api/v1/admin/domain_blocks_controller_spec.rb
Labels: api, moderation, NLnet

#18510 Add administrative webhooks
  app/controllers/admin/webhooks/secrets_controller.rb
  app/controllers/admin/webhooks_controller.rb
  app/javascript/styles/mastodon/admin.scss
  app/models/admin/action_log.rb
  app/models/report.rb
  app/models/user.rb
  app/models/webhook.rb
  app/policies/webhook_policy.rb
  app/presenters/webhooks/event_presenter.rb
  app/serializers/rest/admin/report_serializer.rb
  app/serializers/rest/admin/webhook_event_serializer.rb
  app/services/base_service.rb
  app/services/webhook_service.rb
  app/validators/url_validator.rb
  app/views/admin/webhooks/_form.html.haml
  app/views/admin/webhooks/_webhook.html.haml
  app/views/admin/webhooks/edit.html.haml
  app/views/admin/webhooks/index.html.haml
  app/views/admin/webhooks/new.html.haml
  app/views/admin/webhooks/show.html.haml
  app/views/layouts/admin.html.haml
  app/workers/trigger_webhook_worker.rb
  app/workers/webhooks/delivery_worker.rb
  config/locales/activerecord.en.yml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20220606044941_create_webhooks.rb
  db/schema.rb
  spec/fabricators/webhook_fabricator.rb
  spec/models/webhook_spec.rb
  spec/validators/url_validator_spec.rb
Labels: moderation, NLnet

#18639 Fix wrong aspect ratio of logo in icons
  app/helpers/branding_helper.rb
  app/javascript/icons/favicon-16x16.png
  app/javascript/icons/favicon-32x32.png
  app/javascript/icons/favicon-48x48.png
  app/javascript/images/logo-symbol-icon.svg
  app/javascript/images/logo.svg
  app/javascript/images/mailer/logo.png
  app/javascript/images/mailer/wordmark.png
  lib/assets/wordmark.dark.png
  lib/assets/wordmark.light.png
  lib/tasks/branding.rake
  public/badge.png
  public/favicon.ico
Labels: bug

#18603 Add GitHub Actions to package-ecosystem
  .github/dependabot.yml
Labels: dependencies

#18691 Fix contrast of some elements with new brand colors
  app/javascript/styles/contrast/variables.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/dashboard.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/statuses.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui, accessibility

#18697 Add notifications for new reports
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/components/icon_button.js
  app/javascript/mastodon/features/notifications/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/features/notifications/components/report.js
  app/javascript/mastodon/features/notifications/containers/notification_container.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/styles/mastodon/components.scss
  app/models/notification.rb
  app/serializers/rest/admin/report_serializer.rb
  app/serializers/rest/notification_serializer.rb
  app/serializers/rest/report_serializer.rb
  app/services/report_service.rb
  config/locales/en.yml
Labels: api, moderation, NLnet

#18058 Revamp post filtering system
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/filters/keywords_controller.rb
  app/controllers/api/v1/filters_controller.rb
  app/controllers/api/v2/filters_controller.rb
  app/controllers/filters_controller.rb
  app/javascript/mastodon/actions/filters.js
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/reducers/filters.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/lib/feed_manager.rb
  app/models/concerns/account_interactions.rb
  app/models/custom_filter.rb
  app/models/custom_filter_keyword.rb
  app/presenters/filter_result_presenter.rb
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/filter_keyword_serializer.rb
  app/serializers/rest/filter_result_serializer.rb
  app/serializers/rest/filter_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/serializers/rest/v1/filter_serializer.rb
  app/views/filters/_fields.html.haml
  app/views/filters/_filter.html.haml
  app/views/filters/_filter_fields.html.haml
  app/views/filters/_keyword_fields.html.haml
  app/views/filters/edit.html.haml
  app/views/filters/index.html.haml
  app/views/filters/new.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/routes.rb
  db/migrate/20220613110628_create_custom_filter_keywords.rb
  db/migrate/20220613110711_migrate_custom_filters.rb
  db/migrate/20220613110834_add_action_to_custom_filters.rb
  db/post_migrate/20220613110802_remove_whole_word_from_custom_filters.rb
  db/post_migrate/20220613110903_remove_irreversible_from_custom_filters.rb
  db/schema.rb
  lib/tasks/tests.rake
  package.json
  spec/controllers/api/v1/filters/keywords_controller_spec.rb
  spec/controllers/api/v1/filters_controller_spec.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
  spec/controllers/api/v2/filters_controller_spec.rb
  spec/fabricators/custom_filter_keyword_fabricator.rb
  spec/lib/feed_manager_spec.rb
  spec/models/custom_filter_keyword_spec.rb
  spec/presenters/status_relationships_presenter_spec.rb
  streaming/index.js
  yarn.lock
Labels: NLnet
