Repository mastodon/mastodon, pull requests merged in 2022-02, with the labels that each got.

#17444 Fix error on account relationships page in admin UI
  app/controllers/admin/relationships_controller.rb
  app/views/admin/relationships/index.html.haml
Labels: bug

#17479 Fix localization of cold-start follow recommendations
  app/models/account_suggestions/global_source.rb
  app/views/admin/follow_recommendations/show.html.haml
  app/workers/scheduler/follow_recommendations_scheduler.rb
Labels: bug, new user experience

#17464 Add global `locale` param
  app/controllers/concerns/localized.rb
  config/application.rb
Labels: api

#17486 Fix error in suggestions API due to typo
  app/models/account_suggestions/global_source.rb
Labels: bug

#17390 Add edit history to web UI
  app/controllers/api/v1/statuses/histories_controller.rb
  app/javascript/mastodon/actions/history.js
  app/javascript/mastodon/components/dropdown_menu.js
  app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
  app/javascript/mastodon/components/edited_timestamp/index.js
  app/javascript/mastodon/components/inline_account.js
  app/javascript/mastodon/components/loading_indicator.js
  app/javascript/mastodon/components/relative_timestamp.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/ui/components/compare_history_modal.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/history.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/styles/mastodon/components.scss
  app/lib/formatter.rb
  app/models/status_edit.rb
  app/serializers/rest/status_edit_serializer.rb
Labels: ui

#17492 Add `category` and `rule_ids` params to `POST /api/v1/reports`
  app/controllers/api/v1/reports_controller.rb
  app/models/report.rb
  app/services/report_service.rb
  config/locales/en.yml
Labels: api

#17320 Add editing for published statuses
  app/controllers/api/v1/media_controller.rb
  app/controllers/api/v1/statuses_controller.rb
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/features/compose/containers/compose_form_container.js
  app/javascript/mastodon/features/compose/containers/reply_indicator_container.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/reducers/compose.js
  app/models/media_attachment.rb
  app/models/status.rb
  app/policies/status_policy.rb
  app/services/activitypub/process_status_update_service.rb
  app/services/process_hashtags_service.rb
  app/services/update_status_service.rb
  app/workers/activitypub/status_update_distribution_worker.rb
  config/routes.rb
  spec/controllers/api/v1/media_controller_spec.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
  spec/policies/status_policy_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/update_status_service_spec.rb
Labels: api, ui

#17496 Fix outdated iso-639 reference in update status service
  app/services/update_status_service.rb
Labels: bug

#17484 Fix deletes not being signed in authorized fetch mode
  app/services/concerns/payloadable.rb
  app/services/delete_account_service.rb
  app/services/remove_status_service.rb
Labels: bug

#17404 Add notifications when a reblogged status has been updated
  app/controllers/api/web/push_subscriptions_controller.rb
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/notifications/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/mastodon/service_worker/web_push_locales.js
  app/javascript/mastodon/service_worker/web_push_notifications.js
  app/models/notification.rb
  app/models/status.rb
  app/serializers/rest/notification_serializer.rb
  app/services/fan_out_on_write_service.rb
  app/services/notify_service.rb
  app/workers/local_notification_worker.rb
  config/locales/en.yml
Labels: api, ui

#17523 Fix layout of the report page on smaller screens in admin UI
  app/javascript/styles/mastodon/admin.scss
Labels: bug

#17529 Bump chewy from 7.2.3 to 7.2.4
  Gemfile.lock
Labels: dependencies, ruby

#17524 Fix duplicate accounts when searching by IP range in admin UI
  app/models/account_filter.rb
  app/models/user.rb
Labels: bug

#17533 Fix privacy policy link not being visible on small screens
  app/javascript/styles/mastodon/footer.scss
  app/views/layouts/public.html.haml
Labels: bug

#17539 Remove protobuf dependencies
  .circleci/config.yml
  .github/workflows/build-image.yml
  .github/workflows/check-i18n.yml
  Aptfile
  Dockerfile
  Vagrantfile
Labels: dependencies

#17364 Add appeals
  app/controllers/admin/accounts_controller.rb
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/disputes/appeals_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/controllers/disputes/appeals_controller.rb
  app/controllers/disputes/base_controller.rb
  app/controllers/disputes/strikes_controller.rb
  app/helpers/admin/account_moderation_notes_helper.rb
  app/helpers/admin/action_logs_helper.rb
  app/helpers/admin/trends/statuses_helper.rb
  app/javascript/styles/mastodon/admin.scss
  app/mailers/admin_mailer.rb
  app/mailers/user_mailer.rb
  app/models/account.rb
  app/models/account_filter.rb
  app/models/account_warning.rb
  app/models/admin/action_log_filter.rb
  app/models/admin/appeal_filter.rb
  app/models/appeal.rb
  app/models/user.rb
  app/policies/account_warning_policy.rb
  app/policies/appeal_policy.rb
  app/services/appeal_service.rb
  app/services/approve_appeal_service.rb
  app/views/admin/account_moderation_notes/_account_moderation_note.html.haml
  app/views/admin/account_warnings/_account_warning.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/dashboard/index.html.haml
  app/views/admin/disputes/appeals/_appeal.html.haml
  app/views/admin/disputes/appeals/index.html.haml
  app/views/admin/report_notes/_report_note.html.haml
  app/views/admin/reports/show.html.haml
  app/views/admin_mailer/new_appeal.text.erb
  app/views/auth/registrations/_account_warning.html.haml
  app/views/auth/registrations/_status.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/settings/preferences/notifications/show.html.haml
  app/views/statuses/_detailed_status.html.haml
  app/views/user_mailer/appeal_approved.html.haml
  app/views/user_mailer/appeal_approved.text.erb
  app/views/user_mailer/appeal_rejected.html.haml
  app/views/user_mailer/appeal_rejected.text.erb
  app/views/user_mailer/warning.html.haml
  config/brakeman.ignore
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  config/settings.yml
  db/migrate/20220124141035_create_appeals.rb
  db/migrate/20220210153119_add_overruled_at_to_account_warnings.rb
  db/schema.rb
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/disputes/appeals_controller_spec.rb
  spec/controllers/disputes/strikes_controller_spec.rb
  spec/fabricators/account_warning_fabricator.rb
  spec/fabricators/appeal_fabricator.rb
  spec/mailers/previews/admin_mailer_preview.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/models/appeal_spec.rb
Labels: moderation

#16953 Add notifications for new sign-ups
  app/controllers/api/web/push_subscriptions_controller.rb
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/features/notifications/components/column_settings.js
  app/javascript/mastodon/features/notifications/components/notification.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/mastodon/service_worker/web_push_locales.js
  app/models/notification.rb
  app/services/bootstrap_timeline_service.rb
  app/services/notify_service.rb
  config/i18n-tasks.yml
  config/locales/en.yml
Labels: moderation

#17565 Change report modal to include category selection in web UI
  app/javascript/mastodon/actions/reports.js
  app/javascript/mastodon/actions/rules.js
  app/javascript/mastodon/components/check.js
  app/javascript/mastodon/features/report/category.js
  app/javascript/mastodon/features/report/comment.js
  app/javascript/mastodon/features/report/components/option.js
  app/javascript/mastodon/features/report/components/status_check_box.js
  app/javascript/mastodon/features/report/containers/status_check_box_container.js
  app/javascript/mastodon/features/report/rules.js
  app/javascript/mastodon/features/report/statuses.js
  app/javascript/mastodon/features/report/thanks.js
  app/javascript/mastodon/features/ui/components/report_modal.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/rules.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#17123 Add explore page to web UI
  app/javascript/mastodon/actions/trends.js
  app/javascript/mastodon/components/hashtag.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/components/status_list.js
  app/javascript/mastodon/features/explore/components/story.js
  app/javascript/mastodon/features/explore/index.js
  app/javascript/mastodon/features/explore/links.js
  app/javascript/mastodon/features/explore/results.js
  app/javascript/mastodon/features/explore/statuses.js
  app/javascript/mastodon/features/explore/suggestions.js
  app/javascript/mastodon/features/explore/tags.js
  app/javascript/mastodon/features/getting_started/containers/trends_container.js
  app/javascript/mastodon/features/search/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/mastodon/features/ui/components/tabs_bar.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/reducers/search.js
  app/javascript/mastodon/reducers/status_lists.js
  app/javascript/mastodon/reducers/trends.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#17655 Fix not showing loading indicator when searching in web UI
  app/javascript/mastodon/features/explore/results.js
  app/javascript/mastodon/reducers/search.js
Labels: bug
