Repository mastodon/mastodon, pull requests merged in 2022-12, with the labels that each got.

#22025 Fix unbounded recursion in account discovery
  Gemfile
  Gemfile.lock
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/update.rb
  app/models/concerns/domain_materializable.rb
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/fetch_remote_actor_service.rb
  app/services/activitypub/fetch_remote_status_service.rb
  app/services/activitypub/process_account_service.rb
  app/services/activitypub/process_status_update_service.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: security

#21462 Fix 500 error when trying to migrate to an invalid address
  app/models/account_migration.rb
  app/models/form/redirect.rb
  spec/models/account_migration_spec.rb
Labels: bug, activitypub

#22019 Update Node 16.18.1 for latest security release
  Dockerfile
Labels: security

#21479 Make handle more easily selectable on profile page
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#22177 Fix missing link style in warning and strike cards
  app/javascript/styles/mastodon/admin.scss
Labels: bug, ui

#21395 Validate nodeinfo response by schema
  Gemfile
  Gemfile.lock
  spec/controllers/well_known/nodeinfo_controller_spec.rb
  spec/support/matchers/json/match_json_schema.rb
  spec/support/schema/nodeinfo_2.0.json
Labels: refactoring

#21316 Change dropdown menu to contain “Copy link to post” even for non-public posts
  app/javascript/mastodon/components/status_action_bar.js
Labels: bug, ui

#21325 Revoke all authorized applications on password reset
  app/controllers/auth/passwords_controller.rb
  app/models/user.rb
  spec/controllers/auth/passwords_controller_spec.rb
Labels: security

#21471 Fix missing Javascript in domain block import confirmation page
  app/views/admin/export_domain_blocks/import.html.haml
Labels: bug, moderation

#22117 Don't delivery a reply to domains which are blocked by author
  app/lib/status_reach_finder.rb
Labels: activitypub, privacy

#21006 Fix crash in elasticsearch_check.rb
  app/lib/admin/system_check/elasticsearch_check.rb
Labels: bug

#20994 Fix profile avatar being slightly offset into left border (fixes #20822)
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#20993 Add hadolint as Dockerfile linter
  .github/workflows/build-image.yml
  Dockerfile
Labels: pipeline

#21202 Fix N+1 queries in NotificationsController
  app/controllers/api/v1/notifications_controller.rb
Labels: bug

#22141 Embed js height fix
  public/embed.js
Labels: bug, ui

#21275 Fix hidden label causing accessibility issue for search inputs
  app/javascript/mastodon/features/compose/components/search.js
Labels: ui, accessibility

#21131 Adding 12 hours option for polls
  app/javascript/mastodon/features/compose/components/poll_form.js
Labels: ui

#20982 `FormattedMessage` must be used directly
  app/javascript/mastodon/features/explore/index.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
Labels: bug

#20981 Fix typo in application_helper_spec.rb
  spec/helpers/application_helper_spec.rb
Labels: refactoring

#20979 Add localization for new admin scopes
  config/locales/doorkeeper.en.yml
Labels: i18n

#21878 Render current day formats in the client timezone
  app/javascript/mastodon/locales/en.json
  app/javascript/packs/public.js
  app/views/admin/report_notes/_report_note.html.haml
  app/views/admin/reports/show.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/settings/featured_tags/index.html.haml
  config/locales/en.yml
Labels: ui

#21692 Increase the width of the unread notification border.
  app/javascript/styles/mastodon/components.scss
Labels: ui

#21829 Fix typo in handler function call name
  app/javascript/mastodon/features/ui/components/columns_area.js
Labels: bug, ui

#19932 Fix default S3_HOSTNAME used in mastodon:setup
  lib/tasks/mastodon.rake
Labels: deployment

#20960 Change CSP directives on API to be tight and concise
  app/controllers/api/base_controller.rb
Labels: security

#20943 Fix the top action bar appearing in multi-column layout
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#21013 Add Montenegrin (cnr)
  app/helpers/languages_helper.rb
Labels: i18n

#20946 Add explanation text to log-in page
  app/views/auth/sessions/new.html.haml
  config/locales/en.yml
Labels: ui

#21440 Fix punycode encoding of the local domain
  app/serializers/initial_state_serializer.rb
Labels: ui

#19025 Enable brotli compression for static files
  config/webpack/production.js
Labels: deployment, performance

#20814 Remove inline CSS in SVG logo
  app/javascript/images/logo-symbol-icon.svg
  app/javascript/images/logo-symbol-wordmark.svg
Labels: bug

#20092 Fix single name variables on controller folder
  app/controllers/auth/registrations_controller.rb
  app/controllers/concerns/rate_limit_headers.rb
  app/controllers/concerns/signature_verification.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/controllers/media_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/tags_controller.rb
Labels: refactoring

#21282 Add "disabled" user filter for admin/accounts UI
  app/models/account_filter.rb
  app/views/admin/accounts/index.html.haml
Labels: moderation

#18081 Add transparancy to modal background for accessibility
  app/javascript/styles/mastodon/modal.scss
Labels: wontfix

#22135 Fix changing domain block severity not undoing individual account effects
  app/controllers/admin/domain_blocks_controller.rb
  app/controllers/api/v1/admin/domain_blocks_controller.rb
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/controllers/api/v1/admin/domain_blocks_controller_spec.rb
Labels: bug

#22126 Fix being stuck in edit mode when deleting the edited status
  app/javascript/mastodon/reducers/compose.js
Labels: bug, ui

#21420 Fix media markup
  app/javascript/mastodon/features/account_gallery/components/media_item.js
Labels: bug, ui

#21315 Ensure exact match is the first result in hashtag searches
  app/services/tag_search_service.rb
Labels: bug, expertise wanted

#21342 fix: remove SMTP_SERVER
  .env.production.sample
Labels: deployment

#21262 Add Southern Sami, and Lule Sami to language list under the ISO-639-3 standard
  app/helpers/languages_helper.rb
Labels: i18n

#20923 Fix language surrounding disability in prompts for alt text and other media descriptions
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
Labels: accessibility

#20582 Support "Clone Repository into Container Volume" workflow
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: local development

#20785 Add follow request banner on account header
  app/javascript/mastodon/features/account/components/follow_request_note.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account/containers/follow_request_note_container.js
  app/javascript/mastodon/reducers/relationships.js
  app/javascript/styles/mastodon/components.scss
  app/models/concerns/account_interactions.rb
  app/presenters/account_relationships_presenter.rb
  app/serializers/rest/relationship_serializer.rb
  spec/models/account_spec.rb
  spec/presenters/account_relationships_presenter_spec.rb
Labels: ui

#20464 Add left and right margin to emojis
  app/javascript/styles/mastodon/widgets.scss
Labels: ui

#19836 Remove packages that are provided by Heroku stacks
  Aptfile
Labels: deployment

#19879 Fix status cache hydration discrepancy
  app/lib/status_cache_hydrator.rb
Labels: bug

#18602 Add Western Frisian support
  config/application.rb
Labels: i18n

#22026 Fix unbounded recursion in account discovery (v3.5 backport)
  Gemfile
  Gemfile.lock
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/update.rb
  app/models/concerns/domain_materializable.rb
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/fetch_remote_account_service.rb
  app/services/activitypub/fetch_remote_status_service.rb
  app/services/activitypub/process_account_service.rb
  app/services/activitypub/process_status_update_service.rb
  app/workers/activitypub/synchronize_featured_collection_worker.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: security
