Repository mastodon/mastodon, pull requests merged in 2022-04, with the labels that each got.

#17982 Fix unset `SMTP_RETURN_PATH` environment variable causing e-mail not to send
  config/environments/production.rb
Labels: bug

#17992 Fix cookies secure flag being set when served over Tor
  config/application.rb
  config/initializers/devise.rb
  config/initializers/session_store.rb
  lib/action_dispatch/cookie_jar_extensions.rb
Labels: bug

#17996 Fix trends returning less results per page when filtered in REST API
  app/models/trends/base.rb
  app/models/trends/query.rb
  app/models/trends/statuses.rb
  app/views/admin/trends/links/_preview_card.html.haml
  app/views/admin/trends/statuses/_status.html.haml
Labels: bug

#18051 Fix parsing `TRUSTED_PROXY_IP`
  config/environments/production.rb
  streaming/index.js
Labels: bug

#18061 Add missing locale
  config/locales/en.yml
Labels: bug

#18170 Fix being able to scroll away from the loading bar in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#18171 Fix opening and closing Redis connections instead of using a pool
  app/lib/redis_configuration.rb
  app/models/concerns/redisable.rb
  config/initializers/stoplight.rb
  lib/mastodon/cli_helper.rb
  lib/mastodon/rack_middleware.rb
  lib/mastodon/search_cli.rb
  lib/mastodon/sidekiq_middleware.rb
  spec/services/resolve_account_service_spec.rb
Labels: performance

#18204 Fix error caused by missing subject in Webfinger response
  app/lib/webfinger.rb
Labels: bug

#18205 Fix error when trying to revoke OAuth token without supplying a token
  app/controllers/oauth/tokens_controller.rb
Labels: bug

#18203 Fix double render error when authorizing interaction
  app/controllers/authorize_interactions_controller.rb
  app/controllers/following_accounts_controller.rb
Labels: bug
