Repository mastodon/mastodon, pull requests merged in 2022-07, with the labels that each got.

#18809 Add ability to follow hashtags
  app/controllers/api/v1/featured_tags/suggestions_controller.rb
  app/controllers/api/v1/followed_tags_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/api/v1/trends/tags_controller.rb
  app/lib/feed_manager.rb
  app/models/tag.rb
  app/models/tag_follow.rb
  app/presenters/tag_relationships_presenter.rb
  app/serializers/rest/tag_serializer.rb
  app/services/fan_out_on_write_service.rb
  app/workers/feed_insert_worker.rb
  config/routes.rb
  db/migrate/20220714171049_create_tag_follows.rb
  db/schema.rb
  spec/controllers/api/v1/followed_tags_controller_spec.rb
  spec/controllers/api/v1/tags_controller_spec.rb
  spec/fabricators/tag_follow_fabricator.rb
  spec/models/tag_follow_spec.rb
Labels: api

#18562 Bump react-redux-loading-bar from 4.0.8 to 5.0.4
  app/javascript/mastodon/features/ui/components/image_loader.js
  app/javascript/styles/mastodon/components.scss
  package.json
  yarn.lock
Labels: dependencies, javascript

#18864 Change hashtag numbers to have clearer labels in web UI
  app/javascript/mastodon/components/hashtag.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#18863 Fix unicode regression in #18809
  app/models/account.rb
  app/models/tag.rb
Labels: bug

#18862 Add ability to follow hashtags in web UI
  app/javascript/mastodon/actions/tags.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/tags.js
Labels: ui
