Repository mastodon/mastodon, pull requests merged in 2022-03, with the labels that each got.

#17668 Add ability to mark statuses as sensitive from reports in admin UI
  app/controllers/admin/reports/actions_controller.rb
  app/javascript/styles/mastodon/admin.scss
  app/models/account_warning.rb
  app/models/admin/status_batch_action.rb
  app/models/status.rb
  app/services/approve_appeal_service.rb
  app/services/update_status_service.rb
  app/views/admin/reports/_actions.html.haml
  config/locales/en.yml
Labels: moderation

#17682 Fix report category not being saved in REST API
  app/controllers/api/v1/reports_controller.rb
  app/services/report_service.rb
  spec/controllers/api/v1/reports_controller_spec.rb
  spec/fabricators/rule_fabricator.rb
Labels: bug

#17684 Fix leak of existence of otherwise inaccessible statuses in REST API
  app/controllers/api/v1/statuses_controller.rb
Labels: bug

#17688 Remove profile directory link from main navigation panel
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
Labels: ui

#17687 Fix returning empty `<p>` tag for blank account `note` in REST API
  app/lib/formatter.rb
Labels: bug, api

#17678 Change `follow` scope to be covered by `read` and `write` scopes in REST API
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/blocks_controller.rb
  app/controllers/api/v1/domain_blocks_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/controllers/api/v1/mutes_controller.rb
Labels: api

#17698 Fix infinite re-forwarding of update activities temporarily
  app/lib/activitypub/activity/update.rb
Labels: bug

#17697 Fix duplicate notifications being possible after poll expiration
  app/controllers/api/v1/follow_requests_controller.rb
  app/lib/activitypub/activity/announce.rb
  app/lib/activitypub/activity/follow.rb
  app/lib/activitypub/activity/like.rb
  app/services/bootstrap_timeline_service.rb
  app/services/favourite_service.rb
  app/workers/feed_insert_worker.rb
  app/workers/poll_expiration_notify_worker.rb
Labels: bug

#17700 Add `/api/v1/accounts/familiar_followers` to REST API
  app/controllers/api/v1/accounts/familiar_followers_controller.rb
  app/controllers/follower_accounts_controller.rb
  app/controllers/following_accounts_controller.rb
  app/controllers/settings/preferences_controller.rb
  app/controllers/settings/profiles_controller.rb
  app/lib/user_settings_decorator.rb
  app/models/account.rb
  app/models/user.rb
  app/presenters/familiar_followers_presenter.rb
  app/serializers/rest/familiar_followers_serializer.rb
  app/views/follower_accounts/index.html.haml
  app/views/following_accounts/index.html.haml
  app/views/settings/preferences/other/show.html.haml
  app/views/settings/profiles/show.html.haml
  config/locales/simple_form.en.yml
  config/routes.rb
  config/settings.yml
  db/migrate/20220304195405_migrate_hide_network_preference.rb
  db/schema.rb
  spec/controllers/follower_accounts_controller_spec.rb
  spec/controllers/following_accounts_controller_spec.rb
  spec/presenters/familiar_followers_presenter_spec.rb
Labels: api

#17713 Fix nil error when submitting report without `rule_ids`
  app/models/report.rb
Labels: bug

#17689 Change appearance of account cards in web UI
  app/javascript/mastodon/features/directory/components/account_card.js
  app/javascript/mastodon/features/directory/index.js
  app/javascript/mastodon/features/explore/suggestions.js
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/rtl.scss
  app/views/directories/index.html.haml
  config/locales/en.yml
Labels: ui

#17709 Fix performance of account timelines
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/models/account_statuses_filter.rb
  app/models/status.rb
  spec/models/account_statuses_filter_spec.rb
  spec/models/status_spec.rb
Labels: performance

#17722 Fix invalid language resulting in no fallback being set on statuses
  app/helpers/languages_helper.rb
  app/services/post_status_service.rb
  app/services/update_status_service.rb
Labels: bug

#17712 Fix data integrity of featured tags
  app/models/featured_tag.rb
  db/migrate/20220307094650_fix_featured_tags_constraints.rb
  db/schema.rb
Labels: bug

#17704 Change design of federation pages in admin UI
  app/controllers/admin/domain_blocks_controller.rb
  app/controllers/admin/instances_controller.rb
  app/javascript/mastodon/components/admin/Counter.js
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/tables.scss
  app/lib/admin/metrics/dimension.rb
  app/lib/admin/metrics/dimension/instance_accounts_dimension.rb
  app/lib/admin/metrics/dimension/instance_languages_dimension.rb
  app/lib/admin/metrics/measure.rb
  app/lib/admin/metrics/measure/base_measure.rb
  app/lib/admin/metrics/measure/instance_accounts_measure.rb
  app/lib/admin/metrics/measure/instance_followers_measure.rb
  app/lib/admin/metrics/measure/instance_follows_measure.rb
  app/lib/admin/metrics/measure/instance_media_attachments_measure.rb
  app/lib/admin/metrics/measure/instance_reports_measure.rb
  app/lib/admin/metrics/measure/instance_statuses_measure.rb
  app/lib/delivery_failure_tracker.rb
  app/models/domain_block.rb
  app/models/instance.rb
  app/models/instance_filter.rb
  app/serializers/rest/admin/measure_serializer.rb
  app/views/admin/domain_blocks/edit.html.haml
  app/views/admin/domain_blocks/new.html.haml
  app/views/admin/domain_blocks/show.html.haml
  app/views/admin/instances/_exhausted_deliveries_days.haml
  app/views/admin/instances/_instance.html.haml
  app/views/admin/instances/index.html.haml
  app/views/admin/instances/show.html.haml
  app/workers/admin/domain_purge_worker.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/admin/domain_blocks_controller_spec.rb
Labels: moderation

#17729 Fix being able to add more than 4 hashtags to hashtag column in web UI
  app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js
Labels: ui

#17727 Add polls and media attachments to edit comparison modal in web UI
  app/javascript/mastodon/components/media_attachments.js
  app/javascript/mastodon/features/report/components/status_check_box.js
  app/javascript/mastodon/features/ui/components/compare_history_modal.js
  app/javascript/styles/mastodon/components.scss
  app/models/status_edit.rb
Labels: ui

#17743 Fix `POST /api/v1/emails/confirmations` not being available after sign-up
  app/controllers/api/v1/emails/confirmations_controller.rb
  spec/controllers/api/v1/emails/confirmations_controller_spec.rb
Labels: bug, api

#17711 Fix null values being included in some indexes
  db/migrate/20200620164023_add_fixed_lowercase_index_to_accounts.rb
  db/migrate/20210421121431_add_case_insensitive_btree_index_to_tags.rb
  db/post_migrate/20220307083603_optimize_null_index_conversations_uri.rb
  db/post_migrate/20220310060545_optimize_null_index_statuses_in_reply_to_account_id.rb
  db/post_migrate/20220310060556_optimize_null_index_statuses_in_reply_to_id.rb
  db/post_migrate/20220310060614_optimize_null_index_media_attachments_scheduled_status_id.rb
  db/post_migrate/20220310060626_optimize_null_index_media_attachments_shortcode.rb
  db/post_migrate/20220310060641_optimize_null_index_users_reset_password_token.rb
  db/post_migrate/20220310060653_optimize_null_index_users_created_by_application_id.rb
  db/post_migrate/20220310060706_optimize_null_index_statuses_uri.rb
  db/post_migrate/20220310060722_optimize_null_index_accounts_moved_to_account_id.rb
  db/post_migrate/20220310060740_optimize_null_index_oauth_access_tokens_refresh_token.rb
  db/post_migrate/20220310060750_optimize_null_index_accounts_url.rb
  db/post_migrate/20220310060809_optimize_null_index_oauth_access_tokens_resource_owner_id.rb
  db/post_migrate/20220310060833_optimize_null_index_announcement_reactions_custom_emoji_id.rb
  db/post_migrate/20220310060854_optimize_null_index_appeals_approved_by_account_id.rb
  db/post_migrate/20220310060913_optimize_null_index_account_migrations_target_account_id.rb
  db/post_migrate/20220310060926_optimize_null_index_appeals_rejected_by_account_id.rb
  db/post_migrate/20220310060939_optimize_null_index_list_accounts_follow_id.rb
  db/post_migrate/20220310060959_optimize_null_index_web_push_subscriptions_access_token_id.rb
  db/schema.rb
  lib/mastodon/migration_helpers.rb
  lib/tasks/db.rake
Labels: performance

#17746 Fix moderator account leak in status edit history
  app/models/admin/status_batch_action.rb
Labels: bug

#17747 Fix nil error when trying to fetch key for signature verification
  app/helpers/jsonld_helper.rb
Labels: bug

#17745 Fix not updating a status when newer version is fetched manually
  app/helpers/jsonld_helper.rb
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/update.rb
  app/services/activitypub/fetch_remote_status_service.rb
  spec/rails_helper.rb
  spec/services/activitypub/fetch_remote_status_service_spec.rb
Labels: activitypub

#17760 Fix public timelines being inaccessible on one stage of responsive layout in web UI
  app/javascript/mastodon/features/ui/components/tabs_bar.js
Labels: bug

#17765 Fix nil error when viewing suspended domain in admin UI
  app/models/instance.rb
  app/views/admin/instances/show.html.haml
Labels: bug

#17759 Fix not being able to upload GIF emojis in admin UI
  app/views/admin/custom_emojis/new.html.haml
  config/locales/ar.yml
  config/locales/bn.yml
  config/locales/ca.yml
  config/locales/co.yml
  config/locales/cs.yml
  config/locales/cy.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/en_GB.yml
  config/locales/eo.yml
  config/locales/es-AR.yml
  config/locales/es-MX.yml
  config/locales/es.yml
  config/locales/et.yml
  config/locales/eu.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/gd.yml
  config/locales/gl.yml
  config/locales/hu.yml
  config/locales/hy.yml
  config/locales/id.yml
  config/locales/is.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ka.yml
  config/locales/kab.yml
  config/locales/kk.yml
  config/locales/kmr.yml
  config/locales/ko.yml
  config/locales/ku.yml
  config/locales/lt.yml
  config/locales/lv.yml
  config/locales/ms.yml
  config/locales/nl.yml
  config/locales/nn.yml
  config/locales/no.yml
  config/locales/oc.yml
  config/locales/pl.yml
  config/locales/pt-BR.yml
  config/locales/pt-PT.yml
  config/locales/ru.yml
  config/locales/sc.yml
  config/locales/sk.yml
  config/locales/sl.yml
  config/locales/sq.yml
  config/locales/sr-Latn.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/vi.yml
  config/locales/zh-CN.yml
  config/locales/zh-HK.yml
  config/locales/zh-TW.yml
Labels: bug

#17770 Fix LetterOpennerWeb CSP
  config/initializers/content_security_policy.rb
Labels: bug

#17786 Fix statuses not being referenced in strike when category is spam
  app/models/admin/account_action.rb
Labels: bug

#17767 Add `types` param to `GET /api/v1/notifications` in REST API
  app/controllers/api/v1/notifications_controller.rb
  app/models/notification.rb
  spec/controllers/api/v1/notifications_controller_spec.rb
Labels: api

#17787 Fix individually approved/rejected statuses/links showing as pending review
  app/models/preview_card.rb
  app/models/status.rb
  app/views/admin/trends/links/_preview_card.html.haml
  app/views/admin/trends/statuses/_status.html.haml
Labels: bug

#17802 Replace metadata-action type to match
  .github/workflows/build-image.yml
Labels: bug

#17844 Fix color of show more link in report dialog in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug

#17845 Add hint about missing media attachment description in web UI
  app/javascript/mastodon/features/compose/components/upload.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#17848 Fix IDN domains not being rendered correctly in a few left-over places
  app/views/accounts/_moved.html.haml
  app/views/admin/account_actions/new.html.haml
  app/views/admin/account_warnings/_account_warning.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/change_emails/show.html.haml
  app/views/admin/disputes/appeals/_appeal.html.haml
  app/views/admin/relationships/index.html.haml
  app/views/admin/statuses/index.html.haml
  app/views/admin_mailer/new_report.text.erb
  app/views/auth/registrations/_status.html.haml
  app/views/authorize_interactions/show.html.haml
  app/views/authorize_interactions/success.html.haml
  app/views/notification_mailer/_status.html.haml
  app/views/notification_mailer/digest.text.erb
  app/views/notification_mailer/favourite.html.haml
  app/views/notification_mailer/favourite.text.erb
  app/views/notification_mailer/follow.html.haml
  app/views/notification_mailer/follow.text.erb
  app/views/notification_mailer/follow_request.html.haml
  app/views/notification_mailer/follow_request.text.erb
  app/views/notification_mailer/mention.html.haml
  app/views/notification_mailer/mention.text.erb
  app/views/notification_mailer/reblog.html.haml
  app/views/notification_mailer/reblog.text.erb
  app/views/settings/aliases/index.html.haml
  app/views/settings/migrations/show.html.haml
  config/brakeman.ignore
Labels: bug

#17846 Fix wrong position of fade-out element in account card in web UI
  app/javascript/styles/mastodon/admin.scss
Labels: bug

#17847 Fix locale not being set in REST API
  app/controllers/activitypub/base_controller.rb
  app/controllers/api/base_controller.rb
Labels: bug

#17872 Add offset pagination to trends in REST API
  app/controllers/api/v1/trends/links_controller.rb
  app/controllers/api/v1/trends/statuses_controller.rb
  app/controllers/api/v1/trends/tags_controller.rb
  app/models/trends/query.rb
Labels: api

#17843 Fix edits with no actual changes being allowed
  app/lib/activitypub/parser/media_attachment_parser.rb
  app/models/concerns/status_snapshot_concern.rb
  app/models/media_attachment.rb
  app/models/status.rb
  app/services/activitypub/process_status_update_service.rb
  app/services/update_status_service.rb
  spec/models/media_attachment_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/update_status_service_spec.rb
Labels: bug

#17828 Refactor formatter
  app/chewy/statuses_index.rb
  app/controllers/api/web/embeds_controller.rb
  app/helpers/accounts_helper.rb
  app/helpers/admin/trends/statuses_helper.rb
  app/helpers/application_helper.rb
  app/helpers/formatting_helper.rb
  app/helpers/routing_helper.rb
  app/helpers/statuses_helper.rb
  app/lib/activitypub/activity/create.rb
  app/lib/emoji_formatter.rb
  app/lib/extractor.rb
  app/lib/feed_manager.rb
  app/lib/formatter.rb
  app/lib/html_aware_formatter.rb
  app/lib/plain_text_formatter.rb
  app/lib/rss/serializer.rb
  app/lib/text_formatter.rb
  app/mailers/application_mailer.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/note_serializer.rb
  app/serializers/rest/account_serializer.rb
  app/serializers/rest/announcement_serializer.rb
  app/serializers/rest/status_edit_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/services/fetch_link_card_service.rb
  app/views/accounts/_bio.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/show.html.haml
  app/views/directories/index.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/notification_mailer/_status.html.haml
  app/views/notification_mailer/_status.text.erb
  app/views/notification_mailer/digest.text.erb
  app/views/statuses/_detailed_status.html.haml
  app/views/statuses/_poll.html.haml
  app/views/statuses/_simple_status.html.haml
  app/views/user_mailer/warning.html.haml
  config/initializers/twitter_regex.rb
  spec/lib/emoji_formatter_spec.rb
  spec/lib/formatter_spec.rb
  spec/lib/html_aware_formatter.rb
  spec/lib/plain_text_formatter_spec.rb
  spec/lib/text_formatter_spec.rb
Labels: refactoring

#17875 Fix typo
  app/serializers/activitypub/actor_serializer.rb
Labels: bug

#17909 Fix being able to bypass e-mail restrictions
  app/models/user.rb
Labels: security

#17908 Fix being able to post URLs longer than 4096 characters
  app/lib/extractor.rb
  app/validators/status_length_validator.rb
  spec/validators/status_length_validator_spec.rb
Labels: security
