Repository mastodon/mastodon, pull requests merged in 2022-10, with the labels that each got.

#19263 Change responsive layout of web UI
  app/javascript/mastodon/components/not_signed_in_indicator.js
  app/javascript/mastodon/features/about/index.js
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/features/explore/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/features/keyboard_shortcuts/index.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/compose_panel.js
  app/javascript/mastodon/features/ui/components/header.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/mastodon/features/ui/components/tabs_bar.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#19294 Add server banner to web app, add `GET /api/v2/instance` to REST API
  app/controllers/about_controller.rb
  app/controllers/api/v1/instances_controller.rb
  app/controllers/api/v2/instances_controller.rb
  app/javascript/mastodon/actions/rules.js
  app/javascript/mastodon/actions/server.js
  app/javascript/mastodon/components/account.js
  app/javascript/mastodon/components/display_name.js
  app/javascript/mastodon/components/server_banner.js
  app/javascript/mastodon/features/report/rules.js
  app/javascript/mastodon/features/ui/components/compose_panel.js
  app/javascript/mastodon/features/ui/components/report_modal.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/rules.js
  app/javascript/mastodon/reducers/server.js
  app/javascript/styles/mastodon/components.scss
  app/presenters/instance_presenter.rb
  app/serializers/initial_state_serializer.rb
  app/serializers/manifest_serializer.rb
  app/serializers/rest/instance_serializer.rb
  app/serializers/rest/v1/instance_serializer.rb
  app/views/about/more.html.haml
  app/views/about/show.html.haml
  app/views/application/_sidebar.html.haml
  app/views/privacy/show.html.haml
  app/views/shared/_og.html.haml
  config/routes.rb
  spec/presenters/instance_presenter_spec.rb
  spec/views/about/show.html.haml_spec.rb
Labels: api, ui

#19296 Add server rules to sign-up flow
  app/controllers/auth/registrations_controller.rb
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/forms.scss
  app/views/auth/registrations/new.html.haml
  app/views/auth/registrations/rules.html.haml
  config/locales/en.yml
Labels: ui, new user experience

#19300 Remove previous landing page
  app/controllers/about_controller.rb
  app/views/about/_logged_in.html.haml
  app/views/about/_login.html.haml
  app/views/about/_registration.html.haml
  app/views/about/show.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/about_controller_spec.rb
  spec/requests/localization_spec.rb
  spec/views/about/show.html.haml_spec.rb
Labels: ui

#19306 Add interaction modal to logged-out web UI
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/containers/status_container.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/mastodon/features/interaction_modal/index.js
  app/javascript/mastodon/features/picture_in_picture/components/footer.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/components/modal_root.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#19310 Change privacy policy to be rendered in web UI, add REST API
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/instances/privacy_policies_controller.rb
  app/controllers/privacy_controller.rb
  app/javascript/mastodon/features/privacy_policy/index.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/styles/mastodon/components.scss
  app/models/privacy_policy.rb
  app/serializers/rest/privacy_policy_serializer.rb
  app/views/privacy/show.html.haml
  config/i18n-tasks.yml
  config/locales/en.yml
  config/routes.rb
Labels: api, ui

#19318 Fix privacy policy being empty if custom setting exists but is empty
  app/models/privacy_policy.rb
Labels: bug

#18288 Add support for language preferences for trending statuses and links
  app/controllers/admin/trends/links_controller.rb
  app/controllers/admin/trends/statuses_controller.rb
  app/controllers/api/v1/trends/links_controller.rb
  app/mailers/admin_mailer.rb
  app/models/preview_card.rb
  app/models/preview_card_trend.rb
  app/models/status.rb
  app/models/status_trend.rb
  app/models/trends.rb
  app/models/trends/base.rb
  app/models/trends/links.rb
  app/models/trends/preview_card_filter.rb
  app/models/trends/status_filter.rb
  app/models/trends/statuses.rb
  app/views/admin/trends/links/_preview_card.html.haml
  app/views/admin/trends/links/index.html.haml
  app/views/admin/trends/statuses/_status.html.haml
  app/views/admin/trends/statuses/index.html.haml
  app/views/admin_mailer/_new_trending_links.text.erb
  app/views/admin_mailer/_new_trending_statuses.text.erb
  config/locales/en.yml
  db/migrate/20220824233535_create_status_trends.rb
  db/migrate/20221006061337_create_preview_card_trends.rb
  db/schema.rb
  spec/fabricators/account_fabricator.rb
  spec/mailers/previews/admin_mailer_preview.rb
  spec/models/preview_card_trend_spec.rb
  spec/models/status_trend_spec.rb
  spec/models/trends/statuses_spec.rb
Labels: new user experience

#19320 Remove timeline preview link from nav panel when not signed-in
  app/javascript/mastodon/components/server_banner.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
Labels: bug

#19322 Add title to pages with missing title in Web UI
  app/javascript/mastodon/containers/mastodon.js
  app/javascript/mastodon/features/about/index.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/bookmarked_statuses/index.js
  app/javascript/mastodon/features/community_timeline/index.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/directory/index.js
  app/javascript/mastodon/features/explore/index.js
  app/javascript/mastodon/features/explore/results.js
  app/javascript/mastodon/features/favourited_statuses/index.js
  app/javascript/mastodon/features/favourites/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
  app/javascript/mastodon/features/home_timeline/index.js
  app/javascript/mastodon/features/list_timeline/index.js
  app/javascript/mastodon/features/lists/index.js
  app/javascript/mastodon/features/notifications/index.js
  app/javascript/mastodon/features/privacy_policy/index.js
  app/javascript/mastodon/features/public_timeline/index.js
  app/javascript/mastodon/features/status/index.js
  app/javascript/mastodon/features/ui/index.js
Labels: refactoring

#19315 Add dismissable hints to various timelines in web UI
  app/javascript/mastodon/components/dismissable_banner.js
  app/javascript/mastodon/features/community_timeline/index.js
  app/javascript/mastodon/features/explore/links.js
  app/javascript/mastodon/features/explore/statuses.js
  app/javascript/mastodon/features/explore/tags.js
  app/javascript/mastodon/features/public_timeline/index.js
  app/javascript/mastodon/settings.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#19324 Fix intermediary responsive layout, accessibility on navigation in web UI
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar-test.js.snap
  app/javascript/mastodon/components/avatar.js
  app/javascript/mastodon/components/logo.js
  app/javascript/mastodon/features/ui/components/column_link.js
  app/javascript/mastodon/features/ui/components/follow_requests_column_link.js
  app/javascript/mastodon/features/ui/components/header.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#19329 Fix fedi/local timeline nav link always hide
  app/javascript/mastodon/features/ui/components/navigation_panel.js
Labels: bug

#19334 Fix `ColumnLink` labels not disappearing in mobile UI
  app/javascript/mastodon/features/ui/components/column_link.js
Labels: bug

#19335 Fix missing `skip_review?`
  app/models/trends.rb
Labels: bug

#19348 Add image processing and generate blurhash for server thumbnail
  app/models/form/admin_settings.rb
  app/models/site_upload.rb
  app/presenters/instance_presenter.rb
  app/serializers/rest/instance_serializer.rb
  app/serializers/rest/v1/instance_serializer.rb
  app/views/admin/settings/edit.html.haml
  app/views/application/_sidebar.html.haml
  app/views/shared/_og.html.haml
  config/locales/en.yml
  db/migrate/20221012181003_add_blurhash_to_site_uploads.rb
  db/schema.rb
  spec/presenters/instance_presenter_spec.rb
Labels: api, moderation

#19345 Change about page to be mounted in the web UI
  app/controllers/about_controller.rb
  app/controllers/api/v1/instances/domain_blocks_controller.rb
  app/controllers/api/v1/instances/extended_descriptions_controller.rb
  app/javascript/fonts/montserrat/Montserrat-Medium.ttf
  app/javascript/fonts/montserrat/Montserrat-Regular.ttf
  app/javascript/fonts/montserrat/Montserrat-Regular.woff
  app/javascript/fonts/montserrat/Montserrat-Regular.woff2
  app/javascript/mastodon/actions/server.js
  app/javascript/mastodon/components/image.js
  app/javascript/mastodon/components/server_banner.js
  app/javascript/mastodon/components/skeleton.js
  app/javascript/mastodon/features/about/index.js
  app/javascript/mastodon/features/privacy_policy/index.js
  app/javascript/mastodon/features/report/rules.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/mastodon/reducers/server.js
  app/javascript/styles/application.scss
  app/javascript/styles/contrast/diff.scss
  app/javascript/styles/fonts/montserrat.scss
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/compact_header.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/dashboard.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/widgets.scss
  app/models/domain_block.rb
  app/models/extended_description.rb
  app/serializers/rest/domain_block_serializer.rb
  app/serializers/rest/extended_description_serializer.rb
  app/views/about/_domain_blocks.html.haml
  app/views/about/more.html.haml
  app/views/about/show.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/about_controller_spec.rb
Labels: api, ui

#19352 Replace `CancelToken` to `AbortSignal`
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/api.js
  app/javascript/mastodon/extra_polyfills.js
  app/javascript/mastodon/load_polyfills.js
  jsconfig.json
  package.json
  yarn.lock
Labels: bug

#19354 Fix missing `isCancel`
  app/javascript/mastodon/actions/compose.js
Labels: bug

#19385 Fix error while server rules are loading in report modal in web UI
  app/javascript/mastodon/features/report/category.js
Labels: bug

#19386 Fix error on migration page
  app/views/settings/migrations/show.html.haml
Labels: bug

#19387 Fix missing rules in report modal in web UI
  app/javascript/mastodon/features/report/category.js
Labels: bug

#19388 Fix showing translate button when status has no language in web UI
  app/javascript/mastodon/components/status_content.js
Labels: bug

#19382 Change featured hashtags to be displayed in navigation panel
  app/javascript/mastodon/components/hashtag.js
  app/javascript/mastodon/components/navigation_portal.js
  app/javascript/mastodon/features/account/components/featured_tags.js
  app/javascript/mastodon/features/account/containers/featured_tags_container.js
  app/javascript/mastodon/features/account/navigation.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/styles/mastodon/components.scss
  app/serializers/rest/featured_tag_serializer.rb
Labels: ui

#19396 Fix error on profile in web UI
  app/javascript/mastodon/features/account_timeline/index.js
Labels: bug

#19398 Fix too many featured tags causing navigation panel scroll in web UI
  app/javascript/mastodon/features/account/components/featured_tags.js
Labels: ui

#19397 Fix case-sensitive look-up for profiles in web UI
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/reducers/accounts_map.js
Labels: bug

#19401 Fix `FetchFeaturedCollectionService` spec
  app/services/activitypub/fetch_featured_collection_service.rb
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
Labels: bug

#19351 Fix remote account in contact account setting not being used
  app/presenters/instance_presenter.rb
  app/validators/existing_username_validator.rb
Labels: bug

#19407 Change settings area to be separated into categories in admin UI
  app/controllers/admin/settings/about_controller.rb
  app/controllers/admin/settings/appearance_controller.rb
  app/controllers/admin/settings/branding_controller.rb
  app/controllers/admin/settings/content_retention_controller.rb
  app/controllers/admin/settings/discovery_controller.rb
  app/controllers/admin/settings/registrations_controller.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/site_uploads_controller.rb
  app/helpers/admin/settings_helper.rb
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/models/form/admin_settings.rb
  app/serializers/rest/extended_description_serializer.rb
  app/views/admin/settings/about/show.html.haml
  app/views/admin/settings/appearance/show.html.haml
  app/views/admin/settings/branding/show.html.haml
  app/views/admin/settings/content_retention/show.html.haml
  app/views/admin/settings/discovery/show.html.haml
  app/views/admin/settings/edit.html.haml
  app/views/admin/settings/registrations/show.html.haml
  app/views/admin/settings/shared/_links.html.haml
  app/views/layouts/admin.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes.rb
  spec/controllers/admin/settings/branding_controller_spec.rb
  spec/controllers/admin/settings_controller_spec.rb
Labels: moderation

#19413 Fix error when rendering limited account in web UI
  app/javascript/mastodon/components/avatar.js
Labels: bug

#19418 Fix `Settings::FeaturedTagsController`
  app/controllers/settings/featured_tags_controller.rb
  app/services/create_featured_tag_service.rb
Labels: bug

#19417 Fix reply not opening compose page on certain screen sizes in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/styles/mastodon/components.scss
Labels: bug

#19412 Add error boundary around routes in web UI
  app/javascript/mastodon/features/ui/components/bundle_column_error.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/features/ui/util/react_router_helpers.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#19421 Fix PWA manifest using `/web` paths
  app/javascript/mastodon/service_worker/entry.js
  app/serializers/manifest_serializer.rb
Labels: bug

#19422 Change floating action button to be a button in header in web UI
  app/javascript/mastodon/features/ui/components/columns_area.js
  app/javascript/mastodon/features/ui/components/header.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/mastodon/features/ui/index.js
  app/javascript/styles/mastodon/components.scss
  app/serializers/manifest_serializer.rb
  app/views/layouts/application.html.haml
Labels: ui

#19427 Fix redirecting to `/publish` when compose form is visible in web UI
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/features/ui/components/compose_panel.js
Labels: bug

#19426 Fix media, following and followers tabs in web UI
  app/javascript/mastodon/features/account/navigation.js
  app/javascript/mastodon/features/account_gallery/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
Labels: bug

#19428 Fix language dropdown causing zoom on mobile devices in web UI
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/emoji_picker.scss
Labels: bug

#19455 Fix `nofollow` rel being removed in web UI
  app/javascript/mastodon/components/status_content.js
Labels: bug

#19453 Change design of translations in web UI
  app/javascript/mastodon/components/status_content.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#19423 Change layout of posts in web UI
  app/javascript/mastodon/components/account.js
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/components/status_content.js
  app/javascript/mastodon/features/account/components/featured_tags.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/compose/components/action_bar.js
  app/javascript/mastodon/features/compose/components/navigation_bar.js
  app/javascript/mastodon/features/status/components/action_bar.js
  app/javascript/mastodon/features/status/components/detailed_status.js
  app/javascript/mastodon/features/ui/components/actions_modal.js
  app/javascript/mastodon/features/ui/components/boost_modal.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#19457 Fix wrong size of avatars in admin UI
  app/helpers/home_helper.rb
  app/javascript/styles/mastodon/widgets.scss
Labels: bug

#19326 Change unauthenticated search to not support pagination in REST API
  app/controllers/api/v2/search_controller.rb
  app/services/account_search_service.rb
  spec/controllers/api/v2/search_controller_spec.rb
Labels: api

#19464 Fix negatives values in search index causing queries to fail
  app/services/account_search_service.rb
Labels: bug

#19466 Fix warning about constants in routes
  config/routes.rb
Labels: bug

#19103 Change post editing to be enabled in web UI
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/features/status/components/action_bar.js
Labels: ui

#19472 Fix improperly checking for blocked domain on followed hashtags
  app/lib/feed_manager.rb
Labels: bug

#19481 Fix wrong math function used in search query
  app/services/account_search_service.rb
Labels: bug

#19475 Fix notifications about deleted reports not being also deleted
  app/javascript/mastodon/features/notifications/components/notification.js
  app/models/report.rb
Labels: bug

#19477 Add `--remove-role` option to `tootctl accounts modify`
  lib/mastodon/accounts_cli.rb
Labels: moderation

#19485 Fix missing delete and redraft link in web UI
  app/javascript/mastodon/features/status/components/action_bar.js
Labels: bug

#19486 Change `closed_registrations_message` to `message` and add Markdown
  app/serializers/rest/instance_serializer.rb
Labels: api

#19489 Remove unused method `searchable?` on accounts
  app/models/account.rb
Labels: refactoring

#19490 Fix using wrong policy on status-related actions in admin UI
  app/models/admin/status_batch_action.rb
  app/models/trends/status_batch.rb
Labels: bug

#19488 Fix avatars not using image tags in web UI
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar-test.js.snap
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar_overlay-test.js.snap
  app/javascript/mastodon/components/avatar.js
  app/javascript/mastodon/components/avatar_composite.js
  app/javascript/mastodon/components/avatar_overlay.js
  app/javascript/styles/mastodon/components.scss
Labels: accessibility

#19484 Fix number of uses being shown again on trending hashtags in web UI
  app/javascript/mastodon/components/hashtag.js
  app/javascript/styles/mastodon/components.scss
Labels: bug

#19508 Fix closed registrations message not appearing in web UI
  app/javascript/mastodon/features/closed_registrations_modal/index.js
Labels: bug

#19509 Fix error when uploading malformed CSV import
  app/validators/import_validator.rb
  config/locales/activerecord.en.yml
Labels: bug

#18429 Fix account migration form ever using outdated account data
  app/models/form/redirect.rb
  app/services/resolve_account_service.rb
Labels: wontfix

#19514 Fix logged out search and changed logged-in search placeholder
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/compose/components/search.js
Labels: bug

#19521 Fix wrong host being used for custom.css when asset host configured
  app/views/layouts/application.html.haml
Labels: bug

#19530 Fix upload progress not communicating processing phase in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/compose/components/upload_form.js
  app/javascript/mastodon/features/compose/components/upload_progress.js
  app/javascript/mastodon/features/compose/containers/upload_progress_container.js
  app/javascript/mastodon/reducers/compose.js
Labels: ui

#19533 Fix sidebar and tabs on settings on small screens in admin UI
  app/javascript/packs/public.js
  app/javascript/styles/mastodon/admin.scss
  app/views/layouts/admin.html.haml
  config/locales/en.yml
Labels: ui, accessibility

#19543 Fix language not being saved when editing status
  app/controllers/api/v1/statuses_controller.rb
Labels: bug

#19479 Fix admin APIs returning deleted object instead of empty object upon delete
  app/controllers/api/v1/admin/accounts_controller.rb
  app/controllers/api/v1/admin/canonical_email_blocks_controller.rb
  app/controllers/api/v1/admin/domain_allows_controller.rb
  app/controllers/api/v1/admin/domain_blocks_controller.rb
  app/controllers/api/v1/admin/email_domain_blocks_controller.rb
  app/controllers/api/v1/admin/ip_blocks_controller.rb
Labels: bug, api, breaking

#19476 Fix account action type validation
  app/models/admin/account_action.rb
  spec/controllers/api/v1/admin/account_actions_controller_spec.rb
Labels: bug, api

#19562 Change design of link footer
  app/javascript/mastodon/components/account.js
  app/javascript/mastodon/components/server_banner.js
  app/javascript/mastodon/features/about/index.js
  app/javascript/mastodon/features/ui/components/link_footer.js
  app/javascript/styles/mastodon/components.scss
Labels: ui
