Repository mastodon/mastodon, pull requests merged in 2022-05, with the labels that each got.

#18227 Add translatable string for #17431
  config/locales/en.yml
Labels: i18n

#18289 Change "Conversations" back to "Direct messages" and add warning in web UI
  app/javascript/mastodon/components/status_action_bar.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/direct_timeline/index.js
  app/javascript/mastodon/features/getting_started/index.js
  app/javascript/mastodon/features/keyboard_shortcuts/index.js
  app/javascript/mastodon/features/ui/components/navigation_panel.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#18364 Fix block/mute lists showing a follow button when unblocking a user
  app/javascript/mastodon/components/account.js
  app/javascript/mastodon/features/blocks/index.js
  app/javascript/mastodon/features/mutes/index.js
Labels: ui

#18344 Add `limited` attribute to accounts in REST API and a warning in web UI
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/components/avatar.js
  app/javascript/mastodon/features/account/components/header.js
  app/javascript/mastodon/features/account_timeline/components/header.js
  app/javascript/mastodon/features/account_timeline/components/limited_account_hint.js
  app/javascript/mastodon/features/account_timeline/containers/header_container.js
  app/javascript/mastodon/features/account_timeline/index.js
  app/javascript/mastodon/features/followers/index.js
  app/javascript/mastodon/features/following/index.js
  app/javascript/mastodon/reducers/accounts.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/styles/mastodon/components.scss
  app/serializers/rest/account_serializer.rb
Labels: api, ui

#18400 Refactor how Redis locks are created
  app/controllers/media_proxy_controller.rb
  app/controllers/settings/exports_controller.rb
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/announce.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/delete.rb
  app/models/account_migration.rb
  app/models/concerns/lockable.rb
  app/models/concerns/redisable.rb
  app/services/activitypub/process_account_service.rb
  app/services/activitypub/process_status_update_service.rb
  app/services/fetch_link_card_service.rb
  app/services/remove_status_service.rb
  app/services/resolve_account_service.rb
  app/services/vote_service.rb
  app/workers/distribution_worker.rb
Labels: refactoring

#18424 Fix `Mastodon::RaceConditionError` that occurs when external status is reblogged
  app/lib/activitypub/activity/announce.rb
Labels: bug

#18420 Add language dropdown to compose in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/languages.js
  app/javascript/mastodon/features/compose/components/compose_form.js
  app/javascript/mastodon/features/compose/components/language_dropdown.js
  app/javascript/mastodon/features/compose/components/text_icon_button.js
  app/javascript/mastodon/features/compose/containers/language_dropdown_container.js
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/compose.js
  app/javascript/mastodon/reducers/settings.js
  app/javascript/styles/mastodon/components.scss
  app/serializers/initial_state_serializer.rb
  package.json
  yarn.lock
Labels: ui, NLnet

#18430 Revert "Bump redis from 4.0.6 to 4.1.0"
  package.json
  yarn.lock
Labels: dependencies

#18444 Prevent update to redis 4.1.0
  package.json
  yarn.lock
Labels: dependencies, javascript

#18460 Fix languages dropdown on light theme
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug

#18463 Change algorithm of `tootctl search deploy` to improve performance
  app/chewy/accounts_index.rb
  app/chewy/statuses_index.rb
  app/chewy/tags_index.rb
  app/lib/importer/accounts_index_importer.rb
  app/lib/importer/base_importer.rb
  app/lib/importer/statuses_index_importer.rb
  app/lib/importer/tags_index_importer.rb
  app/models/trends/history.rb
  lib/mastodon/search_cli.rb
Labels: deployment, performance

#18514 Fix regression in `tootctl search deploy` caused by unloaded attribute
  app/models/poll.rb
Labels: bug

#18519 Add ES6 compatibility to browserslist
  .browserslistrc
Labels: bug

#18517 Fix follower and other counters being able to go negative
  app/models/account_stat.rb
  app/models/status_stat.rb
Labels: bug

#18524 Fix suspended users being able to access APIs that don't require a user
  app/controllers/activitypub/base_controller.rb
  app/controllers/api/base_controller.rb
Labels: security

#18525 Fix moderator identity leak when approving appeal of sensitive marked statuses
  app/services/approve_appeal_service.rb
Labels: security

#18526 Fix empty votes arbitrarily increasing voters count in polls
  app/services/vote_service.rb
Labels: security

#18528 Fix being able to report otherwise inaccessible statuses
  app/models/admin/status_batch_action.rb
  app/services/report_service.rb
Labels: security

#18527 Fix concurrent unfollowing decrementing follower count more than once
  app/services/unfollow_service.rb
Labels: security
