Repository mastodon/mastodon, pull requests merged in 2023-07, with the labels that each got.

#24241 Rails 7 update
  Gemfile
  Gemfile.lock
  app/lib/inline_renderer.rb
  app/lib/rss/channel.rb
  app/lib/rss/item.rb
  app/models/announcement.rb
  app/models/concerns/account_search.rb
  app/models/concerns/status_safe_reblog_insert.rb
  app/models/notification.rb
  app/serializers/initial_state_serializer.rb
  app/services/account_search_service.rb
  app/services/batched_remove_status_service.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_7_0.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: refactoring

#25661 Change dropdown icon above compose form from ellipsis to bars in web UI
  app/javascript/mastodon/features/compose/components/action_bar.jsx
Labels: ui

#25677 Change button colors to increase hover/focus contrast and consistency
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/dashboard.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#25679 Fix regression of icon button colors in web UI
  app/javascript/styles/mastodon/variables.scss
Labels: bug

#25683 Change labels of live feeds tabs in web UI
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/mastodon/features/public_timeline/index.jsx
  app/javascript/mastodon/locales/en.json
  config/routes.rb
Labels: ui

#25713 Fix OAuth apps page crashing when listing apps with certain admin API scopes
  app/lib/scope_parser.rb
Labels: bug, to backport

#25726 Add button to see results for polls in web UI
  app/javascript/mastodon/components/poll.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#25788 Fix processing of media files with unusual names
  app/models/concerns/attachmentable.rb
  spec/fixtures/files/attachment-jpg.123456_abcd
  spec/requests/api/v2/media_spec.rb
Labels: to backport

#25794 Fix branding:generate_app_icons failing because of disallowed ICO coder
  lib/tasks/branding.rake
Labels: bug, to backport

#25796 Fix crash in admin interface when viewing a remote user with verified links
  app/lib/text_formatter.rb
Labels: bug, to backport

#25541 simplify counters
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/common_counter.jsx
  app/javascript/mastodon/components/counters.tsx
  app/javascript/mastodon/features/account/components/header.jsx
Labels: typescript

#25492 Rewrite `<ShortNumber />` as FC and TS
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/animated_number.tsx
  app/javascript/mastodon/components/autosuggest_hashtag.tsx
  app/javascript/mastodon/components/hashtag.jsx
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/components/short_number.jsx
  app/javascript/mastodon/components/short_number.tsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/directory/components/account_card.jsx
  app/javascript/mastodon/features/explore/components/story.jsx
Labels: typescript

#25582 Convert `<DismissableBanner>` to Typescript
  app/javascript/mastodon/components/dismissable_banner.jsx
  app/javascript/mastodon/components/dismissable_banner.tsx
  app/javascript/mastodon/features/community_timeline/index.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/mastodon/features/home_timeline/components/explore_prompt.jsx
  app/javascript/mastodon/features/public_timeline/index.jsx
Labels: typescript

#25341 Add forwarding of reported replies to servers being replied to
  app/lib/activitypub/activity/flag.rb
  app/services/report_service.rb
  spec/services/report_service_spec.rb
Labels: activitypub

#25716 Fix explore page being inaccessible when opted-out of trends in web UI
  app/javascript/mastodon/features/explore/index.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/initial_state.js
  app/serializers/initial_state_serializer.rb
Labels: bug

#25714 Fix dropdowns being disabled for logged out users in web UI
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/status/components/action_bar.jsx
Labels: ui

#25564 Add toast with option to open post after publishing in web UI
  app/javascript/mastodon/actions/alerts.js
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/ui/containers/notifications_container.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/alerts.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#25759 Admin mailer parameterization
  app/mailers/admin_mailer.rb
  app/models/trends.rb
  app/models/user.rb
  app/services/appeal_service.rb
  app/services/report_service.rb
  config/i18n-tasks.yml
  spec/controllers/api/v1/reports_controller_spec.rb
  spec/controllers/disputes/appeals_controller_spec.rb
  spec/mailers/admin_mailer_spec.rb
  spec/mailers/previews/admin_mailer_preview.rb
Labels: refactoring, ruby

#25712 Change label and design of sensitive and unavailable media in web UI
  app/javascript/mastodon/components/media_gallery.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#25835 Fix trend calculation working on too many items at a time
  app/models/trends/links.rb
  app/models/trends/statuses.rb
Labels: performance

#25849 Change feed merge, unmerge and regeneration workers to use a replica
  app/workers/merge_worker.rb
  app/workers/regeneration_worker.rb
  app/workers/unmerge_worker.rb
Labels: performance

#25718 Refactor `NotificationMailer` to use parameterization
  app/mailers/notification_mailer.rb
  app/services/notify_service.rb
  spec/mailers/notification_mailer_spec.rb
  spec/mailers/previews/notification_mailer_preview.rb
Labels: refactoring, ruby

#25885 Fix moderation interface for remote instances with a .zip TLD
  config/routes/admin.rb
Labels: to backport

#25886 Fix remote accounts being possibly persisted to database with incomplete protocol values
  app/services/activitypub/process_account_service.rb
Labels: to backport

#25919 Use invariant colors on notification toasts
  app/javascript/styles/mastodon/components.scss
Labels: ui

#23652 Enable Rubocop Style/Semicolon with config
  .rubocop.yml
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#23871 Run Rubocop on Rakefile
  .rubocop.yml
  Rakefile
Labels: ruby, lint fix 💅

#25312 Fix `RSpec/SubjectDeclaration` cop
  .rubocop_todo.yml
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/models/account_migration_spec.rb
  spec/models/account_spec.rb
  spec/models/relationship_filter_spec.rb
  spec/models/user_role_spec.rb
  spec/policies/account_moderation_note_policy_spec.rb
  spec/policies/account_policy_spec.rb
  spec/policies/backup_policy_spec.rb
  spec/policies/custom_emoji_policy_spec.rb
  spec/policies/domain_block_policy_spec.rb
  spec/policies/email_domain_block_policy_spec.rb
  spec/policies/instance_policy_spec.rb
  spec/policies/invite_policy_spec.rb
  spec/policies/relay_policy_spec.rb
  spec/policies/report_note_policy_spec.rb
  spec/policies/report_policy_spec.rb
  spec/policies/settings_policy_spec.rb
  spec/policies/tag_policy_spec.rb
  spec/policies/user_policy_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: ruby, lint fix 💅

#25550 Fix `RSpec/SubjectStub` cop
  .rubocop_todo.yml
  spec/services/unallow_domain_service_spec.rb
  spec/validators/blacklisted_email_validator_spec.rb
Labels: ruby, lint fix 💅

#25920 Fix `Lint/SendWithMixinArgument` cop
  .rubocop_todo.yml
  config/application.rb
Labels: ruby, lint fix 💅

#25921 Fix `Lint/AmbiguousBlockAssociation` cop
  .rubocop_todo.yml
  spec/controllers/settings/two_factor_authentication/confirmations_controller_spec.rb
  spec/controllers/settings/two_factor_authentication/otp_authentication_controller_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/post_status_service_spec.rb
Labels: ruby, lint fix 💅

#25923 Fix `Style/SlicingWithRange` cop
  .rubocop_todo.yml
  app/lib/emoji_formatter.rb
  app/lib/text_formatter.rb
  app/models/account_alias.rb
  app/models/domain_block.rb
  app/models/email_domain_block.rb
  app/models/preview_card_provider.rb
  app/validators/status_length_validator.rb
  db/migrate/20190726175042_add_case_insensitive_index_to_tags.rb
  lib/active_record/batches.rb
  lib/mastodon/premailer_webpack_strategy.rb
  lib/tasks/repo.rake
Labels: ruby, lint fix 💅

#25924 Fix `Naming/AccessorMethodName` cop
  .rubocop_todo.yml
  app/controllers/auth/sessions_controller.rb
  app/controllers/concerns/two_factor_authentication_concern.rb
Labels: ruby, lint fix 💅

#25928 Fix `Naming/MemoizedInstanceVariableName` cop
  .rubocop_todo.yml
  app/controllers/api/v1/bookmarks_controller.rb
  app/controllers/api/v1/favourites_controller.rb
  app/controllers/concerns/rate_limit_headers.rb
  app/lib/activitypub/activity.rb
  app/services/resolve_url_service.rb
  app/services/search_service.rb
  config/initializers/rack_attack.rb
Labels: ruby, lint fix 💅

#25552 Fix `RSpec/StubbedMock` cop
  .rubocop_todo.yml
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/api/v1/media_controller_spec.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/status_filter_spec.rb
  spec/lib/status_finder_spec.rb
  spec/lib/webfinger_resource_spec.rb
  spec/services/activitypub/process_collection_service_spec.rb
Labels: ruby, lint fix 💅

#25879 Refactor `Snowflake` to avoid brakeman sql injection warnings
  config/brakeman.ignore
  lib/mastodon/snowflake.rb
Labels: refactoring, ruby

#25929 Update `haml-lint`
  .haml-lint_todo.yml
  Gemfile.lock
Labels: dependencies, ruby

#25819 Update Stylelint
  app/javascript/styles/mailer.scss
  package.json
  yarn.lock
Labels: dependencies, javascript

#25881 Refactor `Trends::Query` to avoid brakeman sql injection warnings
  app/models/trends/query.rb
  config/brakeman.ignore
Labels: refactoring, ruby

#25874 Change notifications API to use a replica
  app/controllers/api/v1/notifications_controller.rb
  app/controllers/api/v1/timelines/home_controller.rb
  app/controllers/application_controller.rb
  app/helpers/database_helper.rb
  app/workers/feed_insert_worker.rb
  app/workers/merge_worker.rb
  app/workers/regeneration_worker.rb
  app/workers/unmerge_worker.rb
Labels: performance

#25668 Rails 7.0 update
  Gemfile
  Gemfile.lock
  app/lib/inline_renderer.rb
  app/lib/rss/channel.rb
  app/lib/rss/item.rb
  app/models/announcement.rb
  app/models/concerns/account_search.rb
  app/models/concerns/status_safe_reblog_insert.rb
  app/models/notification.rb
  app/serializers/initial_state_serializer.rb
  app/services/account_search_service.rb
  app/services/batched_remove_status_service.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/cookie_rotator.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_7_0.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: dependencies, ruby

#25627 Update rubocop to v1.54.1
  .rubocop_todo.yml
  Gemfile.lock
  app/helpers/domain_control_helper.rb
  app/lib/connection_pool/shared_connection_pool.rb
  app/lib/request_pool.rb
Labels: dependencies, ruby

#25902 Upgrade to Prettier 3
  app/javascript/mastodon/components/animated_number.tsx
  app/javascript/mastodon/components/counters.tsx
  app/javascript/mastodon/components/gifv.tsx
  app/javascript/mastodon/components/relative_timestamp.tsx
  app/javascript/mastodon/components/short_number.tsx
  app/javascript/mastodon/features/emoji/emoji_compressed.d.ts
  app/javascript/mastodon/polyfills/base_polyfills.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/modal.ts
  app/javascript/mastodon/scroll.ts
  app/javascript/mastodon/store/index.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/utils/hashtags.ts
  app/javascript/mastodon/utils/numbers.ts
  app/javascript/styles/fonts/roboto-mono.scss
  app/javascript/styles/fonts/roboto.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/components.scss
  package.json
  yarn.lock
Labels: dependencies

#25583 Convert Home timeline components to Typescript
  app/javascript/mastodon/features/home_timeline/components/column_settings.jsx
  app/javascript/mastodon/features/home_timeline/components/column_settings.tsx
  app/javascript/mastodon/features/home_timeline/components/explore_prompt.jsx
  app/javascript/mastodon/features/home_timeline/components/explore_prompt.tsx
  app/javascript/mastodon/features/home_timeline/containers/column_settings_container.js
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: typescript

#25904 Upgrade to `typescript-eslint` v6
  .eslintrc.js
  app/javascript/mastodon/blurhash.ts
  app/javascript/mastodon/components/autosuggest_hashtag.tsx
  app/javascript/mastodon/components/avatar.tsx
  app/javascript/mastodon/components/avatar_overlay.tsx
  app/javascript/mastodon/components/display_name.tsx
  app/javascript/mastodon/components/short_number.tsx
  app/javascript/mastodon/features/emoji/emoji_compressed.d.ts
  app/javascript/mastodon/features/emoji/emoji_mart_data_light.ts
  app/javascript/mastodon/features/home_timeline/components/column_settings.tsx
  app/javascript/mastodon/locales/global_locale.ts
  app/javascript/mastodon/locales/load_locale.ts
  app/javascript/mastodon/polyfills/base_polyfills.ts
  app/javascript/mastodon/polyfills/index.ts
  app/javascript/mastodon/polyfills/intl.ts
  app/javascript/mastodon/scroll.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
  app/javascript/mastodon/utils/filters.ts
  app/javascript/mastodon/utils/numbers.ts
  app/javascript/mastodon/uuid.ts
  package.json
  yarn.lock
Labels: dependencies, typescript

#25960 Remove some recently-updated packages from Renovabot ignore config
  .github/renovate.json5
Labels: dependencies

#26025 Fix ArgumentError in mailers when a user's timezone is blank
  app/views/notification_mailer/_status.html.haml
  app/views/user_mailer/appeal_approved.html.haml
  app/views/user_mailer/appeal_approved.text.erb
  app/views/user_mailer/appeal_rejected.html.haml
  app/views/user_mailer/appeal_rejected.text.erb
  app/views/user_mailer/suspicious_sign_in.html.haml
  app/views/user_mailer/suspicious_sign_in.text.erb
  app/views/user_mailer/warning.html.haml
Labels: bug

#25975 Fix haml lint Rubocop `Style/RedundantStringCoercion` cop
  .haml-lint_todo.yml
  app/views/settings/imports/show.html.haml
Labels: ruby, lint fix 💅

#25974 Fix haml-lint Rubocop `Style/MinMaxComparison` cop
  .haml-lint_todo.yml
  app/views/statuses/_poll.html.haml
Labels: ruby, lint fix 💅

#25635 Migrate to request specs in `/api/v1/statuses/:status_id/pin`
  spec/controllers/api/v1/statuses/pins_controller_spec.rb
  spec/requests/api/v1/statuses/pins_spec.rb
Labels: testing, ruby

#25624 Migrate to request specs in `/api/v1/statuses/:status_id/bookmark`
  spec/controllers/api/v1/statuses/bookmarks_controller_spec.rb
  spec/requests/api/v1/statuses/bookmarks_spec.rb
Labels: testing, ruby

#25626 Migrate to request specs in `/api/v1/statuses/:status_id/favourite`
  spec/controllers/api/v1/statuses/favourites_controller_spec.rb
  spec/requests/api/v1/statuses/favourites_spec.rb
Labels: testing, ruby

#25948 Fix haml-lint Rubocop `Style/StringLiterals` cop
  .haml-lint_todo.yml
  app/views/settings/imports/show.html.haml
Labels: ruby, lint fix 💅

#25947 Fix haml-lint Rubocop `Style/SlicingWithRange` cop
  .haml-lint_todo.yml
  app/views/accounts/_og.html.haml
  app/views/statuses/show.html.haml
Labels: ruby, rebase needed :construction:, lint fix 💅

#25746 Migrate to request specs in `/api/v1/timelines/public`
  spec/controllers/api/v1/timelines/public_controller_spec.rb
  spec/requests/api/v1/timelines/public_spec.rb
Labels: testing, ruby

#25520 Migrate to request specs in `/api/v1/bookmarks`
  spec/controllers/api/v1/bookmarks_controller_spec.rb
  spec/requests/api/v1/bookmarks_spec.rb
Labels: testing, ruby

#25622 Migrate to request specs in `/api/v1/mutes`
  spec/controllers/api/v1/mutes_controller_spec.rb
  spec/requests/api/v1/mutes_spec.rb
Labels: testing, ruby

#25869 Add a Github Action to send translations to Crowdin for each merge in main
  .github/workflows/crowdin-download.yml
  .github/workflows/crowdin-upload.yml
  crowdin.yml
Labels: i18n

#26057 Fix haml-lint rubocop style negation cops
  .haml-lint_todo.yml
  app/views/admin/reports/actions/preview.html.haml
  app/views/admin/reports/show.html.haml
Labels: ruby, lint fix 💅

#26059 Fix haml-lint Rubocop `Style/SymbolProc` cop
  .haml-lint_todo.yml
  app/views/admin/accounts/index.html.haml
Labels: ruby, lint fix 💅

#26061 Fix haml-lint `InstanceVariables` rule for auth/registrations/edit
  .haml-lint_todo.yml
  app/views/auth/registrations/_session.html.haml
  app/views/auth/registrations/_sessions.html.haml
  app/views/auth/registrations/edit.html.haml
Labels: ruby, rebase needed :construction:, lint fix 💅

#26055 Change request timeout handling to use a longer deadline
  app/lib/request.rb
Labels: to backport

#23607 Paperclip: add support for Azure blob storage
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  config/initializers/content_security_policy.rb
  config/initializers/paperclip.rb
Labels: deployment, ruby

#26040 Fix haml-lint Rubocop `Style/NumericPredicate` cop
  .haml-lint_todo.yml
  app/views/notification_mailer/_status.html.haml
  app/views/statuses/_poll.html.haml
Labels: ruby, lint fix 💅

#25889 Move localized subject mailer shared example to separate file
  spec/mailers/notification_mailer_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/support/examples/mailers.rb
Labels: refactoring, ruby

#25922 Fix `Lint/Void` cop
  .rubocop_todo.yml
  spec/services/resolve_account_service_spec.rb
Labels: ruby, lint fix 💅

#25276 Use username as display name for suspended users or users with blank display names
  app/serializers/activitypub/actor_serializer.rb
Labels: activitypub

#25850 Add check preventing Sidekiq workers from running with Makara configured
  config/initializers/sidekiq.rb
Labels: to backport

#26009 Replace 'favourite' by 'favorite' for American English
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/containers/status_container.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/compose/components/action_bar.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/favourited_statuses/index.jsx
  app/javascript/mastodon/features/favourites/index.jsx
  app/javascript/mastodon/features/getting_started/index.jsx
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/keyboard_shortcuts/index.jsx
  app/javascript/mastodon/features/notifications/components/column_settings.jsx
  app/javascript/mastodon/features/notifications/components/filter_bar.jsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/mastodon/features/status/containers/detailed_status_container.js
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
  app/javascript/mastodon/locales/en.json
  config/locales/doorkeeper.en.yml
Labels: i18n

#26125 Fix focus and hover styles in web UI
  app/javascript/mastodon/components/intersection_observer_article.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26126 Remove back button from bookmarks, favourites and lists screens in web UI
  app/javascript/mastodon/features/bookmarked_statuses/index.jsx
  app/javascript/mastodon/features/favourited_statuses/index.jsx
  app/javascript/mastodon/features/lists/index.jsx
Labels: ui

#26136 Change design of link previews in web UI
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/components.scss
  app/lib/link_details_extractor.rb
  app/serializers/rest/preview_card_serializer.rb
Labels: ui

#26152 Fix missing border on error screen in light theme in web UI
  app/javascript/styles/mastodon-light/diff.scss
Labels: ui

#26155 Add published date and author to news on the explore screen in web UI
  app/javascript/mastodon/features/explore/components/story.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26147 Coverage for `Auth::OmniauthCallbacks` controller
  .github/workflows/test-ruby.yml
  app/controllers/auth/omniauth_callbacks_controller.rb
  spec/requests/omniauth_callbacks_spec.rb
  spec/support/omniauth_mocks.rb
Labels: testing, ruby

#26183 Reformat large text arg in `FetchLinkCardService` spec
  spec/services/fetch_link_card_service_spec.rb
Labels: refactoring, ruby

#26182 Ignore long line in regex initializer
  config/initializers/twitter_regex.rb
Labels: refactoring, ruby

#26181 Reformat large key values in service specs
  spec/services/activitypub/fetch_remote_key_service_spec.rb
  spec/services/activitypub/process_collection_service_spec.rb
Labels: refactoring, ruby

#26180 Reformat large hash in `ContextHelper` module
  app/helpers/context_helper.rb
Labels: refactoring, ruby

#26178 Use heredoc SQL blocks in `AddFromAccountIdToNotifications` migration
  db/migrate/20161203164520_add_from_account_id_to_notifications.rb
Labels: refactoring, ruby

#26177 Extract private methods in `StatusCacheHydrator`
  app/lib/status_cache_hydrator.rb
Labels: refactoring, ruby

#26197 Use correct naming on controller concern specs
  .rubocop.yml
  spec/controllers/concerns/account_controller_concern_spec.rb
  spec/controllers/concerns/export_controller_concern_spec.rb
  spec/controllers/concerns/localized_spec.rb
  spec/controllers/concerns/rate_limit_headers_spec.rb
  spec/controllers/concerns/signature_verification_spec.rb
  spec/controllers/concerns/user_tracking_concern_spec.rb
Labels: testing, ruby

#25721 Migrate to request specs in `/api/v2/filters`
  .rubocop_todo.yml
  spec/controllers/api/v2/filters_controller_spec.rb
  spec/requests/api/v2/filters/filters_spec.rb
Labels: testing, ruby

#26159 Fix wrong filters sometimes applying in streaming
  streaming/index.js
Labels: bug, streaming, to backport

#25649 Add role badges to the WebUI
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/components.scss
  app/views/admin/custom_emojis/_custom_emoji.html.haml
  app/views/custom_css/show.css.erb
  app/views/oauth/authorized_applications/index.html.haml
Labels: ui

#26189 Fix crash when processing Flag activity with no status
  app/lib/activitypub/activity/flag.rb
  spec/lib/activitypub/activity/flag_spec.rb
Labels: bug, activitypub

#26173 Remove queued_at value from pubsub payloads
  app/workers/push_conversation_worker.rb
  app/workers/push_encrypted_message_worker.rb
  app/workers/push_update_worker.rb
Labels: streaming

#26228 Fix: Streaming server memory leak in HTTP EventSource cleanup
  streaming/index.js
Labels: streaming, to backport

#26231 Swap debug statements in streaming server
  streaming/index.js
Labels: build-image

#26233 Fix missing return values in streaming
  streaming/index.js
Labels: streaming, build-image

#25461 Add end-to-end (system) tests
  .github/workflows/test-ruby.yml
  Gemfile
  Gemfile.lock
  config/application.rb
  config/webpack/tests.js
  lib/tasks/spec.rake
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/stories/profile_stories.rb
  spec/system/new_statuses_spec.rb
Labels: testing

#26217 Rubocop fix: `Perfomance/UnfreezeString`
  .rubocop_todo.yml
  app/lib/rss/builder.rb
  app/lib/text_formatter.rb
  app/validators/status_length_validator.rb
  app/views/well_known/host_meta/show.xml.ruby
  lib/tasks/mastodon.rake
Labels: ruby, lint fix 💅

#26190 Update rubocop rules for linelength
  .rubocop.yml
  .rubocop_todo.yml
  config/initializers/twitter_regex.rb
Labels: ruby, lint fix 💅

#25593 Add coverage for `LanguageValidator`
  app/validators/language_validator.rb
  spec/validators/language_validator_spec.rb
Labels: testing, ruby

#25591 Add coverage for `URLValidator`
  app/validators/url_validator.rb
  spec/validators/url_validator_spec.rb
Labels: testing, ruby

#24735 Fix `RSpec/EmptyExampleGroup` cop
  .rubocop_todo.yml
  spec/helpers/admin/action_logs_helper_spec.rb
  spec/models/account_alias_spec.rb
  spec/models/account_deletion_request_spec.rb
  spec/models/account_moderation_note_spec.rb
  spec/models/announcement_mute_spec.rb
  spec/models/announcement_reaction_spec.rb
  spec/models/announcement_spec.rb
  spec/models/backup_spec.rb
  spec/models/conversation_mute_spec.rb
  spec/models/custom_filter_keyword_spec.rb
  spec/models/custom_filter_spec.rb
  spec/models/device_spec.rb
  spec/models/encrypted_message_spec.rb
  spec/models/featured_tag_spec.rb
  spec/models/follow_recommendation_suppression_spec.rb
  spec/models/list_account_spec.rb
  spec/models/list_spec.rb
  spec/models/login_activity_spec.rb
  spec/models/mute_spec.rb
  spec/models/preview_card_spec.rb
  spec/models/preview_card_trend_spec.rb
  spec/models/relay_spec.rb
  spec/models/scheduled_status_spec.rb
  spec/models/status_stat_spec.rb
  spec/models/status_trend_spec.rb
  spec/models/system_key_spec.rb
  spec/models/tag_follow_spec.rb
  spec/models/unavailable_domain_spec.rb
  spec/models/user_invite_request_spec.rb
  spec/models/web/setting_spec.rb
  spec/services/unmute_service_spec.rb
Labels: ruby, lint fix 💅

#26250 Change aspect ratios on link previews in web UI
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui
