Repository mastodon/mastodon, pull requests merged in 2023-06, with the labels that each got.

#23561 Add fix/lint helper dev targets
  .github/workflows/lint-css.yml
  .github/workflows/lint-js.yml
  .github/workflows/lint-json.yml
  .github/workflows/lint-md.yml
  .github/workflows/lint-yml.yml
  .github/workflows/test-js.yml
  package.json
Labels: javascript, lint fix 💅

#25134 Fix multiple N+1s in ConversationsController
  app/controllers/api/v1/conversations_controller.rb
  app/models/account_conversation.rb
Labels: performance, to backport

#25018 Fix crash when S3_ALIAS_HOST or S3_CLOUDFRONT_HOST have a path component
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: bug

#25144 Add a confirmation screen when suspending a domain
  app/controllers/admin/domain_blocks_controller.rb
  app/javascript/mastodon/components/admin/ImpactReport.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/admin.scss
  app/lib/admin/metrics/measure/instance_accounts_measure.rb
  app/lib/admin/metrics/measure/instance_followers_measure.rb
  app/lib/admin/metrics/measure/instance_follows_measure.rb
  app/lib/admin/metrics/measure/instance_media_attachments_measure.rb
  app/lib/admin/metrics/measure/instance_reports_measure.rb
  app/lib/admin/metrics/measure/instance_statuses_measure.rb
  app/views/admin/domain_blocks/confirm_suspension.html.haml
  config/locales/en.yml
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/features/admin/domain_blocks_spec.rb
  spec/lib/admin/metrics/measure/instance_accounts_measure_spec.rb
  spec/lib/admin/metrics/measure/instance_followers_measure_spec.rb
  spec/lib/admin/metrics/measure/instance_follows_measure_spec.rb
  spec/lib/admin/metrics/measure/instance_media_attachments_measure_spec.rb
  spec/lib/admin/metrics/measure/instance_reports_measure_spec.rb
  spec/lib/admin/metrics/measure/instance_statuses_measure_spec.rb
Labels: moderation

#25196 Add test coverage for `Mastodon::CLI::Accounts#refresh`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25131 Fix overflow behavior of account rows
  app/javascript/mastodon/components/account.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24954 Change "Follow 7 people" to "Find at least 7 people to follow" in web UI
  app/javascript/mastodon/features/onboarding/index.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#25199 Add test coverage for `Mastodon::CLI::Accounts#merge`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25239 Add coverage for CLI::CanonicalEmailBlocks command
  spec/lib/mastodon/cli/canonical_email_blocks_spec.rb
Labels: testing, ruby

#25272 Fix design issues with recent react-intl upgrade
  app/javascript/mastodon/locales/intl_provider.tsx
Labels: bug, ui

#25273 Fix CSP headers when S3_ALIAS_HOST includes a path component
  config/initializers/content_security_policy.rb
Labels: bug, to backport

#24956 Change follow button in account row to be more obvious in web UI
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#23289 Add webhook templating
  app/controllers/admin/webhooks_controller.rb
  app/lib/webhooks/payload_renderer.rb
  app/models/webhook.rb
  app/views/admin/webhooks/_form.html.haml
  app/views/admin/webhooks/show.html.haml
  app/workers/webhooks/delivery_worker.rb
  config/locales/simple_form.en.yml
  db/migrate/20230129023109_add_template_to_webhooks.rb
  db/schema.rb
  spec/lib/webhooks/payload_renderer_spec.rb
Labels: moderation

#25275 Fix autocomplete suggestions being cut off in compose form
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#25259 Rewrite `<LoadMore />` as FC and TS
  app/javascript/mastodon/components/load_more.jsx
  app/javascript/mastodon/components/load_more.tsx
  app/javascript/mastodon/components/scrollable_list.jsx
  app/javascript/mastodon/features/account_gallery/index.jsx
  app/javascript/mastodon/features/compose/components/search_results.jsx
  app/javascript/mastodon/features/directory/index.jsx
  app/javascript/mastodon/features/explore/results.jsx
Labels: typescript

#25283 Add coverage for `DomainBlock#public_domain` method
  spec/models/domain_block_spec.rb
Labels: testing, ruby

#25194 Add test coverage for `Mastodon::CLI::Accounts#reset_relationships`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25282 Misc spec coverage for `Admin::` area controllers
  spec/controllers/admin/account_actions_controller_spec.rb
  spec/controllers/admin/accounts_controller_spec.rb
  spec/controllers/admin/announcements_controller_spec.rb
  spec/controllers/admin/relays_controller_spec.rb
  spec/controllers/admin/statuses_controller_spec.rb
  spec/controllers/admin/warning_presets_controller_spec.rb
Labels: testing, ruby

#23690 Autofix Rubocop Regex Style rules
  .rubocop_todo.yml
  app/lib/link_details_extractor.rb
  app/lib/plain_text_formatter.rb
  app/lib/tag_manager.rb
  app/lib/text_formatter.rb
  app/lib/webfinger_resource.rb
  app/models/account.rb
  app/models/domain_allow.rb
  app/models/domain_block.rb
  app/models/site_upload.rb
  app/models/tag.rb
  app/services/backup_service.rb
  app/services/fetch_link_card_service.rb
  app/services/fetch_oembed_service.rb
  app/services/search_service.rb
  config/initializers/rack_attack.rb
  config/initializers/twitter_regex.rb
  config/routes.rb
  lib/mastodon/premailer_webpack_strategy.rb
  lib/paperclip/color_extractor.rb
  lib/tasks/emojis.rake
  lib/tasks/mastodon.rake
Labels: ruby, lint fix 💅

#25107 Change design of dropdowns in web UI
  app/javascript/mastodon/components/dropdown_menu.jsx
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#23941 Add `legal` as report category
  app/javascript/mastodon/features/report/category.jsx
  app/javascript/mastodon/locales/en.json
  app/models/report.rb
Labels: api, ui, moderation

#25337 Migrate to request specs in `/api/v1/admin/email_domain_blocks`
  spec/requests/api/v1/admin/email_domain_blocks_spec.rb
Labels: testing, ruby

#25278 Fix performance of streaming by parsing message JSON once
  streaming/index.js
Labels: streaming

#25355 Migrate to request specs in `/api/v1/admin/reports`
  spec/controllers/api/v1/admin/reports_controller_spec.rb
  spec/requests/api/v1/admin/reports_spec.rb
Labels: testing, ruby

#25335 Migrate to request specs in `/api/v1/admin/domain_blocks`
  spec/controllers/api/v1/admin/domain_blocks_controller_spec.rb
  spec/requests/api/v1/admin/domain_blocks_spec.rb
Labels: testing, ruby

#25333 Migrate to request specs in `/api/v1/admin/domain_allows`
  spec/controllers/api/v1/admin/domain_allows_controller_spec.rb
  spec/fabricators/domain_allow_fabricator.rb
  spec/requests/api/v1/admin/domain_allows_spec.rb
Labels: testing, ruby

#25331 Migrate to request specs in `/api/v1/admin/ip_blocks`
  spec/controllers/api/v1/admin/ip_blocks_controller_spec.rb
  spec/requests/api/v1/admin/ip_blocks_spec.rb
Labels: testing, ruby

#25330 Migrate to request specs in `/api/v1/admin/canonical_email_blocks`
  spec/controllers/api/v1/admin/canonical_email_blocks_controller_spec.rb
  spec/requests/api/v1/admin/canonical_email_blocks_spec.rb
Labels: testing, ruby

#25322 migrate test for `GET /api/v1/accounts/{account_id}` to request spec
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/requests/api/v1/accounts_show_spec.rb
Labels: testing, ruby

#25280 Add logging of websocket send errors
  streaming/index.js
Labels: streaming

#25238 Add coverage for `CLI::Cache` command
  lib/mastodon/cli/cache.rb
  spec/fabricators/status_stat_fabricator.rb
  spec/lib/mastodon/cli/cache_spec.rb
  spec/rails_helper.rb
Labels: testing, ruby

#25313 Reduce `RSpec/MultipleExpectations` cop max to 8
  .rubocop_todo.yml
  spec/controllers/api/v1/accounts/relationships_controller_spec.rb
  spec/controllers/settings/two_factor_authentication/confirmations_controller_spec.rb
  spec/models/form/import_spec.rb
  spec/models/notification_spec.rb
  spec/services/translate_status_service_spec.rb
Labels: ruby, lint fix 💅

#25356 Change "bot" label to "automated"
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/locales/en.json
  config/locales/simple_form.en.yml
Labels: ui

#25376 Update Rubocop 1.52.1
  .rubocop_todo.yml
  Gemfile.lock
Labels: ruby, lint fix 💅

#25364 Rewrite `<LoadingIndicator/>` as FC and TS
  app/javascript/mastodon/components/circular_progress.tsx
  app/javascript/mastodon/components/dropdown_menu.jsx
  app/javascript/mastodon/components/loading_indicator.jsx
  app/javascript/mastodon/components/loading_indicator.tsx
  app/javascript/mastodon/components/scrollable_list.jsx
  app/javascript/mastodon/features/account_gallery/index.jsx
  app/javascript/mastodon/features/account_timeline/index.jsx
  app/javascript/mastodon/features/blocks/index.jsx
  app/javascript/mastodon/features/directory/index.jsx
  app/javascript/mastodon/features/domain_blocks/index.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/features/explore/suggestions.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/favourites/index.jsx
  app/javascript/mastodon/features/followers/index.jsx
  app/javascript/mastodon/features/following/index.jsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/lists/index.jsx
  app/javascript/mastodon/features/mutes/index.jsx
  app/javascript/mastodon/features/reblogs/index.jsx
  app/javascript/mastodon/features/report/statuses.jsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/components/modal_loading.jsx
Labels: typescript

#25138 Rewrite `emoji_mart_data_light` as TS
  app/javascript/mastodon/features/emoji/emoji_compressed.d.ts
  app/javascript/mastodon/features/emoji/emoji_compressed.js
  app/javascript/mastodon/features/emoji/emoji_mart_data_light.js
  app/javascript/mastodon/features/emoji/emoji_mart_data_light.ts
Labels: typescript

#25395 Fix CAPTCHA page not following design pattern of sign-up flow
  app/controllers/concerns/captcha_concern.rb
  app/javascript/styles/mastodon/forms.scss
  app/views/auth/confirmations/captcha.html.haml
  config/locales/en.yml
Labels: ui

#25399 Fix ArgumentError when loading newer Private Mentions
  app/controllers/api/v1/conversations_controller.rb
  app/models/account_conversation.rb
  spec/controllers/api/v1/conversations_controller_spec.rb
Labels: bug, to backport

#25396 Fix always redirecting to onboarding in web UI
  app/controllers/auth/confirmations_controller.rb
  app/javascript/mastodon/features/ui/index.jsx
Labels: ui

#25387 Extract shared examples from api specs
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/api/v1/admin/account_actions_controller_spec.rb
  spec/controllers/api/v1/admin/accounts_controller_spec.rb
  spec/controllers/api/v1/admin/trends/links/preview_card_providers_controller_spec.rb
  spec/controllers/api/v1/admin/trends/links_controller_spec.rb
  spec/controllers/api/v1/admin/trends/statuses_controller_spec.rb
  spec/controllers/api/v1/admin/trends/tags_controller_spec.rb
  spec/controllers/api/v1/domain_blocks_controller_spec.rb
  spec/controllers/api/v2/admin/accounts_controller_spec.rb
  spec/requests/api/v1/admin/canonical_email_blocks_spec.rb
  spec/requests/api/v1/admin/domain_allows_spec.rb
  spec/requests/api/v1/admin/domain_blocks_spec.rb
  spec/requests/api/v1/admin/email_domain_blocks_spec.rb
  spec/requests/api/v1/admin/ip_blocks_spec.rb
  spec/requests/api/v1/admin/reports_spec.rb
  spec/requests/api/v1/featured_tags_spec.rb
  spec/support/examples/api.rb
Labels: testing, ruby

#25401 Migrate to request specs in `/api/v1/apps`
  spec/requests/api/v1/apps_spec.rb
Labels: testing, ruby

#25406 Speed improvement for `AccountsStatusesCleanupScheduler` spec
  .rubocop_todo.yml
  spec/workers/scheduler/accounts_statuses_cleanup_scheduler_spec.rb
Labels: testing, ruby

#25410 Reduce factory data created in spec/models/trends/statuses spec
  spec/models/trends/statuses_spec.rb
Labels: testing, ruby

#25411 Migrate to request specs in `/api/v1/follow_requests`
  spec/controllers/api/v1/follow_requests_controller_spec.rb
  spec/requests/api/v1/follow_requests_spec.rb
Labels: testing, ruby

#24698 Update rubocop-rspec to version 2.22.0, fix `RSpec/IndexedLet` cop
  .rubocop_todo.yml
  Gemfile.lock
  spec/controllers/activitypub/followers_synchronizations_controller_spec.rb
  spec/controllers/admin/instances_controller_spec.rb
  spec/controllers/follower_accounts_controller_spec.rb
  spec/controllers/following_accounts_controller_spec.rb
  spec/lib/account_reach_finder_spec.rb
  spec/lib/feed_manager_spec.rb
  spec/lib/mastodon/cli/ip_blocks_spec.rb
  spec/models/account_statuses_cleanup_policy_spec.rb
  spec/models/concerns/account_interactions_spec.rb
  spec/models/concerns/status_threading_concern_spec.rb
  spec/models/custom_emoji_filter_spec.rb
  spec/models/status_spec.rb
  spec/models/tag_feed_spec.rb
  spec/models/trends/statuses_spec.rb
  spec/models/trends/tags_spec.rb
  spec/serializers/activitypub/note_serializer_spec.rb
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
  spec/services/batched_remove_status_service_spec.rb
  spec/services/block_domain_service_spec.rb
  spec/services/clear_domain_media_service_spec.rb
  spec/services/purge_domain_service_spec.rb
  spec/services/unallow_domain_service_spec.rb
  spec/workers/scheduler/accounts_statuses_cleanup_scheduler_spec.rb
Labels: ruby, lint fix 💅

#25443 Migrate to request specs in `/api/v1/lists`
  spec/controllers/api/v1/lists_controller_spec.rb
  spec/requests/api/v1/lists_spec.rb
Labels: testing, ruby

#25498 Fix cross-origin loading of locales
  app/views/layouts/application.html.haml
  app/views/layouts/embedded.html.haml
Labels: bug

#25439 Migrate to request specs in `/api/v1/tags`
  .rubocop_todo.yml
  spec/controllers/api/v1/tags_controller_spec.rb
  spec/requests/api/v1/tags_spec.rb
Labels: testing, ruby

#25477 Fix incorrect pagination headers in `/api/v2/admin/accounts`
  app/controllers/api/v2/admin/accounts_controller.rb
  spec/controllers/api/v2/admin/accounts_controller_spec.rb
Labels: to backport

#25486 Combine assertions in api/v1/notifications spec
  spec/controllers/api/v1/notifications_controller_spec.rb
Labels: testing, ruby

#25470 Reduce `sleep` time in request pool spec
  app/lib/request_pool.rb
  spec/lib/request_pool_spec.rb
Labels: testing, ruby

#25481 Rewrite `<AutosuggestHashtag />` as FC and TS
  app/javascript/mastodon/components/autosuggest_hashtag.jsx
  app/javascript/mastodon/components/autosuggest_hashtag.tsx
  app/javascript/mastodon/components/autosuggest_input.jsx
  app/javascript/mastodon/components/autosuggest_textarea.jsx
Labels: typescript

#25519 Prevent UserCleanupScheduler from overwhelming streaming
  app/services/remove_status_service.rb
  app/workers/scheduler/user_cleanup_scheduler.rb
Labels: to backport

#25464 Fix wrong view being displayed when a webhook fails validation
  app/controllers/admin/webhooks_controller.rb
  spec/controllers/admin/webhooks_controller_spec.rb
Labels: to backport

#25514 Migrate to request specs in `/api/v1/admin/account_actions`
  spec/controllers/api/v1/admin/account_actions_controller_spec.rb
  spec/requests/api/v1/admin/account_actions_spec.rb
Labels: testing, ruby

#25499 Fix /api/v1/conversations sometimes returning empty accounts
  app/models/account_conversation.rb
  spec/controllers/api/v1/conversations_controller_spec.rb
Labels: bug, to backport

#24841 Add per-test timeouts to AutoStatusesCleanupScheduler tests
  spec/workers/scheduler/accounts_statuses_cleanup_scheduler_spec.rb
Labels: testing, ruby

#25540 Migrate to request specs in `/api/v1/suggestions`
  spec/controllers/api/v1/suggestions_controller_spec.rb
  spec/requests/api/v1/suggestions_spec.rb
Labels: testing, ruby

#25527 Speed-up on `BackupService` spec
  spec/services/backup_service_spec.rb
Labels: testing, ruby

#25463 Add finer permission requirements for managing webhooks
  app/controllers/admin/webhooks_controller.rb
  app/models/webhook.rb
  app/policies/webhook_policy.rb
  app/views/admin/webhooks/_form.html.haml
  config/locales/activerecord.en.yml
  spec/controllers/admin/webhooks_controller_spec.rb
  spec/policies/webhook_policy_spec.rb
Labels: to backport

#25465 Reduce `Admin::Reports::Actions` spec db activity
  spec/controllers/admin/reports/actions_controller_spec.rb
Labels: testing, ruby

#25469 Fix `RSpec/VerifiedDoubles` cop
  .rubocop_todo.yml
  spec/controllers/admin/change_emails_controller_spec.rb
  spec/controllers/admin/confirmations_controller_spec.rb
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/admin/domain_allows_controller_spec.rb
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/controllers/api/v1/reports_controller_spec.rb
  spec/controllers/api/web/embeds_controller_spec.rb
  spec/controllers/auth/sessions_controller_spec.rb
  spec/controllers/authorize_interactions_controller_spec.rb
  spec/controllers/disputes/appeals_controller_spec.rb
  spec/helpers/statuses_helper_spec.rb
  spec/lib/activitypub/activity/add_spec.rb
  spec/lib/activitypub/activity/move_spec.rb
  spec/lib/request_spec.rb
  spec/lib/suspicious_sign_in_detector_spec.rb
  spec/models/account/field_spec.rb
  spec/models/account_migration_spec.rb
  spec/models/session_activation_spec.rb
  spec/models/setting_spec.rb
  spec/services/account_search_service_spec.rb
  spec/services/bootstrap_timeline_service_spec.rb
  spec/services/bulk_import_service_spec.rb
  spec/services/fetch_resource_service_spec.rb
  spec/services/import_service_spec.rb
  spec/services/post_status_service_spec.rb
  spec/services/resolve_url_service_spec.rb
  spec/services/search_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/validators/blacklisted_email_validator_spec.rb
  spec/validators/disallowed_hashtags_validator_spec.rb
  spec/validators/email_mx_validator_spec.rb
  spec/validators/follow_limit_validator_spec.rb
  spec/validators/note_length_validator_spec.rb
  spec/validators/poll_validator_spec.rb
  spec/validators/status_length_validator_spec.rb
  spec/validators/status_pin_validator_spec.rb
  spec/validators/unique_username_validator_spec.rb
  spec/validators/unreserved_username_validator_spec.rb
  spec/validators/url_validator_spec.rb
  spec/views/statuses/show.html.haml_spec.rb
  spec/workers/activitypub/processing_worker_spec.rb
  spec/workers/admin/domain_purge_worker_spec.rb
  spec/workers/domain_block_worker_spec.rb
  spec/workers/domain_clear_media_worker_spec.rb
  spec/workers/feed_insert_worker_spec.rb
  spec/workers/move_worker_spec.rb
  spec/workers/publish_scheduled_announcement_worker_spec.rb
  spec/workers/refollow_worker_spec.rb
  spec/workers/regeneration_worker_spec.rb
Labels: testing, ruby

#25510 Change /api/v1/statuses/:id/history to always return at least one item
  app/controllers/api/v1/statuses/histories_controller.rb
  spec/controllers/api/v1/statuses/histories_controller_spec.rb
Labels: api

#25509 Add POST /api/v1/conversations/:id/unread
  app/controllers/api/v1/conversations_controller.rb
  config/routes/api.rb
Labels: api

#25267 Add onboarding prompt when home feed too slow in web UI
  app/javascript/images/friends-cropped.png
  app/javascript/mastodon/features/community_timeline/index.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/home_timeline/components/explore_prompt.jsx
  app/javascript/mastodon/features/home_timeline/index.jsx
  app/javascript/mastodon/features/public_timeline/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
Labels: ui, new user experience

#25556 Remove unique accounts condition from Home onboarding prompt
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: ui, new user experience

#25559 Change labels and styles on the onboarding screen in web UI
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/features/onboarding/components/step.jsx
  app/javascript/mastodon/features/onboarding/follows.jsx
  app/javascript/mastodon/features/onboarding/index.jsx
  app/javascript/mastodon/features/onboarding/share.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#25576 Fix search not being easily findable on smaller screens in web UI
  app/javascript/mastodon/features/ui/components/header.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#25579 Fix onboarding prompt flashing while home feed is loading in web UI
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: bug

#25577 Change header backgrounds to use fewer different colors in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#23302 Change files to be deleted in batches instead of one-by-one
  app/lib/attachment_batch.rb
  app/lib/vacuum/media_attachments_vacuum.rb
  app/services/clear_domain_media_service.rb
Labels: performance

#25603 Fix suspending an already-limited domain
  app/views/admin/domain_blocks/confirm_suspension.html.haml
  spec/features/admin/domain_blocks_spec.rb
Labels: bug, moderation

#25631 Remove the search button from UI header when logged out
  app/javascript/mastodon/features/ui/components/header.jsx
Labels: ui

#25615 Remove `pkg-config` gem dependency
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#25617 Fix onboarding prompt being displayed because of disconnection gaps
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: bug, ui

#25584 Use an Immutable Record as the root state
  app/javascript/mastodon/reducers/index.ts
Labels: typescript
