Repository mastodon/mastodon, pull requests merged in 2023-08, with the labels that each got.

#26267 Change interaction modal input to disable browser spell-checking, capitalization and autocomplete
  app/javascript/mastodon/features/interaction_modal/index.jsx
Labels: ui

#26287 Fix wrong border radius on link cards in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug

#26281 Change design of role badges in web UI
  app/javascript/mastodon/components/badge.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/styles/mastodon/accounts.scss
  config/webpack/rules/index.js
  config/webpack/rules/material_icons.js
  package.json
  yarn.lock
Labels: ui

#26210 Fix crash in `tootctl status remove` and some old migrations
  db/migrate/20180812173710_copy_status_stats.rb
  db/migrate/20181116173541_copy_account_stats.rb
  lib/mastodon/cli/statuses.rb
Labels: bug

#26300 Add client-side timeout on resend confirmation button
  app/javascript/packs/sign_up.js
  app/views/auth/setup/show.html.haml
Labels: ui

#24443 Add `GET /api/v1/instance/languages` to REST API
  app/controllers/api/v1/instances/languages_controller.rb
  app/presenters/language_presenter.rb
  app/serializers/rest/language_serializer.rb
  config/routes/api.rb
  spec/requests/api/v1/instances/languages_spec.rb
Labels: api

#26302 Change reblogs to be excluded from "Posts and replies" tab in web UI
  app/javascript/mastodon/actions/timelines.js
Labels: ui

#26330 Change design of hidden media overlay (again) in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26342 Fix confirmation when closing media edition modal with unsaved changes
  app/javascript/mastodon/features/ui/components/focal_point_modal.jsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
Labels: bug, ui

#26343 Fix missing cached preview cards attributes
  app/models/status.rb
Labels: bug

#26341 Fix report modal secondary buttons style
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26362 Change header of hashtag timelines in web UI
  app/javascript/mastodon/features/hashtag_timeline/components/hashtag_header.jsx
  app/javascript/mastodon/features/hashtag_timeline/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24751 Make mastodon-streaming systemd unit templated
  dist/mastodon-streaming.service
  dist/mastodon-streaming@.service
  dist/nginx.conf
Labels: deployment, streaming

#25416 Spec media attachment speedups
  spec/fixtures/files/attachment.gif
  spec/fixtures/files/attachment.webm
  spec/models/media_attachment_spec.rb
Labels: testing, ruby, rebase needed :construction:

#26368 Fix interaction modal layout
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
Labels: ui

#24209 Omniauth 2.0 version bump
  .bundler-audit.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#26378 Change account search tokenizer and queries
  app/chewy/accounts_index.rb
  app/services/account_search_service.rb
Labels: area/search

#26339 Prepare v4.2.0-beta1
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: build-image

#26392 Fix blocking subdomains of an already-blocked domain
  app/controllers/admin/domain_blocks_controller.rb
  spec/features/admin/domain_blocks_spec.rb
Labels: bug, to backport

#26435 Add `S3_DISABLE_CHECKSUM_MODE` environment variable for compatibility with some S3-compatible providers
  config/initializers/paperclip.rb
Labels: build-image

#26442 Upgrade JS dev dependencies
  yarn.lock
Labels: dependencies, javascript

#26452 Fix reply not preserving the language from the replied-to post
  app/javascript/mastodon/actions/importer/normalizer.js
Labels: bug

#26457 Upgrade `@types/react`
  yarn.lock
Labels: dependencies, javascript

#26482 Fix unfollow icon styling in advanced column
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26409 Fix cached posts including stale stats
  app/models/status.rb
  spec/controllers/concerns/cache_concern_spec.rb
Labels: build-image

#25124 Add ability to delete avatar or header picture via the API
  app/controllers/api/v1/profiles_controller.rb
  config/routes/api.rb
  spec/requests/api/v1/profiles_spec.rb
Labels: api

#26510 Add auto-refresh of accounts we get new messages/edits of
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/update.rb
  app/models/account.rb
  app/workers/account_refresh_worker.rb
Labels: build-image

#26448 Add Elasticsearch cluster health check and indexes mismatch check to dashboard
  app/chewy/instances_index.rb
  app/lib/admin/system_check/elasticsearch_check.rb
  config/locales/en.yml
  spec/lib/admin/system_check/elasticsearch_check_spec.rb
Labels: area/search

#26579 Bump version to v4.2.0-beta2
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: build-image

#26593 Fix layout of the closed registrations modal
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#26329 Update rubocop and rubocop-rspec
  .rubocop_todo.yml
  Gemfile.lock
  app/lib/importer/base_importer.rb
  lib/redis/namespace_extensions.rb
  spec/controllers/api/v1/instances/translation_languages_controller_spec.rb
  spec/controllers/api/v1/statuses/translations_controller_spec.rb
  spec/helpers/admin/filter_helper_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/home_helper_spec.rb
  spec/lib/admin/system_check/elasticsearch_check_spec.rb
  spec/models/report_filter_spec.rb
  spec/services/suspend_account_service_spec.rb
  spec/services/translate_status_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/views/statuses/show.html.haml_spec.rb
Labels: dependencies, ruby

#26012 Add cherokee to languages dropdown
  app/helpers/languages_helper.rb
Labels: i18n

#26605 Fix admin dashboard check when using Elasticsearch with `ES_PREFIX`
  app/lib/admin/system_check/elasticsearch_check.rb
Labels: bug, build-image

#26583 Add support for federating `memorial` attribute
  app/helpers/context_helper.rb
  app/serializers/activitypub/actor_serializer.rb
  app/services/activitypub/process_account_service.rb
Labels: activitypub

#26608 Fix unexpected audio stream transcoding when uploaded video is eligible to passthrough
  lib/paperclip/transcoder.rb
Labels: to backport, area/media processing

#26636 Fix selecting domains to forward reports to not passing the information correctly
  app/javascript/mastodon/features/ui/components/report_modal.jsx
Labels: bug

#26596 Change admin e-mail notification settins to be their own settings group
  app/views/settings/preferences/notifications/show.html.haml
  config/locales/en.yml
Labels: ui

#26344 Add new public status index
  app/chewy/accounts_index.rb
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
  app/controllers/api/v1/accounts/credentials_controller.rb
  app/controllers/settings/privacy_controller.rb
  app/lib/importer/public_statuses_index_importer.rb
  app/lib/search_query_transformer.rb
  app/lib/vacuum/statuses_vacuum.rb
  app/models/account.rb
  app/models/concerns/account_statuses_search.rb
  app/models/concerns/status_search_concern.rb
  app/models/status.rb
  app/serializers/activitypub/actor_serializer.rb
  app/services/batched_remove_status_service.rb
  app/services/search_service.rb
  app/services/statuses_search_service.rb
  app/views/settings/privacy/show.html.haml
  app/workers/add_to_public_statuses_index_worker.rb
  app/workers/remove_from_public_statuses_index_worker.rb
  app/workers/scheduler/indexing_scheduler.rb
  config/locales/simple_form.en.yml
  lib/mastodon/cli/search.rb
  spec/chewy/public_statuses_index_spec.rb
  spec/lib/importer/public_statuses_index_importer_spec.rb
  spec/lib/search_query_transformer_spec.rb
  spec/models/concerns/account_statuses_search_spec.rb
  spec/workers/add_to_public_statuses_index_worker_spec.rb
  spec/workers/remove_from_public_statuses_index_worker_spec.rb
Labels: area/search

#26657 Fix statuses search Elasticsearch query
  app/services/statuses_search_service.rb
Labels: bug, build-image

#26659 Update ordering to use `id` from body of document instead of deprecated `_id`
  app/services/statuses_search_service.rb
Labels: area/search

#26658 Fix dashboard check for Elasticsearch suggested command including incorrect names
  app/lib/admin/system_check/elasticsearch_check.rb
Labels: bug

#26664 Fix toast saying "published" instead of "saved" after editing post in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/locales/en.json
Labels: ui

#26661 Change `before:`, `after:` and `during:` to use the user's timezone in search
  app/lib/search_query_transformer.rb
Labels: area/search

#26676 Fix nightly build version
  .github/workflows/build-container-image.yml
Labels: bug, github_actions

#26688 Change queue of job when opting into search from `default` to `pull`
  app/workers/add_to_public_statuses_index_worker.rb
Labels: area/search

#26689 Fix unnecessary condition causing seqscan when indexing
  app/models/concerns/account_statuses_search.rb
Labels: bug, area/search

#26692 Change indexing jobs to use database replica
  app/workers/add_to_public_statuses_index_worker.rb
  app/workers/scheduler/indexing_scheduler.rb
Labels: performance, area/search

#26686 Fix multiple issues with status index mappings
  app/chewy/accounts_index.rb
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
Labels: area/search

#26660 Add `from:me` syntax to search
  app/lib/search_query_transformer.rb
  app/services/statuses_search_service.rb
Labels: area/search

#26662 Add search options to search popout in web UI
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui, area/search

#26697 Fix incorrect call to `PublicStatusesIndex.import`
  app/models/concerns/account_statuses_search.rb
Labels: bug, performance, area/search

#26673 Fix bad search type heuristic
  app/services/search_service.rb
  spec/services/search_service_spec.rb
Labels: bug, area/search

#26631 Change video compression parameters
  app/models/media_attachment.rb
  lib/paperclip/transcoder.rb
Labels: area/media processing

#26710 Fix N+1 in `tootctl search deploy`
  app/lib/importer/public_statuses_index_importer.rb
  app/lib/importer/statuses_index_importer.rb
Labels: performance, build-image

#26574 Fix bug with reblogged view on Toots only showing latest reblogging accounts
  app/javascript/mastodon/actions/interactions.js
  app/javascript/mastodon/features/reblogs/index.jsx
  app/javascript/mastodon/reducers/user_lists.js
Labels: rebase needed :construction:

#26713 Change private statuses index to index without crutches
  app/chewy/statuses_index.rb
  app/lib/importer/statuses_index_importer.rb
  app/models/concerns/status_search_concern.rb
  app/models/poll.rb
  app/models/status.rb
Labels: area/search

#26663 Change `language:` to attempt to match to a known value in search
  app/lib/search_query_transformer.rb
Labels: area/search

#26727 Change text extraction in `PlainTextFormatter` to be faster
  app/lib/plain_text_formatter.rb
Labels: performance, to backport, build-image

#26019 Add an explanation banner on switching to single column mode
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/locales/fr.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26739 Fix searching by username by reverting account verbatim tokenizer to `standard`
  app/chewy/accounts_index.rb
Labels: area/search

#26745 Fix videos not playing in some browsers due to unsupported color space
  app/models/media_attachment.rb
Labels: area/media processing

#26721 Change importers to avoid a few inefficiencies
  app/lib/importer/accounts_index_importer.rb
  app/lib/importer/base_importer.rb
  app/lib/importer/instances_index_importer.rb
  app/lib/importer/public_statuses_index_importer.rb
  app/lib/importer/statuses_index_importer.rb
  app/lib/importer/tags_index_importer.rb
Labels: performance, build-image, area/search

#26699 Fix search queries with slash causing or-condition
  app/lib/search_query_transformer.rb
Labels: bug, area/search

#26738 Backport container build changes to the stable-4.1 branch
  .github/workflows/build-container-image.yml
  .github/workflows/build-image.yml
  .github/workflows/build-releases.yml
Labels: github_actions, backport

#26741 Backport container build changes to the stable-4.0 branch
  .github/workflows/build-container-image.yml
  .github/workflows/build-image.yml
  .github/workflows/build-releases.yml
Labels: github_actions, backport

#26742 Backport container build changes to the stable-3.5 branch
  .github/workflows/build-container-image.yml
  .github/workflows/build-image.yml
  .github/workflows/build-releases.yml
Labels: github_actions, backport
