Repository mastodon/mastodon, pull requests merged in 2023-05, with the labels that each got.

#24761 Fix transaction around settings migration
  db/migrate/20230215074423_move_user_settings.rb
Labels: bug

#24783 Fix n+1 query in settings migration
  db/migrate/20230215074423_move_user_settings.rb
Labels: performance

#21054 Rewrite import feature
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/settings/imports_controller.rb
  app/lib/vacuum/imports_vacuum.rb
  app/models/bulk_import.rb
  app/models/bulk_import_row.rb
  app/models/concerns/account_associations.rb
  app/models/form/import.rb
  app/models/import.rb
  app/services/bulk_import_row_service.rb
  app/services/bulk_import_service.rb
  app/services/import_service.rb
  app/validators/import_validator.rb
  app/views/settings/imports/index.html.haml
  app/views/settings/imports/show.html.haml
  app/workers/bulk_import_worker.rb
  app/workers/import/relationship_worker.rb
  app/workers/import/row_worker.rb
  app/workers/import_worker.rb
  app/workers/scheduler/vacuum_scheduler.rb
  config/i18n-tasks.yml
  config/locales/en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20230330135507_create_bulk_imports.rb
  db/migrate/20230330140036_create_bulk_import_rows.rb
  db/schema.rb
  spec/controllers/settings/imports_controller_spec.rb
  spec/fabricators/bulk_import_fabricator.rb
  spec/fabricators/bulk_import_row_fabricator.rb
  spec/fixtures/files/empty.csv
  spec/fixtures/files/following_accounts.csv
  spec/fixtures/files/muted_accounts.csv
  spec/lib/vacuum/imports_vacuum_spec.rb
  spec/models/form/import_spec.rb
  spec/models/import_spec.rb
  spec/services/bulk_import_row_service_spec.rb
  spec/services/bulk_import_service_spec.rb
  spec/workers/bulk_import_worker_spec.rb
  spec/workers/import/row_worker_spec.rb
Labels: bug

#19727 Change lists to be able to include accounts with pending follow requests
  app/models/concerns/account_interactions.rb
  app/models/follow_request.rb
  app/models/list_account.rb
  db/migrate/20230330155710_add_follow_request_id_to_list_accounts.rb
  db/schema.rb
  spec/controllers/api/v1/lists/accounts_controller_spec.rb
  spec/models/concerns/account_interactions_spec.rb
  spec/models/follow_request_spec.rb
Labels: bug

#24782 Add ALT badges to media that has alternative text in web UI
  app/javascript/mastodon/components/media_gallery.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24787 Add type annotation for some js files
  app/javascript/mastodon/blurhash.ts
  app/javascript/mastodon/compare_id.ts
  app/javascript/mastodon/is_mobile.ts
  app/javascript/mastodon/permissions.ts
  app/javascript/mastodon/scroll.ts
  app/javascript/mastodon/utils/base64.ts
  app/javascript/mastodon/utils/filters.ts
  app/javascript/mastodon/utils/hashtags.ts
  app/javascript/mastodon/utils/numbers.ts
  app/javascript/types/resources.ts
  app/javascript/types/util.ts
Labels: typescript

#24807 Remove MastodonMap TS type
  app/javascript/types/resources.ts
  app/javascript/types/util.ts
Labels: typescript

#24801 Rewrite actions/app.ts and reducers/missed_updates.ts with createAction
  app/javascript/mastodon/actions/app.js
  app/javascript/mastodon/actions/app.ts
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/reducers/meta.js
  app/javascript/mastodon/reducers/missed_updates.js
  app/javascript/mastodon/reducers/missed_updates.ts
Labels: typescript

#24817 Fix Performance/RedundantMerge cop
  .rubocop_todo.yml
  config/initializers/paperclip.rb
Labels: ruby, lint fix 💅

#24819 Fix Performance/CollectionLiteralInLoop cop
  .rubocop_todo.yml
  app/models/admin/appeal_filter.rb
  app/models/admin/status_filter.rb
  app/models/media_attachment.rb
  app/models/relationship_filter.rb
  app/models/trends/preview_card_filter.rb
  app/models/trends/status_filter.rb
  app/presenters/status_relationships_presenter.rb
  app/services/fetch_resource_service.rb
  app/services/suspend_account_service.rb
  app/services/unsuspend_account_service.rb
  config/deploy.rb
  lib/mastodon/media_cli.rb
Labels: ruby, lint fix 💅

#24738 Fix RSpec/MultipleSubjects cop
  .rubocop_todo.yml
  spec/controllers/activitypub/collections_controller_spec.rb
  spec/controllers/activitypub/followers_synchronizations_controller_spec.rb
  spec/controllers/activitypub/outboxes_controller_spec.rb
  spec/controllers/api/web/embeds_controller_spec.rb
  spec/controllers/emojis_controller_spec.rb
  spec/controllers/follower_accounts_controller_spec.rb
  spec/controllers/following_accounts_controller_spec.rb
Labels: ruby, lint fix 💅

#23854 Enable Rubocop Rails/FilePath
  .rubocop.yml
  .rubocop_todo.yml
  config/environments/development.rb
  config/environments/test.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: ruby, lint fix 💅

#23756 Autofix Rubocop Style/CaseLikeIf
  .rubocop_todo.yml
  app/controllers/concerns/signature_verification.rb
Labels: ruby, lint fix 💅

#23754 Autofix Rubocop Style/HashSyntax
  .rubocop_todo.yml
  app/helpers/application_helper.rb
  app/models/media_attachment.rb
  lib/terrapin/multi_pipe_extensions.rb
  spec/controllers/admin/reports/actions_controller_spec.rb
  spec/controllers/admin/statuses_controller_spec.rb
  spec/controllers/concerns/signature_verification_spec.rb
Labels: ruby, lint fix 💅

#23755 Autofix Rubocop Style/ConcatArrayLiterals
  .rubocop_todo.yml
  app/lib/feed_manager.rb
Labels: ruby, lint fix 💅

#24469 Bump rubocop-rails 2.19.1 with update .rubocop_todo.yml
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/admin/domain_blocks_controller.rb
  lib/mastodon/emoji_cli.rb
Labels: ruby, lint fix 💅

#24901 Rewrite <Check /> as FC
  app/javascript/mastodon/components/check.tsx
Labels: typescript

#24893 Rewrite Image component as function component
  app/javascript/mastodon/components/image.jsx
  app/javascript/mastodon/components/image.tsx
Labels: typescript

#24897 Rewrite RadioButton component as FC
  app/javascript/mastodon/components/radio_button.jsx
  app/javascript/mastodon/components/radio_button.tsx
Labels: typescript

#24895 Add TypeScript support for `mastodon` alias and image imports
  app/javascript/mastodon/components/hashtag.jsx
  app/javascript/types/image.d.ts
  tsconfig.json
Labels: typescript

#24863 Use LayoutType from is_mobile in actions/app
  app/javascript/mastodon/actions/app.ts
Labels: typescript

#24896 Rewrite Domain component as function component
  app/javascript/mastodon/components/domain.jsx
  app/javascript/mastodon/components/domain.tsx
  app/javascript/mastodon/containers/domain_container.jsx
Labels: typescript

#24815 Add more detailed type annotation for Account
  app/javascript/types/resources.ts
Labels: typescript

#24843 Type Redux store and middleware
  app/javascript/mastodon/containers/compose_container.jsx
  app/javascript/mastodon/containers/mastodon.jsx
  app/javascript/mastodon/main.jsx
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/store/configureStore.js
  app/javascript/mastodon/store/index.ts
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
Labels: typescript

#24752 Add type annotation for DisplayName component
  app/javascript/mastodon/components/__tests__/display_name-test.jsx
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/display_name.jsx
  app/javascript/mastodon/components/display_name.tsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/features/account_timeline/components/moved_note.jsx
  app/javascript/mastodon/features/compose/components/autosuggest_account.jsx
  app/javascript/mastodon/features/compose/components/reply_indicator.jsx
  app/javascript/mastodon/features/directory/components/account_card.jsx
  app/javascript/mastodon/features/follow_requests/components/account_authorize.jsx
  app/javascript/mastodon/features/list_adder/components/account.jsx
  app/javascript/mastodon/features/list_editor/components/account.jsx
  app/javascript/mastodon/features/notifications/components/follow_request.jsx
  app/javascript/mastodon/features/picture_in_picture/components/header.jsx
  app/javascript/mastodon/features/report/components/status_check_box.jsx
  app/javascript/mastodon/features/status/components/detailed_status.jsx
  app/javascript/mastodon/features/ui/components/boost_modal.jsx
Labels: typescript

#24909 Rewrite `logo.tsx` as FC
  app/javascript/mastodon/components/logo.tsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
Labels: typescript

#24471 Enable ESLint react/no-deprecated
  .eslintrc.js
  app/javascript/mastodon/components/autosuggest_input.jsx
  app/javascript/mastodon/components/autosuggest_textarea.jsx
  app/javascript/mastodon/components/media_gallery.jsx
  app/javascript/mastodon/components/modal_root.jsx
  app/javascript/mastodon/features/account/components/account_note.jsx
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/blocks/index.jsx
  app/javascript/mastodon/features/bookmarked_statuses/index.jsx
  app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.jsx
  app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
  app/javascript/mastodon/features/domain_blocks/index.jsx
  app/javascript/mastodon/features/favourited_statuses/index.jsx
  app/javascript/mastodon/features/favourites/index.jsx
  app/javascript/mastodon/features/follow_requests/index.jsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/lists/index.jsx
  app/javascript/mastodon/features/mutes/index.jsx
  app/javascript/mastodon/features/notifications/index.jsx
  app/javascript/mastodon/features/pinned_statuses/index.jsx
  app/javascript/mastodon/features/reblogs/index.jsx
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/components/bundle.jsx
  app/javascript/mastodon/features/ui/components/columns_area.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/video/index.jsx
Labels: javascript, lint fix 💅

#24926 Add stricter ESLint rules for Typescript files
  .eslintrc.js
  app/javascript/mastodon/actions/app.ts
  app/javascript/mastodon/actions/pin_statuses.js
  app/javascript/mastodon/components/animated_number.tsx
  app/javascript/mastodon/components/avatar.tsx
  app/javascript/mastodon/components/avatar_overlay.tsx
  app/javascript/mastodon/components/blurhash.tsx
  app/javascript/mastodon/components/display_name.tsx
  app/javascript/mastodon/components/domain.tsx
  app/javascript/mastodon/components/gifv.tsx
  app/javascript/mastodon/components/icon.tsx
  app/javascript/mastodon/components/icon_button.tsx
  app/javascript/mastodon/components/icon_with_badge.tsx
  app/javascript/mastodon/components/logo.tsx
  app/javascript/mastodon/components/not_signed_in_indicator.tsx
  app/javascript/mastodon/components/radio_button.tsx
  app/javascript/mastodon/components/relative_timestamp.tsx
  app/javascript/mastodon/components/server_hero_image.tsx
  app/javascript/mastodon/components/verified_badge.tsx
  app/javascript/mastodon/features/account_timeline/index.jsx
  app/javascript/mastodon/features/ui/components/columns_area.jsx
  app/javascript/mastodon/features/ui/components/focal_point_modal.jsx
  app/javascript/mastodon/features/ui/components/upload_area.jsx
  app/javascript/mastodon/is_mobile.ts
  app/javascript/mastodon/locales/locale-data/co.js
  app/javascript/mastodon/locales/locale-data/oc.js
  app/javascript/mastodon/locales/locale-data/sa.js
  app/javascript/mastodon/polyfills/base_polyfills.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/markers.js
  app/javascript/mastodon/reducers/missed_updates.ts
  app/javascript/mastodon/store/index.ts
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
  app/javascript/mastodon/uuid.ts
  app/javascript/types/resources.ts
  package.json
  yarn.lock
Labels: typescript

#24942 Change "Sign in" to "Login"
  app/javascript/mastodon/components/not_signed_in_indicator.tsx
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/ui/components/header.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  config/locales/devise.en.yml
  config/locales/en.yml
Labels: ui

#24848 Fix RSpec/ScatteredSetup cop
  .rubocop_todo.yml
  spec/controllers/activitypub/followers_synchronizations_controller_spec.rb
  spec/controllers/activitypub/outboxes_controller_spec.rb
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: ruby, lint fix 💅

#24847 Fix RSpec/SharedContext cop
  .rubocop_todo.yml
  spec/services/unsuspend_account_service_spec.rb
Labels: ruby, lint fix 💅

#24850 Fix RSpec/RepeatedExampleGroupDescription cop
  .rubocop_todo.yml
  spec/controllers/admin/reports/actions_controller_spec.rb
  spec/policies/report_note_policy_spec.rb
Labels: ruby, lint fix 💅

#24988 Fix reports not being closed when performing batch suspensions
  app/models/form/account_batch.rb
  spec/models/form/account_batch_spec.rb
Labels: moderation

#25013 Add polling and automatic redirection to `/start` on email confirmation
  app/controllers/api/v1/emails/confirmations_controller.rb
  app/javascript/packs/sign_up.js
  app/views/auth/setup/show.html.haml
  config/routes/api.rb
  spec/controllers/api/v1/emails/confirmations_controller_spec.rb
Labels: api, new user experience

#25015 Fix being able to vote on your own polls
  app/validators/vote_validator.rb
  config/locales/en.yml
Labels: to backport

#25016 Fix race condition when reblogging a status
  app/controllers/api/v1/statuses/reblogs_controller.rb
Labels: to backport

#25033 Add spec for migration warning module
  spec/lib/mastodon/migration_warning_spec.rb
Labels: testing, ruby

#25034 Fix oversight in backup service
  app/services/backup_service.rb
Labels: bug

#25037 Add tests for avatar/header in backup service
  spec/services/backup_service_spec.rb
Labels: testing, ruby

#25054 Remove duplicate JPG type
  app/javascript/types/image.d.ts
Labels: typescript

#25031 Improve test coverage for `/api/v1/admin/ip_blocks_controller`
  spec/controllers/api/v1/admin/ip_blocks_controller_spec.rb
Labels: testing, ruby

#25022 Autofix Rubocop spacing in config
  .rubocop_todo.yml
  config/initializers/ffmpeg.rb
  config/initializers/omniauth.rb
  config/initializers/paperclip.rb
  config/initializers/webauthn.rb
Labels: ruby, lint fix 💅

#25017 Improve test coverage for `/api/v1/admin/email_domain_blocks`
  spec/controllers/api/v1/admin/email_domain_blocks_controller_spec.rb
Labels: testing, ruby

#23969 Implement pending specs for StatusesController
  spec/controllers/statuses_controller_spec.rb
Labels: testing, ruby

#24958 Fix POST `/api/v1/admin/domain_allows` returning 200 when no domain is specified
  app/controllers/api/v1/admin/domain_allows_controller.rb
  spec/controllers/api/v1/admin/domain_allows_controller_spec.rb
Labels: bug, to backport

#25060 Fix “Authorized applications” inefficiently and incorrectly getting last use date
  app/controllers/oauth/authorized_applications_controller.rb
  app/lib/application_extension.rb
  app/views/oauth/authorized_applications/index.html.haml
Labels: bug, performance, to backport

#24846 Regenerate rubocop-todo
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#24985 Improve test coverage for `/api/v1/admin/canonical_email_blocks`
  spec/controllers/api/v1/admin/canonical_email_blocks_controller_spec.rb
  spec/fabricators/canonical_email_block_fabricator.rb
Labels: testing, ruby

#25055 Rewrite `<Skeleton/>` as FC and TS
  app/javascript/mastodon/components/admin/Counter.jsx
  app/javascript/mastodon/components/admin/Dimension.jsx
  app/javascript/mastodon/components/display_name.tsx
  app/javascript/mastodon/components/empty_account.tsx
  app/javascript/mastodon/components/hashtag.jsx
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/components/skeleton.jsx
  app/javascript/mastodon/components/skeleton.tsx
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/mastodon/features/explore/components/story.jsx
  app/javascript/mastodon/features/privacy_policy/index.jsx
Labels: typescript

#24818 Fix Performance/StartWith cop
  .rubocop_todo.yml
  app/lib/extractor.rb
Labels: ruby, lint fix 💅

#24797 Fix Performance/MapCompact cop
  .rubocop_todo.yml
  app/lib/admin/metrics/dimension.rb
  app/lib/admin/metrics/measure.rb
  app/lib/feed_manager.rb
  app/models/account.rb
  app/models/account_statuses_cleanup_policy.rb
  app/models/account_suggestions/setting_source.rb
  app/models/account_suggestions/source.rb
  app/models/follow_recommendation_filter.rb
  app/models/notification.rb
  app/models/user_role.rb
  app/models/webhook.rb
  app/services/process_mentions_service.rb
  app/validators/existing_username_validator.rb
  db/migrate/20200407202420_migrate_unavailable_inboxes.rb
  spec/presenters/status_relationships_presenter_spec.rb
Labels: ruby, lint fix 💅

#24849 Fix RSpec/RepeatedExample cop
  .rubocop_todo.yml
  spec/policies/status_policy_spec.rb
Labels: ruby, lint fix 💅

#24743 Fix Rails/Exit cop
  .rubocop.yml
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#25099 Add request spec for backups download
  spec/requests/backups_spec.rb
Labels: testing, ruby

#24139 Move the mastodon/*_cli files to mastodon/cli/*
  .rubocop.yml
  .rubocop_todo.yml
  bin/tootctl
  lib/mastodon/cli/accounts.rb
  lib/mastodon/cli/cache.rb
  lib/mastodon/cli/canonical_email_blocks.rb
  lib/mastodon/cli/domains.rb
  lib/mastodon/cli/email_domain_blocks.rb
  lib/mastodon/cli/emoji.rb
  lib/mastodon/cli/feeds.rb
  lib/mastodon/cli/helper.rb
  lib/mastodon/cli/ip_blocks.rb
  lib/mastodon/cli/main.rb
  lib/mastodon/cli/maintenance.rb
  lib/mastodon/cli/media.rb
  lib/mastodon/cli/preview_cards.rb
  lib/mastodon/cli/search.rb
  lib/mastodon/cli/settings.rb
  lib/mastodon/cli/statuses.rb
  lib/mastodon/cli/upgrade.rb
  spec/lib/mastodon/cli/ip_blocks_spec.rb
  spec/lib/mastodon/cli/main_spec.rb
  spec/lib/mastodon/cli/settings_spec.rb
Labels: refactoring

#25100 Fix RSpec/ExpectInHook cop
  .rubocop_todo.yml
  spec/controllers/api/v1/media_controller_spec.rb
  spec/controllers/settings/applications_controller_spec.rb
  spec/lib/status_filter_spec.rb
Labels: ruby, lint fix 💅

#25042 Rewrite `<LoadGap />` as FC and TS
  app/javascript/mastodon/components/load_gap.jsx
  app/javascript/mastodon/components/load_gap.tsx
  app/javascript/mastodon/components/status_list.jsx
  app/javascript/mastodon/features/notifications/index.jsx
Labels: typescript

#25101 Fix RSpec/ExpectChange cop
  .rubocop_todo.yml
  spec/controllers/admin/account_moderation_notes_controller_spec.rb
  spec/controllers/admin/custom_emojis_controller_spec.rb
  spec/controllers/admin/invites_controller_spec.rb
  spec/controllers/admin/report_notes_controller_spec.rb
  spec/controllers/concerns/accountable_concern_spec.rb
  spec/controllers/invites_controller_spec.rb
  spec/controllers/settings/two_factor_authentication/webauthn_credentials_controller_spec.rb
  spec/models/admin/account_action_spec.rb
  spec/services/suspend_account_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/workers/scheduler/accounts_statuses_cleanup_scheduler_spec.rb
Labels: ruby, lint fix 💅

#24833 Rewrite actions/modal and reducers/modal with typescript
  app/javascript/mastodon/actions/blocks.js
  app/javascript/mastodon/actions/boosts.js
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/filters.js
  app/javascript/mastodon/actions/modal.js
  app/javascript/mastodon/actions/modal.ts
  app/javascript/mastodon/actions/mutes.js
  app/javascript/mastodon/actions/reports.js
  app/javascript/mastodon/components/edited_timestamp/index.jsx
  app/javascript/mastodon/containers/account_container.jsx
  app/javascript/mastodon/containers/domain_container.jsx
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/containers/status_container.jsx
  app/javascript/mastodon/features/account_gallery/index.jsx
  app/javascript/mastodon/features/account_timeline/containers/header_container.jsx
  app/javascript/mastodon/features/compose/containers/navigation_container.js
  app/javascript/mastodon/features/compose/containers/privacy_dropdown_container.js
  app/javascript/mastodon/features/compose/index.jsx
  app/javascript/mastodon/features/direct_timeline/containers/conversation_container.js
  app/javascript/mastodon/features/directory/components/account_card.jsx
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/status/containers/detailed_status_container.js
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/components/block_modal.jsx
  app/javascript/mastodon/features/ui/components/compare_history_modal.jsx
  app/javascript/mastodon/features/ui/components/disabled_account_banner.jsx
  app/javascript/mastodon/features/ui/components/header.jsx
  app/javascript/mastodon/features/ui/components/link_footer.jsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/features/ui/components/mute_modal.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
  app/javascript/mastodon/features/ui/containers/modal_container.js
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/modal.js
  app/javascript/mastodon/reducers/modal.ts
Labels: typescript

#25103 Fix RSpec/NoExpectationExample cop
  .rubocop_todo.yml
  spec/controllers/auth/registrations_controller_spec.rb
  spec/services/precompute_feed_service_spec.rb
Labels: ruby, lint fix 💅

#25117 Extract methods for user de-duping in maintenance CLI
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#25143 Add test coverage for `Mastodon::CLI::Accounts#create`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25145 Add test coverage for `Mastodon::CLI::Accounts#modify`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25146 Add test coverage for `Mastodon::CLI::Accounts#delete`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25116 Consistent usage of CLI `dry_run?` method
  lib/mastodon/cli/accounts.rb
  lib/mastodon/cli/domains.rb
  lib/mastodon/cli/feeds.rb
  lib/mastodon/cli/helper.rb
  lib/mastodon/cli/main.rb
  lib/mastodon/cli/media.rb
  lib/mastodon/cli/preview_cards.rb
  lib/mastodon/cli/upgrade.rb
Labels: refactoring, ruby

#25118 Increment index which was previously not used in maintenance CLI loop
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#25123 Fix Rails/WhereExists cop in CLI
  .rubocop_todo.yml
  lib/mastodon/cli/email_domain_blocks.rb
Labels: ruby, lint fix 💅

#25122 Fix FormatStringToken cop in CLI
  .rubocop_todo.yml
  lib/mastodon/cli/maintenance.rb
Labels: ruby, lint fix 💅

#25133 Add specs for admin/webhooks CRUD actions
  spec/controllers/admin/webhooks_controller_spec.rb
Labels: testing, ruby

#25163 Add test coverage for `Mastodon::CLI::Accounts#backup`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#25215 Disable some metrics cops
  .rubocop.yml
  .rubocop_todo.yml
  app/helpers/languages_helper.rb
Labels: ruby, lint fix 💅
