Repository mastodon/mastodon, pull requests merged in 2023-04, with the labels that each got.

#24343 Fix regressions from change in account row design in web UI
  app/helpers/home_helper.rb
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/styles/mastodon/components.scss
Labels: bug

#24305 Change search pop-out in web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/features/compose/components/search_results.jsx
  app/javascript/mastodon/features/compose/containers/search_container.js
  app/javascript/mastodon/features/compose/containers/warning_container.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/search.js
  app/javascript/mastodon/utils/hashtags.js
  app/javascript/styles/mastodon/components.scss
Labels: ui

#16210 [Proposal] Make able to write React in Typescript
  .eslintrc.js
  app/javascript/hooks/useHovering.ts
  app/javascript/mastodon/actions/picture_in_picture.js
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/api.js
  app/javascript/mastodon/components/avatar.jsx
  app/javascript/mastodon/components/avatar.tsx
  app/javascript/mastodon/components/blurhash.jsx
  app/javascript/mastodon/components/common_counter.jsx
  app/javascript/mastodon/components/hashtag.jsx
  app/javascript/mastodon/features/emoji/emoji_mart_data_light.js
  app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light.js
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/is_mobile.js
  app/javascript/mastodon/stream.js
  app/javascript/mastodon/utils/notifications.js
  app/javascript/mastodon/uuid.js
  app/javascript/mastodon/uuid.ts
  app/javascript/packs/public-path.js
  app/javascript/types/resources.ts
  babel.config.js
  config/webpack/rules/babel.js
  config/webpacker.yml
  package.json
  tsconfig.json
  yarn.lock
Labels: wontfix

#24379 Fix unescaped user input in LDAP query
  app/models/concerns/ldap_authenticable.rb
Labels: security

#24510 Bump nokogiri from 1.14.2 to 1.14.3
  Gemfile.lock
Labels: dependencies, ruby

#24512 Change all components to use the same error page in web UI
  app/javascript/mastodon/components/missing_indicator.jsx
  app/javascript/mastodon/features/account_gallery/index.jsx
  app/javascript/mastodon/features/account_timeline/index.jsx
  app/javascript/mastodon/features/followers/index.jsx
  app/javascript/mastodon/features/following/index.jsx
  app/javascript/mastodon/features/generic_not_found/index.jsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/defaultMessages.json
Labels: ui

#23614 Add “In Memoriam” banner back to profiles
  app/javascript/mastodon/features/account_timeline/components/header.jsx
  app/javascript/mastodon/features/account_timeline/components/memorial_note.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24546 Add client-side validation for taken username in sign-up form
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/packs/public.jsx
Labels: ui, new user experience

#20949 Fix characters being emojified even when using Variation Selector 15 (text)
  app/javascript/mastodon/features/emoji/__tests__/emoji-test.js
  app/javascript/mastodon/features/emoji/emoji.js
Labels: bug, ui

#24619 Add new onboarding flow to web UI
  app/javascript/images/elephant_ui_conversation.svg
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/check.jsx
  app/javascript/mastodon/components/column_back_button.jsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/verified_badge.jsx
  app/javascript/mastodon/features/compose/components/compose_form.jsx
  app/javascript/mastodon/features/follow_recommendations/components/account.jsx
  app/javascript/mastodon/features/follow_recommendations/index.jsx
  app/javascript/mastodon/features/onboarding/components/arrow_small_right.jsx
  app/javascript/mastodon/features/onboarding/components/progress_indicator.jsx
  app/javascript/mastodon/features/onboarding/components/step.jsx
  app/javascript/mastodon/features/onboarding/follows.jsx
  app/javascript/mastodon/features/onboarding/index.jsx
  app/javascript/mastodon/features/onboarding/share.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/accounts_counters.js
  app/javascript/mastodon/reducers/compose.js
  app/javascript/styles/mastodon/components.scss
Labels: ui, new user experience

#24549 Add lines to threads in web UI
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/containers/status_container.jsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24623 Fix cutting off first letter of hashtag links sometimes in web UI
  app/javascript/mastodon/components/status_content.jsx
Labels: bug

#24643 Change hashtags and mentions in bios to open in-app in web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/account_timeline/components/header.jsx
  app/javascript/mastodon/features/account_timeline/containers/header_container.jsx
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/features/compose/containers/search_container.js
Labels: ui

#24646 Add more tips to onboarding flow in web UI
  app/javascript/mastodon/features/onboarding/follows.jsx
  app/javascript/mastodon/features/onboarding/share.jsx
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui, new user experience

#24706 Change label from "For you" to "People" on explore screen in web UI
  app/javascript/mastodon/features/explore/index.jsx
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
Labels: ui

#24707 Change logo version in header based on screen size in web UI
  app/javascript/mastodon/components/logo.jsx
  app/javascript/mastodon/features/ui/components/header.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#24705 Add default post text to onboarding flow in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/onboarding/index.jsx
  app/javascript/mastodon/locales/defaultMessages.json
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/compose.js
Labels: ui
