Repository mastodon/mastodon, pull requests merged in 2023-09, with the labels that each got.

#26687 Fix not being able to invoke phrase search using unicode quotation marks
  app/services/search_service.rb
Labels: area/search

#26701 Fix unmatched quotes and prefixes causing search to fail
  app/lib/search_query_parser.rb
  app/lib/search_query_transformer.rb
  spec/lib/search_query_parser_spec.rb
  spec/lib/search_query_transformer_spec.rb
Labels: bug, area/search

#26754 Revert to using primary database in IndexingScheduler
  app/workers/scheduler/indexing_scheduler.rb
Labels: area/search

#26755 Fix search popout including full-text search instructions when full-text search is disabled
  app/javascript/mastodon/features/compose/components/search.jsx
Labels: ui, area/search

#26581 Move to ioredis for streaming
  package.json
  streaming/index.js
  yarn.lock
Labels: streaming

#26582 Add admin notifications for new Mastodon versions
  app/controllers/admin/software_updates_controller.rb
  app/javascript/mastodon/features/home_timeline/components/critical_update_banner.tsx
  app/javascript/mastodon/features/home_timeline/index.jsx
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/tables.scss
  app/lib/admin/system_check.rb
  app/lib/admin/system_check/software_version_check.rb
  app/mailers/admin_mailer.rb
  app/models/software_update.rb
  app/models/user_settings.rb
  app/policies/software_update_policy.rb
  app/presenters/initial_state_presenter.rb
  app/serializers/initial_state_serializer.rb
  app/services/software_update_check_service.rb
  app/views/admin/software_updates/index.html.haml
  app/views/admin_mailer/new_critical_software_updates.text.erb
  app/views/admin_mailer/new_software_updates.text.erb
  app/views/settings/preferences/notifications/show.html.haml
  app/workers/scheduler/software_update_check_scheduler.rb
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes/admin.rb
  config/sidekiq.yml
  db/migrate/20230822081029_create_software_updates.rb
  db/schema.rb
  lib/mastodon/version.rb
  lib/tasks/mastodon.rake
  spec/fabricators/software_update_fabricator.rb
  spec/features/admin/software_updates_spec.rb
  spec/lib/admin/system_check/software_version_check_spec.rb
  spec/mailers/admin_mailer_spec.rb
  spec/models/software_update_spec.rb
  spec/policies/software_update_policy_spec.rb
  spec/services/software_update_check_service_spec.rb
  spec/workers/scheduler/software_update_check_scheduler_spec.rb
Labels: build-image

#26766 Fix some video encoding failing due to uneven dimensions
  app/models/media_attachment.rb
Labels: bug

#26767 Fix wrong color on active icons with counters in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug

#26782 Fix `before:`, `after:` and `during:` failing when time zone not set
  app/lib/search_query_transformer.rb
Labels: bug, area/search

#26781 Fix `#hashtag` matching non-hashtagged posts in search
  app/chewy/public_statuses_index.rb
  app/chewy/statuses_index.rb
  app/chewy/tags_index.rb
  app/lib/search_query_transformer.rb
Labels: area/search

#26014 Remove kmr from language selection
  app/helpers/languages_helper.rb
Labels: i18n

#26760 Add `in:library` syntax to search
  app/lib/search_query_transformer.rb
  app/services/statuses_search_service.rb
  spec/lib/search_query_transformer_spec.rb
Labels: area/search

#26787 Fix language settings for users having selected the `kmr` language
  db/post_migrate/20230904134623_fix_kmr_locale_settings.rb
  db/schema.rb
  lib/tasks/tests.rake
Labels: i18n

#26753 Bump version to v4.2.0-beta3
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: build-image

#26801 Fix video player not being displayed in reports interface
  app/helpers/media_component_helper.rb
  app/views/admin/reports/_media_attachments.html.haml
Labels: bug, moderation

#26784 Add infinite scrolling for search results in web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/compose/components/search_results.jsx
  app/javascript/mastodon/features/explore/components/search_section.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/search.js
  app/javascript/styles/mastodon/components.scss
Labels: ui, area/search

#26768 Remove obfuscation of reply count in web UI
  app/javascript/mastodon/components/animated_number.tsx
  app/javascript/mastodon/components/icon_button.tsx
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
Labels: ui

#26807 Add `in:` to search popout in web UI
  app/javascript/mastodon/features/compose/components/search.jsx
Labels: ui, area/search

#26814 Fix crash when encountering invalid URL
  app/lib/tag_manager.rb
Labels: bug, to backport

#26729 Fix moderator rights inconsistencies
  app/lib/account_statuses_filter.rb
  app/lib/admin/account_statuses_filter.rb
  app/models/admin/status_batch_action.rb
  app/policies/admin/status_policy.rb
  spec/controllers/admin/statuses_controller_spec.rb
  spec/policies/admin/status_policy_spec.rb
Labels: bug, to backport

#26756 Add some information about Full-text search being disabled in search popout
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/locales/en.json
Labels: area/search

#26823 Fix blocked domain appears from account feed
  app/lib/account_statuses_filter.rb
  spec/models/account_statuses_filter_spec.rb
Labels: build-image

#26828 Fix paragraph margins resulting in irregular read-more cut-off in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26829 Change onboarding prompt to use full width of banner in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#26827 Fix mute button and volume slider feeling disconnected in web UI
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/video/index.jsx
Labels: ui

#26835 Fix `#hashtag` matching on individual components in search
  app/lib/search_query_transformer.rb
Labels: bug, area/search

#26834 Add recent searches in web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/actions/store.js
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/features/compose/containers/search_container.js
  app/javascript/mastodon/reducers/search.js
  app/javascript/mastodon/settings.js
Labels: ui, area/search

#26842 Fix performances of profile directory
  app/models/account.rb
  db/migrate/20230907150100_add_index_account_stats_on_last_status_at_and_account_id.rb
  db/schema.rb
  spec/controllers/api/v1/directories_controller_spec.rb
Labels: performance, to backport

#26847 Fix `account_id`, `max_id` and `min_id` params not working in search
  app/lib/search_query_parser.rb
  app/lib/search_query_transformer.rb
  app/services/statuses_search_service.rb
  lib/mastodon/snowflake.rb
  spec/lib/search_query_transformer_spec.rb
Labels: bug, area/search

#26703 Add search tests
  .github/workflows/test-ruby.yml
  Vagrantfile
  lib/tasks/spec.rake
  spec/rails_helper.rb
  spec/search/models/concerns/account_search_spec.rb
  spec/search/models/concerns/account_statuses_search_spec.rb
  spec/spec_helper.rb
Labels: testing, ruby, area/search

#26860 Fix confusing behavior of mute button and volume slider in web UI
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/video/index.jsx
Labels: ui

#26601 Convert `actions/account_notes` into Typescript
  app/javascript/mastodon/actions/account_notes.js
  app/javascript/mastodon/actions/account_notes.ts
  app/javascript/mastodon/api.js
  app/javascript/mastodon/api.ts
  app/javascript/mastodon/features/account/containers/account_note_container.js
  app/javascript/mastodon/reducers/relationships.js
  app/javascript/mastodon/store/index.ts
  app/javascript/mastodon/store/store.ts
  app/javascript/mastodon/store/typed_functions.ts
Labels: typescript

#26884 Fix error on `status` type notification (bell icon)
  app/services/notify_service.rb
Labels: bug

#26899 Fix Redux types
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
  app/javascript/mastodon/store/typed_functions.ts
Labels: typescript

#26872 Added admin api for managing tags
  app/controllers/api/v1/admin/tags_controller.rb
  app/models/tag.rb
  app/serializers/rest/admin/tag_serializer.rb
  config/routes/api.rb
  spec/requests/api/v1/admin/tags_spec.rb
Labels: api, moderation

#26916 Bump version to v4.2.0-rc1
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: build-image

#26922 Change Dockerfile to upgrade packages when building
  .github/workflows/build-container-image.yml
  .github/workflows/build-nightly.yml
  .github/workflows/build-releases.yml
  Dockerfile
Labels: to backport, docker

#26927 Fix processing of `min_id` and `max_id` parameters in `/api/v2/search`
  app/services/statuses_search_service.rb
Labels: bug, area/search

#26932 Fix container build when cache is disabled
  .github/workflows/build-container-image.yml
Labels: docker

#26936 Fix post edits not being forwarded as expected
  app/lib/activitypub/activity/update.rb
  app/services/activitypub/fetch_remote_poll_service.rb
  app/services/activitypub/process_status_update_service.rb
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: activitypub, to backport

#26931 Change Dockerfile to upgrade packages when building
  .github/workflows/build-container-image.yml
  .github/workflows/build-releases.yml
  Dockerfile
Labels: backport

#26930 Change Dockerfile to upgrade packages when building
  .github/workflows/build-container-image.yml
  .github/workflows/build-releases.yml
  Dockerfile
Labels: backport

#26929 Change Dockerfile to upgrade packages when building
  .github/workflows/build-container-image.yml
  .github/workflows/build-releases.yml
  Dockerfile
Labels: backport

#26959 Fix Web UI making duplicate search queries when scrolling
  app/javascript/mastodon/reducers/search.js
Labels: bug

#25900 Fix crash when viewing a moderation appeal and the moderator account has been deleted
  app/views/admin/account_warnings/_account_warning.html.haml
Labels: bug, to backport

#26945 Add additional metrics for streaming
  streaming/index.js
Labels: streaming

#26960 Fix hashtag bar being sometimes incorrectly hidden
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/features/status/components/detailed_status.jsx
Labels: bug

#26990 Fix post translation erroring out (v4.1.x)
  app/lib/translation_service/deepl.rb
  app/lib/translation_service/libre_translate.rb
  app/services/translate_status_service.rb
Labels: bug

#26998 Add `hide_collections`, `discoverable` and `indexable` attributes to credentials API
  app/serializers/rest/credential_account_serializer.rb
  spec/requests/api/v1/accounts/credentials_spec.rb
Labels: api

#27014 Fix search results temporarily disappearing while scrolling and loading more results
  app/javascript/mastodon/features/explore/results.jsx
Labels: build-image

#27036 Fix the search documentation URL in system checks
  app/lib/admin/system_check/elasticsearch_check.rb
Labels: to backport

#27061 Fix ActiveRecord using two connection pools when no replica is defined
  app/helpers/database_helper.rb
  app/models/application_record.rb
Labels: to backport

#26610 Improve modals reducer types
  app/javascript/mastodon/actions/modal.ts
  app/javascript/mastodon/reducers/modal.ts
Labels: typescript

#25585 Convert `dropdown_menu` state to Typescript
  app/javascript/mastodon/actions/dropdown_menu.js
  app/javascript/mastodon/actions/dropdown_menu.ts
  app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
  app/javascript/mastodon/components/scrollable_list.jsx
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/reducers/dropdown_menu.js
  app/javascript/mastodon/reducers/dropdown_menu.ts
  app/javascript/mastodon/reducers/index.ts
Labels: typescript

#27116 Fix inefficient queries in “Follows and followers” as well as several admin pages
  app/models/relationship_filter.rb
Labels: performance, to backport, build-image

#27127 Fix width of large text icon buttons
  app/javascript/mastodon/features/compose/components/text_icon_button.jsx
Labels: bug, area/web interface

#27128 Add redirection on `/deck` URLs for logged-out users
  app/lib/permalink_redirector.rb
Labels: to backport

#27062 Fix explore prompt sometimes showing up when the home TL is loading
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: to backport

#27129 Fix division by zero in video in bitrate computation code
  lib/paperclip/transcoder.rb
Labels: bug, to backport

#27111 Properly remove tIME chunk from PNG uploads
  app/models/concerns/account_avatar.rb
  app/models/concerns/account_header.rb
  app/models/custom_emoji.rb
  app/models/media_attachment.rb
  app/models/preview_card.rb
  app/models/preview_card_provider.rb
  app/models/site_upload.rb
Labels: to backport

#27147 Update `tootctl maintenance fix-duplicates` to Mastodon v4.2.0
  lib/mastodon/cli/maintenance.rb
Labels: to backport

#26602 Add Typescript types for some API objects
  app/javascript/mastodon/api_types/accounts.ts
  app/javascript/mastodon/api_types/custom_emoji.ts
  app/javascript/mastodon/api_types/relationships.ts
  app/serializers/rest/account_serializer.rb
  app/serializers/rest/custom_emoji_serializer.rb
  app/serializers/rest/relationship_serializer.rb
Labels: typescript

#27099 Only strip country code when language not listed in SUPPORTED_LOCALES
  app/helpers/languages_helper.rb
Labels: i18n

#27180 Fix retention dashboard not displaying correct month
  app/javascript/mastodon/components/admin/Retention.jsx
Labels: to backport

#27186 Fix filtering audit log for entries about disabling 2FA
  app/models/admin/action_log_filter.rb
Labels: bug, to backport

#27185 Fix link handling of mentions in user profiles when logged out
  app/javascript/mastodon/actions/search.js
Labels: bug, to backport, area/web interface

#26064 Fix haml-lint `InstanceVariables` rule for invites/_form
  .haml-lint_todo.yml
  app/helpers/invites_helper.rb
  app/views/admin/invites/index.html.haml
  app/views/invites/_form.html.haml
  app/views/invites/index.html.haml
Labels: ruby, lint fix 💅

#26060 Fix rubocop `Layout/ArgumentAlignment` cop
  .rubocop_todo.yml
  config/initializers/cors.rb
  config/initializers/session_store.rb
Labels: ruby, lint fix 💅

#25120 Extract methods for file movement in `CLI::Upgrade`
  .rubocop.yml
  lib/mastodon/cli/upgrade.rb
Labels: refactoring, ruby

#26129 Extract filename and csv helper methods from `Form::Import`
  app/models/form/import.rb
Labels: refactoring, ruby

#26062 Fix haml-lint `InstanceVariables` rule for admin/webhooks/_form
  .haml-lint_todo.yml
  app/views/admin/webhooks/_form.html.haml
  app/views/admin/webhooks/edit.html.haml
  app/views/admin/webhooks/new.html.haml
Labels: ruby, lint fix 💅

#26063 Fix haml-lint `InstanceVariables` rule for admin/roles/_form
  .haml-lint_todo.yml
  app/views/admin/roles/_form.html.haml
  app/views/admin/roles/edit.html.haml
  app/views/admin/roles/new.html.haml
Labels: ruby, lint fix 💅

#26046 Simplify instance presenter view access
  .haml-lint_todo.yml
  app/controllers/about_controller.rb
  app/controllers/auth/registrations_controller.rb
  app/controllers/auth/sessions_controller.rb
  app/controllers/concerns/account_controller_concern.rb
  app/controllers/home_controller.rb
  app/controllers/privacy_controller.rb
  app/controllers/statuses_controller.rb
  app/controllers/tags_controller.rb
  app/helpers/mascot_helper.rb
  app/views/shared/_og.html.haml
Labels: refactoring, ruby, rebase needed :construction:

#27211 Fix explore prompt appearing because of posts being received out of order
  app/javascript/mastodon/features/home_timeline/index.jsx
Labels: bug, area/web interface
