Repository mastodon/mastodon, pull requests merged in 2023-01, with the labels that each got.

#21048 Add ability to set minimum Puma threads with MIN_THREADS environment variable
  config/puma.rb
Labels: deployment, performance

#23037 Fix CSRF protection
  config/environments/production.rb
Labels: bug

#23072 Fix incorrect env file generation in mastodon:setup
  lib/tasks/mastodon.rake
Labels: bug

#22134 Fix crash when marking statuses as sensitive while some statuses are deleted
  app/models/admin/status_batch_action.rb
  app/views/admin/reports/_actions.html.haml
  spec/controllers/admin/reports/actions_controller_spec.rb
Labels: bug

#21470 Change domain block CSV parsing to be more robust and handle more lists
  app/controllers/admin/export_domain_allows_controller.rb
  app/controllers/admin/export_domain_blocks_controller.rb
  app/controllers/concerns/admin_export_controller_concern.rb
  app/models/admin/import.rb
  config/locales/en.yml
  spec/controllers/admin/export_domain_blocks_controller_spec.rb
  spec/fixtures/files/domain_blocks.csv
  spec/fixtures/files/domain_blocks_list.txt
Labels: moderation

#20878 Add support for editing media description and focus point of already-posted statuses
  app/controllers/api/v1/statuses_controller.rb
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/compose/components/upload.js
  app/javascript/mastodon/features/ui/components/focal_point_modal.js
  app/javascript/mastodon/reducers/compose.js
  app/services/update_status_service.rb
  spec/services/update_status_service_spec.rb
Labels: api, ui

#22375 Add confirmation screen when handling reports
  app/controllers/admin/account_actions_controller.rb
  app/controllers/admin/reports/actions_controller.rb
  app/models/admin/status_batch_action.rb
  app/views/admin/reports/_actions.html.haml
  app/views/admin/reports/actions/preview.html.haml
  config/i18n-tasks.yml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/admin/reports/actions_controller_spec.rb
Labels: moderation

#20808 Add option to make the landing page be /about even when trends are enabled
  app/javascript/mastodon/features/ui/index.js
  app/javascript/mastodon/initial_state.js
  app/models/form/admin_settings.rb
  app/serializers/initial_state_serializer.rb
  app/views/admin/settings/discovery/show.html.haml
  config/locales/simple_form.en.yml
  config/settings.yml
Labels: ui, moderation, new user experience

#23157 Fix wrong padding in RTL layout in web UI
  app/javascript/styles/mastodon/polls.scss
  app/javascript/styles/mastodon/rtl.scss
Labels: bug

#23156 Fix wrong text color on some buttons in light theme in web UI
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug

#23255 Add `roles` attribute to Account entities in REST API
  app/models/status.rb
  app/serializers/rest/account_serializer.rb
  spec/fabricators/user_role_fabricator.rb
Labels: api

#23290 Fix unserialized `role` on account entities in admin API
  app/serializers/rest/admin/account_serializer.rb
Labels: bug
