Repository mastodon/mastodon, pull requests merged in 2023-10, with the labels that each got.

#27238 Fix websocket connections being incorrectly decremented twice on errors
  streaming/index.js
Labels: bug, to backport

#27247 Fix import progress not updating on certain failures
  app/workers/import/row_worker.rb
Labels: bug, to backport

#27258 Fix importer returning negative row estimates
  app/lib/importer/base_importer.rb
Labels: to backport

#27253 Add a short-lived lock to trend refresh scheduler
  app/workers/scheduler/trends/refresh_scheduler.rb
Labels: performance, to backport

#27204 Fix boosts of local users being filtered in account timelines
  app/lib/account_statuses_filter.rb
  spec/lib/account_statuses_filter_spec.rb
Labels: bug, to backport

#27187 Fix double scroll bars in some columns in advanced interface
  app/javascript/mastodon/components/column.jsx
  app/javascript/mastodon/features/explore/index.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/features/explore/suggestions.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/styles/mastodon/components.scss
Labels: bug, area/web interface

#24236 Move migration_helpers Rubocop ignore to config
  .rubocop.yml
  lib/mastodon/migration_helpers.rb
Labels: ruby, lint fix 💅

#26042 Fix haml-lint Rubocop `Rails/*` cops
  .haml-lint_todo.yml
  app/helpers/admin/announcements_helper.rb
  app/views/admin/accounts/show.html.haml
  app/views/admin/announcements/edit.html.haml
  app/views/admin/announcements/new.html.haml
  app/views/admin/reports/actions/preview.html.haml
  app/views/admin/statuses/show.html.haml
  app/views/admin/tags/show.html.haml
  app/views/auth/registrations/new.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/statuses/_detailed_status.html.haml
  app/views/user_mailer/warning.html.haml
Labels: ruby, lint fix 💅

#24145 Autofix Rubocop cops for config/
  .rubocop_todo.yml
  config/application.rb
  config/environments/production.rb
  config/initializers/3_omniauth.rb
  config/initializers/content_security_policy.rb
  config/initializers/rack_attack.rb
  config/routes.rb
Labels: ruby, lint fix 💅

#25656 Dont match mention in url query string
  .rubocop_todo.yml
  app/models/account.rb
  spec/models/account_spec.rb
Labels: ruby

#27286 Fix auto-loading-more when not scrolled
  app/javascript/mastodon/components/scrollable_list.jsx
Labels: to backport, area/web interface

#27307 Fix some remote posts getting truncated
  app/javascript/mastodon/components/__tests__/hashtag_bar.tsx
  app/javascript/mastodon/components/hashtag_bar.tsx
Labels: bug, to backport, area/web interface

#27306 Fix crash when filtering for “dormant” relationships
  app/models/account.rb
  app/models/relationship_filter.rb
  spec/models/relationship_filter_spec.rb
Labels: bug

#27207 Fix incorrect serialization of regional languages in `contentMap`
  app/lib/activitypub/case_transform.rb
  spec/serializers/activitypub/note_serializer_spec.rb
Labels: bug

#27331 Fix clicking on already-opened thread post scrolling to the top of the thread
  app/javascript/mastodon/features/status/index.jsx
Labels: bug, to backport, area/web interface

#26711 Change `eslint` config to autofix missing comma and indentation in JS files
  .eslintrc.js
  app/javascript/mastodon/actions/alerts.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/components/column.jsx
  app/javascript/mastodon/components/poll.jsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/features/compose/components/navigation_bar.jsx
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/reblogs/index.jsx
  app/javascript/mastodon/features/report/comment.jsx
  app/javascript/mastodon/features/status/components/detailed_status.jsx
  app/javascript/mastodon/features/ui/components/header.jsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
  app/javascript/packs/application.js
  streaming/index.js
Labels: javascript, lint fix 💅

#27338 Fix clicking on already-loaded thread scrolling to the top of the thread
  app/javascript/mastodon/features/status/index.jsx
Labels: bug, area/web interface

#27350 Fix scroll position in thread view reseting when closing a modal
  app/javascript/mastodon/features/status/index.jsx
Labels: bug, backport, area/web interface

#27352 Update dependencies
  Gemfile.lock
Labels: backport

#27354 Update dependencies
  Gemfile.lock
Labels: backport

#27355 Fix duplicate reports being sent when reporting some remote posts
  app/services/report_service.rb
  spec/services/report_service_spec.rb
Labels: bug, to backport

#27356 Fix duplicate reports being sent when reporting some remote posts (port to v4.2.1)
  CHANGELOG.md
  app/services/report_service.rb
  spec/services/report_service_spec.rb
Labels: backport, build-image

#27339 Fix haml-lint `InstanceVariables` rule for admin/reports/actions
  .haml-lint_todo.yml
  app/views/admin/reports/_actions.html.haml
  app/views/admin/reports/show.html.haml
Labels: ruby, lint fix 💅

#27341 Fix haml-lint `InstanceVariables` rule for auth/registrations/status
  .haml-lint_todo.yml
  app/views/auth/registrations/_status.html.haml
  app/views/auth/registrations/edit.html.haml
Labels: ruby, lint fix 💅

#27342 Fix haml-lint `InstanceVariables` rule for relationships/account
  .haml-lint_todo.yml
  app/views/relationships/_account.html.haml
  app/views/relationships/show.html.haml
Labels: ruby, rebase needed :construction:, lint fix 💅

#25027 Add system specs for admin area `batch` actions
  spec/features/admin/accounts_spec.rb
  spec/features/admin/custom_emojis_spec.rb
  spec/features/admin/email_domain_blocks_spec.rb
  spec/features/admin/ip_blocks_spec.rb
  spec/features/admin/statuses_spec.rb
  spec/features/admin/trends/links/preview_card_providers_spec.rb
  spec/features/admin/trends/links_spec.rb
  spec/features/admin/trends/statuses_spec.rb
  spec/features/admin/trends/tags_spec.rb
Labels: testing, ruby

#27391 Fix when unfollow a tag, my post also disappears from the home timeline
  app/lib/feed_manager.rb
  spec/lib/feed_manager_spec.rb
Labels: bug, to backport

#25797 Migrate to request specs in `/api/v1/timelines/tag/:hashtag`
  spec/controllers/api/v1/timelines/tag_controller_spec.rb
  spec/requests/api/v1/timelines/tag_spec.rb
Labels: testing, ruby

#25634 Migrate to request specs in `/api/v1/statuses/:status_id/source`
  spec/controllers/api/v1/statuses/sources_controller_spec.rb
  spec/requests/api/v1/statuses/sources_spec.rb
Labels: testing, ruby

#25518 Migrate to request specs in `/api/v1/favourites`
  spec/controllers/api/v1/favourites_controller_spec.rb
  spec/requests/api/v1/favourites_spec.rb
Labels: testing, ruby

#25516 DB speedup in `API::` controller/request specs
  spec/controllers/api/oembed_controller_spec.rb
  spec/controllers/api/v1/accounts/credentials_controller_spec.rb
  spec/controllers/api/v1/accounts/follower_accounts_controller_spec.rb
  spec/controllers/api/v1/accounts/following_accounts_controller_spec.rb
  spec/controllers/api/v1/accounts/notes_controller_spec.rb
  spec/controllers/api/v1/accounts/pins_controller_spec.rb
  spec/controllers/api/v1/accounts/relationships_controller_spec.rb
  spec/controllers/api/v1/accounts/statuses_controller_spec.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/api/v1/admin/accounts_controller_spec.rb
  spec/controllers/api/v1/announcements/reactions_controller_spec.rb
  spec/controllers/api/v1/announcements_controller_spec.rb
  spec/controllers/api/v1/blocks_controller_spec.rb
  spec/controllers/api/v1/conversations_controller_spec.rb
  spec/controllers/api/v1/filters_controller_spec.rb
  spec/controllers/api/v1/instances/translation_languages_controller_spec.rb
  spec/controllers/api/v1/lists/accounts_controller_spec.rb
  spec/controllers/api/v1/markers_controller_spec.rb
  spec/controllers/api/v1/media_controller_spec.rb
  spec/controllers/api/v1/polls/votes_controller_spec.rb
  spec/controllers/api/v1/reports_controller_spec.rb
  spec/controllers/api/v1/statuses/mutes_controller_spec.rb
  spec/controllers/api/v1/statuses/reblogged_by_accounts_controller_spec.rb
  spec/controllers/api/v1/statuses/reblogs_controller_spec.rb
  spec/controllers/api/v1/statuses_controller_spec.rb
  spec/controllers/api/v2/admin/accounts_controller_spec.rb
  spec/controllers/api/v2/filters/keywords_controller_spec.rb
  spec/controllers/api/v2/filters/statuses_controller_spec.rb
  spec/requests/api/v1/admin/account_actions_spec.rb
  spec/requests/api/v1/admin/canonical_email_blocks_spec.rb
  spec/requests/api/v1/admin/domain_allows_spec.rb
  spec/requests/api/v1/admin/domain_blocks_spec.rb
  spec/requests/api/v1/admin/email_domain_blocks_spec.rb
  spec/requests/api/v1/admin/ip_blocks_spec.rb
  spec/requests/api/v1/admin/reports_spec.rb
  spec/requests/api/v1/apps/credentials_spec.rb
  spec/requests/api/v1/apps_spec.rb
  spec/requests/api/v1/domain_blocks_spec.rb
  spec/requests/api/v1/follow_requests_spec.rb
  spec/requests/api/v1/lists_spec.rb
  spec/requests/api/v1/tags_spec.rb
Labels: testing, ruby

#25472 Migrate to request specs in `/api/v1/followed_tags`
  .rubocop_todo.yml
  spec/controllers/api/v1/followed_tags_controller_spec.rb
  spec/requests/api/v1/followed_tags_spec.rb
Labels: testing, ruby

#25453 Move `SignedReqestHelpers` rspec config to separate file
  spec/rails_helper.rb
  spec/support/signed_request_helpers.rb
Labels: testing, ruby

#25475 Add request specs for `/api/v1/reports`
  spec/requests/api/v1/reports_spec.rb
Labels: testing, ruby

#25528 Speed-up on `MoveWorker` spec
  spec/workers/move_worker_spec.rb
Labels: testing, ruby

#27395 Fix duplicate tests
  spec/controllers/api/v1/reports_controller_spec.rb
  spec/requests/api/v1/reports_spec.rb
Labels: testing, ruby

#25542 Speed-up on `Rack::Attack` spec
  spec/config/initializers/rack_attack_spec.rb
Labels: testing, ruby

#25739 Migrate to request specs in `/api/v1/admin/trends/links`
  spec/controllers/api/v1/admin/trends/links_controller_spec.rb
  spec/requests/api/v1/admin/trends/links/links_spec.rb
Labels: testing, ruby

#27423 Fix handling of `inLanguage` attribute in preview card processing
  app/lib/link_details_extractor.rb
  spec/lib/link_details_extractor_spec.rb
Labels: bug, to backport

#25321 Add coverage for `CLI::Statuses` command
  spec/lib/mastodon/cli/statuses_spec.rb
  spec/rails_helper.rb
Labels: testing, ruby

#25454 Remove unused stub json ld context
  spec/fixtures/requests/json-ld.activitystreams.txt
  spec/fixtures/requests/json-ld.identity.txt
  spec/fixtures/requests/json-ld.security.txt
  spec/lib/activitypub/linked_data_signature_spec.rb
  spec/rails_helper.rb
  spec/services/after_block_domain_from_account_service_spec.rb
Labels: testing, ruby

#25592 Add coverage for `ExistingUsernameValidator`
  app/validators/existing_username_validator.rb
  spec/validators/existing_username_validator_spec.rb
Labels: testing, ruby

#25563 Migrate to request specs in `/api/v1/admin/accounts`
  .rubocop_todo.yml
  spec/controllers/api/v1/admin/accounts_controller_spec.rb
  spec/requests/api/v1/admin/accounts_spec.rb
Labels: testing, ruby

#25517 Migrate to request specs in `/api/v1/blocks`
  spec/controllers/api/v1/blocks_controller_spec.rb
  spec/requests/api/v1/blocks_spec.rb
Labels: testing, ruby

#25468 Migrate to request specs in `/api/v1/lists/:id/accounts`
  spec/controllers/api/v1/lists/accounts_controller_spec.rb
  spec/requests/api/v1/lists/accounts_spec.rb
Labels: testing, ruby

#25346 Misc coverage improvements for `Admin::` and `Settings::` controllers
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/controllers/admin/export_domain_allows_controller_spec.rb
  spec/controllers/admin/export_domain_blocks_controller_spec.rb
  spec/controllers/admin/instances_controller_spec.rb
  spec/controllers/admin/settings/about_controller_spec.rb
  spec/controllers/admin/settings/appearance_controller_spec.rb
  spec/controllers/admin/settings/content_retention_controller_spec.rb
  spec/controllers/admin/settings/discovery_controller_spec.rb
  spec/controllers/admin/settings/registrations_controller_spec.rb
  spec/controllers/admin/tags_controller_spec.rb
  spec/controllers/admin/webhooks_controller_spec.rb
  spec/controllers/settings/imports_controller_spec.rb
Labels: testing, ruby

#25590 Add coverage for `UnreservedUsernameValidator`
  app/validators/unreserved_username_validator.rb
  spec/validators/unreserved_username_validator_spec.rb
Labels: testing, ruby

#25391 Spec speed ups on `AccountsController` spec
  spec/controllers/accounts_controller_spec.rb
Labels: testing, ruby

#23399 Add spec for poll model
  spec/models/poll_spec.rb
Labels: testing, ruby

#27399 Fix errors in CLI specs
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: bug, testing, ruby

#25878 Refactor domains cli to remove model call from regex
  config/brakeman.ignore
  lib/mastodon/cli/domains.rb
Labels: refactoring, ruby

#26976 Support "in:public" search filter
  app/javascript/mastodon/features/compose/components/search.jsx
  app/lib/search_query_transformer.rb
Labels: area/search

#24040 Add RSpec GitHub annotations gem
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: testing, ruby

#27450 Fix duplicate github annotations for rspec failures
  .github/workflows/test-ruby.yml
  spec/spec_helper.rb
Labels: testing

#25204 Add test coverage for `Mastodon::CLI::Accounts#prune`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#27448 Fix `Performance/DeletePrefix` cop
  .rubocop_todo.yml
  app/models/featured_tag.rb
Labels: ruby, lint fix 💅

#27447 Fix `Naming/VariableNumber` cop
  .rubocop_todo.yml
  db/migrate/.rubocop.yml
  spec/models/account_spec.rb
  spec/models/domain_block_spec.rb
  spec/models/user_spec.rb
Labels: ruby, rebase needed :construction:, lint fix 💅

#25284 Add test coverage for `Mastodon::CLI::Accounts#migrate`
  spec/lib/mastodon/cli/accounts_spec.rb
Labels: testing, ruby

#27476 Do not display the navigation banner in the logo container
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/styles/mastodon/components.scss
Labels: to backport

#27479 Fix missing background behind dismissable banner in web UI
  app/javascript/mastodon/features/explore/statuses.jsx
Labels: bug

#25883 Configure brakeman to ignore url safe preview card urls
  app/helpers/formatting_helper.rb
  app/views/admin/trends/links/_preview_card.html.haml
  config/brakeman.ignore
  config/brakeman.yml
  spec/views/admin/trends/links/_preview_card.html.haml_spec.rb
Labels: refactoring, ruby

#26889 Change Content-Security-Policy to be tighter on media paths
  config/initializers/content_security_policy.rb
Labels: to backport

#21464 Improve error handling in mastodon:setup task
  lib/tasks/mastodon.rake
Labels: deployment, refactoring

#27512 Fix Layout/EmptyLineAfterGuardClause issues caused by merging an old PR
  lib/tasks/mastodon.rake
Labels: lint fix 💅

#27489 Fix explore page reloading when you navigate back to it in web UI
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/explore/suggestions.jsx
  app/javascript/mastodon/features/explore/tags.jsx
Labels: bug

#25543 Migrate to request specs in `/api/v1/media`
  .rubocop_todo.yml
  spec/controllers/api/v1/media_controller_spec.rb
  spec/requests/api/v1/media_spec.rb
Labels: testing, ruby

#25963 Rails 7.1 update
  Gemfile
  Gemfile.lock
  app/javascript/packs/admin.jsx
  app/javascript/packs/public.jsx
  app/lib/cache_buster.rb
  app/models/concerns/has_user_settings.rb
  app/models/concerns/status_safe_reblog_insert.rb
  config/application.rb
  lib/active_record/batches.rb
  package.json
  spec/generators/post_deployment_migration_generator_spec.rb
  spec/lib/cache_buster_spec.rb
  yarn.lock
Labels: dependencies, ruby

#25444 Rewrite `emoji_unicode_mapping_light` to TS
  app/javascript/mastodon/components/autosuggest_emoji.jsx
  app/javascript/mastodon/features/emoji/emoji.js
  app/javascript/mastodon/features/emoji/emoji_compressed.d.ts
  app/javascript/mastodon/features/emoji/emoji_mart_data_light.ts
  app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light.js
  app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light.ts
  app/javascript/mastodon/features/getting_started/components/announcements.jsx
Labels: typescript

#27513 Regenerate lint todos
  .haml-lint_todo.yml
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#27531 Fix haml-lint `UnnecessaryStringOutput` for views
  .haml-lint_todo.yml
  app/views/accounts/show.html.haml
  app/views/admin/custom_emojis/_custom_emoji.html.haml
  app/views/admin/relays/_relay.html.haml
  app/views/admin/rules/_rule.html.haml
  app/views/admin/statuses/index.html.haml
  app/views/auth/registrations/_session.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/notification_mailer/_status.html.haml
  app/views/settings/two_factor_authentication_methods/index.html.haml
  app/views/statuses/_detailed_status.html.haml
  app/views/statuses/_poll.html.haml
  app/views/statuses/_simple_status.html.haml
  app/views/user_mailer/suspicious_sign_in.html.haml
  app/views/user_mailer/webauthn_credential_added.html.haml
  app/views/user_mailer/webauthn_credential_deleted.html.haml
  app/views/user_mailer/welcome.html.haml
Labels: ruby, lint fix 💅

#27529 Solve simplest haml-lint `Rubocop` lints
  .haml-lint_todo.yml
  app/views/.rubocop.yml
  app/views/admin/accounts/_account.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/domain_blocks/confirm_suspension.html.haml
  app/views/admin/software_updates/index.html.haml
  app/views/admin/tags/show.html.haml
  app/views/admin/trends/tags/_tag.html.haml
  app/views/auth/registrations/new.html.haml
  app/views/layouts/error.html.haml
  app/views/statuses_cleanup/show.html.haml
Labels: ruby, rebase needed :construction:, lint fix 💅

#27554 Fix batch attachment deletion when using OpenStack Swift
  app/lib/attachment_batch.rb
Labels: bug, to backport

#27368 Fix confusing screen when visiting a confirmation link for an already-confirmed email
  app/controllers/auth/confirmations_controller.rb
  app/views/auth/confirmations/new.html.haml
  app/views/auth/shared/_progress.html.haml
  config/locales/en.yml
  spec/features/captcha_spec.rb
Labels: new user experience

#27559 Use `next` keyword in field loop in admin/accounts/index view
  .haml-lint_todo.yml
  app/views/admin/accounts/index.html.haml
Labels: ruby, lint fix 💅

#27442 Fix report processing notice not mentioning the report number when performing a custom action
  app/controllers/admin/account_actions_controller.rb
Labels: bug, to backport

#27503 Add HTML lang attribute to preview card descriptions
  app/javascript/mastodon/features/status/components/card.jsx
Labels: javascript, area/web interface

#27579 Fix various icon styles in web UI
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/mastodon/features/video/index.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#27459 Fix error and incorrect URLs in `/api/v1/accounts/:id/featured_tags` for remote accounts
  app/serializers/rest/featured_tag_serializer.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/featured_tags_controller_spec.rb
  spec/requests/api/v1/accounts/featured_tags_spec.rb
Labels: bug, to backport

#27486 Misc spec/refactor to user mailer and user mailer spec
  app/controllers/admin/disputes/appeals_controller.rb
  app/mailers/user_mailer.rb
  config/i18n-tasks.yml
  spec/mailers/user_mailer_spec.rb
Labels: testing, refactoring, ruby

#27587 Fix account click on detailed status
  app/javascript/mastodon/features/status/components/detailed_status.jsx
Labels: bug

#27584 Fix hashtag matching pattern matching some URLs
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: bug, to backport

#27586 Have `Follow` activities bypass availability
  app/services/follow_service.rb
  app/workers/activitypub/delivery_worker.rb
Labels: activitypub

#26905 Extract class from CSP configuration/initialization
  app/lib/content_security_policy.rb
  config/initializers/content_security_policy.rb
  spec/lib/content_security_policy_spec.rb
Labels: ruby

#27620 Fix posts from force-sensitized accounts being able to trend
  app/models/trends/statuses.rb
Labels: bug, to backport

#27469 Add some more tests and clean up domain block controller
  app/controllers/admin/domain_blocks_controller.rb
  spec/features/admin/domain_blocks_spec.rb
Labels: testing, refactoring

#27570 Update haml-lint line length configuration to match rubocop value
  .haml-lint.yml
  .haml-lint_todo.yml
Labels: lint fix 💅

#27333 Improve Babel configuration and automatically load polyfills
  .env.test
  app/javascript/mastodon/polyfills/base_polyfills.ts
  app/javascript/mastodon/polyfills/extra_polyfills.ts
  app/javascript/mastodon/polyfills/index.ts
  babel.config.js
  config/webpack/rules/index.js
  config/webpack/rules/node_modules.js
  config/webpack/tests.js
  package.json
  yarn.lock
Labels: to backport

#25991 Update strong_migrations to version 1.3.0
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby
