Repository mastodon/mastodon, pull requests merged in 2023-12, with the labels that each got.

#28158 Eliminate double subject call in admin/ controller specs
  spec/controllers/admin/account_moderation_notes_controller_spec.rb
  spec/controllers/admin/custom_emojis_controller_spec.rb
  spec/controllers/admin/report_notes_controller_spec.rb
Labels: performance, testing, refactoring, ruby

#28149 Model concerns organization into module namespaces
  .rubocop_todo.yml
  app/models/account.rb
  app/models/concerns/account/associations.rb
  app/models/concerns/account/avatar.rb
  app/models/concerns/account/counters.rb
  app/models/concerns/account/finder_concern.rb
  app/models/concerns/account/header.rb
  app/models/concerns/account/interactions.rb
  app/models/concerns/account/merging.rb
  app/models/concerns/account/search.rb
  app/models/concerns/account/statuses_search.rb
  app/models/concerns/status/safe_reblog_insert.rb
  app/models/concerns/status/search_concern.rb
  app/models/concerns/status/snapshot_concern.rb
  app/models/concerns/status/threading_concern.rb
  app/models/concerns/user/has_settings.rb
  app/models/concerns/user/ldap_authenticable.rb
  app/models/concerns/user/omniauthable.rb
  app/models/concerns/user/pam_authenticable.rb
  app/models/status.rb
  app/models/user.rb
  app/views/settings/profiles/show.html.haml
  lib/mastodon/cli/maintenance.rb
  spec/models/account_spec.rb
  spec/models/concerns/account/counters_spec.rb
  spec/models/concerns/account/finder_concern_spec.rb
  spec/models/concerns/account/interactions_spec.rb
  spec/models/concerns/account/statuses_search_spec.rb
  spec/models/concerns/status/threading_concern_spec.rb
  spec/search/models/concerns/account/search_spec.rb
  spec/search/models/concerns/account/statuses_search_spec.rb
Labels: refactoring, ruby

#28167 Add spec coverage for media CLI usage command
  spec/lib/mastodon/cli/media_spec.rb
Labels: testing

#28171 Fix `Style/SelfAssignment` cop
  lib/mastodon/snowflake.rb
Labels: ruby, lint fix 💅

#28169 Add explicit `dependent: nil` to associations
  .rubocop_todo.yml
  app/models/concerns/account/counters.rb
  app/models/conversation.rb
  app/models/custom_emoji.rb
  app/models/custom_emoji_category.rb
  app/models/domain_block.rb
  app/models/invite.rb
  app/models/status.rb
  app/models/user.rb
  app/models/web/push_subscription.rb
Labels: ruby, lint fix 💅

#28172 Fix `Lint/RedundantSafeNavigation` cop
  app/controllers/api/v1/accounts_controller.rb
  app/models/trends/history.rb
Labels: ruby, lint fix 💅

#28173 Fix `Style/HashEachMethods` cop
  db/seeds/03_roles.rb
Labels: ruby, lint fix 💅

#28178 Fix `Style/HashEachMethods` cop in HAML files
  app/views/admin/reports/index.html.haml
  app/views/settings/applications/_fields.html.haml
Labels: ruby, lint fix 💅

#28181 Add spec coverage for `CLI::EmailDomainBlocks` commands
  lib/mastodon/cli/email_domain_blocks.rb
  spec/lib/mastodon/cli/email_domain_blocks_spec.rb
Labels: testing, ruby

#28210 Remove triple subject call in `api/v1/lists` spec
  spec/requests/api/v1/lists_spec.rb
Labels: testing, ruby

#28209 Remove 2x double subject call in `models/form/account_batch` spec
  spec/models/form/account_batch_spec.rb
Labels: testing, ruby

#28217 Enable the eslint `react/no-unknown-property` rule
  .eslintrc.js
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/features/video/index.jsx
  package.json
  yarn.lock
Labels: javascript, lint fix 💅

#28248 Fix flaky tests related to file creation
  spec/generators/post_deployment_migration_generator_spec.rb
  spec/lib/mastodon/cli/emoji_spec.rb
Labels: bug, testing, ruby

#28252 Fix error when processing link preview with an array as `inLanguage`
  app/lib/link_details_extractor.rb
Labels: bug

#28208 Use composite primary key for `PreviewCardsStatus` model
  app/models/preview_cards_status.rb
  app/models/status.rb
Labels: refactoring, ruby

#28316 Fix notification sounds
  app/javascript/mastodon/actions/notifications_typed.ts
Labels: bug, area/web interface

#28268 Fix `LinkCrawlWorker` error when encountering empty OEmbed response
  app/services/fetch_oembed_service.rb
Labels: bug

#28323 Add `migrator_version` method to CLI maintenance script
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#28339 Fix N+1s because of association preloaders not actually getting called
  app/lib/inline_renderer.rb
  app/models/announcement.rb
  app/models/concerns/account/search.rb
  app/models/notification.rb
  app/serializers/initial_state_serializer.rb
  app/services/account_search_service.rb
  app/services/batched_remove_status_service.rb
Labels: performance, build-image

#28350 Improve spec coverage for `models/announcement` class
  spec/controllers/emojis_controller_spec.rb
  spec/fabricators/announcement_mute_fabricator.rb
  spec/fabricators/announcement_reaction_fabricator.rb
  spec/fabricators/custom_emoji_fabricator.rb
  spec/models/announcement_spec.rb
  spec/models/custom_emoji_spec.rb
  spec/requests/api/v1/custom_emojis_spec.rb
Labels: testing, ruby

#28354 Update stylelint to version 16.0.2
  package.json
  yarn.lock
Labels: dependencies, javascript

#28356 Convert `api/v1/directories` controller spec to request spec
  spec/requests/api/v1/directories_spec.rb
Labels: refactoring, ruby

#28359 Un-nest contexts in `settings/2fa/webauthn` spec
  spec/controllers/settings/two_factor_authentication/webauthn_credentials_controller_spec.rb
Labels: refactoring, ruby

#28355 Move default `meta` options from `InitialStateSerializer` to private method (AbcSize reduction)
  .rubocop_todo.yml
  app/serializers/initial_state_serializer.rb
Labels: refactoring, ruby

#28363 Fix reference to non-existent var in CLI maintenance command
  lib/mastodon/cli/maintenance.rb
Labels: to backport

#28358 Unwind `map` on single-item array in `spec/services/delete_account_service` spec
  spec/services/delete_account_service_spec.rb
Labels: refactoring, ruby

#28371 Opt out of `Rails/SkipsModelValidations` cop in db/migrate
  .rubocop.yml
  .rubocop_todo.yml
  db/migrate/20230215074423_move_user_settings.rb
Labels: ruby, lint fix 💅

#28377 Fix `Style/InverseMethods` cop
  .rubocop_todo.yml
  app/models/custom_filter.rb
  app/services/update_account_service.rb
  spec/controllers/activitypub/replies_controller_spec.rb
Labels: rebase needed :construction:

#28386 Fix `Style/SymbolProc` cop
  .rubocop_todo.yml
  config/initializers/3_omniauth.rb
Labels: ruby, lint fix 💅

#28389 Fix `Style/StderrPuts` cop
  .rubocop_todo.yml
  config/boot.rb
Labels: ruby, lint fix 💅

#28391 Fix `Style/RedundantReturn` cop
  .rubocop_todo.yml
  app/controllers/api/v1/directories_controller.rb
  app/controllers/auth/confirmations_controller.rb
  app/lib/ostatus/tag_manager.rb
  app/models/form/import.rb
Labels: ruby, lint fix 💅

#28412 Fix SQL query in `/api/v1/directory`
  app/models/account.rb
  spec/requests/api/v1/directories_spec.rb
Labels: bug, backport

#28385 Opt out of `Rails/UnusedIgnoredColumns` cop
  .rubocop.yml
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#28399 Fix `Performance/StringIdentifierArgument` cop
  app/helpers/application_helper.rb
  app/models/account.rb
  app/models/concerns/remotable.rb
  app/models/form/admin_settings.rb
  spec/models/concerns/remotable_spec.rb
  spec/requests/omniauth_callbacks_spec.rb
Labels: ruby, lint fix 💅

#28370 Opt out of `Rails/NegateInclude` cop
  .rubocop.yml
  .rubocop_todo.yml
Labels: ruby, rebase needed :construction:, lint fix 💅

#28388 Add spec coverage for `models/form/custom_emoji_batch` class
  spec/fabricators/custom_emoji_category_fabricator.rb
  spec/models/form/custom_emoji_batch_spec.rb
Labels: testing, ruby

#28413 Group artifact actions
  .github/renovate.json5
Labels: bug, dependencies

#28374 Fix call to inefficient `delete_matched` cache method in domain blocks
  app/controllers/api/v1/accounts/notes_controller.rb
  app/controllers/api/v1/accounts/pins_controller.rb
  app/controllers/api/v1/accounts/relationships_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/controllers/relationships_controller.rb
  app/models/account_domain_block.rb
  app/models/concerns/account/interactions.rb
  app/models/concerns/relationship_cacheable.rb
  app/presenters/account_relationships_presenter.rb
  spec/presenters/account_relationships_presenter_spec.rb
Labels: performance

#28367 Fix call to inefficient `delete_matched` cache method in domain blocks
  app/controllers/api/v1/accounts/notes_controller.rb
  app/controllers/api/v1/accounts/pins_controller.rb
  app/controllers/api/v1/accounts/relationships_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/controllers/relationships_controller.rb
  app/models/account_domain_block.rb
  app/models/concerns/account_interactions.rb
  app/models/concerns/relationship_cacheable.rb
  app/presenters/account_relationships_presenter.rb
  spec/presenters/account_relationships_presenter_spec.rb
Labels: performance, backport, build-image

#28314 Change algorithm of follow recommendations
  .github/renovate.json5
  app/controllers/admin/follow_recommendations_controller.rb
  app/controllers/api/v1/suggestions_controller.rb
  app/controllers/api/v2/suggestions_controller.rb
  app/lib/potential_friendship_tracker.rb
  app/models/account_domain_block.rb
  app/models/account_suggestions.rb
  app/models/account_suggestions/friends_of_friends_source.rb
  app/models/account_suggestions/global_source.rb
  app/models/account_suggestions/past_interactions_source.rb
  app/models/account_suggestions/setting_source.rb
  app/models/account_suggestions/similar_profiles_source.rb
  app/models/account_suggestions/source.rb
  app/models/block.rb
  app/models/concerns/account/associations.rb
  app/models/concerns/account/interactions.rb
  app/models/concerns/account/search.rb
  app/models/follow.rb
  app/models/follow_recommendation_filter.rb
  app/models/follow_recommendation_mute.rb
  app/models/follow_recommendation_suppression.rb
  app/models/follow_request.rb
  app/models/mute.rb
  app/models/preview_cards_status.rb
  app/services/account_search_service.rb
  app/services/favourite_service.rb
  app/services/post_status_service.rb
  app/services/reblog_service.rb
  app/views/admin/follow_recommendations/show.html.haml
  app/workers/scheduler/follow_recommendations_scheduler.rb
  db/migrate/20231211234923_create_follow_recommendation_mutes.rb
  db/migrate/20231212073317_add_languages_index_to_account_summaries.rb
  db/schema.rb
  spec/requests/api/v1/suggestions_spec.rb
  spec/workers/scheduler/follow_recommendations_scheduler_spec.rb
Labels: new user experience, build-image

#28326 Add spec for `CLI::Maintenance#fix_duplicates`
  lib/mastodon/cli/maintenance.rb
  spec/lib/mastodon/cli/maintenance_spec.rb
Labels: testing, refactoring, ruby

#28425 Remove unneeded settings cleanup from specs
  spec/controllers/admin/settings/branding_controller_spec.rb
  spec/controllers/api/v1/trends/links_controller_spec.rb
  spec/controllers/api/v1/trends/statuses_controller_spec.rb
  spec/controllers/api/v1/trends/tags_controller_spec.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/controllers/concerns/account_controller_concern_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/instance_helper_spec.rb
  spec/models/user_spec.rb
  spec/presenters/instance_presenter_spec.rb
  spec/requests/api/v1/instances/activity_spec.rb
  spec/requests/api/v1/instances/domain_blocks_spec.rb
  spec/requests/api/v1/instances/peers_spec.rb
  spec/requests/cache_spec.rb
  spec/services/app_sign_up_service_spec.rb
Labels: testing, ruby

#28433 Fix `friends_of_friends` sometimes suggesting already-followed accounts
  app/models/account_suggestions/friends_of_friends_source.rb
Labels: bug

#28453 Fix profile setup showing default avatar in web UI
  app/javascript/mastodon/features/onboarding/profile.jsx
Labels: bug, ui

#28444 Clean up of `RSpec/LetSetup` within `spec/models`
  .rubocop_todo.yml
  spec/models/account_spec.rb
  spec/models/canonical_email_block_spec.rb
  spec/models/user_spec.rb
Labels: testing, ruby

#28446 Clean up of `RSpec/LetSetup` within `spec/controllers`
  .rubocop_todo.yml
  spec/controllers/follower_accounts_controller_spec.rb
  spec/controllers/following_accounts_controller_spec.rb
  spec/controllers/oauth/authorized_applications_controller_spec.rb
  spec/controllers/oauth/tokens_controller_spec.rb
  spec/controllers/settings/imports_controller_spec.rb
Labels: testing, ruby

#28452 Change "Follow" to "Follow back" and "Mutual" when appropriate in web UI
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#28448 Clean up of `RSpec/LetSetup` within `api/`
  .rubocop_todo.yml
  spec/controllers/api/v1/accounts/statuses_controller_spec.rb
  spec/controllers/api/v1/filters_controller_spec.rb
  spec/controllers/api/v2/admin/accounts_controller_spec.rb
  spec/controllers/api/v2/filters/keywords_controller_spec.rb
  spec/controllers/api/v2/filters/statuses_controller_spec.rb
Labels: testing, ruby

#28445 Clean up of `RSpec/LetSetup` within `spec/services/activitypub`
  .rubocop_todo.yml
  spec/services/account_statuses_cleanup_service_spec.rb
  spec/services/activitypub/fetch_remote_status_service_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
  spec/services/activitypub/process_collection_service_spec.rb
Labels: testing, ruby

#28447 Clean up of `RSpec/LetSetup` within `spec/lib`
  .rubocop_todo.yml
  spec/lib/activitypub/activity/delete_spec.rb
  spec/lib/vacuum/applications_vacuum_spec.rb
  spec/lib/vacuum/preview_cards_vacuum_spec.rb
Labels: testing, ruby

#28464 Fix `RSpec/LetSetup` cop in auth controller specs
  .rubocop_todo.yml
  spec/controllers/auth/confirmations_controller_spec.rb
  spec/controllers/auth/passwords_controller_spec.rb
  spec/controllers/auth/sessions_controller_spec.rb
Labels: ruby, lint fix 💅

#28462 Clean up `tagged_with_*` Status specs, fix `RSpec/LetSetup` cop
  .rubocop_todo.yml
  spec/models/status_spec.rb
  spec/rails_helper.rb
Labels: testing, ruby

#28461 Fix `RSpec/LetSetup` cop in ap/fetch_featured_collection_service
  .rubocop_todo.yml
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
Labels: testing, ruby, rebase needed :construction:

#28469 Fix media attachment order of remote posts
  app/lib/activitypub/activity/create.rb
  app/models/status.rb
  spec/lib/activitypub/activity/create_spec.rb
Labels: bug

#28443 Convert signature verification specs to request specs
  spec/controllers/concerns/signature_verification_spec.rb
  spec/requests/signature_verification_spec.rb
Labels: testing, ruby

#28510 Replace our custom `compression-webpack-plugin` patch with the fixed upstream version
  .yarn/patches/compression-webpack-plugin-npm-6.1.1-3a2a65987e.patch
  package.json
  yarn.lock
Labels: dependencies, javascript

#28521 Fix random `NoMethodError` errors on cached `CustomFilter` objects
  app/models/custom_filter.rb
  app/models/custom_filter_keyword.rb
Labels: bug, backport

#28522 Change media to be hidden/blurred by default in report modal
  app/javascript/mastodon/components/media_attachments.jsx
  app/javascript/mastodon/features/report/components/status_check_box.jsx
Labels: ui, area/web interface
