Repository mastodon/mastodon, pull requests merged in 2023-03, with the labels that each got.

#21431 Allow streaming to connect to postgress with self-signed certs
  package.json
  streaming/index.js
  yarn.lock
Labels: deployment

#23960 Fix streaming API not being usable without `DATABASE_URL`
  streaming/index.js
Labels: bug

#23958 Fix pgBouncer resetting application name on every transaction
  config/database.yml
Labels: performance

#24121 Remove `bullet` and `active_record_query_trace` gems
  Gemfile
  Gemfile.lock
  config/environments/development.rb
Labels: dependencies

#24122 Refactor monkey-patching of `PrivateAddressCheck`
  app/lib/request.rb
  config/environments/development.rb
Labels: refactoring

#19723 Update profile link verification instructions
  config/locales/en.yml
Labels: ui

#24238 Add missing parenthesis
  app/javascript/mastodon/features/ui/components/compose_panel.jsx
Labels: bug

#24247 Change design of account rows in web UI
  app/javascript/mastodon/components/account.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#23944 Refactor styles to use logical properties for positioning
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/accounts.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/containers.scss
  app/javascript/styles/mastodon/emoji_picker.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/modal.scss
  app/javascript/styles/mastodon/polls.scss
  app/javascript/styles/mastodon/rich_text.scss
  app/javascript/styles/mastodon/rtl.scss
  app/javascript/styles/mastodon/statuses.scss
  app/javascript/styles/mastodon/tables.scss
  app/javascript/styles/mastodon/widgets.scss
Labels: refactoring
