Repository mastodon/mastodon, pull requests merged in 2024-03, with the labels that each got.

#29469 Fix regression in handling `select` elements in `packs/admin.tsx`
  app/javascript/packs/admin.tsx
Labels: bug

#29460 Improve `IpBlock` model test coverage
  spec/models/ip_block_spec.rb
Labels: testing, ruby

#26024 Add Kashubian to languages dropdown
  app/helpers/languages_helper.rb
Labels: i18n

#26634 Add Pennsylvania Dutch to languages dropdown
  app/helpers/languages_helper.rb
Labels: i18n

#27136 Add Vai to posting languages
  app/helpers/languages_helper.rb
Labels: i18n

#28630 Add Interlingue to available_locales
  config/initializers/i18n.rb
Labels: i18n, area/web interface

#29306 Fix follow suggestions potentially including silenced or blocked accounts
  app/models/account_suggestions/friends_of_friends_source.rb
  app/models/account_suggestions/similar_profiles_source.rb
  app/models/account_suggestions/source.rb
  spec/models/account_suggestions/friends_of_friends_source_spec.rb
  spec/models/account_suggestions/source_spec.rb
Labels: bug

#27115 Add Mohawk to posting languages
  app/helpers/languages_helper.rb
Labels: i18n

#29098 Add Jawi Malay to posting languages
  app/helpers/languages_helper.rb
Labels: i18n

#29520 Update `json-jwt` gem to fix CVE-2023-51774
  Gemfile.lock
Labels: dependencies, ruby

#29529 Fix interaction settings migration error when encountering no settings
  db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb
Labels: bug

#27434 Add nds locale to posting languages
  app/helpers/languages_helper.rb
Labels: i18n

#29530 Normalize idna domain before account unblock domain
  app/models/concerns/account/interactions.rb
  spec/models/concerns/account/interactions_spec.rb
Labels: to backport

#29537 Change icons in navigation panel to be filled when active in web UI
  app/javascript/mastodon/features/ui/components/column_link.jsx
  app/javascript/mastodon/features/ui/components/follow_requests_column_link.jsx
  app/javascript/mastodon/features/ui/components/list_panel.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/mastodon/features/ui/components/notifications_counter_icon.js
Labels: ui

#29533 Change action button to be last on profiles in web UI
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29433 Add notification policies and notification requests in web UI
  app/controllers/api/v1/notifications/requests_controller.rb
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/components/column_header.jsx
  app/javascript/mastodon/features/community_timeline/components/column_settings.jsx
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/mastodon/features/hashtag_timeline/components/column_settings.jsx
  app/javascript/mastodon/features/home_timeline/components/column_settings.tsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/notifications/components/checkbox_with_label.jsx
  app/javascript/mastodon/features/notifications/components/column_settings.jsx
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.jsx
  app/javascript/mastodon/features/notifications/components/notification_request.jsx
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/notifications/containers/filter_bar_container.js
  app/javascript/mastodon/features/notifications/index.jsx
  app/javascript/mastodon/features/notifications/request.jsx
  app/javascript/mastodon/features/notifications/requests.jsx
  app/javascript/mastodon/features/public_timeline/components/column_settings.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/notification_policy.js
  app/javascript/mastodon/reducers/notification_requests.js
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/utils/numbers.ts
  app/javascript/material-icons/400-24px/archive-fill.svg
  app/javascript/material-icons/400-24px/archive.svg
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/models/notification_request.rb
  config/routes.rb
  config/routes/api.rb
  spec/models/notification_policy_spec.rb
  spec/models/notification_request_spec.rb
Labels: ui, build-image

#29489 Convert request-based setup into factory setup in push/subscriptions request spec
  spec/requests/api/v1/push/subscriptions_spec.rb
Labels: testing, ruby

#29522 Change background color in web UI
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/basics.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#29104 Reduce `RSpec/ExampleLength` in CSP request spec
  spec/requests/content_security_policy_spec.rb
Labels: testing, ruby

#29319 Add basic coverage for `TagSearchService` class
  spec/services/tag_search_service_spec.rb
Labels: testing, ruby

#29304 Remove unneeded `type: :service` from spec/services files
  spec/services/account_search_service_spec.rb
  spec/services/account_statuses_cleanup_service_spec.rb
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
  spec/services/activitypub/fetch_featured_tags_collection_service_spec.rb
  spec/services/activitypub/fetch_remote_account_service_spec.rb
  spec/services/activitypub/fetch_remote_actor_service_spec.rb
  spec/services/activitypub/fetch_remote_key_service_spec.rb
  spec/services/activitypub/fetch_remote_status_service_spec.rb
  spec/services/activitypub/fetch_replies_service_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
  spec/services/activitypub/process_collection_service_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/activitypub/synchronize_followers_service_spec.rb
  spec/services/after_block_domain_from_account_service_spec.rb
  spec/services/after_block_service_spec.rb
  spec/services/app_sign_up_service_spec.rb
  spec/services/authorize_follow_service_spec.rb
  spec/services/backup_service_spec.rb
  spec/services/batched_remove_status_service_spec.rb
  spec/services/block_domain_service_spec.rb
  spec/services/block_service_spec.rb
  spec/services/bootstrap_timeline_service_spec.rb
  spec/services/clear_domain_media_service_spec.rb
  spec/services/delete_account_service_spec.rb
  spec/services/fan_out_on_write_service_spec.rb
  spec/services/favourite_service_spec.rb
  spec/services/fetch_link_card_service_spec.rb
  spec/services/fetch_oembed_service_spec.rb
  spec/services/fetch_remote_status_service_spec.rb
  spec/services/fetch_resource_service_spec.rb
  spec/services/follow_service_spec.rb
  spec/services/import_service_spec.rb
  spec/services/mute_service_spec.rb
  spec/services/notify_service_spec.rb
  spec/services/post_status_service_spec.rb
  spec/services/precompute_feed_service_spec.rb
  spec/services/process_mentions_service_spec.rb
  spec/services/purge_domain_service_spec.rb
  spec/services/reblog_service_spec.rb
  spec/services/reject_follow_service_spec.rb
  spec/services/remove_from_followers_service_spec.rb
  spec/services/remove_status_service_spec.rb
  spec/services/report_service_spec.rb
  spec/services/resolve_account_service_spec.rb
  spec/services/resolve_url_service_spec.rb
  spec/services/search_service_spec.rb
  spec/services/software_update_check_service_spec.rb
  spec/services/suspend_account_service_spec.rb
  spec/services/translate_status_service_spec.rb
  spec/services/unallow_domain_service_spec.rb
  spec/services/unblock_domain_service_spec.rb
  spec/services/unblock_service_spec.rb
  spec/services/unfollow_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/services/update_account_service_spec.rb
  spec/services/update_status_service_spec.rb
  spec/services/verify_link_service_spec.rb
Labels: testing, ruby

#29437 Use `before_all` block to setup `requests/cache_spec` data
  spec/rails_helper.rb
  spec/requests/cache_spec.rb
Labels: testing, ruby

#27602 Use `normalizes` on `CustomFilter#context` value
  app/models/custom_filter.rb
  spec/models/custom_filter_spec.rb
Labels: refactoring

#28956 Move `api/v2/filters/*` to request spec
  spec/requests/api/v2/filters/keywords_spec.rb
  spec/requests/api/v2/filters/statuses_spec.rb
Labels: testing, ruby

#29005 Accept extra args that we wont verify in `ap/activity/add_spec`
  spec/lib/activitypub/activity/add_spec.rb
Labels: testing, ruby

#28844 Move `pagination_max_id` and `pagination_since_id` into api/base controller
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/accounts/statuses_controller.rb
  app/controllers/api/v1/admin/accounts_controller.rb
  app/controllers/api/v1/admin/canonical_email_blocks_controller.rb
  app/controllers/api/v1/admin/domain_allows_controller.rb
  app/controllers/api/v1/admin/domain_blocks_controller.rb
  app/controllers/api/v1/admin/email_domain_blocks_controller.rb
  app/controllers/api/v1/admin/ip_blocks_controller.rb
  app/controllers/api/v1/admin/reports_controller.rb
  app/controllers/api/v1/admin/tags_controller.rb
  app/controllers/api/v1/admin/trends/links/preview_card_providers_controller.rb
  app/controllers/api/v1/blocks_controller.rb
  app/controllers/api/v1/bookmarks_controller.rb
  app/controllers/api/v1/crypto/encrypted_messages_controller.rb
  app/controllers/api/v1/domain_blocks_controller.rb
  app/controllers/api/v1/endorsements_controller.rb
  app/controllers/api/v1/favourites_controller.rb
  app/controllers/api/v1/followed_tags_controller.rb
  app/controllers/api/v1/lists/accounts_controller.rb
  app/controllers/api/v1/mutes_controller.rb
  app/controllers/api/v1/notifications_controller.rb
  app/controllers/api/v1/scheduled_statuses_controller.rb
  app/controllers/api/v1/timelines/base_controller.rb
Labels: refactoring, ruby

#28976 Use rails built-in `tag` methods in `TextFormatter.shortened_link`
  app/lib/text_formatter.rb
Labels: refactoring, ruby

#29006 Merge `api/v1/accounts/credentials` controller spec into existing request spec
  spec/controllers/api/v1/accounts/credentials_controller_spec.rb
  spec/requests/api/v1/accounts/credentials_spec.rb
Labels: testing, ruby

#28955 Readability clean up in `ImportVacuum` spec
  spec/lib/vacuum/imports_vacuum_spec.rb
Labels: testing, ruby

#28144 Use enum-generated scope for `IpBlock` in CLI
  app/models/ip_block.rb
  app/models/user.rb
  lib/mastodon/cli/ip_blocks.rb
Labels: refactoring, ruby

#28156 Use enum-generated `public_visibility` scope on Status
  app/models/concerns/account/statuses_search.rb
  app/models/concerns/status/search_concern.rb
  app/models/public_feed.rb
  app/models/status.rb
  spec/search/models/concerns/account/statuses_search_spec.rb
Labels: refactoring, ruby

#29588 Fix accounts not getting imported into redux store for some filtered notification types
  app/javascript/mastodon/actions/notifications.js
Labels: bug

#28914 Use `with_options` for shared option in `accounts#show` routing block
  config/routes.rb
Labels: refactoring, ruby

#29551 Fix back button appearing in column header unexpectedly in web UI
  app/javascript/mastodon/components/column_header.jsx
Labels: ui

#28157 Use `Account.activitypub` generated scope
  app/models/account.rb
  lib/mastodon/cli/accounts.rb
Labels: refactoring, ruby

#28360 Extract shared behavior methods in oauth feature spec
  spec/features/oauth_spec.rb
Labels: refactoring, ruby

#29413 Use inclusive range in `ActivityTracker#get`
  app/lib/activity_tracker.rb
Labels: bug, ruby

#29463 Remove unused `Account::Interactions#endorsed?` method
  app/models/concerns/account/interactions.rb
Labels: refactoring

#29601 Extract target account on list method in bulk import row service spec
  spec/services/bulk_import_row_service_spec.rb
Labels: testing

#29596 Add `include_pagination_headers` matcher to check `Link` header in api specs
  spec/requests/api/v1/blocks_spec.rb
  spec/requests/api/v1/bookmarks_spec.rb
  spec/requests/api/v1/favourites_spec.rb
  spec/requests/api/v1/followed_tags_spec.rb
  spec/requests/api/v1/mutes_spec.rb
  spec/requests/api/v1/notifications_spec.rb
  spec/requests/api/v1/timelines/home_spec.rb
  spec/requests/api/v1/timelines/public_spec.rb
  spec/requests/api/v1/timelines/tag_spec.rb
  spec/support/matchers/api_pagination.rb
Labels: testing, ruby

#29560 Move common module inclusion in sub classes to `ActivityPub::BaseController`
  app/controllers/activitypub/base_controller.rb
  app/controllers/activitypub/claims_controller.rb
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/followers_synchronizations_controller.rb
  app/controllers/activitypub/inboxes_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/activitypub/replies_controller.rb
  app/controllers/instance_actors_controller.rb
Labels: refactoring, ruby

#28680 Fix haml-lint `LineLength` cops in app/views/admin
  .haml-lint_todo.yml
  app/views/admin/account_actions/new.html.haml
  app/views/admin/accounts/index.html.haml
  app/views/admin/announcements/edit.html.haml
  app/views/admin/announcements/new.html.haml
  app/views/admin/custom_emojis/index.html.haml
  app/views/admin/custom_emojis/new.html.haml
  app/views/admin/domain_blocks/edit.html.haml
  app/views/admin/domain_blocks/new.html.haml
  app/views/admin/email_domain_blocks/index.html.haml
  app/views/admin/email_domain_blocks/new.html.haml
  app/views/admin/export_domain_allows/new.html.haml
  app/views/admin/export_domain_blocks/import.html.haml
  app/views/admin/export_domain_blocks/new.html.haml
  app/views/admin/follow_recommendations/show.html.haml
  app/views/admin/ip_blocks/index.html.haml
  app/views/admin/ip_blocks/new.html.haml
  app/views/admin/relationships/index.html.haml
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/show.html.haml
  app/views/admin/roles/_form.html.haml
  app/views/admin/settings/about/show.html.haml
  app/views/admin/settings/appearance/show.html.haml
  app/views/admin/settings/branding/show.html.haml
  app/views/admin/settings/content_retention/show.html.haml
  app/views/admin/settings/discovery/show.html.haml
  app/views/admin/settings/registrations/show.html.haml
  app/views/admin/statuses/index.html.haml
  app/views/admin/trends/links/index.html.haml
  app/views/admin/trends/links/preview_card_providers/index.html.haml
  app/views/admin/trends/statuses/_status.html.haml
  app/views/admin/trends/statuses/index.html.haml
  app/views/admin/trends/tags/index.html.haml
  app/views/admin/users/roles/show.html.haml
  app/views/admin/webhooks/_form.html.haml
  app/views/filters/_filter_fields.html.haml
  app/views/statuses_cleanup/show.html.haml
Labels: ruby, lint fix 💅

#29602 Add domain information to profiles in web UI
  app/javascript/mastodon/features/account/components/domain_pill.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/material-icons/400-24px/badge-fill.svg
  app/javascript/material-icons/400-24px/badge.svg
  app/javascript/material-icons/400-24px/globe-fill.svg
  app/javascript/material-icons/400-24px/globe.svg
  app/javascript/material-icons/400-24px/star-fill.svg
  app/javascript/material-icons/400-24px/star.svg
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29501 Convert `packs/public.jsx` to Typescript
  app/javascript/mastodon/components/relative_timestamp.tsx
  app/javascript/packs/public.jsx
  app/javascript/packs/public.tsx
Labels: typescript

#29462 Add diagnostic message for failure during CLI search deploy
  lib/mastodon/cli/search.rb
  spec/lib/mastodon/cli/search_spec.rb
Labels: bug, ruby

#29607 Fix `user_mailer.welcome.hashtags_recent_count` not having plural form
  app/views/application/mailer/_hashtag.html.haml
  app/views/user_mailer/welcome.text.erb
  config/locales/en.yml
Labels: i18n

#29619 Revert friends-of-friends follow recommendation query to using a CTE
  app/models/account_suggestions/friends_of_friends_source.rb
  spec/models/account_suggestions/friends_of_friends_source_spec.rb
Labels: performance, build-image

#29617 Remove unused `active_nav_class` helper method
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: rebase needed :construction:

#29646 Change “Notifications” settings page to “E-mail notifications”
  config/locales/en.yml
  config/navigation.rb
Labels: ui

#29648 Slightly increase font weight of favorite/boost numbers in detailed statuses
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29513 Add `BrowserDetection` model concern
  app/models/concerns/browser_detection.rb
  app/models/login_activity.rb
  app/models/session_activation.rb
Labels: refactoring, ruby

#29652 Change filtered icon from “archive” to “inventory 2”
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.jsx
  app/javascript/mastodon/features/notifications/request.jsx
  app/javascript/mastodon/features/notifications/requests.jsx
  app/javascript/material-icons/400-24px/archive-fill.svg
  app/javascript/material-icons/400-24px/archive.svg
  app/javascript/material-icons/400-24px/inventory_2-fill.svg
  app/javascript/material-icons/400-24px/inventory_2.svg
Labels: ui

#29499 Pull out full `li` element into admin/status_edits/status_edit partial
  app/views/admin/status_edits/_status_edit.html.haml
  app/views/admin/statuses/show.html.haml
Labels: refactoring

#29651 Fix emoji picker placement on limited-height viewports
  app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.jsx
Labels: ui

#29653 Fix emoji picker dropdown background and borders
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/emoji_picker.scss
Labels: ui

#29658 Fix icon and styling in browser notifications banner
  app/javascript/mastodon/features/notifications/components/column_settings.jsx
  app/javascript/mastodon/features/notifications/components/notifications_permission_banner.jsx
  app/javascript/material-icons/400-20px/settings-fill.svg
  app/javascript/material-icons/400-20px/settings.svg
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29659 Fix blockquote color in reply indicator
  app/javascript/styles/mastodon/rich_text.scss
Labels: ui

#29649 Fix “Explore” icon in navigation bar not being filled when selected
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
Labels: ui

#27511 Add notifications of severed relationships
  app/controllers/severed_relationships_controller.rb
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/notifications/components/relationships_severance_event.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/material-icons/400-24px/link_off-fill.svg
  app/javascript/material-icons/400-24px/link_off.svg
  app/models/account_relationship_severance_event.rb
  app/models/concerns/account/interactions.rb
  app/models/concerns/account/merging.rb
  app/models/notification.rb
  app/models/relationship_severance_event.rb
  app/models/severed_relationship.rb
  app/serializers/rest/account_relationship_severance_event_serializer.rb
  app/serializers/rest/notification_serializer.rb
  app/services/after_block_domain_from_account_service.rb
  app/services/block_domain_service.rb
  app/services/delete_account_service.rb
  app/services/notify_service.rb
  app/services/purge_domain_service.rb
  app/services/suspend_account_service.rb
  app/views/severed_relationships/index.html.haml
  config/locales/en.yml
  config/navigation.rb
  config/routes.rb
  db/migrate/20240312100644_create_relationship_severance_events.rb
  db/migrate/20240312105620_create_severed_relationships.rb
  db/migrate/20240320140159_create_account_relationship_severance_events.rb
  db/schema.rb
  lib/mastodon/cli/maintenance.rb
  spec/fabricators/account_relationship_severance_event_fabricator.rb
  spec/fabricators/relationship_severance_event_fabricator.rb
  spec/fabricators/severed_relationship_fabricator.rb
  spec/models/relationship_severance_event_spec.rb
  spec/models/severed_relationship_spec.rb
  spec/requests/severed_relationships_spec.rb
  spec/services/after_block_domain_from_account_service_spec.rb
  spec/services/block_domain_service_spec.rb
  spec/services/suspend_account_service_spec.rb
Labels: rebase needed :construction:

#29669 Change back button to always appear in advanced web UI
  app/javascript/mastodon/components/column_header.jsx
  app/javascript/mastodon/features/follow_requests/index.jsx
Labels: ui

#29597 Fix results/query in `api/v1/featured_tags/suggestions`
  app/controllers/api/v1/featured_tags/suggestions_controller.rb
  spec/fabricators/featured_tag_fabricator.rb
  spec/requests/api/v1/featured_tags/suggestions_spec.rb
Labels: bug, ruby, to backport

#29644 Change new modals to allow vertical scrolling
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29373 Remove setting for unfollow confirmation modal, and make it unconditional
  app/javascript/mastodon/containers/account_container.jsx
  app/javascript/mastodon/features/account_timeline/containers/header_container.jsx
  app/javascript/mastodon/features/directory/components/account_card.jsx
  app/javascript/mastodon/initial_state.js
  app/models/concerns/user/has_settings.rb
  app/models/user_settings.rb
  app/serializers/initial_state_serializer.rb
  app/views/settings/preferences/appearance/show.html.haml
Labels: ui

#28456 Add ability to reorder uploaded media before posting in web UI
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/features/compose/components/compose_form.jsx
  app/javascript/mastodon/features/compose/components/upload.jsx
  app/javascript/mastodon/features/compose/components/upload_form.jsx
  app/javascript/mastodon/features/compose/components/upload_progress.jsx
  app/javascript/mastodon/features/compose/containers/upload_container.js
  app/javascript/mastodon/features/compose/containers/upload_form_container.js
  app/javascript/mastodon/features/compose/containers/upload_progress_container.js
  app/javascript/mastodon/features/ui/components/focal_point_modal.jsx
  app/javascript/mastodon/reducers/compose.js
Labels: ui

#29732 Change out-of-band hashtags design in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29731 Change design of notification about lost connections in web UI
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/notifications/components/relationships_severance_event.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29706 Fix background and icon on notification requests in web UI
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.jsx
  app/javascript/mastodon/features/notifications/components/notification_request.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29599 Add `not_allowed` scope for `PreviewCardTrend`
  app/models/preview_card_trend.rb
  app/models/trends/links.rb
Labels: refactoring, ruby

#29752 Use `upsert_all` and `insert_all` to reduce back-and-forth in costly migrations
  db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb
  db/post_migrate/20240321160706_migrate_interaction_settings_to_policy_again.rb
Labels: performance

#29763 Fix column borders disappearing in advanced interface on low width viewports
  app/javascript/styles/mastodon/components.scss
Labels: ui

#27644 Rewrite markers reducer in Typescript
  app/javascript/mastodon/actions/markers.js
  app/javascript/mastodon/actions/markers.ts
  app/javascript/mastodon/api.ts
  app/javascript/mastodon/api_types/markers.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/markers.js
  app/javascript/mastodon/reducers/markers.ts
  app/javascript/mastodon/reducers/notifications.js
  app/serializers/rest/marker_serializer.rb
Labels: typescript

#27645 Rewrite PIP state in Typescript
  app/javascript/mastodon/actions/picture_in_picture.js
  app/javascript/mastodon/actions/picture_in_picture.ts
  app/javascript/mastodon/containers/status_container.jsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/picture_in_picture/components/header.jsx
  app/javascript/mastodon/features/picture_in_picture/components/header.tsx
  app/javascript/mastodon/features/picture_in_picture/index.jsx
  app/javascript/mastodon/features/picture_in_picture/index.tsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/picture_in_picture.js
  app/javascript/mastodon/reducers/picture_in_picture.ts
  app/javascript/mastodon/selectors/index.js
Labels: typescript

#29777 Fix notifications marker fetch
  app/javascript/mastodon/actions/markers.ts
Labels: bug

#29779 Fix language picker and privacy picker not having a backdrop filter
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29780 Fix props for `<Button>`
  app/javascript/mastodon/components/button.tsx
Labels: typescript

#29781 Fix `<RelativeTimestamp>` types
  app/javascript/mastodon/components/relative_timestamp.tsx
Labels: typescript

#29787 Fix logo pushing header buttons out of view on certain conditions in mobile layout
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29774 Remove global `boosts` state and convert boosts modal to Typescript
  app/javascript/mastodon/actions/boosts.js
  app/javascript/mastodon/components/visibility_icon.tsx
  app/javascript/mastodon/containers/status_container.jsx
  app/javascript/mastodon/features/notifications/containers/notification_container.js
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/status/containers/detailed_status_container.js
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/ui/components/boost_modal.jsx
  app/javascript/mastodon/features/ui/components/boost_modal.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/models/status.ts
  app/javascript/mastodon/reducers/boosts.js
  app/javascript/mastodon/reducers/index.ts
Labels: typescript

#29791 Handle `createAppAsyncThunk` rejected actions in the errors middleware
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/typed_functions.ts
Labels: typescript
