Repository mastodon/mastodon, pull requests merged in 2024-01, with the labels that each got.

#28548 Add wget to base Dockerfile
  Dockerfile
Labels: docker

#28558 Fix streaming API redirection ignoring the port of `streaming_api_base_url`
  app/controllers/api/v1/streaming_controller.rb
Labels: bug

#28218 Update `@typescript-eslint/parser` to version 6.17.0
  package.json
  yarn.lock
Labels: rebase needed :construction:

#28468 Add ability to require approval when users sign up using specific email domains
  app/controllers/admin/email_domain_blocks_controller.rb
  app/controllers/api/v1/admin/email_domain_blocks_controller.rb
  app/models/email_domain_block.rb
  app/models/user.rb
  app/serializers/rest/admin/email_domain_block_serializer.rb
  app/views/admin/email_domain_blocks/_email_domain_block.html.haml
  app/views/admin/email_domain_blocks/new.html.haml
  config/locales/en.yml
  db/migrate/20231222100226_add_allow_with_approval_to_email_domain_blocks.rb
  db/schema.rb
  spec/controllers/admin/email_domain_blocks_controller_spec.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/services/app_sign_up_service_spec.rb
Labels: moderation

#28561 Add `PAPERCLIP_ROOT_URL` to Content-Security-Policy when used
  app/lib/content_security_policy.rb
  spec/lib/content_security_policy_spec.rb
Labels: bug

#28585 Upgrade Redux packages
  .eslintrc.js
  app/javascript/mastodon/features/compose/containers/emoji_picker_dropdown_container.js
  app/javascript/mastodon/features/compose/containers/language_dropdown_container.js
  app/javascript/mastodon/features/getting_started/containers/announcements_container.js
  app/javascript/mastodon/features/home_timeline/index.jsx
  app/javascript/mastodon/features/list_adder/index.jsx
  app/javascript/mastodon/features/lists/index.jsx
  app/javascript/mastodon/features/notifications/index.jsx
  app/javascript/mastodon/features/report/comment.jsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/features/subscribed_languages_modal/index.jsx
  app/javascript/mastodon/features/ui/components/list_panel.jsx
  app/javascript/mastodon/features/ui/containers/status_list_container.js
  app/javascript/mastodon/reducers/accounts.ts
  app/javascript/mastodon/reducers/modal.ts
  app/javascript/mastodon/reducers/relationships.ts
  app/javascript/mastodon/selectors/accounts.ts
  app/javascript/mastodon/selectors/index.js
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/middlewares/loading_bar.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
  app/javascript/mastodon/store/typed_functions.ts
  config/webpack/rules/babel.js
  package.json
  yarn.lock
Labels: dependencies, javascript, typescript

#26015 Fix ISO code for Canadian French
  app/helpers/languages_helper.rb
  app/javascript/mastodon/locales/fr-CA.json
  config/initializers/i18n.rb
  config/locales/activerecord.fr-CA.yml
  config/locales/devise.fr-CA.yml
  config/locales/doorkeeper.fr-CA.yml
  config/locales/fr-CA.yml
  config/locales/simple_form.fr-CA.yml
  db/migrate/20240109103012_fix_canadian_french_locale.rb
  db/schema.rb
  lib/tasks/tests.rake
Labels: i18n, rebase needed :construction:

#28672 Add a system spec for the `/share` endpoint
  spec/system/share_entrypoint_spec.rb
Labels: testing

#25369 Use Sidekiq `fake!` instead of `inline!` in specs
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/admin/domain_blocks_controller_spec.rb
  spec/controllers/admin/resets_controller_spec.rb
  spec/controllers/api/v1/conversations_controller_spec.rb
  spec/controllers/api/v1/statuses/reblogs_controller_spec.rb
  spec/controllers/auth/sessions_controller_spec.rb
  spec/controllers/concerns/user_tracking_concern_spec.rb
  spec/controllers/disputes/appeals_controller_spec.rb
  spec/controllers/settings/deletes_controller_spec.rb
  spec/controllers/settings/exports_controller_spec.rb
  spec/features/admin/accounts_spec.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/lib/activitypub/activity/delete_spec.rb
  spec/lib/activitypub/activity/move_spec.rb
  spec/models/admin/account_action_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/featured_tags_spec.rb
  spec/requests/api/v1/notifications_spec.rb
  spec/requests/api/v1/statuses/favourites_spec.rb
  spec/requests/api/v1/timelines/home_spec.rb
  spec/search/models/concerns/account/statuses_search_spec.rb
  spec/services/activitypub/fetch_remote_status_service_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
  spec/services/authorize_follow_service_spec.rb
  spec/services/batched_remove_status_service_spec.rb
  spec/services/block_domain_service_spec.rb
  spec/services/block_service_spec.rb
  spec/services/bulk_import_service_spec.rb
  spec/services/delete_account_service_spec.rb
  spec/services/fan_out_on_write_service_spec.rb
  spec/services/favourite_service_spec.rb
  spec/services/follow_service_spec.rb
  spec/services/import_service_spec.rb
  spec/services/mute_service_spec.rb
  spec/services/notify_service_spec.rb
  spec/services/reblog_service_spec.rb
  spec/services/reject_follow_service_spec.rb
  spec/services/remove_from_followers_service_spec.rb
  spec/services/remove_status_service_spec.rb
  spec/services/report_service_spec.rb
  spec/services/resolve_account_service_spec.rb
  spec/services/suspend_account_service_spec.rb
  spec/services/unallow_domain_service_spec.rb
  spec/services/unblock_service_spec.rb
  spec/services/unfollow_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/services/update_account_service_spec.rb
  spec/services/update_status_service_spec.rb
  spec/system/new_statuses_spec.rb
  spec/workers/backup_worker_spec.rb
  spec/workers/move_worker_spec.rb
  spec/workers/poll_expiration_notify_worker_spec.rb
Labels: testing, ruby

#18482 Fix Undo Announce activity is not sent, when not followed by the reblogged post author
  app/lib/status_reach_finder.rb
  app/services/reblog_service.rb
  spec/lib/activitypub/tag_manager_spec.rb
  spec/services/reblog_service_spec.rb
  spec/services/remove_status_service_spec.rb
Labels: bug, to backport

#28719 Use rubygems released version of `omniauth-cas` gem
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#28732 Fix sign-up restrictions based on email addresses not being enforced
  app/models/user.rb
Labels: bug

#28608 Fix registrations not checking MX records for email domain blocks requiring approval
  app/models/user.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/services/app_sign_up_service_spec.rb
Labels: bug

#28735 Rename and refactor `User#confirm!` to `User#mark_email_as_confirmed!`
  app/controllers/admin/confirmations_controller.rb
  app/models/concerns/user/omniauthable.rb
  app/models/user.rb
  lib/mastodon/cli/accounts.rb
  spec/features/oauth_spec.rb
  spec/models/user_spec.rb
  spec/policies/user_policy_spec.rb
Labels: refactoring, ruby

#28775 Fix various icon alignment issues
  app/javascript/styles/mastodon/components.scss
Labels: ui

#28289 Order by sql in `CLI::Maintenance` task
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#27828 Streaming: replace npmlog with pino & pino-http
  streaming/.eslintrc.js
  streaming/index.js
  streaming/logging.js
  streaming/package.json
  yarn.lock
Labels: streaming

#28801 Add rate-limit of TOTP authentication attempts at controller level
  app/controllers/auth/sessions_controller.rb
  app/controllers/concerns/auth/two_factor_authentication_concern.rb
  config/locales/en.yml
  spec/controllers/auth/sessions_controller_spec.rb
Labels: to backport

#28816 Fix processing of compacted single-item JSON-LD collections
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/fetch_replies_service.rb
  app/services/activitypub/synchronize_followers_service.rb
  app/services/keys/query_service.rb
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
  spec/services/activitypub/fetch_replies_service_spec.rb
Labels: bug, activitypub, to backport

#28823 Fix error when processing remote files with unusually long names
  lib/paperclip/response_with_limit_adapter.rb
Labels: bug, to backport

#28834 Fix duplicate and missing keys in search popout component in web UI
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/features/compose/components/search.jsx
Labels: bug

#28825 Streaming: Move more methods to the utils from the main file
  streaming/index.js
  streaming/utils.js
Labels: streaming

#28838 docs: update FEDERATION.md to more closely follow FEP conventions.
  FEDERATION.md
Labels: activitypub

#28822 Add notification email on invalid second authenticator
  app/controllers/auth/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/failed_2fa.html.haml
  app/views/user_mailer/failed_2fa.text.erb
  config/locales/en.yml
  spec/controllers/auth/sessions_controller_spec.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
Labels: security

#28876 Fix search form re-rendering spuriously in web UI
  app/javascript/mastodon/features/compose/containers/search_container.js
Labels: performance

#28693 Add annual reports for accounts
  app/controllers/api/v1/annual_reports_controller.rb
  app/lib/annual_report.rb
  app/lib/annual_report/archetype.rb
  app/lib/annual_report/commonly_interacted_with_accounts.rb
  app/lib/annual_report/most_reblogged_accounts.rb
  app/lib/annual_report/most_used_apps.rb
  app/lib/annual_report/percentiles.rb
  app/lib/annual_report/source.rb
  app/lib/annual_report/time_series.rb
  app/lib/annual_report/top_hashtags.rb
  app/lib/annual_report/top_statuses.rb
  app/lib/annual_report/type_distribution.rb
  app/models/generated_annual_report.rb
  app/presenters/annual_reports_presenter.rb
  app/serializers/rest/annual_report_serializer.rb
  app/serializers/rest/annual_reports_serializer.rb
  app/workers/generate_annual_report_worker.rb
  app/workers/scheduler/indexing_scheduler.rb
  config/routes/api.rb
  db/migrate/20240111033014_create_generated_annual_reports.rb
  db/schema.rb
Labels: api, build-image

#27792 Add confirmation when redirecting logged-out requests to permalink
  app/controllers/concerns/web_app_controller_concern.rb
  app/controllers/redirect/accounts_controller.rb
  app/controllers/redirect/base_controller.rb
  app/controllers/redirect/statuses_controller.rb
  app/javascript/styles/mastodon/containers.scss
  app/lib/permalink_redirector.rb
  app/views/redirects/show.html.haml
  config/locales/en.yml
  config/routes.rb
Labels: ui

#28862 Fix `Rails/WhereExists` cop in app/lib
  .rubocop_todo.yml
  app/lib/activitypub/activity/create.rb
  app/lib/delivery_failure_tracker.rb
  app/lib/feed_manager.rb
  app/lib/suspicious_sign_in_detector.rb
Labels: rebase needed :construction:

#28881 Fix wrong colors on compose form in light mode in web UI
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon-light/variables.scss
Labels: bug, ui

#26527 Fix process of receiving posts with bearcaps is not working
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/parser/status_parser.rb
Labels: activitypub

#28902 Fix redirect confirmation for accounts
  app/controllers/redirect/accounts_controller.rb
Labels: bug

#28903 Add tests for redirect confirmations
  spec/features/redirections_spec.rb
Labels: testing

#28904 Add tests for processing statuses using bearcap URIs
  spec/lib/activitypub/activity/create_spec.rb
Labels: testing, activitypub

#28361 Reduce factory creation in `spec/models/account_statuses_cleanup_policy`
  spec/models/account_statuses_cleanup_policy_spec.rb
Labels: refactoring, ruby

#28281 Extract helper methods for db connection and table existence check in `CLI::Maintenance` task
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#28833 Refactor conversations components in web UI
  app/javascript/mastodon/features/direct_timeline/components/conversation.jsx
  app/javascript/mastodon/features/direct_timeline/components/conversations_list.jsx
  app/javascript/mastodon/features/direct_timeline/containers/conversation_container.js
  app/javascript/mastodon/features/direct_timeline/containers/conversations_list_container.js
  app/javascript/mastodon/features/direct_timeline/index.jsx
Labels: refactoring

#28379 Update paperclip and climate_control gems
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#28420 Fix `Style/GuardClause` cop in app/controllers
  .rubocop_todo.yml
  app/controllers/admin/confirmations_controller.rb
  app/controllers/auth/confirmations_controller.rb
  app/controllers/auth/passwords_controller.rb
  app/controllers/settings/two_factor_authentication/webauthn_credentials_controller.rb
Labels: ruby, lint fix 💅

#28747 Refactor: fix streaming postgresql and redis typing issues
  streaming/index.js
Labels: streaming

#28322 Handle CLI failure exit status at the top-level script
  .rubocop.yml
  bin/tootctl
  lib/mastodon/cli/accounts.rb
  lib/mastodon/cli/base.rb
  lib/mastodon/cli/cache.rb
  lib/mastodon/cli/domains.rb
  lib/mastodon/cli/email_domain_blocks.rb
  lib/mastodon/cli/emoji.rb
  lib/mastodon/cli/federation.rb
  lib/mastodon/cli/feeds.rb
  lib/mastodon/cli/ip_blocks.rb
  lib/mastodon/cli/maintenance.rb
  lib/mastodon/cli/media.rb
  lib/mastodon/cli/progress_helper.rb
  lib/mastodon/cli/search.rb
  lib/mastodon/cli/statuses.rb
  lib/mastodon/cli/upgrade.rb
  spec/lib/mastodon/cli/accounts_spec.rb
  spec/lib/mastodon/cli/cache_spec.rb
  spec/lib/mastodon/cli/email_domain_blocks_spec.rb
  spec/lib/mastodon/cli/feeds_spec.rb
  spec/lib/mastodon/cli/ip_blocks_spec.rb
  spec/lib/mastodon/cli/main_spec.rb
  spec/lib/mastodon/cli/maintenance_spec.rb
  spec/lib/mastodon/cli/media_spec.rb
  spec/lib/mastodon/cli/search_spec.rb
  spec/lib/mastodon/cli/statuses_spec.rb
Labels: refactoring, ruby

#28964 Remove unused l18n messages
  app/javascript/mastodon/features/compose/components/poll_form.jsx
  app/javascript/mastodon/locales/en.json
Labels: i18n

#29017 Fix follow recommendations for less used languages
  app/models/account_summary.rb
Labels: bug

#29015 Change materialized views to be refreshed concurrently to avoid locks
  app/models/account_summary.rb
  app/models/follow_recommendation.rb
  db/migrate/20210322164601_create_account_summaries.rb
  db/migrate/20210505174616_update_follow_recommendations_to_version_2.rb
  db/migrate/20211213040746_update_account_summaries_to_version_2.rb
  db/migrate/20230818141056_create_global_follow_recommendations.rb
  db/post_migrate/20230818142253_drop_follow_recommendations.rb
Labels: performance
