Repository mastodon/mastodon, pull requests merged in 2024-06, with the labels that each got.

#28102 Add libvirt provider parameters to Vagrant
  Vagrantfile
Labels: area/dev environment

#30090 Add support for libvips in addition to ImageMagick
  .devcontainer/Dockerfile
  .github/actions/setup-ruby/action.yml
  .github/workflows/test-ruby.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/lib/admin/metrics/dimension/software_versions_dimension.rb
  app/models/concerns/attachmentable.rb
  app/models/preview_card.rb
  config/application.rb
  config/initializers/vips.rb
  lib/paperclip/blurhash_transcoder.rb
  lib/paperclip/color_extractor.rb
  lib/paperclip/vips_lazy_thumbnail.rb
  spec/fixtures/files/monochrome.png
  spec/models/media_attachment_spec.rb
Labels: performance

#30525 Change counters to be displayed on profile timelines in web UI
  app/javascript/mastodon/features/account_timeline/index.jsx
Labels: ui

#30381 Add timeline of public posts about a trending link to REST API
  app/controllers/api/v1/timelines/link_controller.rb
  app/models/link_feed.rb
  config/routes/api.rb
  spec/requests/api/v1/timelines/link_spec.rb
Labels: api

#30574 Run as root in devcontainer from vscode
  .devcontainer/devcontainer.json
Labels: area/dev environment

#30573 Use corepack yarn in `bin/setup`
  bin/setup
Labels: area/dev environment

#30581 Provide richer failure information in `bin/setup`
  bin/setup
Labels: area/dev environment

#30536 Restore `verbose` option to media remove cli
  lib/mastodon/cli/media.rb
Labels: bug, backport

#30597 Improve handling of libvips failures
  lib/paperclip/blurhash_transcoder.rb
  lib/paperclip/color_extractor.rb
  lib/paperclip/vips_lazy_thumbnail.rb
Labels: bug

#30582 Doc updates for Docker/devcontainers/codespace
  .devcontainer/Dockerfile
  .devcontainer/codespaces/devcontainer.json
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  README.md
Labels: area/dev environment

#30585 Add Specs for Scheduled Status Model Validations
  spec/models/scheduled_status_spec.rb
Labels: testing, ruby

#30378 Use correct params in `v1/admin/domain_allows` spec
  spec/requests/api/v1/admin/domain_allows_spec.rb
Labels: testing, refactoring

#30379 Use correct params in `settings/preferences/appearance` spec
  spec/controllers/settings/preferences/appearance_controller_spec.rb
Labels: testing, refactoring

#29928 Extract method to generate series of days in measure sql classes
  app/lib/admin/metrics/measure/instance_accounts_measure.rb
  app/lib/admin/metrics/measure/instance_followers_measure.rb
  app/lib/admin/metrics/measure/instance_follows_measure.rb
  app/lib/admin/metrics/measure/instance_media_attachments_measure.rb
  app/lib/admin/metrics/measure/instance_reports_measure.rb
  app/lib/admin/metrics/measure/instance_statuses_measure.rb
  app/lib/admin/metrics/measure/new_users_measure.rb
  app/lib/admin/metrics/measure/opened_reports_measure.rb
  app/lib/admin/metrics/measure/query_helper.rb
  app/lib/admin/metrics/measure/resolved_reports_measure.rb
  app/lib/admin/metrics/measure/tag_servers_measure.rb
Labels: refactoring

#29667 Remove duplicate fabricator validity checks
  spec/models/import_spec.rb
  spec/models/poll_spec.rb
Labels: testing

#29936 Add expired/revoked scopes for doorkeeper models via extension modules
  app/lib/access_grant_extension.rb
  app/lib/access_token_extension.rb
  app/lib/vacuum/access_tokens_vacuum.rb
  app/models/web/push_subscription.rb
  config/application.rb
Labels: refactoring

#30380 Extract `PERMITTED_PARAMS` constant from `admin/domain_blocks` controller
  app/controllers/admin/domain_blocks_controller.rb
Labels: testing, refactoring

#30598 Fix cutoff of instance name
  app/javascript/styles/mastodon/forms.scss
Labels: bug, ui, area/web interface

#30653 Fix duplicate `@context` attribute in user export
  app/services/backup_service.rb
  spec/services/backup_service_spec.rb
Labels: bug, to backport

#30670 Fix a few visual glitches with link previews in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug

#30675 Disable `consistent-return` eslint rule for Typescript files
  .eslintrc.js
Labels: typescript, lint fix 💅

#30685 Fix limit handling in grouped notifications CTE
  app/models/notification.rb
Labels: bug, performance

#30521 Add author links on the explore page in web UI
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/actions/trends.js
  app/javascript/mastodon/components/more_from_author.jsx
  app/javascript/mastodon/features/explore/components/author_link.jsx
  app/javascript/mastodon/features/explore/components/story.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#30672 Remove bundler-audit ignore config
  .bundler-audit.yml
  .github/workflows/bundler-audit.yml
Labels: pipeline, area/dev environment

#30688 Fix pagination attributes not being returned in ungroupable-only pages
  app/serializers/rest/notification_group_serializer.rb
  spec/requests/api/v2_alpha/notifications_spec.rb
Labels: bug

#30571 Build libvips from source in Dockerfile
  Dockerfile
Labels: docker

#30692 Migrate `form_tag` to `form_with` in admin and auth views
  app/views/admin/accounts/index.html.haml
  app/views/admin/action_logs/index.html.haml
  app/views/admin/custom_emojis/index.html.haml
  app/views/admin/follow_recommendations/show.html.haml
  app/views/admin/instances/index.html.haml
  app/views/admin/reports/_actions.html.haml
  app/views/admin/reports/actions/preview.html.haml
  app/views/admin/reports/index.html.haml
  app/views/admin/trends/links/index.html.haml
  app/views/admin/trends/statuses/index.html.haml
  app/views/auth/confirmations/captcha.html.haml
  app/views/mail_subscriptions/show.html.haml
  app/views/oauth/authorizations/new.html.haml
Labels: refactoring

#30693 Fix (relax) remaining `RSpec/*` cops
  .rubocop/rspec.yml
  .rubocop_todo.yml
Labels: lint fix 💅

#30694 Fix `Style/GlobalStdStream` cop in environments/* files
  config/environments/development.rb
  config/environments/production.rb
Labels: lint fix 💅

#30695 Fix `Style/NilLambda` cop in paperclip initializer
  config/initializers/paperclip.rb
Labels: lint fix 💅

#30696 Change sidebar text in web UI
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/features/ui/components/sign_in_banner.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29868 Convert notifications policies frontend code to Typescript
  app/javascript/mastodon/actions/notification_policies.ts
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/api/notification_policies.ts
  app/javascript/mastodon/api_types/notification_policies.ts
  app/javascript/mastodon/features/notifications/components/column_settings.jsx
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.jsx
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.tsx
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/models/notification_policy.ts
  app/javascript/mastodon/reducers/notification_policy.js
  app/javascript/mastodon/reducers/notification_policy.ts
  app/serializers/rest/notification_policy_serializer.rb
Labels: typescript

#30569 Build ffmpeg from source in Dockerfile
  Dockerfile
Labels: docker

#30753 Fix SQL error in admin measures API
  app/lib/admin/metrics/measure/query_helper.rb
  spec/requests/api/v1/admin/measures_spec.rb
Labels: bug

#30776 Add `group_key` attribute to `NotificationSerializer`
  app/serializers/rest/notification_serializer.rb
Labels: api

#30777 Convert `disconnectTimeline` and `timelineDelete` actions to Typescript
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/actions/timelines_typed.ts
  app/javascript/mastodon/features/account_timeline/index.jsx
  app/javascript/mastodon/reducers/compose.js
  app/javascript/mastodon/reducers/contexts.js
  app/javascript/mastodon/reducers/modal.ts
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/mastodon/reducers/picture_in_picture.ts
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/mastodon/reducers/timelines.js
Labels: typescript

#30779 Fix missing `account_warning` delegation in `NotificationGroup`
  app/models/notification_group.rb
Labels: bug

#30058 Fix `Style/ClassEqualityComparison` cop
  .rubocop_todo.yml
  app/helpers/jsonld_helper.rb
  app/serializers/activitypub/outbox_serializer.rb
Labels: lint fix 💅

#30697 Remove exclusion for `Rails/LexicallyScopedActionFilter` cop
  .rubocop/rails.yml
  app/controllers/auth/registrations_controller.rb
Labels: lint fix 💅

#30691 Added check for STATSD_ADDR setting to emit a warning and proceed rather than crashing if the address is unreachable
  config/initializers/statsd.rb
Labels: to backport

#30837 Fix API requests after #30818
  app/javascript/mastodon/api/accounts.ts
  app/javascript/mastodon/api/interactions.ts
  app/javascript/mastodon/api/notification_policies.ts
Labels: bug

#30803 Fix account search results
  app/services/account_search_service.rb
Labels: build-image, area/search

#30833 Fix `Rails/ReversibleMigration` cop for `remove`
  db/migrate/20170520145338_change_language_filter_to_opt_out.rb
Labels: lint fix 💅

#30835 Fix `Rails/ReversibleMigration` cop for `change_column`
  db/migrate/20160223164502_make_uris_nullable_in_statuses.rb
  db/migrate/20170322143850_change_primary_key_to_bigint_on_statuses.rb
  db/migrate/20170609145826_remove_default_language_from_statuses.rb
Labels: lint fix 💅

#30829 Convert `<Directory>` to Typescript / function component
  app/javascript/mastodon/actions/directory.js
  app/javascript/mastodon/actions/directory.ts
  app/javascript/mastodon/api/directory.ts
  app/javascript/mastodon/features/directory/components/account_card.jsx
  app/javascript/mastodon/features/directory/components/account_card.tsx
  app/javascript/mastodon/features/directory/index.jsx
  app/javascript/mastodon/features/directory/index.tsx
  app/javascript/mastodon/reducers/user_lists.js
Labels: typescript

#30754 Add hover cards in web UI
  app/javascript/hooks/useLinks.ts
  app/javascript/hooks/useTimeout.ts
  app/javascript/mastodon/components/account_bio.tsx
  app/javascript/mastodon/components/account_fields.tsx
  app/javascript/mastodon/components/follow_button.tsx
  app/javascript/mastodon/components/hover_card_account.tsx
  app/javascript/mastodon/components/hover_card_controller.tsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_content.jsx
  app/javascript/mastodon/features/explore/components/author_link.jsx
  app/javascript/mastodon/features/explore/components/card.jsx
  app/javascript/mastodon/features/home_timeline/components/inline_follow_suggestions.jsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/status/components/detailed_status.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/components.scss
Labels: ui

#30849 Convert `<ColumnHeader>` to Typescript
  app/javascript/mastodon/components/column_header.jsx
  app/javascript/mastodon/components/column_header.tsx
  app/javascript/mastodon/features/directory/index.tsx
  app/javascript/mastodon/features/ui/components/column_loading.tsx
Labels: refactoring, typescript

#30284 Use flatware to parallelize CI specs
  .github/workflows/test-ruby.yml
  Gemfile
  Gemfile.lock
  bin/flatware
  spec/flatware_helper.rb
Labels: performance, testing

#30846 Change `author_account` to be `authors` in REST API
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/actions/trends.js
  app/javascript/mastodon/api_types/statuses.ts
  app/javascript/mastodon/features/explore/components/author_link.jsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/status/components/card.jsx
  app/models/preview_card.rb
  app/serializers/rest/preview_card_serializer.rb
Labels: api

#30864 Fix follow button in hover cards not working when signed out in web UI
  app/javascript/mastodon/components/follow_button.tsx
Labels: ui
