Repository mastodon/mastodon, pull requests merged in 2024-10, with the labels that each got.

#32188 Use account display name for pretend blog example in attribution area
  app/views/settings/verifications/show.html.haml
Labels: to backport

#32179 Fix follow notifications from streaming being grouped
  app/javascript/mastodon/actions/notification_groups.ts
  app/javascript/mastodon/reducers/notification_groups.ts
Labels: to backport

#32181 Avoid `id` duplication conflict with main navigation from settings profile link
  app/views/settings/shared/_profile_navigation.html.haml
  config/navigation.rb
Labels: to backport

#32153 Improve alignment of icons on admin roles list
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/tables.scss
Labels: ui, to backport

#32187 Add `date_range` view helper
  app/helpers/admin/dashboard_helper.rb
  app/views/admin/dashboard/index.html.haml
  app/views/admin/instances/show.html.haml
  app/views/admin/tags/show.html.haml
Labels: to backport

#31203 Remove `WebfingerHelper` module & move usage inline
  app/helpers/webfinger_helper.rb
  app/models/remote_follow.rb
  app/services/activitypub/fetch_remote_actor_service.rb
  app/services/resolve_account_service.rb
Labels: refactoring, ruby

#30767 Use `module: :users` in routes/admin section
  config/routes/admin.rb
Labels: refactoring

#32176 Remove explicit `put` action in settings forms
  app/views/settings/applications/show.html.haml
  app/views/settings/preferences/appearance/show.html.haml
  app/views/settings/preferences/notifications/show.html.haml
  app/views/settings/preferences/other/show.html.haml
  app/views/settings/privacy/show.html.haml
  app/views/settings/profiles/show.html.haml
  app/views/settings/verifications/show.html.haml
Labels: to backport

#32159 Fix nav item active highlight for some paths
  config/navigation.rb
Labels: bug, ui, to backport

#32155 Only show email domain blocks MX table when some found
  app/views/admin/email_domain_blocks/new.html.haml
Labels: bug, refactoring, ruby, to backport

#32151 Extract constants for header and avatar geometry
  app/models/concerns/account/avatar.rb
  app/models/concerns/account/header.rb
  app/views/settings/profiles/show.html.haml
Labels: refactoring, ruby, to backport

#31161 Fix unneeded requests to blocked domains when receiving relayed signed activities from them
  app/services/activitypub/process_collection_service.rb
Labels: to backport

#32147 Fix broken border on applications list
  app/views/settings/applications/index.html.haml
  app/views/settings/applications/show.html.haml
Labels: ui, to backport

#32137 Adjust spacing on setting sub-nav items when below mobile size
  app/javascript/styles/mastodon/admin.scss
Labels: ui, accessibility, to backport

#32201 Avoid repeated icon stack in settings sidebar
  config/navigation.rb
Labels: ui, to backport

#30836 Fix `Rails/CreateTableWithTimestamps` cop
  db/migrate/.rubocop.yml
  db/migrate/20170508230434_create_conversation_mutes.rb
  db/migrate/20170823162448_create_status_pins.rb
  db/migrate/20171116161857_create_list_accounts.rb
  db/migrate/20180929222014_create_account_conversations.rb
  db/migrate/20181007025445_create_pghero_space_stats.rb
  db/migrate/20190103124649_create_scheduled_statuses.rb
  db/migrate/20220824233535_create_status_trends.rb
  db/migrate/20221006061337_create_preview_card_trends.rb
Labels: lint fix 💅

#29215 Ignore error if mentioned account was not processable
  app/lib/activitypub/activity/create.rb
  app/workers/mention_resolve_worker.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/workers/mention_resolve_worker_spec.rb
Labels: to backport

#32206 Support /.well-known/host-meta.json
  app/controllers/well_known/host_meta_controller.rb
  config/routes.rb
  spec/requests/well_known/host_meta_spec.rb
  spec/routing/well_known_routes_spec.rb
Labels: to backport

#32212 Expand coverage for `Export` utility class
  spec/fabricators/account_domain_block_fabricator.rb
  spec/models/export_spec.rb
Labels: to backport

#32208 Extract `WebPushRequest` from push notification worker and subscription
  app/lib/web_push_request.rb
  app/models/web/push_subscription.rb
  app/workers/web/push_notification_worker.rb
  spec/workers/web/push_notification_worker_spec.rb
Labels: to backport

#32199 More link/button conversion across views
  app/views/admin/accounts/show.html.haml
  app/views/admin/instances/show.html.haml
  app/views/admin/invites/index.html.haml
  app/views/admin/reports/_actions.html.haml
  app/views/admin/reports/show.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/settings/exports/show.html.haml
  app/views/settings/two_factor_authentication/otp_authentication/show.html.haml
  app/views/settings/two_factor_authentication_methods/index.html.haml
Labels: refactoring, ruby, to backport

#32136 Add `relevant_params` to ReportFilter (matches account filter)
  app/models/report_filter.rb
  spec/models/report_filter_spec.rb
Labels: bug, refactoring, ruby, to backport

#32127 Provide `use_path` to qr generator for svg data size reduction
  app/views/settings/two_factor_authentication/confirmations/new.html.haml
  spec/controllers/settings/two_factor_authentication/confirmations_controller_spec.rb
Labels: ui, performance, to backport

#32217 Fix media uploads in composer appearing over search results in advanced interface
  app/javascript/styles/mastodon/components.scss
Labels: to backport, area/web interface

#32221 Fix editing description of media uploads with custom thumbnails
  app/javascript/mastodon/reducers/compose.js
Labels: bug, to backport, area/web interface

#32109 Enable hostname config for all system specs
  spec/rails_helper.rb
  spec/system/invites_spec.rb
Labels: testing, ruby

#32116 Clean up labels on development application form
  app/helpers/application_helper.rb
  app/models/session_activation.rb
  app/views/settings/applications/_form.html.haml
Labels: ui, refactoring, ruby, to backport

#32119 Add `copyable_input` helper method to wrap shared options
  app/helpers/application_helper.rb
  app/views/admin/invites/_invite.html.haml
  app/views/invites/_invite.html.haml
  app/views/oauth/authorizations/show.html.haml
  app/views/settings/verifications/show.html.haml
Labels: refactoring, ruby, to backport

#32178 Move admin action log type list generation to helper
  app/helpers/admin/action_logs_helper.rb
  app/views/admin/action_logs/index.html.haml
Labels: ui, to backport

#32240 Fix recently-broken admin interface buttons
  app/javascript/styles/mastodon/forms.scss
  app/views/admin/accounts/_buttons.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/instances/show.html.haml
  app/views/admin/invites/index.html.haml
  app/views/admin/reports/_actions.html.haml
  app/views/admin/reports/show.html.haml
  app/views/disputes/strikes/show.html.haml
  app/views/settings/exports/show.html.haml
  app/views/settings/two_factor_authentication/otp_authentication/show.html.haml
  app/views/settings/two_factor_authentication_methods/index.html.haml
Labels: bug

#30532 Rename transformer constant in sanitizer
  lib/sanitize_ext/sanitize_config.rb
Labels: refactoring

#30531 Rename preloaded models constant in cli media
  lib/mastodon/cli/media.rb
Labels: refactoring

#32241 Fix Content-Security-Policy when using sso-redirect
  app/controllers/concerns/web_app_controller_concern.rb
Labels: bug, to backport

#32086 Use `async_count` in more view locations
  app/controllers/admin/announcements_controller.rb
  app/controllers/admin/disputes/appeals_controller.rb
  app/controllers/admin/trends/links/preview_card_providers_controller.rb
  app/controllers/admin/trends/tags_controller.rb
  app/views/admin/announcements/index.html.haml
  app/views/admin/disputes/appeals/index.html.haml
  app/views/admin/trends/links/preview_card_providers/index.html.haml
  app/views/admin/trends/tags/index.html.haml
Labels: performance, ruby, to backport

#32098 Reduce factory usage across `spec/services` area
  spec/services/account_statuses_cleanup_service_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/authorize_follow_service_spec.rb
  spec/services/batched_remove_status_service_spec.rb
  spec/services/block_service_spec.rb
  spec/services/bulk_import_service_spec.rb
  spec/services/favourite_service_spec.rb
  spec/services/follow_service_spec.rb
  spec/services/process_mentions_service_spec.rb
  spec/services/reject_follow_service_spec.rb
  spec/services/remove_from_followers_service_spec.rb
  spec/services/remove_status_service_spec.rb
  spec/services/report_service_spec.rb
  spec/services/resolve_account_service_spec.rb
  spec/services/resolve_url_service_spec.rb
  spec/services/translate_status_service_spec.rb
  spec/services/unblock_domain_service_spec.rb
  spec/services/unblock_service_spec.rb
  spec/services/unfollow_service_spec.rb
  spec/services/update_account_service_spec.rb
  spec/services/update_status_service_spec.rb
Labels: performance, testing, refactoring, pipeline, to backport

#32256 Add coverage for missing status scenario in NotificationMailer
  app/mailers/notification_mailer.rb
  spec/mailers/notification_mailer_spec.rb
Labels: to backport

#32257 Fix media gallery items having incorrect borders when hidden
  app/javascript/mastodon/components/media_gallery.jsx
Labels: bug, ui, area/web interface

#32271 Fix wrong width on logo in detailed link card in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui, to backport

#32281 Add missing `on_delete: :cascade` on `notification_permissions`
  db/migrate/20241007071624_fix_notification_permission_foreign_keys.rb
  db/schema.rb
Labels: bug, to backport

#32270 Fix missing avatar fallback interfering with transparency in web UI
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar-test.jsx.snap
  app/javascript/mastodon/components/avatar.tsx
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui, to backport

#28351 Move account suspension-related methods to concern
  app/models/account.rb
  app/models/concerns/account/suspensions.rb
Labels: refactoring, ruby, to backport

#31910 Add error message when user tries to follow their own account
  app/controllers/api/v1/accounts_controller.rb
  config/locales/en.yml
  spec/requests/api/v1/accounts_spec.rb
Labels: to backport

#32298 Fix source strings being uploaded to crowdin in merge groups
  .github/workflows/crowdin-upload.yml
Labels: to backport

#32361 Fix 4 columns barely not fitting on 1920px screen
  app/javascript/styles/mastodon/components.scss
Labels: to backport, area/web interface

#32358 Fix list edition modal styling
  app/javascript/styles/mastodon/components.scss
Labels: to backport

#32354 Fix notification requests from suspended accounts still being listed
  app/controllers/api/v1/notifications/requests_controller.rb
  app/models/notification_policy.rb
  app/models/notification_request.rb
  spec/models/notification_policy_spec.rb
Labels: bug, to backport

#32356 Fix “Mention” appearing for otherwise filtered posts
  app/javascript/mastodon/features/notifications_v2/components/notification_with_status.tsx
  app/javascript/mastodon/selectors/filters.ts
  app/javascript/mastodon/selectors/index.js
Labels: bug, to backport, area/web interface

#32385 Fix “Mark every notification as read” not updating the read marker if scrolled down
  app/javascript/mastodon/reducers/notification_groups.ts
Labels: bug, to backport, area/web interface

#32388 Fix mute duration not being shown in list of muted accounts in web UI
  app/javascript/mastodon/api_types/accounts.ts
  app/javascript/mastodon/models/account.ts
Labels: to backport

#32413 Add note about not changing ActiveRecord encryption secrets once they are set
  lib/tasks/db.rake
Labels: to backport

#32415 Fix language of push notifications
  app/workers/web/push_notification_worker.rb
Labels: bug, to backport

#32418 Add tag with commit hash to PR image builds
  .github/workflows/build-push-pr.yml
Labels: build-image

#32392 Fix follow recommendation suppressions not applying immediately
  app/models/follow_recommendation.rb
Labels: to backport

#32476 Add further warnings about encryption secrets
  config/initializers/active_record_encryption.rb
  lib/tasks/db.rake
Labels: to backport

#32462 Fix follow recommendation carrousel scrolling on RTL layouts
  app/javascript/mastodon/features/home_timeline/components/inline_follow_suggestions.jsx
Labels: bug, to backport, area/web interface

#32493 Fix: Use consistent REDIS_USER environment variable in streaming
  streaming/redis.js
Labels: to backport

#32439 add SWIFT object storage uri to CSP media hosts
  app/lib/content_security_policy.rb
Labels: to backport

#32506 Fix reblog icons on account media view
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
Labels: to backport

#32500 Extend spec coverage for `Poll` model
  spec/models/poll_spec.rb
Labels: testing, ruby

#32498 Reduce factory creation (132 -> 40) in lib/vacuum/* specs
  spec/lib/vacuum/access_tokens_vacuum_spec.rb
  spec/lib/vacuum/backups_vacuum_spec.rb
  spec/lib/vacuum/feeds_vacuum_spec.rb
  spec/lib/vacuum/media_attachments_vacuum_spec.rb
  spec/lib/vacuum/preview_cards_vacuum_spec.rb
  spec/lib/vacuum/statuses_vacuum_spec.rb
Labels: testing, ruby

#32491 Reduce factory creation (73 -> 64) in `PublicFeed` spec
  spec/models/public_feed_spec.rb
Labels: testing, ruby

#32492 Reduce factory creation (48 -> 8) in `AP::Note` serializer spec
  spec/serializers/activitypub/note_serializer_spec.rb
Labels: testing, ruby

#32489 Use `context` for repeated scenarios in `AccountStatusCleanupPolicy` spec
  spec/models/account_statuses_cleanup_policy_spec.rb
Labels: testing, ruby

#32482 Reduce factories (36 > 12) in `AccountReachFinder` spec
  spec/lib/account_reach_finder_spec.rb
Labels: testing, ruby

#32434 Expand coverage for `User#token_for_app`
  spec/models/user_spec.rb
Labels: testing, ruby

#32488 Reduce factory creation (14 -> 8) in `ActivityPub::Activity::Block` spec
  spec/lib/activitypub/activity/block_spec.rb
Labels: testing, ruby

#32403 Use array compact style for classes in `nothing_here` helper
  app/helpers/statuses_helper.rb
Labels: refactoring

#32487 Reduce factory creation (17 -> 0) in `PlainTextFormatter` spec
  spec/lib/plain_text_formatter_spec.rb
Labels: testing, ruby

#32406 Fix missing content warning text in rss formatter
  app/helpers/formatting_helper.rb
  spec/helpers/formatting_helper_spec.rb
Labels: bug, refactoring

#32348 Fix only the first paragraph being displayed in some notifications
  app/javascript/styles/mastodon/components.scss
Labels: to backport, area/web interface

#32534 Explicitly install ImageMagick in CI (except for libvips tests)
  .github/workflows/test-ruby.yml
Labels: to backport

#32537 Change Active Record Encryption variable check to check for emptiness
  .env.production.sample
  config/initializers/active_record_encryption.rb
Labels: to backport

#32542 Update rails to version 7.1.4.1
  Gemfile.lock
  package.json
  yarn.lock
Labels: dependencies, to backport

#32545 Fix trailing slash newline in changelog
  CHANGELOG.md
Labels: to backport

#32383 Add more explicit explanations about author attribution and `fediverse:creator`
  app/javascript/styles/mastodon/forms.scss
  app/views/settings/verifications/show.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
Labels: ui, to backport

#32571 Fix broken i18n in text welcome mailer tags area
  app/helpers/application_helper.rb
  app/views/application/mailer/_hashtag.html.haml
  app/views/user_mailer/welcome.text.erb
Labels: bug, ui, to backport

#32567 Fix column-settings spacing in local timeline in advanced view
  app/javascript/mastodon/features/community_timeline/components/column_settings.jsx
Labels: to backport

#32580 Fix follow recommendation moderation page default language when using regional variant
  app/models/follow_recommendation_filter.rb
Labels: to backport

#30579 Pre-import Rails 7.2 generated config minor changes
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: dependencies

#32606 Fix tl language native name
  app/helpers/languages_helper.rb
Labels: to backport

#32625 Fix that blocking was not working on link timeline
  app/models/link_feed.rb
Labels: to backport

#32622 Do not change follow counters when already following
  app/javascript/mastodon/reducers/accounts.ts
Labels: to backport

#31936 Add coverage for `AccountAlias` validations
  spec/models/account_alias_spec.rb
Labels: testing

#32303 Add coverage for `api/v1/domain_blocks/preview` endpoint
  spec/requests/api/v1/domain_blocks/previews_spec.rb
Labels: testing

#32305 Add coverage for ActivityPub likes/shares endpoints
  spec/requests/activitypub/likes_spec.rb
  spec/requests/activitypub/shares_spec.rb
Labels: testing

#32464 Top off coverage for `Appeal` model
  spec/models/appeal_spec.rb
Labels: testing

#32472 Fortify coverage for `Follow` model
  spec/models/follow_spec.rb
Labels: testing

#32481 Simplify model validation specs for `Announcement`
  spec/models/announcement_spec.rb
Labels: testing

#32541 Worker specs coverage increase
  spec/fabricators/account_conversation_fabricator.rb
  spec/workers/account_refresh_worker_spec.rb
  spec/workers/activitypub/followers_synchronization_worker_spec.rb
  spec/workers/push_conversation_worker_spec.rb
  spec/workers/push_update_worker_spec.rb
  spec/workers/remote_account_refresh_worker_spec.rb
  spec/workers/remove_featured_tag_worker_spec.rb
  spec/workers/resolve_account_worker_spec.rb
Labels: testing

#32543 Redesign Content Warning and filters
  app/javascript/mastodon/components/content_warning.tsx
  app/javascript/mastodon/components/filter_warning.tsx
  app/javascript/mastodon/components/status_banner.tsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui, area/web interface

#32581 Remove unused svg logos
  app/javascript/images/logo_full.svg
  app/javascript/images/logo_transparent.svg
Labels: fit for beginners

#32454 Remove duplicate indexes from database
  db/migrate/20241014010506_remove_duplicate_indexes.rb
  db/schema.rb
Labels: performance

#32420 Constants for account refresh
  app/models/account.rb
  spec/models/account_spec.rb
Labels: refactoring

#31164 Remove single-use `ProfileStories` method
  spec/support/stories/profile_stories.rb
  spec/system/profile_spec.rb
Labels: testing, ruby

#30663 Move translation service config to `config_for` yml
  app/lib/translation_service.rb
  config/application.rb
  config/translation.yml
Labels: refactoring, lint fix 💅

#30662 Move hcaptcha service config to `config_for` yml
  app/controllers/concerns/auth/captcha_concern.rb
  app/helpers/admin/settings_helper.rb
  config/application.rb
  config/captcha.yml
Labels: refactoring, lint fix 💅

#32633 Change design of rich text elements in web UI
  app/javascript/images/quote.svg
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/rich_text.scss
  app/javascript/styles/mastodon/variables.scss
Labels: ui

#32066 Simplify uniqueness validation spec for `IpBlock`
  spec/models/ip_block_spec.rb
Labels: testing, refactoring

#32465 Explore more resplendent model validation specs for `Form::AdminSettings`
  spec/models/form/admin_settings_spec.rb
Labels: testing

#32474 Contribute more coverage for `Account` model
  spec/models/account_spec.rb
Labels: testing

#31792 Simplify model validation spec in AccountModerationNote/ReportNote
  spec/models/account_moderation_note_spec.rb
  spec/models/report_note_spec.rb
Labels: testing, ruby

#32469 Simplify model validation specs for `PreviewCard`
  spec/models/preview_card_spec.rb
Labels: testing

#32466 Simplify model validation specs for `WebauthnCredential`
  spec/models/webauthn_credential_spec.rb
Labels: testing

#32432 Move account suspension related coverage to concern spec
  spec/models/account_spec.rb
  spec/models/concerns/account/suspensions_spec.rb
Labels: testing

#32486 Use `subject` for `FeedManager` lib spec
  spec/lib/feed_manager_spec.rb
Labels: testing, ruby

#32490 Provide `establish_policy` helper method in `AccountStatusesCleanupPolicy` spec
  spec/models/account_statuses_cleanup_policy_spec.rb
Labels: testing, ruby

#32494 Simplify model validation specs for `AccountMigration`
  spec/models/account_migration_spec.rb
Labels: testing, ruby

#32495 Simplify model validation specs for `AccountStatusCleanupPolicy`
  spec/models/account_statuses_cleanup_policy_spec.rb
Labels: testing, ruby

#32496 Simplify model validation specs for `DomainAllow`
  spec/models/domain_allow_spec.rb
Labels: testing, ruby

#32515 Enhance coverage for `StatusPin` model
  app/models/status_pin.rb
  spec/models/status_pin_spec.rb
Labels: testing

#32637 Fix and improve batch attachment deletion handling when using OpenStack Swift
  app/lib/attachment_batch.rb
Labels: to backport

#32585 Mailer header partial access cleanup
  app/views/application/mailer/_heading.html.haml
  app/views/notification_mailer/favourite.html.haml
  app/views/notification_mailer/follow.html.haml
  app/views/notification_mailer/follow_request.html.haml
  app/views/notification_mailer/mention.html.haml
  app/views/notification_mailer/reblog.html.haml
  app/views/user_mailer/appeal_approved.html.haml
  app/views/user_mailer/appeal_rejected.html.haml
  app/views/user_mailer/backup_ready.html.haml
  app/views/user_mailer/confirmation_instructions.html.haml
  app/views/user_mailer/email_changed.html.haml
  app/views/user_mailer/failed_2fa.html.haml
  app/views/user_mailer/password_change.html.haml
  app/views/user_mailer/reconfirmation_instructions.html.haml
  app/views/user_mailer/reset_password_instructions.html.haml
  app/views/user_mailer/suspicious_sign_in.html.haml
  app/views/user_mailer/two_factor_disabled.html.haml
  app/views/user_mailer/two_factor_enabled.html.haml
  app/views/user_mailer/two_factor_recovery_codes_changed.html.haml
  app/views/user_mailer/warning.html.haml
  app/views/user_mailer/webauthn_credential_added.html.haml
  app/views/user_mailer/webauthn_credential_deleted.html.haml
  app/views/user_mailer/webauthn_disabled.html.haml
  app/views/user_mailer/webauthn_enabled.html.haml
  app/views/user_mailer/welcome.html.haml
Labels: refactoring, ruby, lint fix 💅

#32641 Embed modal mobile fix
  app/javascript/styles/mastodon/components.scss
Labels: to backport

#32678 Fix preview cards with long titles erroneously causing layout changes
  app/javascript/styles/mastodon/components.scss
Labels: bug, to backport, area/web interface

#32713 Fix 'unknown' media attachment rendering in detailed view
  app/javascript/mastodon/features/status/components/detailed_status.tsx
Labels: to backport

#32710 Fix IDs not being serialized as strings in annual reports API
  app/lib/annual_report/commonly_interacted_with_accounts.rb
  app/lib/annual_report/most_reblogged_accounts.rb
  app/lib/annual_report/top_statuses.rb
  spec/lib/annual_report/commonly_interacted_with_accounts_spec.rb
  spec/lib/annual_report/most_reblogged_accounts_spec.rb
  spec/lib/annual_report/top_statuses_spec.rb
Labels: bug

#32080 Migrate from the deprecated `azure-storage-blob` to `azure-blob`
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, rebase needed :construction:

#32363 Drop support for ruby 3.1
  .github/workflows/test-ruby.yml
  .rubocop.yml
  Gemfile
  README.md
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/follow_requests_controller.rb
  app/helpers/media_component_helper.rb
  app/helpers/routing_helper.rb
  app/lib/activitypub/activity.rb
  app/lib/rss/element.rb
  app/lib/translation_service/deepl.rb
  app/lib/translation_service/libre_translate.rb
  app/models/concerns/status/snapshot_concern.rb
  app/models/session_activation.rb
  app/models/user.rb
  lib/mastodon/cli/accounts.rb
  spec/support/command_line_helpers.rb
Labels: dependencies

#32723 Update `zeitwerk` to version 2.7.1
  Gemfile.lock
Labels: dependencies, ruby
