Repository mastodon/mastodon, pull requests merged in 2024-12, with the labels that each got.

#32364 Always validate `inbox_url` presence on Relay
  app/models/relay.rb
Labels: bug, ui, area/web interface

#26470 Update robots.txt to prevent crawling of domain blocks
  public/robots.txt
Labels: fit for beginners, deployment

#33119 Change profile bios to be displayed during onboarding in web UI
  app/javascript/mastodon/features/onboarding/follows.tsx
Labels: ui, javascript

#33129 Fix processing incoming post edits with mentions to unresolvable accounts
  app/services/activitypub/process_status_update_service.rb
Labels: to backport

#33081 Refactor `<Column>` to TypeScript
  app/javascript/mastodon/components/column.jsx
  app/javascript/mastodon/components/column.tsx
  app/javascript/mastodon/features/directory/index.tsx
  app/javascript/mastodon/features/link_timeline/index.tsx
  app/javascript/mastodon/features/lists/index.tsx
  app/javascript/mastodon/features/lists/members.tsx
  app/javascript/mastodon/features/lists/new.tsx
  app/javascript/mastodon/features/notifications_v2/index.tsx
  app/javascript/mastodon/features/onboarding/follows.tsx
  app/javascript/mastodon/features/onboarding/profile.tsx
  app/javascript/mastodon/features/ui/components/column_loading.tsx
Labels: refactoring

#32117 Provide option to force use of system scrollbar styling
  app/helpers/application_helper.rb
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/reset.scss
  app/models/concerns/user/has_settings.rb
  app/models/user_settings.rb
  app/views/settings/preferences/appearance/show.html.haml
  config/locales/simple_form.en.yml
Labels: ui, area/web interface

#33148 Change percentile label in year in review in web UI
  app/javascript/mastodon/features/annual_report/percentile.tsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#33036 Add ability to search for all accounts when creating a list in web UI
  app/javascript/mastodon/actions/alerts.js
  app/javascript/mastodon/actions/alerts.ts
  app/javascript/mastodon/api/accounts.ts
  app/javascript/mastodon/components/account.jsx
  app/javascript/mastodon/components/account.tsx
  app/javascript/mastodon/components/empty_account.tsx
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/containers/account_container.jsx
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/mastodon/features/blocks/index.jsx
  app/javascript/mastodon/features/compose/components/navigation_bar.jsx
  app/javascript/mastodon/features/compose/components/search_results.jsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/features/favourites/index.jsx
  app/javascript/mastodon/features/followers/index.jsx
  app/javascript/mastodon/features/following/index.jsx
  app/javascript/mastodon/features/lists/members.tsx
  app/javascript/mastodon/features/mutes/index.jsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/onboarding/follows.tsx
  app/javascript/mastodon/features/reblogs/index.jsx
  app/javascript/mastodon/features/ui/components/confirmation_modals/follow_to_list.tsx
  app/javascript/mastodon/features/ui/components/confirmation_modals/index.ts
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#33151 Fix empty authors preview card serialization
  app/models/preview_card.rb
  spec/serializers/rest/preview_card_serializer_spec.rb
Labels: to backport

#33186 Fix deletion of unconfirmed users with Webauthn set
  app/workers/scheduler/user_cleanup_scheduler.rb
  spec/workers/scheduler/user_cleanup_scheduler_spec.rb
Labels: bug, to backport

#33089 Add explicit migration breakpoints
  .github/workflows/test-migrations.yml
  lib/tasks/db.rake
Labels: deployment, ruby

#31971 Remove `thing_type` and `thing_id` columns from settings table
  app/models/setting.rb
  db/migrate/20220304195405_migrate_hide_network_preference.rb
  db/migrate/20241205135901_remove_legacy_user_settings_data.rb
  db/post_migrate/20241205135925_remove_legacy_user_settings_columns.rb
  db/schema.rb
  spec/fabricators/setting_fabricator.rb
Labels: refactoring, ruby

#33189 Fix tag trend migration failing due to duplicate rows
  db/post_migrate/20241123160722_move_tag_trends_to_table.rb
Labels: bug

#33096 Refactor `<HashtagHeader>` to TypeScript
  app/javascript/mastodon/actions/tags.js
  app/javascript/mastodon/actions/tags_typed.ts
  app/javascript/mastodon/api/tags.ts
  app/javascript/mastodon/api_types/tags.ts
  app/javascript/mastodon/features/hashtag_timeline/components/hashtag_header.jsx
  app/javascript/mastodon/features/hashtag_timeline/components/hashtag_header.tsx
  app/javascript/mastodon/features/hashtag_timeline/index.jsx
  app/javascript/mastodon/models/tags.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/tags.js
Labels: refactoring, typescript

#33209 Change ability to navigate of unconfirmed users
  app/controllers/application_controller.rb
  app/views/auth/registrations/new.html.haml
  app/views/auth/registrations/rules.html.haml
  app/views/auth/setup/show.html.haml
  config/locales/en.yml
  spec/system/log_in_spec.rb
Labels: ui

#33224 Fix design of search bar on explore screen in light theme in web UI
  app/javascript/styles/mastodon/components.scss
Labels: ui

#31443 Fix missing top border on Admin Hashtags UI
  app/javascript/styles/mastodon/tables.scss
  app/views/admin/tags/index.html.haml
Labels: ui, area/web interface

#33214 Change referrer policy to be controlled by header in web UI
  .eslintrc.js
  app/controllers/admin/base_controller.rb
  app/javascript/mastodon/components/attachment_list.jsx
  app/javascript/mastodon/components/dropdown_menu.jsx
  app/javascript/mastodon/components/error_boundary.jsx
  app/javascript/mastodon/components/follow_button.tsx
  app/javascript/mastodon/components/media_gallery.jsx
  app/javascript/mastodon/components/server_banner.jsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/emoji/__tests__/emoji-test.js
  app/javascript/mastodon/features/getting_started/components/announcements.jsx
  app/javascript/mastodon/features/notifications/components/relationships_severance_event.jsx
  app/javascript/mastodon/features/notifications/components/report.jsx
  app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx
  app/javascript/mastodon/features/standalone/status/index.tsx
  app/javascript/mastodon/features/status/components/card.jsx
  app/javascript/mastodon/features/ui/components/actions_modal.jsx
  app/javascript/mastodon/features/ui/components/link_footer.tsx
  app/lib/text_formatter.rb
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/actions/preview.html.haml
  app/views/admin/statuses/show.html.haml
  app/views/admin/tags/show.html.haml
  app/views/admin/trends/statuses/_status.html.haml
  app/views/admin/trends/tags/_tag.html.haml
  app/views/application/_card.html.haml
  app/views/disputes/strikes/_card.html.haml
  app/views/filters/statuses/_status_filter.html.haml
  app/views/oauth/authorized_applications/index.html.haml
  app/views/redirects/show.html.haml
  config/environments/production.rb
  lib/sanitize_ext/sanitize_config.rb
  spec/lib/sanitize/config_spec.rb
Labels: javascript, ruby

#33230 Fix hard wrap of markdown list in TOS template
  config/templates/terms-of-service.md
Labels: bug, expertise wanted, legal, area/web interface

#33229 Change URL truncation to account for ellipses
  app/lib/text_formatter.rb
  spec/lib/text_formatter_spec.rb
Labels: ruby, area/web interface

#33231 Add coverage for `AccountPin` model
  app/models/account_pin.rb
  spec/models/account_pin_spec.rb
Labels: bug, testing, ruby

#33247 Standardize uniqueness validation declaration on `Mention`
  app/models/mention.rb
  spec/models/mention_spec.rb
Labels: bug, testing, refactoring, ruby

#29789 Convert polls to Typescript / Immutable Records
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/actions/importer/polls.ts
  app/javascript/mastodon/actions/polls.js
  app/javascript/mastodon/actions/polls.ts
  app/javascript/mastodon/api/polls.ts
  app/javascript/mastodon/api_types/polls.ts
  app/javascript/mastodon/components/poll.jsx
  app/javascript/mastodon/containers/poll_container.js
  app/javascript/mastodon/models/account.ts
  app/javascript/mastodon/models/custom_emoji.ts
  app/javascript/mastodon/models/poll.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/polls.js
  app/javascript/mastodon/reducers/polls.ts
Labels: javascript, typescript

#33251 Add coverage for admin/terms/drafts#update and admin/terms/generates#create actions
  spec/controllers/admin/terms_of_service/drafts_controller_spec.rb
  spec/controllers/admin/terms_of_service/generates_controller_spec.rb
Labels: testing

#28516 Support animated PNGs in media attachments
  app/models/media_attachment.rb
  config/application.rb
  lib/paperclip/blurhash_transcoder.rb
  lib/paperclip/gif_transcoder.rb
  lib/paperclip/gifv_transcoder.rb
  spec/fixtures/files/600x400-animated.gif
  spec/fixtures/files/600x400-animated.png
  spec/fixtures/files/600x400.gif
  spec/fixtures/files/attachment.gif
  spec/models/media_attachment_spec.rb
  spec/requests/api/v1/media_spec.rb
Labels: dependencies, area/media processing

#33253 Add non-matching cases to `Report#history` spec
  spec/models/report_spec.rb
Labels: testing

#33255 Avoid double request in `admin/export_domain_allows` controller spec
  spec/controllers/admin/export_domain_allows_controller_spec.rb
Labels: testing, ruby

#33248 Simplify model validation specs for `CustomFilter`
  spec/models/custom_filter_spec.rb
Labels: testing, refactoring

#28101 Fix Vagrant failure to sync dangling symlinks
  Vagrantfile
Labels: bug, area/dev environment

#31659 Change label of grouped favourite notification on private mentions
  app/javascript/mastodon/features/notifications_v2/components/notification_favourite.tsx
  app/javascript/mastodon/locales/en.json
Labels: javascript, area/web interface

#33266 Fix voting on polls
  app/javascript/mastodon/api/polls.ts
Labels: bug, build-image

#33227 Fix processing of mentions for post edits with an existing corresponding silent mention
  app/services/activitypub/process_status_update_service.rb
  app/services/process_mentions_service.rb
  app/workers/mention_resolve_worker.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/update_status_service_spec.rb
Labels: bug, to backport

#27588 Fix bug where remote suspension causes local instance to remove remote follows
  app/services/suspend_account_service.rb
Labels: bug, activitypub, ruby

#33264 Enable `Rails/ReversibleMigration` cop
  db/migrate/.rubocop.yml
  db/migrate/20170205175257_remove_devices.rb
  db/migrate/20170711225116_fix_null_booleans.rb
  db/migrate/20220827195229_change_canonical_email_blocks_nullable.rb
Labels: rebase needed :construction:

#32925 Update deprecated `enum` style in older migrations
  db/migrate/20170304202101_add_type_to_media_attachments.rb
  db/migrate/20181024224956_migrate_account_conversations.rb
  db/migrate/20190511134027_add_silenced_at_suspended_at_to_accounts.rb
  db/post_migrate/20190511152737_remove_suspended_silenced_account_fields.rb
  db/post_migrate/20201017234926_fill_account_suspension_origin.rb
Labels: bug, dependencies, ruby

#32949 Change search to use query params in web UI
  app/javascript/hooks/useLinks.ts
  app/javascript/mastodon/actions/search.js
  app/javascript/mastodon/actions/search.ts
  app/javascript/mastodon/api/search.ts
  app/javascript/mastodon/api_types/search.ts
  app/javascript/mastodon/components/hashtag.tsx
  app/javascript/mastodon/features/account/components/header.jsx
  app/javascript/mastodon/features/account_timeline/containers/header_container.jsx
  app/javascript/mastodon/features/compose/components/search.jsx
  app/javascript/mastodon/features/compose/components/search.tsx
  app/javascript/mastodon/features/compose/components/search_results.jsx
  app/javascript/mastodon/features/compose/containers/search_container.js
  app/javascript/mastodon/features/compose/index.jsx
  app/javascript/mastodon/features/explore/components/search_section.jsx
  app/javascript/mastodon/features/explore/index.jsx
  app/javascript/mastodon/features/explore/index.tsx
  app/javascript/mastodon/features/explore/results.jsx
  app/javascript/mastodon/features/search/components/search_section.tsx
  app/javascript/mastodon/features/search/index.tsx
  app/javascript/mastodon/features/ui/components/compose_panel.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/models/search.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/search.js
  app/javascript/mastodon/reducers/search.ts
  app/javascript/styles/mastodon/components.scss
Labels: ui, javascript, area/search

#33281 Run optimize PNG on emoji sheet asset
  public/emoji/sheet_13.png
Labels: expertise wanted, ui, deployment, performance, new user experience, area/web interface

#33090 don't start OTel traces with Redis spans
  config/initializers/opentelemetry.rb
Labels: deployment

#33286 Fix long account username leaving container
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui, area/web interface

#33291 Add coverage for `Tag` model validations on name/display_name
  spec/models/tag_spec.rb
Labels: testing, ruby

#33285 Convert `settings/verifications` controller spec to system spec
  spec/controllers/settings/verifications_controller_spec.rb
  spec/system/settings/verifications_spec.rb
Labels: testing

#33284 Add missing `NOT NULL` requirement to small, indexed, valid data tables
  app/models/account_alias.rb
  app/models/account_deletion_request.rb
  app/models/account_domain_block.rb
  app/models/admin/action_log.rb
  app/models/announcement_mute.rb
  app/models/announcement_reaction.rb
  app/models/custom_filter.rb
  app/models/scheduled_status.rb
  app/models/user_invite_request.rb
  db/migrate/20241212152158_add_not_null_to_account_alias_columns.rb
  db/migrate/20241212152618_add_not_null_to_account_deletion_request_columns.rb
  db/migrate/20241212152734_add_not_null_to_account_domain_block_columns.rb
  db/migrate/20241212152910_add_not_null_to_admin_action_log_columns.rb
  db/migrate/20241212153054_add_not_null_to_announcement_mute_columns.rb
  db/migrate/20241212153202_add_not_null_to_announcement_reaction_columns.rb
  db/migrate/20241212153254_add_not_null_to_custom_filter_columns.rb
  db/migrate/20241212154231_add_not_null_to_scheduled_status_columns.rb
  db/migrate/20241212154346_add_not_null_to_user_invite_request_columns.rb
  db/schema.rb
Labels: deployment, ruby

#33292 Replace deprecated "github" format for stylelint on CI runs
  .github/workflows/lint-css.yml
  package.json
  yarn.lock
Labels: pipeline, lint fix 💅

#33086 Ensure datetime/date are serialized to correct format
  spec/fabricators/status_edit_fabricator.rb
  spec/serializers/rest/account_relationship_severance_event_serializer_spec.rb
  spec/serializers/rest/account_serializer/field_serializer_spec.rb
  spec/serializers/rest/account_serializer_spec.rb
  spec/serializers/rest/account_warning_serializer_spec.rb
  spec/serializers/rest/admin/account_serializer_spec.rb
  spec/serializers/rest/admin/cohort_serializer_spec.rb
  spec/serializers/rest/admin/domain_allow_serializer_spec.rb
  spec/serializers/rest/admin/domain_block_serializer_spec.rb
  spec/serializers/rest/admin/email_domain_block_serializer_spec.rb
  spec/serializers/rest/admin/ip_block_serializer_spec.rb
  spec/serializers/rest/admin/ip_serializer_spec.rb
  spec/serializers/rest/admin/measure_serializer_spec.rb
  spec/serializers/rest/admin/report_serializer_spec.rb
  spec/serializers/rest/announcement_serializer_spec.rb
  spec/serializers/rest/extended_description_serializer_spec.rb
  spec/serializers/rest/featured_tag_serializer_spec.rb
  spec/serializers/rest/filter_serializer_spec.rb
  spec/serializers/rest/marker_serializer_spec.rb
  spec/serializers/rest/muted_account_serializer_spec.rb
  spec/serializers/rest/notification_group_serializer_spec.rb
  spec/serializers/rest/notification_request_serializer_spec.rb
  spec/serializers/rest/notification_serializer_spec.rb
  spec/serializers/rest/poll_serializer_spec.rb
  spec/serializers/rest/report_serializer_spec.rb
  spec/serializers/rest/scheduled_status_serializer_spec.rb
  spec/serializers/rest/status_edit_serializer_spec.rb
  spec/serializers/rest/status_serializer_spec.rb
Labels: api, testing, ruby

#33311 Change animation on feed generation screen in web UI
  app/javascript/mastodon/components/regeneration_indicator.jsx
  app/javascript/mastodon/components/regeneration_indicator.tsx
  app/javascript/mastodon/components/status_list.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
  public/loading.gif
  public/loading.png
Labels: ui

#33320 Fix error decrementing status count when `FeaturedTags#last_status_at` is `nil`
  app/models/featured_tag.rb
Labels: bug, to backport

#33256 Use explicit config loading from `bin/rubocop`
  .github/workflows/lint-ruby.yml
  bin/rubocop
  db/migrate/.rubocop.yml
  db/migrate/20170112154826_migrate_settings.rb
  spec/controllers/.rubocop.yml
  spec/controllers/concerns/account_controller_concern_spec.rb
  spec/controllers/concerns/api/rate_limit_headers_spec.rb
  spec/controllers/concerns/challengable_concern_spec.rb
  spec/controllers/concerns/localized_spec.rb
  spec/controllers/concerns/preloading_concern_spec.rb
  spec/controllers/concerns/settings/export_controller_concern_spec.rb
  spec/controllers/concerns/user_tracking_concern_spec.rb
Labels: lint fix 💅

#33324 Fix clicking on a profile mention while logged out potentially leading to incorrect account
  app/javascript/mastodon/actions/search.ts
Labels: bug

#33334 Revert "Support animated PNGs in media attachments (#28516)"
  app/models/media_attachment.rb
  config/application.rb
  lib/paperclip/blurhash_transcoder.rb
  lib/paperclip/gif_transcoder.rb
  lib/paperclip/gifv_transcoder.rb
  spec/fixtures/files/600x400-animated.gif
  spec/fixtures/files/600x400-animated.png
  spec/fixtures/files/600x400.gif
  spec/fixtures/files/attachment.gif
  spec/models/media_attachment_spec.rb
  spec/requests/api/v1/media_spec.rb
Labels: bug, build-image

#33278 Change design of interaction modal in web UI
  app/javascript/mastodon/features/interaction_modal/index.jsx
  app/javascript/mastodon/features/interaction_modal/index.tsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#33325 Add API datetime/format matcher for serialization specs, reduce factories
  spec/serializers/rest/account_relationship_severance_event_serializer_spec.rb
  spec/serializers/rest/account_serializer/field_serializer_spec.rb
  spec/serializers/rest/account_serializer_spec.rb
  spec/serializers/rest/account_warning_serializer_spec.rb
  spec/serializers/rest/admin/account_serializer_spec.rb
  spec/serializers/rest/admin/cohort_serializer_spec.rb
  spec/serializers/rest/admin/domain_allow_serializer_spec.rb
  spec/serializers/rest/admin/domain_block_serializer_spec.rb
  spec/serializers/rest/admin/email_domain_block_serializer_spec.rb
  spec/serializers/rest/admin/ip_block_serializer_spec.rb
  spec/serializers/rest/admin/ip_serializer_spec.rb
  spec/serializers/rest/admin/measure_serializer_spec.rb
  spec/serializers/rest/admin/report_serializer_spec.rb
  spec/serializers/rest/announcement_serializer_spec.rb
  spec/serializers/rest/filter_serializer_spec.rb
  spec/serializers/rest/marker_serializer_spec.rb
  spec/serializers/rest/muted_account_serializer_spec.rb
  spec/serializers/rest/notification_group_serializer_spec.rb
  spec/serializers/rest/notification_request_serializer_spec.rb
  spec/serializers/rest/notification_serializer_spec.rb
  spec/serializers/rest/poll_serializer_spec.rb
  spec/serializers/rest/report_serializer_spec.rb
  spec/serializers/rest/scheduled_status_serializer_spec.rb
  spec/serializers/rest/status_edit_serializer_spec.rb
  spec/serializers/rest/status_serializer_spec.rb
  spec/support/matchers/api_datetime_format.rb
Labels: rebase needed :construction:

#33335 Wrap assertions in `change` within `AccountStatusesCleanupPolicy` spec
  spec/models/account_statuses_cleanup_policy_spec.rb
Labels: testing

#33336 Convert `statuses#activity` action controller to request spec
  spec/controllers/statuses_controller_spec.rb
  spec/requests/statuses/activity_spec.rb
Labels: testing

#33337 Use bundler version 2.6.0
  Gemfile.lock
Labels: dependencies, pipeline

#33172 Fix missing value limits for `UserRole` position
  app/models/user_role.rb
  spec/models/user_role_spec.rb
Labels: bug, ruby, area/web interface

#33327 Convert `admin/custom_emojis` spec controller->system
  spec/controllers/admin/custom_emojis_controller_spec.rb
  spec/system/admin/custom_emojis_spec.rb
Labels: testing, ruby

#33340 Fix down clause for notification policy v2 migrations
  db/migrate/20240808124338_migrate_notifications_policy_v2.rb
  db/post_migrate/20240808124339_post_deployment_migrate_notifications_policy_v2.rb
Labels: to backport

#33348 Fix incorrect notification settings migration for non-followers
  db/migrate/20240808124338_migrate_notifications_policy_v2.rb
  db/post_migrate/20240808124339_post_deployment_migrate_notifications_policy_v2.rb
Labels: bug, to backport

#33351 Use bundler version 2.6.1
  Gemfile.lock
Labels: dependencies, ruby

#33350 Remove unused `Poll.unattached` scope
  app/models/poll.rb
  spec/models/poll_spec.rb
Labels: ruby

#33349 Update user role position range limit
  app/models/user_role.rb
  spec/models/user_role_spec.rb
Labels: ruby

#33362 Fix `/health` endpoint when OTEL is configured
  config/initializers/opentelemetry.rb
Labels: bug, build-image

#33363 Convert `statuses_cleanup` controller specs to system specs
  spec/controllers/statuses_cleanup_controller_spec.rb
  spec/system/statuses_cleanup_spec.rb
Labels: testing, ruby

#33364 Convert `admin/webhooks` spec controller->system
  spec/controllers/admin/webhooks_controller_spec.rb
  spec/system/admin/webhooks_spec.rb
Labels: testing, ruby

#33372 Fix featured tags for remote accounts not being kept up to date
  app/lib/activitypub/activity/create.rb
  app/services/activitypub/process_status_update_service.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: to backport
