Repository mastodon/mastodon, pull requests merged in 2024-02, with the labels that each got.

#28878 Change onboarding prompt to follow suggestions carousel in web UI
  app/javascript/mastodon/actions/suggestions.js
  app/javascript/mastodon/actions/timelines.js
  app/javascript/mastodon/components/status_list.jsx
  app/javascript/mastodon/features/home_timeline/components/explore_prompt.tsx
  app/javascript/mastodon/features/home_timeline/components/inline_follow_suggestions.jsx
  app/javascript/mastodon/features/home_timeline/index.jsx
  app/javascript/mastodon/features/ui/containers/status_list_container.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/settings.js
  app/javascript/mastodon/reducers/suggestions.js
  app/javascript/mastodon/reducers/timelines.js
  app/javascript/material-icons/400-24px/navigate_before-fill.svg
  app/javascript/material-icons/400-24px/navigate_before.svg
  app/javascript/material-icons/400-24px/navigate_next-fill.svg
  app/javascript/material-icons/400-24px/navigate_next.svg
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
Labels: ui, build-image

#29064 Fix confirmation e-mails when signing up through an app
  app/views/user_mailer/confirmation_instructions.html.haml
Labels: bug

#28111 Extract scenic view model common methods to concern
  app/models/account_summary.rb
  app/models/concerns/database_view_record.rb
  app/models/follow_recommendation.rb
  app/models/instance.rb
  app/models/user_ip.rb
Labels: refactoring, ruby

#29026 Fix report reason selector in moderation interface not unselecting rules when changing category
  app/javascript/mastodon/components/admin/ReportReasonSelector.jsx
Labels: bug, ui, moderation

#29031 Move status serializer error handling to private method
  app/controllers/api/v1/statuses_controller.rb
Labels: rebase needed :construction:

#29049 Fix self-destruct schedule not actually replacing initial schedule
  config/initializers/sidekiq.rb
Labels: bug

#29108 Change `source` attribute of `Suggestion` entity in `/api/v2/suggestions` back to a string
  app/javascript/mastodon/features/home_timeline/components/inline_follow_suggestions.jsx
  app/models/account_suggestions.rb
  app/models/account_suggestions/suggestion.rb
  app/serializers/rest/suggestion_serializer.rb
  spec/requests/api/v2/suggestions_spec.rb
  spec/serializers/rest/suggestion_serializer_spec.rb
Labels: api

#29122 Add support for specifying custom CA cert for Elasticsearch
  config/initializers/chewy.rb
Labels: build-image

#29133 Rewrite signature verification using regexps and `StringScanner`
  app/lib/signature_parser.rb
  spec/lib/signature_parser_spec.rb
Labels: performance

#29187 Disable administrative doorkeeper routes
  config/initializers/doorkeeper.rb
  spec/requests/disabled_oauth_endpoints_spec.rb
Labels: to backport

#29207 Fix user creation failure handling in OAuth paths
  app/controllers/auth/omniauth_callbacks_controller.rb
  config/locales/devise.en.yml
  spec/requests/omniauth_callbacks_spec.rb
Labels: to backport

#29206 Update `nsa` gem to version 0.3.0 (#29065)
  Gemfile
  Gemfile.lock
Labels: backport

#29212 Re-enable fixed `Style/Semicolon` cop
  .rubocop.yml
Labels: ruby, lint fix 💅

#29278 Add a missing thread example to the statuses spec
  spec/requests/api/v1/statuses_spec.rb
Labels: testing, ruby

#29245 Use `capture_emails` helper to improve email assertions in specs
  spec/controllers/admin/disputes/appeals_controller_spec.rb
  spec/controllers/admin/resets_controller_spec.rb
  spec/controllers/auth/sessions_controller_spec.rb
  spec/controllers/disputes/appeals_controller_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/reports_spec.rb
  spec/services/notify_service_spec.rb
  spec/services/report_service_spec.rb
  spec/workers/backup_worker_spec.rb
Labels: testing, ruby

#29294 Change explore icon from hashtag to compass in web UI
  app/javascript/mastodon/features/explore/index.jsx
  app/javascript/mastodon/features/ui/components/navigation_panel.jsx
  app/javascript/material-icons/400-24px/explore-fill.svg
  app/javascript/material-icons/400-24px/explore.svg
Labels: ui

#29279 Remove CSS definitions for some unused classes
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
Labels: refactoring

#29302 Remove erroneous service type on `TagFeed` model spec
  spec/models/tag_feed_spec.rb
Labels: testing, ruby

#29320 Add basic coverage for `ProcessHashtagsService` class
  spec/services/process_hashtags_service_spec.rb
Labels: testing, ruby

#29321 Add basic coverage for `CreateFeaturedTagService` class
  spec/services/create_featured_tag_service_spec.rb
Labels: testing, ruby

#29322 Add basic coverage for `AppealService` class
  spec/services/appeal_service_spec.rb
Labels: testing, ruby

#29324 Add basic coverage for `AfterUnallowDomainService` class
  spec/services/after_unallow_domain_service_spec.rb
Labels: testing, ruby

#29339 Update yarn to version 4.1.0
  package.json
  streaming/package.json
  yarn.lock
Labels: dependencies

#29338 Update husky and remove deprecated features
  .husky/pre-commit
  package.json
  yarn.lock
Labels: dependencies

#29333 Add basic coverage for `ApproveAppealService` class
  spec/services/approve_appeal_service_spec.rb
Labels: testing, ruby

#29334 Add basic coverage for `VoteService` class
  spec/services/vote_service_spec.rb
Labels: testing, ruby

#29330 Add basic coverage for `UnmuteService` class
  spec/services/unmute_service_spec.rb
Labels: testing, ruby

#29331 Add basic coverage for `WebhookService` class
  spec/services/webhook_service_spec.rb
Labels: testing, ruby

#29327 Add basic coverage for `RemoveDomainsFromFollowersService` class
  spec/services/remove_domains_from_followers_service_spec.rb
Labels: testing, ruby

#28632 Streaming: refactor to custom Error classes
  streaming/errors.js
  streaming/index.js
Labels: streaming

#29337 Automatically switch from open to approved registrations in absence of moderators
  app/mailers/admin_mailer.rb
  app/views/admin_mailer/auto_close_registrations.text.erb
  app/workers/scheduler/auto_close_registrations_scheduler.rb
  config/locales/en.yml
  config/sidekiq.yml
  spec/workers/scheduler/auto_close_registrations_scheduler_spec.rb
Labels: backport

#29350 Update dependencies
  Gemfile.lock
Labels: backport

#29356 Fix auto-close email being sent to users with devops permissions instead of settings permissions
  app/workers/scheduler/auto_close_registrations_scheduler.rb
Labels: backport

#29353 Change registrations to be disabled by default for new servers
  app/javascript/packs/admin.jsx
  app/views/admin/settings/registrations/show.html.haml
  config/locales/en.yml
  config/settings.yml
  spec/models/setting_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: backport

#29358 Fix link verifications when page size exceeds 1MB
  app/services/verify_link_service.rb
  spec/services/verify_link_service_spec.rb
Labels: bug, to backport

#29335 Fix processing of `Link` objects in `Image` objects
  app/services/activitypub/process_account_service.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: bug, activitypub, to backport

#29363 Fix processing of `Link` objects in `Image` objects
  app/services/activitypub/process_account_service.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: backport

#29364 Fix processing of `Link` objects in `Image` objects
  app/services/activitypub/process_account_service.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: backport

#29301 Add basic coverage for `MoveService` class
  spec/services/move_service_spec.rb
Labels: testing, ruby

#29277 Add a missing spec to `SessionsController#webauthn_options`
  spec/controllers/auth/sessions_controller_spec.rb
Labels: testing, ruby

#29303 Better tests for auth/registrations#update
  spec/controllers/auth/registrations_controller_spec.rb
Labels: testing, ruby

#29406 Change behavior of privacy dropdown to only change value on validation
  app/javascript/mastodon/features/compose/components/language_dropdown.jsx
  app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
  app/javascript/mastodon/features/compose/components/privacy_dropdown_menu.jsx
Labels: ui, accessibility, refactoring

#29419 Use "cacheable response" shared example in more places
  spec/controllers/custom_css_controller_spec.rb
  spec/controllers/instance_actors_controller_spec.rb
  spec/controllers/manifests_controller_spec.rb
  spec/controllers/tags_controller_spec.rb
  spec/support/examples/cache.rb
Labels: testing, ruby

#29389 Convert the streaming server to ESM
  streaming/.eslintrc.cjs
  streaming/errors.js
  streaming/index.js
  streaming/logging.js
  streaming/metrics.js
  streaming/package.json
  streaming/tsconfig.json
  streaming/utils.js
Labels: streaming

#29412 Add `change` block expectation to `admin/invites#deactivate_all` spec
  spec/controllers/admin/invites_controller_spec.rb
Labels: testing, ruby

#29435 Align `TagServersMeasure` to use `WITH` query style similar to others
  app/lib/admin/metrics/measure/tag_servers_measure.rb
Labels: refactoring, ruby

#29456 Fix regression with search bar icon position
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29457 Fix preview card player getting embedded when clicking on the external link button
  app/javascript/mastodon/features/status/components/card.jsx
Labels: bug, ui

#29442 Allow pagination `Link` headers on API accounts/statuses when pinned true
  app/controllers/api/v1/accounts/statuses_controller.rb
  spec/controllers/api/v1/accounts/statuses_controller_spec.rb
Labels: api

#29425 Convert `packs/admin.jsx` to Typescript
  app/javascript/packs/admin.jsx
  app/javascript/packs/admin.tsx
Labels: typescript
