Repository mastodon/mastodon, pull requests merged in 2024-11, with the labels that each got.

#32728 Update browser to version 6.0.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#32727 Reduce factory generation in `AccountStatusesFilter` spec
  spec/lib/account_statuses_filter_spec.rb
Labels: performance, testing

#32720 Refactor common checks in `tootctl media remove-orphans`
  lib/mastodon/cli/media.rb
Labels: refactoring

#32289 Remove cookie rotator
  config/initializers/cookie_rotator.rb
Labels: dependencies

#32766 Fix alt-text pop-in not using the translated description
  app/javascript/mastodon/components/media_gallery.jsx
Labels: to backport

#32709 Add year in review feature to web UI
  app/controllers/api/v1/annual_reports_controller.rb
  app/javascript/images/archetypes/booster.png
  app/javascript/images/archetypes/lurker.png
  app/javascript/images/archetypes/oracle.png
  app/javascript/images/archetypes/pollster.png
  app/javascript/images/archetypes/replier.png
  app/javascript/mastodon/api_types/notifications.ts
  app/javascript/mastodon/components/modal_root.jsx
  app/javascript/mastodon/features/annual_report/archetype.tsx
  app/javascript/mastodon/features/annual_report/followers.tsx
  app/javascript/mastodon/features/annual_report/highlighted_post.tsx
  app/javascript/mastodon/features/annual_report/index.tsx
  app/javascript/mastodon/features/annual_report/most_used_app.tsx
  app/javascript/mastodon/features/annual_report/most_used_hashtag.tsx
  app/javascript/mastodon/features/annual_report/new_posts.tsx
  app/javascript/mastodon/features/annual_report/percentile.tsx
  app/javascript/mastodon/features/notifications_v2/components/notification_annual_report.tsx
  app/javascript/mastodon/features/notifications_v2/components/notification_group.tsx
  app/javascript/mastodon/features/status/components/detailed_status.tsx
  app/javascript/mastodon/features/ui/components/annual_report_modal.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/models/annual_report.ts
  app/javascript/mastodon/models/notification_group.ts
  app/javascript/material-icons/400-24px/celebration-fill.svg
  app/javascript/material-icons/400-24px/celebration.svg
  app/javascript/material-icons/400-24px/explore-fill.svg
  app/javascript/material-icons/400-24px/explore.svg
  app/javascript/styles/application.scss
  app/javascript/styles/mastodon/annual_reports.scss
  app/javascript/styles/mastodon/components.scss
  app/models/notification.rb
  app/models/notification_group.rb
  app/serializers/rest/annual_report_event_serializer.rb
  app/serializers/rest/notification_group_serializer.rb
  app/services/notify_service.rb
  config/routes/api.rb
Labels: ui

#32718 Update faraday to version 2.12.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#32778 Fix out-of-view post contents being inconsistent with in-view post contents
  app/javascript/mastodon/components/status.jsx
Labels: area/web interface

#32796 Fix “uninitialized constant HttpLog” errors in tootctl
  lib/mastodon/cli/progress_helper.rb
  lib/tasks/mastodon.rake
  lib/tasks/repo.rake
Labels: bug

#30847 Use `with_options` for shared settings options in routes
  config/routes/admin.rb
  config/routes/api.rb
Labels: refactoring, ruby

#31217 Update location of unused `MIN_SCHEDULE_OFFSET` constant
  app/models/scheduled_status.rb
  app/services/post_status_service.rb
  app/workers/scheduler/scheduled_statuses_scheduler.rb
Labels: refactoring, ruby

#32065 Add `Status.not_direct_visibility` scope
  app/models/account_statuses_cleanup_policy.rb
  app/models/status.rb
  lib/mastodon/cli/cache.rb
Labels: refactoring

#31969 Use `shell.indent` for list output indentation in CLI area
  lib/mastodon/cli/accounts.rb
  lib/mastodon/cli/email_domain_blocks.rb
  lib/mastodon/cli/emoji.rb
Labels: refactoring

#31968 Add `EmailDomainBlock.parents` scope
  app/controllers/admin/email_domain_blocks_controller.rb
  app/models/email_domain_block.rb
  lib/mastodon/cli/email_domain_blocks.rb
Labels: refactoring, rebase needed :construction:

#30391 Update Rails to version 7.2.2
  Gemfile
  Gemfile.lock
  app/lib/admin/system_check/database_schema_check.rb
  app/models/concerns/status/safe_reblog_insert.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  lib/active_record/with_recursive.rb
  lib/arel/union_parenthesizing.rb
  lib/tasks/tests.rake
  spec/lib/admin/system_check/database_schema_check_spec.rb
Labels: dependencies

#32744 Remove postgres version support check for `REINDEX` in migration
  db/post_migrate/20230803082451_add_unique_index_on_preview_cards_statuses.rb
Labels: refactoring, dependencies

#32801 Use existing arel scopes instead of string ordering
  app/models/admin/status_filter.rb
  app/models/session_activation.rb
Labels: ruby

#31210 Use enum-generated `IpBlock.severity...` scopes
  app/helpers/registration_helper.rb
Labels: refactoring, ruby

#28866 Move account silence-related methods to concern
  app/models/account.rb
  app/models/concerns/account/silences.rb
  spec/models/account_spec.rb
  spec/models/concerns/account/silences_spec.rb
Labels: refactoring, ruby

#28865 Move account sensitize-related methods to concern
  app/models/account.rb
  app/models/concerns/account/sensitizes.rb
  spec/models/concerns/account/sensitizes_spec.rb
Labels: refactoring, ruby

#30534 Use `mastodon` config namespace to load software update default value via `config_for`
  app/models/software_update.rb
  app/services/software_update_check_service.rb
  config/application.rb
  config/mastodon.yml
  config/navigation.rb
  spec/lib/admin/system_check/software_version_check_spec.rb
  spec/services/software_update_check_service_spec.rb
Labels: refactoring

#32805 Define constants for sampling sizes in `AccountReachFinder`
  app/lib/account_reach_finder.rb
Labels: accessibility, ruby

#32807 Fix a few visual issues with annual reports in web UI
  app/javascript/mastodon/features/annual_report/most_used_hashtag.tsx
  app/javascript/mastodon/features/annual_report/percentile.tsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/annual_reports.scss
Labels: ui

#30317 Add client_secret_expires_at to OAuth Applications
  app/serializers/rest/credential_application_serializer.rb
  spec/requests/api/v1/apps/credentials_spec.rb
  spec/requests/api/v1/apps_spec.rb
Labels: api, to backport

#32863 Fix error in CLI EmailDomainBlocks when supplying `--with-dns-records`
  lib/mastodon/cli/email_domain_blocks.rb
  spec/lib/mastodon/cli/email_domain_blocks_spec.rb
Labels: to backport

#32869 Fix list creation limit check
  app/models/list.rb
  spec/models/list_spec.rb
Labels: bug, to backport

#32887 Fix Content Warning and filter states not applying to boosted posts properly
  app/javascript/mastodon/components/status.jsx
Labels: bug, build-image

#32895 Fix filters not being correctly applied to boosted posts
  app/javascript/mastodon/components/status.jsx
Labels: bug

#32903 Fix domain attribution field having autocorrect and autocapitalize enabled
  app/views/settings/verifications/show.html.haml
Labels: to backport

#32911 Fix uploading higher-than-wide GIF profile picture with libvips enabled
  lib/paperclip/vips_lazy_thumbnail.rb
  spec/fixtures/files/avatar-high.gif
  spec/support/examples/models/concerns/account_avatar.rb
Labels: bug, to backport

#31797 Move body class to shared partial for web app controller concern views
  app/controllers/concerns/web_app_controller_concern.rb
  app/views/shared/_web_app.html.haml
  spec/system/about_spec.rb
  spec/system/home_spec.rb
  spec/system/privacy_spec.rb
  spec/system/tags_spec.rb
Labels: refactoring

#32419 Remove remnants of embed views
  app/helpers/statuses_helper.rb
  app/views/admin/reports/_status.html.haml
  app/views/filters/statuses/_status_filter.html.haml
  spec/helpers/accounts_helper_spec.rb
  spec/helpers/statuses_helper_spec.rb
Labels: refactoring, rebase needed :construction:

#32840 Use `with_options` blocks in `Associations` concern
  app/models/concerns/account/associations.rb
Labels: refactoring

#32904 Add OpenTelemetry VCS attributes
  .github/workflows/build-container-image.yml
  Dockerfile
  config/initializers/opentelemetry.rb
  lib/mastodon/version.rb
Labels: build-image

#32921 Extract constants for controller `LIMIT` queries
  app/controllers/admin/instances_controller.rb
  app/controllers/api/v1/featured_tags/suggestions_controller.rb
  app/controllers/settings/featured_tags_controller.rb
  app/controllers/settings/imports_controller.rb
Labels: refactoring

#32922 Reduce long lines in `relationships/show` view
  app/views/relationships/show.html.haml
Labels: lint fix 💅

#32926 Use `nil` instead of `false` for datetime value in spec
  spec/models/concerns/account/sensitizes_spec.rb
Labels: bug, refactoring, dependencies, ruby

#32857 Fix `min_id` and `max_id` causing error in search API
  app/lib/search_query_transformer.rb
  lib/exceptions.rb
  spec/lib/search_query_transformer_spec.rb
Labels: bug, to backport

#30232 Change dependency from annotate to annotaterb
  .annotaterb.yml
  Gemfile
  Gemfile.lock
  lib/tasks/annotate_rb.rake
  lib/tasks/auto_annotate_models.rake
Labels: dependencies, ruby

#32917 Use hash arguments to `select` when possible (Rails 7.2)
  app/controllers/api/v1/accounts/familiar_followers_controller.rb
  app/lib/feed_manager.rb
  app/lib/importer/statuses_index_importer.rb
  app/models/status.rb
Labels: refactoring

#32915 Use hash arguments to `order` when possible (Rails 7.2)
  app/models/concerns/account/associations.rb
  app/models/concerns/account/interactions.rb
  app/models/instance_filter.rb
  app/models/tag.rb
Labels: performance, refactoring

#32914 Use group/count approach in annual report classes
  app/lib/annual_report/commonly_interacted_with_accounts.rb
  app/lib/annual_report/most_reblogged_accounts.rb
  app/lib/annual_report/most_used_apps.rb
  app/lib/annual_report/top_hashtags.rb
  spec/lib/annual_report/commonly_interacted_with_accounts_spec.rb
  spec/lib/annual_report/most_reblogged_accounts_spec.rb
  spec/lib/annual_report/most_used_apps_spec.rb
  spec/lib/annual_report/top_hashtags_spec.rb
Labels: refactoring, ruby

#32960 Fix notification polling showing a loading bar in web UI
  app/javascript/mastodon/actions/notification_groups.ts
Labels: bug

#32986 Fix error when viewing statuses to deleted replies in moderation view
  app/views/admin/reports/_status.html.haml
  app/views/admin/statuses/show.html.haml
Labels: bug

#32984 Add `AccountWarning` case to `Report#history` spec
  spec/models/report_spec.rb
Labels: testing

#32988 Add ability to middle-mouse click posts in web UI
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_content.jsx
  app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx
Labels: ui

#30729 block scheduled status from frozen users
  app/workers/publish_scheduled_status_worker.rb
  spec/workers/publish_scheduled_status_worker_spec.rb
Labels: to backport

#33008 Fix wrong video dimensions for some rotated videos
  app/lib/video_metadata_extractor.rb
Labels: bug

#32881 Change design of lists in web UI
  app/javascript/mastodon/actions/lists.js
  app/javascript/mastodon/actions/lists_typed.ts
  app/javascript/mastodon/api.ts
  app/javascript/mastodon/api/lists.ts
  app/javascript/mastodon/api_types/lists.ts
  app/javascript/mastodon/components/check_box.tsx
  app/javascript/mastodon/components/scrollable_list.jsx
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/features/list_adder/components/account.jsx
  app/javascript/mastodon/features/list_adder/components/list.jsx
  app/javascript/mastodon/features/list_adder/index.jsx
  app/javascript/mastodon/features/list_adder/index.tsx
  app/javascript/mastodon/features/list_editor/components/account.jsx
  app/javascript/mastodon/features/list_editor/components/edit_list_form.jsx
  app/javascript/mastodon/features/list_editor/components/search.jsx
  app/javascript/mastodon/features/list_editor/index.jsx
  app/javascript/mastodon/features/list_timeline/index.jsx
  app/javascript/mastodon/features/lists/components/new_list_form.jsx
  app/javascript/mastodon/features/lists/index.jsx
  app/javascript/mastodon/features/lists/index.tsx
  app/javascript/mastodon/features/lists/members.tsx
  app/javascript/mastodon/features/lists/new.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/models/list.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/list_adder.js
  app/javascript/mastodon/reducers/list_editor.js
  app/javascript/mastodon/reducers/lists.js
  app/javascript/mastodon/reducers/lists.ts
  app/javascript/mastodon/selectors/lists.ts
  app/javascript/styles/mastodon-light/variables.scss
  app/javascript/styles/mastodon/admin.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/styles/mastodon/variables.scss
  app/javascript/svg-icons/squiggly_arrow.svg
Labels: ui

#33018 Fix pushing hashtag-followed posts to feeds of inactive users
  app/models/tag_follow.rb
  app/services/fan_out_on_write_service.rb
Labels: bug, to backport

#29316 Fix accounts table long display name
  app/javascript/styles/mastodon/widgets.scss
Labels: to backport, area/web interface

#33023 Remove redundant temporary index creation in `tootctl status remove`
  lib/mastodon/cli/statuses.rb
Labels: performance

#33028 Add coverage for `User` validations
  spec/models/user_spec.rb
Labels: testing

#33029 Add coverage for `UserRole` validations
  spec/models/user_role_spec.rb
Labels: testing

#33026 Add coverage for `Webhook` validations
  app/models/webhook.rb
  spec/models/webhook_spec.rb
Labels: testing

#33054 Fix arrow in the wrong place on empty list members screen in web UI
  app/javascript/mastodon/features/lists/members.tsx
Labels: ui

#33063 Fix `TagFollow` records not being correctly handled in account operations
  app/models/concerns/account/interactions.rb
  app/models/concerns/account/merging.rb
  app/services/delete_account_service.rb
  lib/mastodon/cli/maintenance.rb
Labels: bug, to backport

#33067 Fix direct inbox delivery pushing posts into inactive followers' timelines
  app/lib/feed_manager.rb
  app/models/user.rb
Labels: to backport, build-image

#32970 Fix `Style/SafeNavigation` cop
  app/controllers/concerns/cache_concern.rb
Labels: lint fix 💅

#33038 Remove old notifications route from web UI
  app/javascript/mastodon/features/notifications/components/filter_bar.jsx
  app/javascript/mastodon/features/notifications/containers/filter_bar_container.js
  app/javascript/mastodon/features/notifications/index.jsx
  app/javascript/mastodon/features/notifications_wrapper.jsx
  app/javascript/mastodon/features/ui/components/columns_area.jsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/features/ui/util/async-components.js
Labels: refactoring

#33082 Fix list error messages
  app/models/list_account.rb
  config/locales/activerecord.en.yml
  spec/requests/api/v1/lists/accounts_spec.rb
Labels: bug, api

#33094 Fix inactive users' timelines being backfilled on follow and unsuspend
  app/lib/feed_manager.rb
Labels: to backport

#33092 Change design of modal loading and error screens in web UI
  app/javascript/mastodon/components/gif.tsx
  app/javascript/mastodon/features/ui/components/bundle_column_error.jsx
  app/javascript/mastodon/features/ui/components/bundle_modal_error.jsx
  app/javascript/mastodon/features/ui/components/modal_loading.jsx
  app/javascript/mastodon/features/ui/components/modal_placeholder.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#33106 Fix middle-click handling conflicting with automatic scrolling
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_content.jsx
Labels: area/web interface

#33107 Remove constant definition from global scope in embed.js
  public/embed.js
Labels: to backport

#33039 Change server rules to be collapsible
  app/javascript/entrypoints/public.tsx
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/components.scss
  app/views/auth/registrations/rules.html.haml
Labels: ui

#33101 Change "social web" to "fediverse" in a few banners in web UI
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/firehose/index.jsx
  app/javascript/mastodon/features/public_timeline/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui
