Repository mastodon/mastodon, pull requests merged in 2024-04, with the labels that each got.

#29800 Fix Redux Middleware types
  app/javascript/mastodon/store/middlewares/errors.ts
  app/javascript/mastodon/store/middlewares/sounds.ts
Labels: typescript

#29792 Add API types for status and related objects
  app/javascript/mastodon/api_types/media_attachments.ts
  app/javascript/mastodon/api_types/polls.ts
  app/javascript/mastodon/api_types/statuses.ts
  app/javascript/mastodon/models/status.ts
  app/serializers/rest/media_attachment_serializer.rb
  app/serializers/rest/poll_serializer.rb
  app/serializers/rest/status_serializer.rb
Labels: typescript

#29441 Add `max_pinned_statuses` to instances serializer and api response
  app/serializers/rest/instance_serializer.rb
  spec/requests/api/v2/instance_spec.rb
  spec/serializers/rest/instance_serializer_spec.rb
Labels: api

#29826 Fix contrast in notification request badge
  app/javascript/styles/mastodon/components.scss
Labels: ui

#28366 Update stoplight to version 4.1.0
  Gemfile
  Gemfile.lock
  app/controllers/concerns/signature_verification.rb
  app/services/bulk_import_row_service.rb
  app/workers/activitypub/delivery_worker.rb
  app/workers/import/relationship_worker.rb
  config/initializers/stoplight.rb
  lib/paperclip/attachment_extensions.rb
Labels: dependencies, ruby

#29850 Add stub for trending tags in user mailer spec
  spec/mailers/user_mailer_spec.rb
Labels: testing

#29838 Improve email address validation
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/validators/email_address_validator.rb
  spec/models/user_spec.rb
Labels: to backport

#29837 Move OAuth flow tests from feature tests to system tests
  spec/system/oauth_spec.rb
Labels: testing

#29862 Remove caching in `cache_collection`
  app/controllers/concerns/cache_concern.rb
  app/models/concerns/cacheable.rb
  app/models/feed.rb
  app/models/public_feed.rb
  app/models/status.rb
  app/models/tag_feed.rb
  spec/controllers/application_controller_spec.rb
  spec/models/home_feed_spec.rb
Labels: performance, to backport, build-image

#29921 Add `/` keyboard shortcut to focus the search field
  app/javascript/mastodon/features/keyboard_shortcuts/index.jsx
  app/javascript/mastodon/features/ui/index.jsx
Labels: ui

#29702 Drop support for Ruby 3.0 (reaching EOL)
  .github/workflows/test-ruby.yml
  .rubocop.yml
  Gemfile
  README.md
Labels: dependencies, ruby

#29923 Fix unfollow button being out of frame on small screens on old browsers
  app/javascript/styles/mastodon/components.scss
Labels: ui

#29922 Fix incorrect label for filtered notifications badge
  app/javascript/mastodon/features/notifications/components/filtered_notifications_banner.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#28738 Use Rails `upsert` to generate update_count! query in Counters concern
  app/models/concerns/account/counters.rb
  spec/models/concerns/account/counters_spec.rb
Labels: refactoring, ruby

#29402 Combine double subject runs and DRY up change check in bulk import service spec
  spec/services/bulk_import_row_service_spec.rb
Labels: testing, ruby

#28910 Add reusable duplicate ID finder methods in maintenance CLI
  lib/mastodon/cli/maintenance.rb
Labels: refactoring, ruby

#26736 Change `/api/v1/announcements` to return regular `Status` entities
  app/models/announcement.rb
  app/serializers/rest/announcement_serializer.rb
Labels: api, rebase needed :construction:

#28826 Add `API::Pagination` concern
  app/controllers/api/base_controller.rb
  app/controllers/concerns/api/pagination.rb
Labels: refactoring, ruby

#28400 Fix `Bundler/OrderedGems` cop
  .rubocop_todo.yml
  Gemfile
Labels: dependencies, ruby, lint fix 💅

#29173 Replace deprecated `dotenv-rails` gem with `dotenv` gem
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: dependencies, ruby

#27461 Fix Rubocop `Rails/UniqueValidationWithoutIndex` cop
  .rubocop_todo.yml
  db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb
  db/migrate/20231018193209_add_index_to_account_alias_uri_account_id.rb
  db/migrate/20231018193355_add_index_to_custom_filter_statuses_status_custom_filter.rb
  db/migrate/20231018193659_add_index_to_identities_uid_provider.rb
  db/schema.rb
  lib/tasks/tests.rake
Labels: ruby, lint fix 💅

#30022 Fixed crash when supplying FFMPEG_BINARY environment variable
  app/lib/video_metadata_extractor.rb
  config/initializers/ffmpeg.rb
  lib/paperclip/image_extractor.rb
  lib/paperclip/transcoder.rb
Labels: bug, to backport

#27780 Add material design icons to admin/settings views
  app/helpers/application_helper.rb
  app/javascript/styles/mastodon/admin.scss
  app/views/admin/account_warnings/_account_warning.html.haml
  app/views/admin/accounts/_remote_account.html.haml
  app/views/admin/accounts/index.html.haml
  app/views/admin/accounts/show.html.haml
  app/views/admin/custom_emojis/index.html.haml
  app/views/admin/dashboard/index.html.haml
  app/views/admin/email_domain_blocks/index.html.haml
  app/views/admin/export_domain_blocks/_domain_block.html.haml
  app/views/admin/export_domain_blocks/import.html.haml
  app/views/admin/follow_recommendations/show.html.haml
  app/views/admin/instances/show.html.haml
  app/views/admin/invites/_invite.html.haml
  app/views/admin/ip_blocks/index.html.haml
  app/views/admin/relationships/index.html.haml
  app/views/admin/relays/_relay.html.haml
  app/views/admin/reports/_header_card.html.haml
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/actions/preview.html.haml
  app/views/admin/reports/show.html.haml
  app/views/admin/roles/_role.html.haml
  app/views/admin/settings/shared/_links.html.haml
  app/views/admin/status_edits/_status_edit.html.haml
  app/views/admin/statuses/index.html.haml
  app/views/admin/tags/show.html.haml
  app/views/admin/trends/links/index.html.haml
  app/views/admin/trends/links/preview_card_providers/index.html.haml
  app/views/admin/trends/statuses/_status.html.haml
  app/views/admin/trends/statuses/index.html.haml
  app/views/admin/trends/tags/_tag.html.haml
  app/views/admin/trends/tags/index.html.haml
  config/initializers/propshaft.rb
Labels: ui, refactoring, ruby

#30036 Update to Ruby 3.2.4
  .ruby-version
  Dockerfile
Labels: dependencies

#30049 Change mute options to be in dropdown on muted users list in web UI
  app/javascript/mastodon/components/account.jsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#30045 Extract constants for column size length validation limits
  app/models/account_moderation_note.rb
  app/models/account_note.rb
  app/models/invite.rb
  app/models/report.rb
  app/models/report_note.rb
  app/models/rule.rb
  app/models/user_invite_request.rb
Labels: refactoring, ruby

#30059 Change design of people tab on explore in web UI
  app/javascript/mastodon/features/explore/components/card.jsx
  app/javascript/mastodon/features/explore/suggestions.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
Labels: ui

#30065 Add in-app notifications for moderation actions/warnings
  app/javascript/mastodon/features/notifications/components/moderation_warning.tsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/notifications.js
  app/javascript/styles/mastodon/components.scss
  app/models/admin/account_action.rb
  app/models/admin/status_batch_action.rb
  app/models/notification.rb
  app/serializers/rest/account_warning_serializer.rb
  app/serializers/rest/appeal_serializer.rb
  app/serializers/rest/notification_serializer.rb
  app/services/notify_service.rb
  spec/models/admin/account_action_spec.rb
Labels: api, ui

#30082 Fix moderator account being exposed in account moderation notification
  app/models/notification.rb
  spec/models/notification_spec.rb
Labels: bug

#30084 Fix Idempotency-Key ignored when scheduling a post
  app/services/post_status_service.rb
  spec/services/post_status_service_spec.rb
Labels: bug, to backport

#27733 Reword and rearrange Content Retention page
  app/views/admin/settings/content_retention/show.html.haml
  config/locales/en.yml
  config/locales/simple_form.en.yml
Labels: moderation

#28013 Change default ruby version to 3.3.1
  .github/workflows/test-ruby.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: ruby

#30102 Convert easy entrypoints files to Typescript
  app/javascript/entrypoints/application.ts
  app/javascript/entrypoints/error.ts
  app/javascript/entrypoints/inert.ts
  app/javascript/entrypoints/mailer.ts
  app/javascript/entrypoints/public-path.ts
  app/javascript/entrypoints/share.tsx
  package.json
  yarn.lock
Labels: typescript

#30106 Convert `entrypoints/sign_up` to Typescript
  app/javascript/entrypoints/sign_up.js
  app/javascript/entrypoints/sign_up.ts
Labels: typescript

#30068 Remove unused `Account.popular` scope
  app/models/account.rb
Labels: refactoring, ruby

#30087 Move `Account` limits to constants
  app/models/account.rb
Labels: refactoring, ruby

#30088 Use `EXPIRATION_DURATIONS` constant in `CustomFilter` class
  app/models/custom_filter.rb
  app/views/filters/_filter_fields.html.haml
Labels: refactoring, ruby

#30067 Use shared form partial for `admin/rules` views
  app/views/admin/rules/_form.html.haml
  app/views/admin/rules/edit.html.haml
  app/views/admin/rules/index.html.haml
Labels: refactoring, ruby

#30069 Use shared form partial for `admin/warning_presets` views
  app/views/admin/warning_presets/_form.html.haml
  app/views/admin/warning_presets/edit.html.haml
  app/views/admin/warning_presets/index.html.haml
Labels: refactoring, ruby

#30099 Remove usage of deprecated `defaultTypes` on React functional components
  app/javascript/mastodon/components/badge.jsx
Labels: refactoring, javascript

#30086 Use composable query in `Status.without_replies` scope
  app/models/status.rb
Labels: refactoring, ruby

#30125 Fix missing destory audit logs for Domain Allows
  app/controllers/admin/domain_allows_controller.rb
Labels: to backport

#30131 Change width breakpoint for mobile placement behavior
  app/javascript/styles/mastodon/components.scss
Labels: ui
