Repository mastodon/mastodon, pull requests merged in 2025-08, with the labels that each got.

#35629 Accept remote quotes of local quotes according to set policy
  app/lib/activitypub/activity/quote_request.rb
  app/serializers/activitypub/accept_quote_request_serializer.rb
  app/serializers/activitypub/quote_request_serializer.rb
  spec/lib/activitypub/activity/quote_request_spec.rb
  spec/serializers/activitypub/accept_quote_request_serializer_spec.rb
Labels: activitypub, build-image

#35710 Fix quote revocation not being streamed
  app/lib/activitypub/activity/delete.rb
  app/services/revoke_quote_service.rb
Labels: to backport

#35724 Add test for `Delete` of inlined `QuoteAuthorization`
  spec/lib/activitypub/activity/delete_spec.rb
Labels: to backport

#35752 Remove unnecessary limitation on manual build-security workflow
  .github/workflows/build-security.yml
Labels: pipeline

#35749 Move composer buttons to top
  app/javascript/mastodon/features/compose/components/compose_form.jsx
  app/javascript/mastodon/features/compose/components/language_dropdown.tsx
  app/javascript/styles/mastodon/components.scss
Labels: ui, javascript

#35771 First pass coverage addition for antispam class
  app/lib/antispam.rb
  spec/lib/antispam_spec.rb
Labels: to backport

#34824 Update sidekiq to version 8.0.7
  Gemfile
  Gemfile.lock
  README.md
  app/workers/concerns/bulk_mailing_concern.rb
Labels: dependencies, ruby

#35644 Refactor to reuse the one status partial across moderation tools
  app/helpers/application_helper.rb
  app/javascript/styles/mastodon/components.scss
  app/models/status_edit.rb
  app/views/admin/reports/_media_attachments.html.haml
  app/views/admin/reports/_status.html.haml
  app/views/admin/reports/show.html.haml
  app/views/admin/shared/_status.html.haml
  app/views/admin/shared/_status_attachments.html.haml
  app/views/admin/shared/_status_batch_row.html.haml
  app/views/admin/shared/_status_content.html.haml
  app/views/admin/status_edits/_status_edit.html.haml
  app/views/admin/statuses/index.html.haml
  app/views/admin/statuses/show.html.haml
  config/locales/en.yml
Labels: ui, refactoring, ruby, to backport

#35892 Fix Edit as well as “Delete & Redraft” on a poll not inserting empty option
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/reducers/compose.js
Labels: to backport

#35893 Consolidate labels for quote policy settings
  app/javascript/mastodon/features/ui/components/visibility_modal.tsx
  app/javascript/mastodon/locales/en.json
  config/locales/en.yml
Labels: to backport

#35909 Fix WebUI fetching deleted quote in an endless loop
  app/javascript/mastodon/components/status_quoted.tsx
Labels: to backport

#35562 Fix incorrect RSS feed MIME type in gzip_types directive
  dist/nginx.conf
Labels: deployment
