Repository mastodon/mastodon, pull requests merged in 2025-06, with the labels that each got.

#34814 Accept HTTP Message Signatures (RFC9421)
  app/controllers/concerns/signature_verification.rb
  app/lib/signed_request.rb
  spec/requests/signature_verification_spec.rb
Labels: activitypub, ruby

#34933 fix: Fix broken audio player layout in Safari, #34930
  app/javascript/styles/mastodon/components.scss
Labels: area/web interface

#34905 Replace local vars with `let` in JS-enabled system specs
  spec/system/account_notes_spec.rb
  spec/system/new_statuses_spec.rb
Labels: testing, refactoring

#34931 Add a way to easily unpin profiles from the featured account area
  app/javascript/mastodon/actions/accounts.js
  app/javascript/mastodon/components/account.tsx
Labels: javascript, area/web interface

#34907 feat: Add Storybook for component documentation, testing, and development
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/storybook-addon-vitest.d.ts
  .storybook/storybook-theme.ts
  .storybook/vitest.setup.ts
  app/javascript/mastodon/components/button/button.stories.tsx
  app/javascript/mastodon/components/button/index.tsx
  eslint.config.mjs
  package.json
  tsconfig.json
  vitest.config.mts
  vitest.shims.d.ts
  yarn.lock
Labels: ui

#34925 Rewrite `AccountNote` as Typescript functional component
  app/javascript/mastodon/features/account/components/account_note.jsx
  app/javascript/mastodon/features/account/components/account_note.tsx
  app/javascript/mastodon/features/account/containers/account_note_container.js
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
Labels: refactoring, javascript, typescript

#34989 Fix wrong styles on action bar in media modal in web UI
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui

#34996 Add basic support for remote attachments with multiple media types
  app/helpers/json_ld_helper.rb
  app/lib/activitypub/parser/media_attachment_parser.rb
  spec/lib/activitypub/parser/media_attachment_parser_spec.rb
Labels: to backport

#34985 Change "Explore" to "Trending" and remove explanation banners
  app/javascript/mastodon/features/explore/index.tsx
  app/javascript/mastodon/features/explore/links.jsx
  app/javascript/mastodon/features/explore/statuses.jsx
  app/javascript/mastodon/features/explore/tags.jsx
  app/javascript/mastodon/features/link_timeline/index.tsx
  app/javascript/mastodon/features/ui/components/navigation_panel.tsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#34872 Change media attachments in moderated posts to not be accessible
  app/controllers/backups_controller.rb
  app/controllers/media_proxy_controller.rb
  app/helpers/media_component_helper.rb
  app/helpers/routing_helper.rb
  app/models/media_attachment.rb
  app/models/status_edit.rb
  app/policies/media_attachment_policy.rb
  app/serializers/rest/media_attachment_serializer.rb
  app/services/remove_status_service.rb
  app/services/suspend_account_service.rb
  app/services/unsuspend_account_service.rb
  app/services/update_media_attachments_permissions_service.rb
  app/views/admin/reports/_media_attachments.html.haml
Labels: moderation

#34986 Change viewport behaviour to cover
  app/javascript/styles/mastodon/basics.scss
  app/views/layouts/application.html.haml
Labels: ui

#35041 Move "limited federation mode" config to `x.mastodon` area
  .rubocop_todo.yml
  app/controllers/api/base_controller.rb
  app/helpers/authorized_fetch_helper.rb
  app/helpers/domain_control_helper.rb
  app/serializers/initial_state_serializer.rb
  app/serializers/rest/instance_serializer.rb
  app/serializers/webfinger_serializer.rb
  config/initializers/2_limited_federation_mode.rb
  config/initializers/deprecations.rb
  config/mastodon.yml
  spec/requests/cache_spec.rb
  spec/requests/instance_actor_spec.rb
  spec/requests/well_known/webfinger_spec.rb
  spec/services/unallow_domain_service_spec.rb
  spec/system/admin/domain_allows_spec.rb
Labels: refactoring, ruby

#34964 Add FASP follow recommendation support
  app/controllers/api/v2/suggestions_controller.rb
  app/models/async_refresh.rb
  app/models/fasp/provider.rb
  app/workers/fasp/follow_recommendation_worker.rb
  spec/fabricators/fasp/provider_fabricator.rb
  spec/requests/api/v2/suggestions_spec.rb
  spec/workers/fasp/follow_recommendation_worker_spec.rb
Labels: ruby

#35040 Allow more flexible host/port treatment with LOCAL_DOMAIN values in tests
  spec/helpers/home_helper_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/remote_follow_spec.rb
  spec/requests/status_show_page_spec.rb
  spec/support/domain_helpers.rb
  spec/system/captcha_spec.rb
  spec/system/profile_spec.rb
  spec/system/redirections_spec.rb
  spec/workers/publish_scheduled_announcement_worker_spec.rb
Labels: testing

#35035 Fix vite helpers crash in development mode
  config/vite/plugin-mastodon-themes.ts
  lib/vite_ruby/sri_extensions.rb
Labels: javascript, ruby

#35076 Bump version to v4.4.0-beta.2
  CHANGELOG.md
  lib/mastodon/version.rb
Labels: build-image

#35070 Update rubocop to version 1.76.2
  .rubocop_todo.yml
  Gemfile.lock
  app/lib/emoji_formatter.rb
  app/lib/text_formatter.rb
Labels: lint fix 💅

#35074 fix: Prevent mobile navbar from overscrolling
  app/javascript/styles/mastodon/_variables.scss
  app/javascript/styles/mastodon/components.scss
Labels: area/web interface

#35096 fix: Prevent click on content warning banner in notification from opening the post
  app/javascript/mastodon/components/status_banner.tsx
Labels: typescript, area/web interface

#35120 Limit count to pending&trending on admin/trends/tags page
  app/controllers/admin/trends/tags_controller.rb
  spec/system/admin/trends/tags_spec.rb
Labels: ruby

#35126 Change terms of service e-mail job to be iterable
  app/workers/admin/distribute_announcement_notification_worker.rb
  app/workers/admin/distribute_terms_of_service_notification_worker.rb
  app/workers/concerns/bulk_mailer.rb
Labels: performance

#35147 Fix “Alt text” button submitting form in moderation interface
  app/javascript/mastodon/components/alt_text_badge.tsx
Labels: to backport

#35015 Use `config_for` for omniauth enabled values
  app/controllers/application_controller.rb
  config/application.rb
  config/initializers/3_omniauth.rb
  config/omniauth.yml
  spec/requests/omniauth_callbacks_spec.rb
Labels: refactoring, ruby

#31529 Implement Instance Moderation Notes
  app/controllers/admin/instances/moderation_notes_controller.rb
  app/controllers/admin/instances_controller.rb
  app/javascript/styles/mastodon/admin.scss
  app/models/concerns/account/associations.rb
  app/models/instance.rb
  app/models/instance_moderation_note.rb
  app/policies/instance_moderation_note_policy.rb
  app/views/admin/instances/show.html.haml
  app/views/admin/report_notes/_report_note.html.haml
  config/locales/en.yml
  config/routes/admin.rb
  db/migrate/20250328153843_create_instance_moderation_notes.rb
  db/schema.rb
  spec/fabricators/instance_moderation_note_fabricator.rb
  spec/models/instance_moderation_note_spec.rb
  spec/models/instance_spec.rb
  spec/requests/admin/instances/moderation_notes_spec.rb
  spec/requests/admin/instances_spec.rb
  spec/system/admin/account_moderation_notes_spec.rb
  spec/system/admin/instance/moderation_notes_spec.rb
Labels: moderation, ruby

#35204 Add coverage for `TermsOfService` scopes/validations
  app/models/terms_of_service.rb
  spec/models/terms_of_service_spec.rb
Labels: testing, ruby
