Repository mastodon/mastodon, pull requests merged in 2025-04, with the labels that each got.

#34337 Fix static version of animated PNG emojis not being properly extracted
  lib/paperclip/vips_lazy_thumbnail.rb
Labels: to backport

#34338 Backport changes to v4.3
  lib/paperclip/vips_lazy_thumbnail.rb
Labels: backport

#34324 Upgrade to ESLint v9 flat config
  .eslintignore
  .eslintrc.js
  .github/renovate.json5
  .github/workflows/lint-js.yml
  .prettierrc.js
  app/javascript/entrypoints/public.tsx
  app/javascript/mastodon/components/counters.tsx
  app/javascript/mastodon/components/router.tsx
  app/javascript/mastodon/features/emoji/emoji_compressed.js
  app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light.ts
  app/javascript/mastodon/features/emoji/unicode_to_filename.js
  app/javascript/mastodon/features/emoji/unicode_to_unified_name.js
  app/javascript/mastodon/service_worker/web_push_locales.js
  eslint.config.mjs
  package.json
  streaming/.eslintrc.cjs
  streaming/eslint.config.mjs
  streaming/lint-staged.config.mjs
  streaming/package.json
  streaming/tsconfig.json
  yarn.lock
Labels: dependencies, lint fix 💅

#34341 Extract constant for `Poll` last fetch duration check
  app/models/poll.rb
Labels: refactoring, ruby

#34344 Refactor `<CopyIconButton>` to TypeScript
  app/javascript/mastodon/components/copy_icon_button.tsx
Labels: refactoring, typescript

#34342 Refactoring: Move `SignatureVerificationError` into `Mastodon` namespace
  app/controllers/concerns/signature_verification.rb
  app/lib/fasp/request.rb
  lib/exceptions.rb
  spec/lib/fasp/request_spec.rb
Labels: refactoring, ruby

#34347 Refactor `<DomainBlocks>` to TypeScript
  app/javascript/mastodon/actions/domain_blocks.js
  app/javascript/mastodon/api/domain_blocks.ts
  app/javascript/mastodon/components/domain.tsx
  app/javascript/mastodon/features/domain_blocks/index.jsx
  app/javascript/mastodon/features/domain_blocks/index.tsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/domain_lists.js
  app/javascript/mastodon/reducers/index.ts
  app/javascript/styles/mastodon/components.scss
Labels: refactoring, typescript

#34351 Fix Typescript dependency resolution
  package.json
  streaming/package.json
  yarn.lock
Labels: dependencies

#34340 Convert `settings/pictures` spec controller->request
  spec/controllers/settings/pictures_controller_spec.rb
  spec/requests/settings/pictures_spec.rb
Labels: testing, refactoring

#34349 Refactor local-URI-to-account resolving
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/tag_manager.rb
  app/services/activitypub/synchronize_followers_service.rb
  spec/lib/activitypub/tag_manager_spec.rb
Labels: refactoring

#34398 Fix usage of incorrect API endpoint for suggestion deletion
  app/javascript/mastodon/api/suggestions.ts
Labels: bug, to backport

#34355 Refactor `<FollowedTags>` into TypeScript
  app/javascript/mastodon/actions/tags.js
  app/javascript/mastodon/api/tags.ts
  app/javascript/mastodon/components/hashtag.tsx
  app/javascript/mastodon/features/followed_tags/index.jsx
  app/javascript/mastodon/features/followed_tags/index.tsx
  app/javascript/mastodon/reducers/followed_tags.js
  app/javascript/mastodon/reducers/index.ts
  app/javascript/styles/mastodon/components.scss
Labels: ui, refactoring, typescript

#34356 Refactor `<FavouritedStatuses>` and `<BookmarkedStatuses>` into TypeScript
  app/javascript/mastodon/features/bookmarked_statuses/index.jsx
  app/javascript/mastodon/features/bookmarked_statuses/index.tsx
  app/javascript/mastodon/features/favourited_statuses/index.jsx
  app/javascript/mastodon/features/favourited_statuses/index.tsx
  app/javascript/mastodon/reducers/status_lists.js
  app/javascript/mastodon/selectors/index.js
  app/javascript/mastodon/selectors/statuses.ts
Labels: refactoring, typescript

#34392 Change unfollow button label from "Mutual" to "Unfollow" in web UI
  app/javascript/mastodon/components/follow_button.tsx
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
Labels: ui

#34345 Change alt text modal to use spring animations in web UI
  app/javascript/mastodon/features/alt_text_modal/index.tsx
Labels: ui

#34357 Refactor `<Dropdown>` into TypeScript
  app/javascript/mastodon/actions/dropdown_menu.ts
  app/javascript/mastodon/components/account.tsx
  app/javascript/mastodon/components/dropdown_menu.jsx
  app/javascript/mastodon/components/dropdown_menu.tsx
  app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
  app/javascript/mastodon/components/edited_timestamp/index.jsx
  app/javascript/mastodon/components/edited_timestamp/index.tsx
  app/javascript/mastodon/components/icon_button.tsx
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/containers/dropdown_menu_container.js
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
  app/javascript/mastodon/features/compose/components/action_bar.tsx
  app/javascript/mastodon/features/direct_timeline/components/conversation.jsx
  app/javascript/mastodon/features/hashtag_timeline/components/hashtag_header.tsx
  app/javascript/mastodon/features/lists/index.tsx
  app/javascript/mastodon/features/notifications/components/notification_request.jsx
  app/javascript/mastodon/features/notifications/requests.jsx
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/mastodon/features/status/components/detailed_status.tsx
  app/javascript/mastodon/models/dropdown_menu.ts
  app/javascript/mastodon/reducers/dropdown_menu.ts
Labels: refactoring, typescript

#33353 Remove deprecated single-argument variation of `UnfilterNotificationsWorker`
  app/workers/unfilter_notifications_worker.rb
  spec/workers/unfilter_notifications_worker_spec.rb
Labels: breaking, ruby

#34371 Remove deprecated `Import` model
  app/lib/admin/metrics/dimension/space_usage_dimension.rb
  app/models/import.rb
  app/services/import_service.rb
  app/workers/import/relationship_worker.rb
  app/workers/import_worker.rb
  config/initializers/paperclip.rb
  db/migrate/20250410144908_drop_imports.rb
  db/schema.rb
  lib/mastodon/cli/media.rb
  spec/fabricators/import_fabricator.rb
  spec/models/import_spec.rb
  spec/services/import_service_spec.rb
  spec/workers/import_worker_spec.rb
Labels: refactoring, ruby

#34400 Extract `frontend_translations` helper to support module
  spec/support/system_helpers.rb
  spec/system/account_notes_spec.rb
  spec/system/log_out_spec.rb
  spec/system/new_statuses_spec.rb
  spec/system/share_entrypoint_spec.rb
Labels: testing, refactoring

#34391 Add dropdown to lists of accounts in web UI
  app/javascript/mastodon/components/account.tsx
Labels: ui

#34414 Refactor `StatusCacheHydrator`
  app/lib/status_cache_hydrator.rb
Labels: refactoring, ruby

#34430 Fix editing and redrafting polls
  app/javascript/mastodon/reducers/compose.js
Labels: bug, area/web interface

#34431 Fix empty menu section in status dropdown
  app/javascript/mastodon/components/status_action_bar.jsx
Labels: area/web interface

#34393 Add dropdown menu to hashtag links in web UI
  app/javascript/mastodon/components/dropdown_menu.tsx
  app/javascript/mastodon/components/edited_timestamp/index.tsx
  app/javascript/mastodon/components/hashtag_bar.tsx
  app/javascript/mastodon/components/status_content.jsx
  app/javascript/mastodon/features/ui/components/hashtag_menu_controller.tsx
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui, typescript

#34422 Fix "Feature on profile" option on profile dropdown menu in web UI
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
Labels: bug

#34452 Use enum validation instead of `ArgumentError` rescue for `List` replies policy check
  app/controllers/api/v1/lists_controller.rb
  app/models/list.rb
  spec/requests/api/v1/lists_spec.rb
Labels: refactoring, ruby

#34421 Add REST API for fetching an account's endorsed accounts
  app/controllers/api/v1/accounts/endorsements_controller.rb
  app/controllers/api/v1/accounts/featured_tags_controller.rb
  app/controllers/api/v1/accounts/pins_controller.rb
  config/routes/api.rb
  spec/requests/api/v1/accounts/endorsements_spec.rb
Labels: api

#34453 Use bundler version 2.6.8
  Gemfile.lock
Labels: dependencies

#34370 Add initial support for ingesting and verifying remote quote posts
  FEDERATION.md
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/activity/delete.rb
  app/lib/activitypub/parser/status_parser.rb
  app/lib/status_cache_hydrator.rb
  app/models/concerns/status/snapshot_concern.rb
  app/models/quote.rb
  app/models/status.rb
  app/models/status_edit.rb
  app/presenters/status_relationships_presenter.rb
  app/serializers/rest/base_quote_serializer.rb
  app/serializers/rest/quote_serializer.rb
  app/serializers/rest/shallow_quote_serializer.rb
  app/serializers/rest/shallow_status_serializer.rb
  app/serializers/rest/status_edit_serializer.rb
  app/serializers/rest/status_serializer.rb
  app/services/activitypub/process_status_update_service.rb
  app/services/activitypub/verify_quote_service.rb
  app/workers/activitypub/quote_refresh_worker.rb
  app/workers/activitypub/refetch_and_verify_quote_worker.rb
  db/migrate/20250411094808_create_quotes.rb
  db/migrate/20250411095859_add_quote_id_to_status_edit.rb
  db/schema.rb
  spec/fabricators/quote_fabricator.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/lib/activitypub/activity/delete_spec.rb
  spec/lib/status_cache_hydrator_spec.rb
  spec/serializers/rest/quote_serializer_spec.rb
  spec/serializers/rest/shallow_quote_serializer_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
  spec/services/activitypub/verify_quote_service_spec.rb
  spec/workers/activitypub/quote_refresh_worker_spec.rb
  spec/workers/activitypub/refetch_and_verify_quote_worker_spec.rb
Labels: api, activitypub, build-image

#34491 Fix featured hashtags not showing year for date in web UI
  app/javascript/mastodon/features/account_featured/components/featured_tag.tsx
Labels: ui

#34497 Update `rubocop-rspec` to version 3.6.0
  .rubocop_todo.yml
  Gemfile.lock
  spec/controllers/application_controller_spec.rb
  spec/controllers/auth/registrations_controller_spec.rb
  spec/controllers/concerns/localized_spec.rb
  spec/controllers/relationships_controller_spec.rb
  spec/controllers/settings/imports_controller_spec.rb
  spec/controllers/settings/two_factor_authentication/confirmations_controller_spec.rb
  spec/lib/cache_buster_spec.rb
  spec/lib/fasp/request_spec.rb
  spec/lib/link_details_extractor_spec.rb
  spec/lib/mastodon/cli/ip_blocks_spec.rb
  spec/lib/mastodon/redis_configuration_spec.rb
  spec/mailers/notification_mailer_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/account_spec.rb
  spec/models/custom_filter_spec.rb
  spec/models/invite_spec.rb
  spec/models/ip_block_spec.rb
  spec/models/login_activity_spec.rb
  spec/models/mute_spec.rb
  spec/models/poll_spec.rb
  spec/models/preview_card_provider_spec.rb
  spec/models/preview_card_trend_spec.rb
  spec/models/session_activation_spec.rb
  spec/models/status_spec.rb
  spec/models/status_trend_spec.rb
  spec/models/tag_spec.rb
  spec/models/tag_trend_spec.rb
  spec/policies/admin/fasp/provider_policy_spec.rb
  spec/requests/oauth/token_spec.rb
  spec/requests/omniauth_callbacks_spec.rb
  spec/services/activitypub/fetch_remote_account_service_spec.rb
  spec/services/activitypub/fetch_remote_actor_service_spec.rb
  spec/services/bulk_import_row_service_spec.rb
  spec/services/delete_account_service_spec.rb
  spec/services/suspend_account_service_spec.rb
  spec/services/unsuspend_account_service_spec.rb
  spec/workers/import/row_worker_spec.rb
  spec/workers/move_worker_spec.rb
  spec/workers/scheduler/accounts_statuses_cleanup_scheduler_spec.rb
Labels: refactoring, ruby, lint fix 💅

#34548 Fix sign-up e-mail confirmation page reloading on error or redirect
  app/javascript/entrypoints/sign_up.ts
Labels: to backport

#34455 Change account search to be more forgiving of spaces
  app/chewy/accounts_index.rb
  app/services/account_search_service.rb
Labels: area/search

#34549 Fix incorrect redirect in response to unauthenticated API requests in limited federation mode
  app/controllers/api/base_controller.rb
  app/controllers/application_controller.rb
Labels: to backport

#34489 Add REST API for featuring and unfeaturing a hashtag
  app/controllers/api/v1/featured_tags_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/settings/featured_tags_controller.rb
  app/models/featured_tag.rb
  app/presenters/tag_relationships_presenter.rb
  app/serializers/rest/tag_serializer.rb
  app/services/create_featured_tag_service.rb
  app/services/remove_featured_tag_service.rb
  config/routes/api.rb
  lib/mastodon/version.rb
  spec/models/featured_tag_spec.rb
  spec/requests/api/v1/featured_tags_spec.rb
  spec/requests/api/v1/tags_spec.rb
  spec/services/create_featured_tag_service_spec.rb
  spec/services/remove_featured_tag_service_spec.rb
Labels: api

#34492 Change "Pin on profile" to "Feature on profile" for posts in web UI
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#34480 Reject incoming `QuoteRequest` activities
  app/helpers/context_helper.rb
  app/lib/activitypub/activity.rb
  app/lib/activitypub/activity/quote_request.rb
  app/serializers/activitypub/quote_request_serializer.rb
  app/serializers/activitypub/reject_quote_request_serializer.rb
  spec/lib/activitypub/activity/quote_request_spec.rb
Labels: activitypub

#34479 Add support for ingesting quote policies
  app/lib/activitypub/activity/create.rb
  app/lib/activitypub/parser/status_parser.rb
  app/models/status.rb
  app/services/activitypub/process_status_update_service.rb
  db/migrate/20250428095029_add_quote_approval_policy_to_statuses.rb
  db/schema.rb
  spec/lib/activitypub/parser/status_parser_spec.rb
Labels: activitypub

#34559 Refactor `<ActionsModal>` to TypeScript
  app/javascript/mastodon/components/dropdown_menu.tsx
  app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
  app/javascript/mastodon/features/compose/containers/privacy_dropdown_container.js
  app/javascript/mastodon/features/ui/components/actions_modal.jsx
  app/javascript/mastodon/features/ui/components/actions_modal.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/models/dropdown_menu.ts
  app/javascript/styles/mastodon/components.scss
Labels: refactoring, typescript

#34490 Add ability to feature and unfeature hashtags from web UI
  app/javascript/mastodon/actions/tags_typed.ts
  app/javascript/mastodon/api/tags.ts
  app/javascript/mastodon/api_types/tags.ts
  app/javascript/mastodon/features/hashtag_timeline/components/hashtag_header.tsx
  app/javascript/mastodon/locales/en.json
Labels: ui

#34566 Fix `tootctl search deploy --only-mapping` not updating index settings
  lib/chewy/index_extensions.rb
  lib/mastodon/cli/search.rb
Labels: bug, area/search

#34506 Refactor context reducer to TypeScript
  app/javascript/mastodon/actions/statuses.js
  app/javascript/mastodon/actions/statuses_typed.ts
  app/javascript/mastodon/api/statuses.ts
  app/javascript/mastodon/api_types/statuses.ts
  app/javascript/mastodon/features/notifications_v2/components/notification_mention.tsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/reducers/contexts.js
  app/javascript/mastodon/reducers/contexts.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/mastodon/selectors/contexts.ts
  app/javascript/mastodon/store/index.ts
  app/javascript/mastodon/store/typed_functions.ts
Labels: refactoring, typescript

#34573 Fix context selector trying to mutate immutable state
  app/javascript/mastodon/selectors/contexts.ts
Labels: bug

#34574 Add built-in context for interaction policies
  app/helpers/context_helper.rb
Labels: bug, activitypub, to backport

#34568 Add endorsed accounts to profiles in web UI
  app/javascript/mastodon/actions/accounts_typed.ts
  app/javascript/mastodon/actions/featured_tags.js
  app/javascript/mastodon/actions/featured_tags.ts
  app/javascript/mastodon/actions/importer/accounts.ts
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/api/accounts.ts
  app/javascript/mastodon/features/account_featured/index.tsx
  app/javascript/mastodon/features/account_gallery/index.tsx
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
  app/javascript/mastodon/features/account_timeline/index.jsx
  app/javascript/mastodon/features/compose/components/action_bar.tsx
  app/javascript/mastodon/features/followers/index.jsx
  app/javascript/mastodon/features/following/index.jsx
  app/javascript/mastodon/hooks/useAccountId.ts
  app/javascript/mastodon/hooks/useAccountVisibility.ts
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/accounts.ts
  app/javascript/mastodon/reducers/accounts_map.js
  app/javascript/mastodon/reducers/accounts_map.ts
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/user_lists.js
Labels: ui
