Repository mastodon/mastodon, pull requests merged in 2025-02, with the labels that each got.

#33818 Fix emoji rewrite adding unnecessary curft to the DOM for most emoji
  app/javascript/mastodon/features/emoji/__tests__/emoji-test.js
  app/javascript/mastodon/features/emoji/emoji.js
Labels: to backport

#33827 Change preview cards to be shown when Content Warnings are expanded
  app/javascript/mastodon/components/status.jsx
Labels: to backport, area/web interface

#33842 Fix filtering for lists
  app/lib/feed_manager.rb
  spec/lib/feed_manager_spec.rb
Labels: bug, to backport

#33788 Use github's native arm64 runners for docker builds
  .github/workflows/build-container-image.yml
  .github/workflows/build-nightly.yml
  .github/workflows/build-push-pr.yml
  .github/workflows/build-releases.yml
  .github/workflows/build-security.yml
  .github/workflows/test-image-build.yml
Labels: build-image

#33858 Fix potential inefficiency in media privacy system check
  app/lib/admin/system_check/media_privacy_check.rb
Labels: performance

#33880 Convert `settings/featured_tags` controller->request/system spec
  spec/controllers/settings/featured_tags_controller_spec.rb
  spec/requests/settings/featured_tags_spec.rb
  spec/system/settings/featured_tags_spec.rb
Labels: testing

#33881 Remove unused "oversized" spec fixture PNG file
  spec/fixtures/files/4096x4097.png
Labels: testing

#33882 Run optimize PNG on archetypes images
  app/javascript/images/archetypes/booster.png
  app/javascript/images/archetypes/lurker.png
  app/javascript/images/archetypes/oracle.png
  app/javascript/images/archetypes/pollster.png
  app/javascript/images/archetypes/replier.png
Labels: performance

#33879 Use common `before` and contexts in admin/base controller spec
  spec/controllers/admin/base_controller_spec.rb
Labels: testing, ruby

#33887 Use github's native arm64 runners for docker builds
  .github/workflows/build-container-image.yml
  .github/workflows/build-nightly.yml
  .github/workflows/build-push-pr.yml
  .github/workflows/build-releases.yml
  .github/workflows/test-image-build.yml
  .github/workflows/test-ruby.yml
Labels: backport, build-image

#33888 Use github's native arm64 runners for docker builds
  .github/workflows/build-container-image.yml
  .github/workflows/build-push-pr.yml
  .github/workflows/build-releases.yml
  .github/workflows/test-image-build.yml
  .github/workflows/test-ruby.yml
Labels: backport, build-image

#33886 Use github's native arm64 runners for docker builds
  .github/workflows/build-container-image.yml
  .github/workflows/build-nightly.yml
  .github/workflows/build-push-pr.yml
  .github/workflows/build-releases.yml
  .github/workflows/build-security.yml
  .github/workflows/test-image-build.yml
Labels: backport, build-image

#33911 Fix handling of duplicate mentions in incoming status `Update`
  app/services/activitypub/process_status_update_service.rb
  spec/lib/activitypub/activity/create_spec.rb
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: to backport

#33774 Fix streaming server not filtering unknown-language posts from public timelines
  streaming/index.js
Labels: javascript, streaming, to backport

#33947 Convert `admin/roles` controller spec to request/sytem specs
  spec/controllers/admin/roles_controller_spec.rb
  spec/requests/admin/roles_spec.rb
  spec/system/admin/roles_spec.rb
Labels: testing

#33955 Remove `rails-controller-testing` gem
  Gemfile
  Gemfile.lock
  spec/controllers/admin/domain_blocks_controller_spec.rb
Labels: testing

#33994 Add choice of law to terms of service generator
  app/models/terms_of_service/generator.rb
  app/views/admin/terms_of_service/generates/show.html.haml
  config/locales/simple_form.en.yml
  config/templates/terms-of-service.md
  spec/controllers/admin/terms_of_service/generates_controller_spec.rb
Labels: legal

#33990 Fix `GET /api/v2/notifications/:id` and `POST /api/v2/notifications/:id/dismiss` for ungrouped notifications
  app/controllers/api/v2/notifications_controller.rb
  app/models/concerns/notification/groups.rb
  spec/requests/api/v2/notifications_spec.rb
Labels: api, to backport

#34007 Fix docker image build workflow on stable-4.1
  .github/workflows/build-container-image.yml
  .github/workflows/build-push-pr.yml
Labels: build-image

#34021 Change HTML sanitization to remove unusable and unused `embed` tag
  lib/sanitize_ext/sanitize_config.rb
Labels: to backport

#34034 Update rubocop to version 1.73.1
  .rubocop_todo.yml
  Gemfile.lock
  app/models/concerns/account/interactions.rb
Labels: dependencies, lint fix 💅

#34036 Rely on `haml-lint` parallel default
  .github/workflows/lint-haml.yml
  lint-staged.config.js
Labels: lint fix 💅

#33784 Change alt text reminder to not appear for private mentions in web UI
  app/javascript/mastodon/features/compose/components/compose_form.jsx
Labels: ui
