Repository mastodon/mastodon, pull requests merged in 2025-09, with the labels that each got.

#36004 Add compatibility hack for GoToSocial interaction policies
  app/serializers/activitypub/note_serializer.rb
Labels: activitypub

#36055 Move quote post fallback removal import-time
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/components/status_content.jsx
Labels: to backport

#36158 Fix posts when omitting quote policy and default policy is `nobody`
  app/controllers/concerns/api/interaction_policies_concern.rb
  spec/requests/api/v1/statuses_spec.rb
Labels: build-image

#36209 Renovate config improvements
  .github/renovate.json5
  package.json
Labels: dependencies

#36217 Add support for `has:quote` in search
  app/models/concerns/status/search_concern.rb
Labels: to backport
