Repository mastodon/mastodon, pull requests merged in 2025-05, with the labels that each got.

#34520 Change design of audio player in web UI
  app/javascript/mastodon/blurhash.ts
  app/javascript/mastodon/components/picture_in_picture_placeholder.jsx
  app/javascript/mastodon/components/picture_in_picture_placeholder.tsx
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/containers/media_container.jsx
  app/javascript/mastodon/features/alt_text_modal/index.tsx
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/audio/index.tsx
  app/javascript/mastodon/features/audio/visualizer.js
  app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx
  app/javascript/mastodon/features/notifications_v2/components/notification_mention.tsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.tsx
  app/javascript/mastodon/features/picture_in_picture/index.tsx
  app/javascript/mastodon/features/status/components/detailed_status.tsx
  app/javascript/mastodon/features/ui/components/audio_modal.jsx
  app/javascript/mastodon/features/ui/components/audio_modal.tsx
  app/javascript/mastodon/features/ui/components/media_modal.jsx
  app/javascript/mastodon/features/ui/components/video_modal.jsx
  app/javascript/mastodon/features/video/index.tsx
  app/javascript/mastodon/hooks/useAudioVisualizer.ts
  app/javascript/mastodon/reducers/statuses.js
  app/javascript/material-icons/400-24px/pip_exit-fill.svg
  app/javascript/material-icons/400-24px/pip_exit.svg
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/css_variables.scss
Labels: ui

#34581 Add warning for REDIS_NAMESPACE deprecation at startup
  config/initializers/deprecations.rb
Labels: to backport

#34454 Migrate from Jest to Vitest
  .github/workflows/test-js.yml
  CONTRIBUTING.md
  app/javascript/mastodon/components/__tests__/__snapshots__/autosuggest_emoji-test.jsx.snap
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar-test.jsx.snap
  app/javascript/mastodon/components/__tests__/__snapshots__/avatar_overlay-test.jsx.snap
  app/javascript/mastodon/components/__tests__/__snapshots__/button-test.jsx.snap
  app/javascript/mastodon/components/__tests__/__snapshots__/display_name-test.jsx.snap
  app/javascript/mastodon/components/__tests__/button-test.jsx
  app/javascript/mastodon/features/ui/components/__tests__/column-test.jsx
  app/javascript/mastodon/test_helpers.tsx
  app/javascript/mastodon/test_setup.js
  config/vite.json
  eslint.config.mjs
  jest.config.js
  package.json
  tsconfig.json
  vite.config.mts
  yarn.lock
Labels: testing, refactoring, javascript

#34677 Fix emoji bundle size
  app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.jsx
  app/javascript/mastodon/features/emoji/emoji_compressed.d.ts
  app/javascript/mastodon/features/emoji/emoji_compressed.js
  app/javascript/mastodon/features/emoji/emoji_picker.js
  app/javascript/mastodon/features/emoji/emoji_picker.tsx
  app/javascript/types/emoji_picker.d.ts
  tsconfig.json
Labels: ui, performance, javascript, typescript, area/web interface

#34415 Add support for FASP data sharing
  app/controllers/api/fasp/data_sharing/v0/backfill_requests_controller.rb
  app/controllers/api/fasp/data_sharing/v0/continuations_controller.rb
  app/controllers/api/fasp/data_sharing/v0/event_subscriptions_controller.rb
  app/lib/fasp/request.rb
  app/models/account.rb
  app/models/concerns/account/fasp_concern.rb
  app/models/concerns/favourite/fasp_concern.rb
  app/models/concerns/status/fasp_concern.rb
  app/models/fasp.rb
  app/models/fasp/backfill_request.rb
  app/models/fasp/provider.rb
  app/models/fasp/subscription.rb
  app/models/favourite.rb
  app/models/status.rb
  app/workers/fasp/announce_account_lifecycle_event_worker.rb
  app/workers/fasp/announce_content_lifecycle_event_worker.rb
  app/workers/fasp/announce_trend_worker.rb
  app/workers/fasp/backfill_worker.rb
  config/routes/fasp.rb
  config/sidekiq.yml
  db/migrate/20241213130230_create_fasp_subscriptions.rb
  db/migrate/20250103131909_create_fasp_backfill_requests.rb
  db/schema.rb
  spec/fabricators/account_fabricator.rb
  spec/fabricators/fasp/backfill_request_fabricator.rb
  spec/fabricators/fasp/subscription_fabricator.rb
  spec/models/concerns/account/fasp_concern_spec.rb
  spec/models/concerns/favourite/fasp_concern_spec.rb
  spec/models/concerns/status/fasp_concern_spec.rb
  spec/models/fasp/backfill_request_spec.rb
  spec/models/fasp/subscription_spec.rb
  spec/requests/api/fasp/data_sharing/v0/backfill_requests_spec.rb
  spec/requests/api/fasp/data_sharing/v0/continuations_spec.rb
  spec/requests/api/fasp/data_sharing/v0/event_subscriptions_spec.rb
  spec/workers/fasp/announce_account_lifecycle_event_worker_spec.rb
  spec/workers/fasp/announce_content_lifecycle_event_worker_spec.rb
  spec/workers/fasp/announce_trend_worker_spec.rb
  spec/workers/fasp/backfill_worker_spec.rb
Labels: activitypub, ruby

#34733 Bypass date of birth check in `dev:populate_sample_data` task
  lib/tasks/dev.rake
Labels: ruby, local development

#30413 Drop compatibility with Redis < 6.2
  README.md
  app/controllers/auth/sessions_controller.rb
Labels: deployment, dependencies, ruby

#34665 Drop redis namespace code (except for Rails cache)
  config/initializers/chewy.rb
  lib/mastodon/redis_configuration.rb
  spec/lib/mastodon/redis_configuration_spec.rb
  spec/support/streaming_server_manager.rb
  streaming/redis.js
Labels: refactoring, ruby

#34390 Change Node.js minimum version to Node 20
  README.md
  package.json
  streaming/package.json
Labels: dependencies

#34734 Use `ActiveSupport::TaggedLogging.logger` shorthand to set logger
  config/environments/development.rb
Labels: refactoring, ruby

#34757 Remove `OTP_SECRET` env configuration from setup
  .env.production.sample
  app.json
  lib/tasks/mastodon.rake
  scalingo.json
Labels: deployment, ruby

#34742 Remove `redis-namespace` gem
  Gemfile
  Gemfile.lock
  app/lib/admin/metrics/dimension/software_versions_dimension.rb
  app/lib/admin/metrics/dimension/space_usage_dimension.rb
  app/lib/redis_connection.rb
  config/application.rb
  lib/redis/namespace_extensions.rb
  spec/controllers/oauth/authorized_applications_controller_spec.rb
  spec/models/user_spec.rb
  spec/system/settings/applications_spec.rb
Labels: dependencies

#34738 Add rendering of quote posts in web UI
  app/javascript/mastodon/actions/importer/index.js
  app/javascript/mastodon/actions/importer/normalizer.js
  app/javascript/mastodon/components/status.jsx
  app/javascript/mastodon/components/status_list.jsx
  app/javascript/mastodon/components/status_quoted.tsx
  app/javascript/mastodon/features/account_featured/index.tsx
  app/javascript/mastodon/features/notifications/components/notification.jsx
  app/javascript/mastodon/features/notifications_v2/components/notification_with_status.tsx
  app/javascript/mastodon/features/search/index.tsx
  app/javascript/mastodon/features/status/components/detailed_status.tsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/css_variables.scss
Labels: ui

#34748 Remove `OTP_SECRET` env configuration
  app/models/user.rb
  config/environments/development.rb
Labels: deployment, ruby

#34775 Fix `Style/PreferredHashMethods` cop
  .rubocop_todo.yml
  config/initializers/paperclip.rb
Labels: ruby, lint fix 💅

#34788 Revert React Spring to 9.7.5 and updates Renovate
  .github/renovate.json5
  app/javascript/mastodon/features/video/components/hotkey_indicator.tsx
  package.json
  yarn.lock
Labels: bug, dependencies, area/web interface

#34789 Fix handling of inlined `featured` collections in ActivityPub actor objects
  app/services/activitypub/fetch_featured_collection_service.rb
  app/services/activitypub/process_account_service.rb
  app/workers/activitypub/synchronize_featured_collection_worker.rb
  spec/services/activitypub/fetch_featured_collection_service_spec.rb
  spec/services/activitypub/process_account_service_spec.rb
Labels: to backport

#34745 Update sidekiq to version 7
  Gemfile
  Gemfile.lock
  app/lib/redis_connection.rb
  app/workers/scheduler/self_destruct_scheduler.rb
  config/database.yml
  config/initializers/sidekiq.rb
  lib/mastodon/redis_configuration.rb
  spec/lib/mastodon/redis_configuration_spec.rb
  spec/rails_helper.rb
Labels: dependencies, ruby

#34820 Add language picker to server rules section
  app/javascript/mastodon/components/dropdown_selector.tsx
  app/javascript/mastodon/features/about/components/rules.tsx
  app/javascript/mastodon/features/about/components/section.tsx
  app/javascript/mastodon/features/about/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/styles/mastodon/about.scss
  app/javascript/styles/mastodon/components.scss
Labels: ui, typescript

#34825 Regenerate rubocop todo with 1.75.7
  .rubocop_todo.yml
Labels: ruby, lint fix 💅

#34816 Update `rack` to version 3
  .github/renovate.json5
  Gemfile
  Gemfile.lock
  config/initializers/mime_types.rb
Labels: dependencies, ruby

#34749 Fix `NoMethodError` in edge case of emoji cache handling
  app/lib/entity_cache.rb
Labels: ruby

#34844 Fix `Style/FetchEnvVar` cop in production env config
  .rubocop_todo.yml
  config/environments/production.rb
Labels: lint fix 💅

#34845 Use `config_for` for VAPID key storage
  .rubocop_todo.yml
  app/lib/web_push_request.rb
  app/serializers/rest/application_serializer.rb
  app/serializers/rest/instance_serializer.rb
  app/serializers/rest/web_push_subscription_serializer.rb
  app/views/shared/_web_app.html.haml
  config/application.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/vapid.rb
  config/vapid.yml
  spec/requests/api/v1/apps/credentials_spec.rb
  spec/requests/api/v1/apps_spec.rb
  spec/serializers/rest/instance_serializer_spec.rb
  spec/workers/web/push_notification_worker_spec.rb
Labels: refactoring

#34846 Fix `Style/FetchEnvVar` cop in devise config
  .rubocop_todo.yml
  config/initializers/devise.rb
Labels: lint fix 💅

#34850 Update `fabrication` to version 3.0.0
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#34858 Fix pinned carousel scroll on mobile
  app/javascript/styles/mastodon/components.scss
Labels: bug, ui, area/web interface, build-image

#34792 feat: Add relationship info to hover card
  app/javascript/mastodon/components/hover_card_account.tsx
  app/javascript/styles/mastodon/components.scss
Labels: ui, typescript

#34807 Make account header profile pic exactly 2x post profile pic
  app/javascript/mastodon/features/account_timeline/components/account_header.tsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#34859 Increase capybara default timeout to reduce test flakiness
  spec/support/capybara.rb
Labels: pipeline, to backport

#34863 Fix inconsistent filtering of silenced accounts for other silenced accounts
  app/lib/status_filter.rb
Labels: to backport

#34862 Fix `Style/FetchEnvVar` cop in omniauth config
  .rubocop_todo.yml
  config/initializers/3_omniauth.rb
Labels: lint fix 💅

#34864 Fix multiple issues in quoted posts hydration
  app/lib/status_cache_hydrator.rb
  spec/lib/status_cache_hydrator_spec.rb
Labels: ruby
