Repository mastodon/mastodon, pull requests merged in 2025-01, with the labels that each got.

#33406 Fix intermittent failure on ap/activity/create spec timestamp check
  spec/lib/activitypub/activity/create_spec.rb
Labels: testing, ruby, pipeline, to backport

#33425 Fix intermittent failure on ap/activity/update spec timestamp check
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: to backport

#33377 Convert `admin/rules` spec controller->system
  spec/controllers/admin/rules_controller_spec.rb
  spec/system/admin/rules_spec.rb
  spec/system/admin/webhooks_spec.rb
Labels: testing, ruby

#27209 Fix favorite & bookmark text toggle in timeline, status and image view
  app/javascript/mastodon/components/status_action_bar.jsx
  app/javascript/mastodon/features/picture_in_picture/components/footer.jsx
  app/javascript/mastodon/features/status/components/action_bar.jsx
  app/javascript/mastodon/locales/en.json
Labels: i18n, javascript

#33436 Use bundler version 2.6.2
  Gemfile
  Gemfile.lock
Labels: dependencies

#33443 Fix incorrect `relationship_severance_event` attribute name in changelog
  CHANGELOG.md
Labels: to backport

#33402 Localize language names
  app/javascript/mastodon/components/status_content.jsx
  app/javascript/mastodon/initial_state.js
Labels: i18n

#32357 Update `rails` to version 8.0.1
  Gemfile
  Gemfile.lock
  config/application.rb
  config/initializers/filter_parameter_logging.rb
  lib/active_record/batches.rb
  spec/rails_helper.rb
Labels: dependencies

#31843 Remove old notifications actions and reducers
  app/javascript/mastodon/actions/notifications.js
  app/javascript/mastodon/actions/notifications_migration.tsx
  app/javascript/mastodon/actions/notifications_typed.ts
  app/javascript/mastodon/actions/streaming.js
  app/javascript/mastodon/features/notifications/containers/column_settings_container.js
  app/javascript/mastodon/features/ui/index.jsx
  app/javascript/mastodon/reducers/notifications.js
Labels: javascript, area/web interface

#33444 Fix audio player modal having white-on-white buttons in light theme
  app/javascript/mastodon/features/ui/components/audio_modal.jsx
  app/javascript/mastodon/features/ui/components/video_modal.jsx
Labels: ui, javascript, area/web interface

#33445 Replace deprecated `STATS_DIRECTORIES` with `Rails::CodeStatistics.register_directory` approach
  config/initializers/statistics.rb
  lib/tasks/statistics.rake
Labels: refactoring, ruby

#33435 Refactor status `handleClick` and `handleHotkeyOpen` handlers
  app/javascript/mastodon/components/status.jsx
Labels: javascript

#33421 Added validator for extra profile field values with empty name
  app/models/account.rb
  app/validators/empty_profile_field_names_validator.rb
  config/locales/activerecord.en.yml
  spec/models/account_spec.rb
Labels: ruby

#33446 Use `in_order_of` with `filter: false` in `AccountSummary.localized`
  app/models/account_summary.rb
  spec/models/account_summary_spec.rb
Labels: refactoring, ruby

#33466 Fix `fediverse:creator` metadata not showing up in REST API
  app/models/preview_card.rb
  spec/serializers/rest/preview_card_serializer_spec.rb
Labels: to backport

#33449 Avoid "double icon" near each other in nav sidebar
  config/navigation.rb
Labels: ui, area/web interface

#33313 Fix Style/MultipleComparison
  .rubocop/style.yml
  app/lib/activitypub/tag_manager.rb
Labels: ruby, lint fix 💅

#33482 Fix preview card sizing in “Author attribution” in profile settings
  app/javascript/styles/mastodon/forms.scss
Labels: bug, ui

#33304 Use ruby version 3.4.1
  .github/ISSUE_TEMPLATE/2.server_bug_report.yml
  .github/ISSUE_TEMPLATE/3.troubleshooting.yml
  .github/renovate.json5
  .github/workflows/test-ruby.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, pipeline

#33207 Extend custom CSS cache time with digest paths
  app/controllers/custom_css_controller.rb
  app/helpers/theme_helper.rb
  app/models/form/admin_settings.rb
  app/views/layouts/application.html.haml
  config/initializers/settings_digests.rb
  config/routes.rb
  spec/helpers/theme_helper_spec.rb
  spec/models/form/admin_settings_spec.rb
  spec/requests/cache_spec.rb
  spec/requests/custom_css_spec.rb
  spec/routing/custom_css_routing_spec.rb
Labels: performance, ruby

#30817 Unpin peter-evans/create-pull-request to v7
  .github/workflows/crowdin-download.yml
Labels: testing, dependencies, pipeline

#32143 Refresh `README.md`
  README.md
Labels: expertise wanted

#33191 Include time portion in formatted datetimes when provided
  app/javascript/entrypoints/public.tsx
  app/views/admin/report_notes/_report_note.html.haml
  app/views/admin/reports/_comment.html.haml
  app/views/disputes/strikes/show.html.haml
Labels: javascript, ruby, area/web interface

#33328 Extract development section from top-level readme into standalone doc
  CONTRIBUTING.md
  README.md
  docs/DEVELOPMENT.md
Labels: expertise wanted, meta/project

#33508 Add `Account#remote?` query method
  app/models/account.rb
  app/models/poll.rb
  spec/models/account_spec.rb
Labels: refactoring, ruby

#33507 Add "Account::Search" shared example for use in `Account` spec
  spec/models/account_spec.rb
  spec/support/examples/models/concerns/account/search.rb
Labels: testing, ruby

#32729 Do now swallow response body on persistent connection
  app/lib/request.rb
  spec/lib/request_spec.rb
Labels: ruby

#33271 Fix last paginated notification group only including data on a single notification
  app/controllers/api/v2/notifications_controller.rb
  app/models/notification_group.rb
  spec/requests/api/v2/notifications_spec.rb
Labels: ruby, to backport

#18329 Add timestamp to all announcements in Web UI
  app/javascript/mastodon/features/getting_started/components/announcements.jsx
Labels: ui, area/web interface

#33489 Rename `app/helpers/jsonld_helper.rb` to `app/helpers/json_ld_helper.rb`
  .rubocop_todo.yml
  app/helpers/json_ld_helper.rb
Labels: lint fix 💅

#33529 Use `with_options` for Account `if: :local?` validation group
  app/models/account.rb
  spec/models/account_spec.rb
Labels: refactoring, ruby

#33532 Extract `CSS_COLORS` constant for `UserRole` regex validation
  app/models/user_role.rb
Labels: refactoring, ruby

#33536 Add `duplicate_record` helper to maintenance CLI spec
  spec/lib/mastodon/cli/maintenance_spec.rb
Labels: testing

#33537 Add `build_object` method for defaults in `AP::Activity::Create` spec
  spec/lib/activitypub/activity/create_spec.rb
Labels: testing

#33527 Change ActivityPub path generation to all happen in `ActivityPub::TagManager`
  app/controllers/activitypub/collections_controller.rb
  app/controllers/activitypub/outboxes_controller.rb
  app/controllers/follower_accounts_controller.rb
  app/lib/activitypub/tag_manager.rb
  app/serializers/activitypub/actor_serializer.rb
  app/serializers/activitypub/add_serializer.rb
  app/serializers/activitypub/remove_serializer.rb
  app/serializers/webfinger_serializer.rb
  spec/lib/activitypub/tag_manager_spec.rb
Labels: refactoring, ruby

#33571 Fix media preview height in compose form when 3 or more images are attached
  app/javascript/styles/mastodon/components.scss
Labels: to backport, area/web interface

#33572 Switch `webpush` dependency to latest version of Mastodon-maintained fork
  Gemfile
  Gemfile.lock
  app/lib/web_push_request.rb
  app/validators/web_push_key_validator.rb
  spec/workers/web/push_notification_worker_spec.rb
Labels: dependencies

#29308 Fix HTTP 500 on `POST /api/v1/admin/ip_blocks`
  app/models/ip_block.rb
  spec/models/ip_block_spec.rb
  spec/requests/api/v1/admin/ip_blocks_spec.rb
Labels: partially a bug, ruby

#29158 Add enum validation to `DomainBlock#severity`
  app/models/domain_block.rb
  spec/requests/api/v1/admin/domain_blocks_spec.rb
Labels: ruby

#33528 Add support for standard webpush
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/push/subscriptions_controller.rb
  app/controllers/api/web/push_subscriptions_controller.rb
  app/lib/web_push_request.rb
  app/models/web/push_subscription.rb
  app/serializers/rest/web_push_subscription_serializer.rb
  app/validators/web_push_key_validator.rb
  app/workers/web/push_notification_worker.rb
  db/migrate/20250108111200_add_standard_to_push_subscription.rb
  db/schema.rb
  spec/workers/web/push_notification_worker_spec.rb
Labels: refactoring, dependencies, ruby

#33577 Move mastodon version config to `config_for` yml
  config/mastodon.yml
  lib/mastodon/version.rb
  spec/presenters/instance_presenter_spec.rb
Labels: ruby

#33578 Add `Status::Visibility` concern to hold visibility logic
  app/models/concerns/status/visibility.rb
  app/models/status.rb
  spec/models/status_spec.rb
  spec/support/examples/models/concerns/status/visibility.rb
Labels: refactoring, ruby

#33593 Enable parallel execution for linting tasks in HAML workflows
  .github/workflows/lint-haml.yml
  lint-staged.config.js
Labels: performance, lint fix 💅

#33594 Expand coverage of `admin/*blocks` areas
  spec/system/admin/email_domain_blocks_spec.rb
  spec/system/admin/ip_blocks_spec.rb
Labels: testing

#33580 Promote `Style/WordArray` rule out of todo into main config
  .rubocop/style.yml
  .rubocop_todo.yml
Labels: lint fix 💅

#33631 Further harden the warnings against changing encryption secrets
  .env.production.sample
  lib/tasks/db.rake
Labels: to backport

#33634 Fix re-encoding of high-framerate VFR videos with FFmpeg 6+
  lib/paperclip/transcoder.rb
Labels: area/media processing

#33658 Use bundler version 2.6.3
  Gemfile.lock
Labels: dependencies

#33516 Change design of edit media modal in web UI
  app/javascript/images/reticle.png
  app/javascript/mastodon/actions/compose.js
  app/javascript/mastodon/actions/compose_typed.ts
  app/javascript/mastodon/actions/modal.ts
  app/javascript/mastodon/api/compose.ts
  app/javascript/mastodon/components/button.tsx
  app/javascript/mastodon/components/follow_button.tsx
  app/javascript/mastodon/components/gifv.tsx
  app/javascript/mastodon/features/alt_text_modal/index.tsx
  app/javascript/mastodon/features/audio/index.jsx
  app/javascript/mastodon/features/compose/components/character_counter.jsx
  app/javascript/mastodon/features/compose/components/character_counter.tsx
  app/javascript/mastodon/features/compose/components/compose_form.jsx
  app/javascript/mastodon/features/compose/components/upload.tsx
  app/javascript/mastodon/features/compose/components/upload_form.tsx
  app/javascript/mastodon/features/notifications_v2/components/notification_follow.tsx
  app/javascript/mastodon/features/ui/components/boost_modal.tsx
  app/javascript/mastodon/features/ui/components/focal_point_modal.jsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/features/ui/containers/modal_container.js
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/compose.js
  app/javascript/mastodon/reducers/index.ts
  app/javascript/mastodon/reducers/modal.ts
  app/javascript/styles/mastodon-light/diff.scss
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
  app/javascript/types/tesseract.d.ts
  app/views/admin/accounts/index.html.haml
  app/views/admin/custom_emojis/index.html.haml
  app/views/admin/domain_blocks/confirm_suspension.html.haml
  app/views/admin/instances/index.html.haml
  app/views/admin/relays/index.html.haml
  app/views/admin/reports/index.html.haml
  app/views/admin/tags/index.html.haml
  app/views/settings/two_factor_authentication/otp_authentication/show.html.haml
  app/views/settings/two_factor_authentication/webauthn_credentials/index.html.haml
  app/views/settings/two_factor_authentication_methods/index.html.haml
  config/webpack/rules/tesseract.js
  package.json
  spec/system/ocr_spec.rb
  yarn.lock
Labels: ui, javascript

#33654 Change notifications from moderators to not be filtered
  app/services/notify_service.rb
  spec/services/notify_service_spec.rb
Labels: ruby, to backport

#33630 Order emoji categories (in admin interface) by name
  app/models/custom_emoji_category.rb
  app/views/admin/custom_emojis/index.html.haml
Labels: moderation, refactoring, ruby

#33675 Use `expect` for nested params in more controllers
  app/controllers/disputes/appeals_controller.rb
  app/controllers/filters_controller.rb
  app/controllers/invites_controller.rb
  app/controllers/statuses_cleanup_controller.rb
  spec/requests/disputes/appeals_spec.rb
  spec/requests/filters_spec.rb
  spec/requests/invites_spec.rb
  spec/requests/statuses_cleanup_spec.rb
Labels: ruby, lint fix 💅

#33680 Refactor `<DomainPill>` into TypeScript
  app/javascript/mastodon/features/account/components/domain_pill.jsx
  app/javascript/mastodon/features/account/components/domain_pill.tsx
Labels: refactoring, typescript

#33673 Use `expect` for nested params in `settings/*` controllers
  app/controllers/settings/aliases_controller.rb
  app/controllers/settings/deletes_controller.rb
  app/controllers/settings/featured_tags_controller.rb
  app/controllers/settings/imports_controller.rb
  app/controllers/settings/migration/redirects_controller.rb
  app/controllers/settings/migrations_controller.rb
  app/controllers/settings/privacy_controller.rb
  app/controllers/settings/profiles_controller.rb
  spec/requests/settings/aliases_spec.rb
  spec/requests/settings/deletes_spec.rb
  spec/requests/settings/featured_tags_spec.rb
  spec/requests/settings/imports_spec.rb
  spec/requests/settings/migration/redirects_spec.rb
  spec/requests/settings/migrations_spec.rb
  spec/requests/settings/privacy_spec.rb
  spec/requests/settings/profiles_spec.rb
Labels: ruby, lint fix 💅

#33647 Change `first_of_value` to `first_of_hash`, and add more test cases
  app/lib/link_details_extractor.rb
  spec/lib/link_details_extractor_spec.rb
Labels: ruby

#33684 Change `mastodon:setup` to prevent overwriting already-configured servers
  lib/tasks/mastodon.rake
Labels: to backport

#33691 Fix issue with saving empty fields values on filter keyword updates
  app/controllers/filters_controller.rb
  spec/system/filters_spec.rb
Labels: bug, ruby

#33702 Add information about alt text to alt text modal in web UI
  app/javascript/mastodon/features/alt_text_modal/components/info_button.tsx
  app/javascript/mastodon/features/alt_text_modal/index.tsx
  app/javascript/mastodon/locales/en.json
  app/javascript/material-icons/400-24px/question_mark-fill.svg
  app/javascript/material-icons/400-24px/question_mark.svg
  app/javascript/styles/mastodon/components.scss
  app/javascript/styles/mastodon/forms.scss
Labels: ui, build-image

#33695 Fix intermittent services/ap/process_status_update tags failure
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: testing, ruby, pipeline

#33705 Fix LDSignature tests
  spec/lib/activitypub/linked_data_signature_spec.rb
Labels: to backport

#33677 Store Bootsnap cache outside bind mounts (devcontainer only)
  .devcontainer/compose.yaml
Labels: performance, docker

#33725 Fix wrong styles on rules and buttons in the sign-up form
  app/javascript/styles/mastodon/forms.scss
Labels: bug

#33723 Refactor `<LanguageDropdown>` into TypeScript
  app/javascript/mastodon/features/compose/components/language_dropdown.jsx
  app/javascript/mastodon/features/compose/components/language_dropdown.tsx
Labels: refactoring, typescript

#33724 Fix color of language indicator in light theme in web UI
  app/javascript/styles/mastodon-light/diff.scss
Labels: bug

#33736 Remove system tooltip for alt text in web UI
  app/javascript/mastodon/components/media_gallery.jsx
  app/javascript/mastodon/features/account_gallery/components/media_item.tsx
Labels: ui

#33734 Add an optional metric exporter
  Gemfile
  Gemfile.lock
  bin/prometheus_exporter
  config/initializers/prometheus_exporter.rb
  config/initializers/sidekiq.rb
  config/puma.rb
Labels: build-image

#33686 Use `expect` for `admin/` controllers
  app/controllers/admin/account_actions_controller.rb
  app/controllers/admin/account_moderation_notes_controller.rb
  app/controllers/admin/accounts_controller.rb
  app/controllers/admin/announcements_controller.rb
  app/controllers/admin/change_emails_controller.rb
  app/controllers/admin/custom_emojis_controller.rb
  app/controllers/admin/domain_allows_controller.rb
  app/controllers/admin/domain_blocks_controller.rb
  app/controllers/admin/email_domain_blocks_controller.rb
  app/controllers/admin/follow_recommendations_controller.rb
  app/controllers/admin/invites_controller.rb
  app/controllers/admin/ip_blocks_controller.rb
  app/controllers/admin/relays_controller.rb
  app/controllers/admin/report_notes_controller.rb
  app/controllers/admin/roles_controller.rb
  app/controllers/admin/rules_controller.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/statuses_controller.rb
  app/controllers/admin/tags_controller.rb
  app/controllers/admin/terms_of_service/drafts_controller.rb
  app/controllers/admin/terms_of_service/generates_controller.rb
  app/controllers/admin/trends/links/preview_card_providers_controller.rb
  app/controllers/admin/trends/links_controller.rb
  app/controllers/admin/trends/statuses_controller.rb
  app/controllers/admin/trends/tags_controller.rb
  app/controllers/admin/users/roles_controller.rb
  app/controllers/admin/warning_presets_controller.rb
  app/controllers/admin/webhooks_controller.rb
  spec/controllers/admin/settings/branding_controller_spec.rb
  spec/requests/admin/account_actions_spec.rb
  spec/requests/admin/account_moderation_notes_spec.rb
  spec/requests/admin/accounts_spec.rb
  spec/requests/admin/announcements_spec.rb
  spec/requests/admin/change_emails_spec.rb
  spec/requests/admin/custom_emojis_spec.rb
  spec/requests/admin/domain_allows_spec.rb
  spec/requests/admin/domain_blocks_spec.rb
  spec/requests/admin/email_domain_blocks_spec.rb
  spec/requests/admin/follow_recommendations_spec.rb
  spec/requests/admin/invites_spec.rb
  spec/requests/admin/ip_blocks_spec.rb
  spec/requests/admin/relays_spec.rb
  spec/requests/admin/report_notes_spec.rb
  spec/requests/admin/roles_spec.rb
  spec/requests/admin/rules_spec.rb
  spec/requests/admin/settings/about_spec.rb
  spec/requests/admin/statuses_spec.rb
  spec/requests/admin/tags_spec.rb
  spec/requests/admin/terms_of_service/drafts_spec.rb
  spec/requests/admin/terms_of_service/generates_spec.rb
  spec/requests/admin/trends/links/preview_card_providers_spec.rb
  spec/requests/admin/trends/links_spec.rb
  spec/requests/admin/trends/statuses_spec.rb
  spec/requests/admin/trends/tags_spec.rb
  spec/requests/admin/users/roles_spec.rb
  spec/requests/admin/warning_presets_spec.rb
  spec/requests/admin/webhooks_spec.rb
Labels: ruby, lint fix 💅

#33755 Fix polls not being validated on edition
  app/models/poll.rb
  app/serializers/rest/instance_serializer.rb
  app/serializers/rest/v1/instance_serializer.rb
  app/validators/poll_expiration_validator.rb
  app/validators/poll_options_validator.rb
  spec/requests/api/v2/instance_spec.rb
  spec/validators/poll_expiration_validator_spec.rb
  spec/validators/poll_options_validator_spec.rb
Labels: bug, to backport

#33769 Fix missing timeout options in `Request` class
  app/lib/request.rb
Labels: bug, to backport, build-image

#33762 Add loading indicator to timeline gap indicators in web UI
  app/javascript/mastodon/components/load_gap.tsx
  app/javascript/styles/mastodon/components.scss
Labels: ui

#33770 Change language detection debouncing behavior to refresh at least once every 1.5 seconds
  app/javascript/mastodon/features/compose/util/language_detection.js
Labels: area/web interface

#33758 Fix “x” hotkey not working on boosted filtered posts
  app/javascript/mastodon/components/status.jsx
Labels: bug, area/web interface

#33771 Fix missing button styles on some forms
  app/views/admin/invites/_invite.html.haml
  app/views/invites/_invite.html.haml
  app/views/mail_subscriptions/show.html.haml
  app/views/oauth/authorizations/new.html.haml
  app/views/oauth/authorizations/show.html.haml
  app/views/settings/verifications/show.html.haml
Labels: bug

#33760 Add reminder when about to post without alt text in web UI
  app/javascript/mastodon/features/compose/components/compose_form.jsx
  app/javascript/mastodon/features/compose/containers/compose_form_container.js
  app/javascript/mastodon/features/ui/components/confirmation_modals/confirmation_modal.tsx
  app/javascript/mastodon/features/ui/components/confirmation_modals/index.ts
  app/javascript/mastodon/features/ui/components/confirmation_modals/missing_alt_text.tsx
  app/javascript/mastodon/features/ui/components/modal_root.jsx
  app/javascript/mastodon/initial_state.js
  app/javascript/mastodon/locales/en.json
  app/models/user_settings.rb
  app/serializers/initial_state_serializer.rb
  app/views/settings/preferences/appearance/show.html.haml
  config/locales/simple_form.en.yml
Labels: ui

#33773 Fix flaky test in `/api/v2/notifications` tests
  spec/requests/api/v2/notifications_spec.rb
Labels: to backport

#33737 Add ability to dismiss alt text badge by tapping it in web UI
  app/javascript/hooks/useSelectableClick.ts
  app/javascript/mastodon/components/alt_text_badge.tsx
  app/javascript/mastodon/features/account/components/domain_pill.tsx
  app/javascript/mastodon/features/alt_text_modal/components/info_button.tsx
Labels: ui

#33712 build(Dockerfiles): Set the base registry via an ARG
  Dockerfile
  streaming/Dockerfile
Labels: deployment, performance, docker

#33783 Fix `tootctl feeds build` not building list timelines
  app/lib/feed_manager.rb
  app/models/list.rb
  app/models/list_account.rb
  app/services/precompute_feed_service.rb
  spec/services/precompute_feed_service_spec.rb
Labels: to backport, build-image
