Repository mastodon/mastodon, pull requests merged in 2025-07, with the labels that each got.

#35235 Add coverage for TOS interstitial interruption flow of web app controller concern
  spec/controllers/concerns/web_app_controller_concern_spec.rb
Labels: to backport

#35246 Fix error handling for blank actions in account moderation action form
  app/controllers/admin/account_actions_controller.rb
  app/models/admin/account_action.rb
  spec/system/admin/account_actions_spec.rb
Labels: to backport

#35262 Raise better exception on FASP error responses
  app/lib/fasp/request.rb
  spec/lib/fasp/request_spec.rb
Labels: ruby, to backport

#35281 fix: Fix can't skip search field by tabbing
  app/javascript/mastodon/features/compose/components/search.tsx
Labels: to backport

#35317 Fix replying from media modal or pop-in-player tagging user `@undefined`
  app/javascript/mastodon/features/picture_in_picture/components/footer.tsx
Labels: to backport

#35321 Relax error restriction in initializer
  config/initializers/settings_digests.rb
Labels: ruby, to backport

#35320 Fix styling of external log-in button
  app/helpers/application_helper.rb
Labels: to backport

#35252 Simplify `DatabaseViewRecord.refresh`
  app/models/concerns/database_view_record.rb
Labels: ruby

#35354 Fix quote attributes missing from Mastodon's context
  app/helpers/context_helper.rb
Labels: to backport

#35383 Always give local quote of remote posts a quote request URI
  app/models/quote.rb
  app/serializers/activitypub/quote_request_serializer.rb
Labels: to backport

#35382 Refactor `ActivityPub::Activity::Accept` and `ActivityPub::Activity::Reject` specs
  spec/lib/activitypub/activity/accept_spec.rb
  spec/lib/activitypub/activity/reject_spec.rb
Labels: refactoring, ruby, to backport

#35384 Fix support for quote verification in implicit status updates
  app/services/activitypub/process_status_update_service.rb
  spec/services/activitypub/process_status_update_service_spec.rb
Labels: activitypub, to backport

#35195 Replace Ruby Vite plugins
  .storybook/main.ts
  config/vite/plugin-mastodon-themes.ts
  package.json
  vite.config.mts
  vitest.config.mts
  yarn.lock
Labels: dependencies

#35414 refactor: Disable `useDrag` hook when main menu is not openable
  app/javascript/mastodon/features/navigation_panel/index.tsx
Labels: to backport

#35430 Use bundler version 2.7.0
  Gemfile.lock
Labels: dependencies, ruby

#35448 Update playwright-ruby-client to version 1.54.0
  Gemfile.lock
  package.json
  yarn.lock
Labels: dependencies

#35210 Add button to load new replies in web UI
  app/controllers/api/v1/statuses_controller.rb
  app/javascript/mastodon/actions/statuses_typed.ts
  app/javascript/mastodon/api.ts
  app/javascript/mastodon/api/async_refreshes.ts
  app/javascript/mastodon/api/statuses.ts
  app/javascript/mastodon/api_types/async_refreshes.ts
  app/javascript/mastodon/features/status/components/refresh_controller.tsx
  app/javascript/mastodon/features/status/index.jsx
  app/javascript/mastodon/locales/en.json
  app/javascript/mastodon/reducers/contexts.ts
  app/models/concerns/status/fetch_replies_concern.rb
  app/models/worker_batch.rb
  app/services/activitypub/fetch_all_replies_service.rb
  app/services/activitypub/fetch_replies_service.rb
  app/workers/activitypub/fetch_all_replies_worker.rb
  app/workers/fetch_reply_worker.rb
  spec/models/worker_batch_spec.rb
  spec/workers/activitypub/fetch_all_replies_worker_spec.rb
Labels: ui

#35478 Fix “Expand this post” link including user `@undefined`
  app/javascript/mastodon/features/picture_in_picture/components/footer.tsx
Labels: to backport

#35507 Add restrictions on which quote posts can trend
  app/models/trends/statuses.rb
  spec/models/trends/statuses_spec.rb
Labels: to backport

#35515 Fix unnecessary duplication in vite code for finding entrypoints
  vite.config.mts
Labels: typescript

#35496 Fix jobs being added to batch after they might already execute
  app/models/worker_batch.rb
  app/services/activitypub/fetch_replies_service.rb
  config/initializers/sidekiq.rb
  lib/mastodon/worker_batch_middleware.rb
Labels: bug

#35526 Fix `Style/GuardClause` in app/helpers
  app/helpers/formatting_helper.rb
  app/helpers/theme_helper.rb
Labels: lint fix 💅

#35524 Fix `Style/GuardClause` in `User#wrap_email_confirmation`
  app/models/user.rb
Labels: lint fix 💅

#35522 Fix `Style/GuardClause` in `Tag`
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: testing, lint fix 💅

#35523 Fix `Style/GuardClause` in `User#regenerate_feed!`
  app/models/user.rb
Labels: lint fix 💅

#35575 Change "new replies available" notice to be above replies in web UI
  app/javascript/mastodon/features/status/components/refresh_controller.tsx
  app/javascript/mastodon/features/status/index.jsx
Labels: ui

#35500 Fix async refresh never being finished when status cannot be fetched
  app/controllers/api/v1/statuses_controller.rb
  app/models/concerns/status/fetch_replies_concern.rb
  app/models/worker_batch.rb
  app/services/activitypub/fetch_all_replies_service.rb
  app/services/activitypub/fetch_replies_service.rb
  app/workers/activitypub/fetch_all_replies_worker.rb
  app/workers/fetch_reply_worker.rb
  spec/models/worker_batch_spec.rb
Labels: bug

#35407 Add ability to block words in usernames
  app/controllers/admin/username_blocks_controller.rb
  app/helpers/admin/action_logs_helper.rb
  app/javascript/material-icons/400-24px/supervised_user_circle_off-fill.svg
  app/javascript/material-icons/400-24px/supervised_user_circle_off.svg
  app/models/admin/action_log_filter.rb
  app/models/form/username_block_batch.rb
  app/models/user.rb
  app/models/username_block.rb
  app/policies/username_block_policy.rb
  app/validators/unreserved_username_validator.rb
  app/views/admin/username_blocks/_form.html.haml
  app/views/admin/username_blocks/_username_block.html.haml
  app/views/admin/username_blocks/edit.html.haml
  app/views/admin/username_blocks/index.html.haml
  app/views/admin/username_blocks/new.html.haml
  config/i18n-tasks.yml
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/navigation.rb
  config/routes/admin.rb
  config/settings.yml
  db/migrate/20250717003848_create_username_blocks.rb
  db/schema.rb
  db/seeds/05_blocked_usernames.rb
  spec/fabricators/username_block_fabricator.rb
  spec/models/username_block_spec.rb
  spec/requests/admin/username_blocks_spec.rb
  spec/validators/unreserved_username_validator_spec.rb
Labels: deployment, moderation, ruby

#35603 Change new replies to be loaded automatically if thread previously empty
  app/javascript/mastodon/features/status/components/refresh_controller.tsx
Labels: ui
